import { CognitiveAuditTrail } from './CognitiveAuditTrail';
import { CognitiveComplexityEstimator, CognitiveResourceAllocator, CognitiveTimeline, CreativeIntelligenceHealthMonitor, CreativeIntelligenceScoreV3, DecisionStabilityAnalyzer, ExplainabilityValidator, HallucinationDetector, KnowledgeCoverageAnalyzer, MetaConfidenceEngine, SelfMonitoringEngine, ThinkingBudgetManager, UnknownDetector } from './components';
import { deepImmutable } from './immutable';
import { HeuristicGovernanceModel, HeuristicHallucinationModel, HeuristicKnowledgeCoverageModel, HeuristicMetaLearningModel, HeuristicMetaReasoningModel, HeuristicReflectionModel, HeuristicStabilityModel, HeuristicThinkingPolicyModel } from './models';
import type { GovernanceModel, HallucinationModel, KnowledgeCoverageModel, MetaDependencies, MetaInput, MetaLearningModel, MetaReasoningModel, MetaResult, ReflectionModel, Scope, StabilityModel, ThinkingPolicyModel } from './types';

export interface MetaModels { reasoning?: MetaReasoningModel; thinking?: ThinkingPolicyModel; hallucination?: HallucinationModel; governance?: GovernanceModel; reflection?: ReflectionModel; coverage?: KnowledgeCoverageModel; stability?: StabilityModel; learning?: MetaLearningModel }
export class MetaCognitiveController {
  private readonly audit: CognitiveAuditTrail; private readonly complexity = new CognitiveComplexityEstimator(); private readonly resources = new CognitiveResourceAllocator(); private readonly monitoring = new SelfMonitoringEngine(); private readonly explainability = new ExplainabilityValidator(); private readonly confidence = new MetaConfidenceEngine(); private readonly health = new CreativeIntelligenceHealthMonitor(); private readonly scoring = new CreativeIntelligenceScoreV3(); private readonly timeline = new CognitiveTimeline(); private readonly unknown = new UnknownDetector();
  private readonly thinking: ThinkingBudgetManager; private readonly hallucination: HallucinationDetector; private readonly coverage: KnowledgeCoverageAnalyzer; private readonly stability: DecisionStabilityAnalyzer;
  private readonly reasoning: MetaReasoningModel; private readonly governance: GovernanceModel; private readonly reflection: ReflectionModel; private readonly learning: MetaLearningModel; private readonly results = new Map<string, MetaResult>();
  constructor(private readonly dependencies: MetaDependencies, models: MetaModels = {}) { this.audit = new CognitiveAuditTrail(dependencies); this.reasoning = models.reasoning ?? new HeuristicMetaReasoningModel(); this.thinking = new ThinkingBudgetManager(models.thinking ?? new HeuristicThinkingPolicyModel()); this.hallucination = new HallucinationDetector(models.hallucination ?? new HeuristicHallucinationModel()); this.governance = models.governance ?? new HeuristicGovernanceModel(); this.reflection = models.reflection ?? new HeuristicReflectionModel(); this.coverage = new KnowledgeCoverageAnalyzer(models.coverage ?? new HeuristicKnowledgeCoverageModel()); this.stability = new DecisionStabilityAnalyzer(models.stability ?? new HeuristicStabilityModel()); this.learning = models.learning ?? new HeuristicMetaLearningModel(); }
  analyze(raw: MetaInput): MetaResult {
    this.validate(raw); const input = deepImmutable(structuredClone(raw)); const id = this.dependencies.id(); const at = this.dependencies.now(); const scope = { tenantId: input.tenantId, projectId: input.projectId, userId: input.userId };
    const difficulty = this.complexity.estimate(input.prompt, input.difficulty); const coverage = this.coverage.analyze(input.domain, input.prompt); this.unknown.detect(coverage);
    const hallucinations = this.hallucination.detect(input); const explainability = this.explainability.validate(input.observations); const metaConfidence = this.confidence.calculate(input.observations, coverage.score, hallucinations.length, explainability.penalty);
    const trustedSource = this.reasoning.chooseTrust(input.observations, coverage); const thinkingBudget = this.thinking.allocate({ ...input, difficulty }, metaConfidence.confidenceOfConfidence); const allocation = this.resources.allocate(input.prompt); const monitoring = this.monitoring.evaluate(input); const stability = this.stability.analyze(input); const mode = this.governance.select({ ...input, difficulty }, coverage);
    const finalStrategy = trustedSource === 'NONE' ? 'DEFER' : input.observations.find((item) => item.source === trustedSource)?.strategy ?? 'DEFER'; const shouldStop = !thinkingBudget.shouldContinue || coverage.state === 'IMPOSSIBLE' || (stability.stable && metaConfidence.confidenceOfConfidence >= .7);
    const reflection = this.reflection.reflect(input, monitoring, allocation); const health = this.health.evaluate(monitoring, coverage.score, metaConfidence.confidenceOfConfidence); const score = this.scoring.calculate(monitoring, coverage.score, metaConfidence.confidenceOfConfidence, 1 - thinkingBudget.iterations / 25);
    const audit = [this.audit.record(scope, 'META', 'TRUST_SELECTED', `Trusted ${trustedSource}`, { rule: 'confidence-with-evidence', expert: trustedSource, strategy: finalStrategy }), this.audit.record(scope, 'GOVERNANCE', 'MODE_SELECTED', mode, { rule: 'risk-budget-coverage' }), this.audit.record(scope, 'META', shouldStop ? 'STOP' : 'CONTINUE', `confidence-of-confidence=${metaConfidence.confidenceOfConfidence}`)];
    const timeline = this.timeline.build(id, at, { Intent: input.intent ?? input.prompt, Goals: input.goals.join(', '), 'Meta Review': trustedSource, Learning: this.learning.key({ mode, trustedSource, finalStrategy }), Reflection: reflection.nextTime.join(', ') });
    const debugSnapshot = ['Prompt', 'Intent', 'Goals', 'Decision Core', 'Creative Director', 'Studio Brain', 'Orchestrator', 'Meta Controller', 'Thinking Budget', 'Resource Allocation', 'Stability', 'Coverage', 'Unknown Detection', 'Hallucination Check', 'Governance', 'Reflection', 'Learning', 'Health', 'Creative Intelligence Score'].join('\n↓\n');
    const result = deepImmutable({ id, ...scope, mode, trustedSource, shouldStop, thinkingBudget, allocation, monitoring, hallucinations, stability, coverage, explainable: explainability.explainable, metaConfidence, audit, reflection, health, score, timeline, finalStrategy, debugSnapshot }); this.results.set(id, result); return result;
  }
  replay(id: string, scope: Scope): MetaResult { const result = this.results.get(id); if (!result) throw new Error(`Unknown meta result ${id}`); this.assertScope(result, scope); return deepImmutable(structuredClone(result)); }
  auditHistory(scope: Scope) { return this.audit.history(scope); }
  private validate(input: MetaInput) { if (!input.tenantId || !input.projectId || !input.userId) throw new Error('Complete scope is required'); if (!input.prompt.trim()) throw new Error('Prompt is required'); if (input.budget < 0) throw new Error('Budget cannot be negative'); }
  private assertScope(result: Scope, scope: Scope) { if (result.tenantId !== scope.tenantId || result.projectId !== scope.projectId || result.userId !== scope.userId) throw new Error('Meta scope violation'); }
}
