import { DecisionConstraintLayer } from './DecisionConstraintLayer';
import { DecisionCalibrationV2 } from './DecisionCalibrationV2';
import { DecisionRepresentationEncoderV2 } from './DecisionRepresentationEncoderV2';
import { clamp, immutable, mean, stableHash } from './immutable';
import type { DecisionDatasetRecord, MultiHeadPrediction, RankedDecisionCandidate, UtilityPolicy } from './types';
import type { CounterfactualResultV2, DecisionInputV2, DistilledModelV2, ListwiseExampleV2, MultiTaskPredictionV2, NeuralDecisionRanker, PairwiseExampleV2, PairwisePredictionV2 } from './v2-types';

const sigmoid = (value: number) => 1 / (1 + Math.exp(-Math.max(-20, Math.min(20, value))));
const utilityDefaults: UtilityPolicy & { satisfaction: number; regret: number } = Object.freeze({ quality: 3, success: 2, acceptance: 1.5, latency: 1, cost: 1, escalation: .5, satisfaction: 1.5, regret: 1 });
type Head = 'quality' | 'success' | 'acceptance' | 'cost' | 'latency' | 'escalation' | 'satisfaction' | 'regret' | 'rank';
const heads: readonly Head[] = ['quality', 'success', 'acceptance', 'cost', 'latency', 'escalation', 'satisfaction', 'regret', 'rank'];
interface NeuralState { hidden: readonly (readonly number[])[]; biases: readonly number[]; output: Readonly<Record<Head, readonly number[]>>; outputBias: Readonly<Record<Head, number>>; coverage: Readonly<Record<string, number>> }
const deterministicWeight = (key: string) => ((stableHash(key) / 0xffffffff) * 2 - 1) * .12;
const linear = (weights: readonly number[], values: readonly number[], bias = 0) => weights.reduce((sum, weight, index) => sum + weight * (values[index] ?? 0), bias);
export class CompactNeuralDecisionRankerV2 implements NeuralDecisionRanker {
  private readonly state: NeuralState;
  constructor(private readonly modelVersion = 'neural-ranker-v2.0', readonly encoder = new DecisionRepresentationEncoderV2(), private readonly gate = new DecisionConstraintLayer(), private readonly calibration = new DecisionCalibrationV2(), state?: NeuralState, private readonly hiddenSize = 12) { const dimensions = encoder.encode({ context: { operation: '', intent: '', goal: '', deviceClass: '', platform: '', projectType: '', privacyMode: 'NORMAL', budget: 0, latencyTarget: 0, qualityTarget: 0 }, candidate: { id: '', executionTarget: 'LOCAL', model: '', provider: '', runtime: '', estimatedQuality: 0, estimatedLatency: 0, estimatedCost: 0, energy: 0, memory: 0, reliability: 0 }, history: { modelSuccessRate: 0, providerSuccessRate: 0, deviceSpecificSuccessRate: 0, cloudAvoidance: 0, acceptanceRate: 0, undoRate: 0 } }).values.length; this.state = state ?? this.initialize(dimensions); }
  private initialize(dimensions: number): NeuralState { const hidden = Array.from({ length: this.hiddenSize }, (_, row) => Array.from({ length: dimensions }, (_, column) => deterministicWeight(`${this.modelVersion}:h:${row}:${column}`))), output = heads.reduce((result, head) => ({ ...result, [head]: Array.from({ length: this.hiddenSize }, (_, index) => deterministicWeight(`${this.modelVersion}:${head}:${index}`)) }), {} as Record<Head, readonly number[]>), outputBias = heads.reduce((result, head) => ({ ...result, [head]: 0 }), {} as Record<Head, number>); return immutable({ hidden, biases: Array(this.hiddenSize).fill(0), output, outputBias, coverage: {} }); }
  encode(input: DecisionInputV2) { return this.encoder.encode(input); }
  private hidden(input: DecisionInputV2) { const values = this.encode(input).values; return this.state.hidden.map((weights, index) => Math.tanh(linear(weights, values, this.state.biases[index]))); }
  private raw(input: DecisionInputV2, head: Head) { return linear(this.state.output[head], this.hidden(input), this.state.outputBias[head]); }
  predict(input: DecisionInputV2, policy: Partial<UtilityPolicy> = {}): MultiTaskPredictionV2 {
    const representation = this.encode(input), quality = clamp(.65 * sigmoid(this.raw(input, 'quality')) + .35 * input.candidate.estimatedQuality), successProbability = clamp(.6 * sigmoid(this.raw(input, 'success')) + .4 * input.candidate.reliability), acceptanceProbability = sigmoid(this.raw(input, 'acceptance')), cost = Math.max(0, input.candidate.estimatedCost * (.75 + .5 * sigmoid(this.raw(input, 'cost')))), latency = Math.max(0, input.candidate.estimatedLatency * (.75 + .5 * sigmoid(this.raw(input, 'latency')))), escalationProbability = sigmoid(this.raw(input, 'escalation')), satisfaction = clamp(.5 * sigmoid(this.raw(input, 'satisfaction')) + .25 * acceptanceProbability + .25 * (input.preferences?.styleAlignment ?? .5)), regret = clamp(sigmoid(this.raw(input, 'regret')));
    const weights = { ...utilityDefaults, ...policy }, expectedUtility = weights.quality * quality + weights.success * successProbability + weights.acceptance * acceptanceProbability + weights.satisfaction * satisfaction - weights.cost * clamp(cost / Math.max(.01, input.context.budget)) - weights.latency * clamp(latency / Math.max(1, input.context.latencyTarget)) - weights.escalation * escalationProbability - weights.regret * regret;
    const knownKey = `${input.context.operation}|${input.context.deviceClass}|${input.candidate.model}|${input.candidate.provider}`, samples = this.state.coverage[knownKey] ?? 0, epistemic = clamp(1 / Math.sqrt(samples + 1)), aleatoric = clamp(1 - input.candidate.reliability), oodScore = clamp((1 - representation.coverage) * .65 + epistemic * .35), critical = oodScore > .72, predictionConfidence = clamp(1 - mean([aleatoric, epistemic, oodScore])); const action = critical ? input.context.privacyMode === 'LOCAL_ONLY' ? 'SAFE_LOCAL' : 'FALLBACK_TO_HEURISTIC' : oodScore > .5 ? 'SHOW_PREVIEW' : 'LOCAL_FIRST';
    const calibrationHeads = this.calibration.heads(); return immutable({ quality, successProbability, acceptanceProbability, latency, cost, escalationProbability, satisfaction, regret, expectedUtility, predictionConfidence, calibration: mean(Object.values(calibrationHeads)), uncertainty: mean([aleatoric, epistemic]), ood: oodScore > .65, recommendedAction: critical ? 'FALLBACK_TO_HEURISTIC' : undefined, uncertaintyV2: { aleatoric, epistemic, dataCoverage: representation.coverage, oodScore, predictionConfidence, critical, action }, calibrationHeads });
  }
  rankPairwise(left: DecisionInputV2, right: DecisionInputV2): PairwisePredictionV2 { const margin = this.raw(left, 'rank') - this.raw(right, 'rank') + (this.predict(left).expectedUtility - this.predict(right).expectedUtility) * .25, leftProbability = sigmoid(margin), rightProbability = 1 - leftProbability, preferred = Math.abs(margin) < .02 ? 'TIE' : margin > 0 ? 'LEFT' : 'RIGHT'; return immutable({ preferred, leftProbability, rightProbability, margin, confidence: clamp(Math.abs(leftProbability - .5) * 2) }); }
  predictList(inputs: readonly DecisionInputV2[], policy: Partial<UtilityPolicy> = {}): readonly RankedDecisionCandidate[] { const pairWins = inputs.map((input, index) => inputs.reduce((wins, opponent, opponentIndex) => index === opponentIndex ? wins : wins + this.rankPairwise(input, opponent).leftProbability, 0)); return immutable(inputs.map((input, index) => { const prediction = this.predict(input, policy), constraint = this.gate.evaluate(input.context, input.candidate); return { candidate: input.candidate, prediction: prediction as MultiHeadPrediction, excluded: !constraint.allowed || prediction.uncertaintyV2.critical, exclusions: [...constraint.exclusions, ...(prediction.uncertaintyV2.critical ? ['CRITICAL_UNCERTAINTY'] : [])], rank: 0, pairwiseScore: pairWins[index] }; }).sort((a, b) => Number(a.excluded) - Number(b.excluded) || b.pairwiseScore - a.pairwiseScore || b.prediction.expectedUtility - a.prediction.expectedUtility || a.candidate.id.localeCompare(b.candidate.id)).map((row, index) => ({ ...row, rank: index + 1 }))); }
  counterfactual(chosen: DecisionInputV2, alternative: DecisionInputV2): CounterfactualResultV2 { const a = this.predict(chosen), b = this.predict(alternative), delta = b.expectedUtility - a.expectedUtility; return immutable({ chosen: a, alternative: b, utilityDelta: delta, qualityDelta: b.quality - a.quality, costDelta: b.cost - a.cost, latencyDelta: b.latency - a.latency, acceptanceDelta: b.acceptanceProbability - a.acceptanceProbability, recommendation: delta > .02 ? `Prefer ${alternative.candidate.id}` : delta < -.02 ? `Keep ${chosen.candidate.id}` : 'Equivalent under current policy' }); }
  version() { return this.modelVersion; }
  static train(pairwise: readonly PairwiseExampleV2[], listwise: readonly ListwiseExampleV2[] = [], options: { version?: string; epochs?: number; learningRate?: number; records?: readonly DecisionDatasetRecord[] } = {}) { const base = new CompactNeuralDecisionRankerV2(options.version ?? 'neural-ranker-v2.1'), mutable = structuredClone(base.state) as { hidden: number[][]; biases: number[]; output: Record<Head, number[]>; outputBias: Record<Head, number>; coverage: Record<string, number> }, examples = [...pairwise]; for (const list of listwise) for (let left = 0; left < list.candidates.length; left++) for (let right = left + 1; right < list.candidates.length; right++) examples.push({ context: list.context, left: list.candidates[left], right: list.candidates[right], preferred: list.relevance[left] === list.relevance[right] ? 'TIE' : list.relevance[left] > list.relevance[right] ? 'LEFT' : 'RIGHT', source: 'OUTCOME', weight: 1 }); const rate = options.learningRate ?? .05;
    for (let epoch = 0; epoch < (options.epochs ?? 20); epoch++) { for (const example of examples) { const leftHidden = base.hidden(example.left), rightHidden = base.hidden(example.right), target = example.preferred === 'LEFT' ? 1 : example.preferred === 'RIGHT' ? 0 : .5, prediction = sigmoid(linear(mutable.output.rank, leftHidden.map((value, index) => value - rightHidden[index]), mutable.outputBias.rank)), error = (target - prediction) * example.weight; mutable.output.rank.forEach((_, index) => mutable.output.rank[index] += rate * error * (leftHidden[index] - rightHidden[index])); mutable.outputBias.rank += rate * error; for (const input of [example.left, example.right]) { const key = `${input.context.operation}|${input.context.deviceClass}|${input.candidate.model}|${input.candidate.provider}`; mutable.coverage[key] = (mutable.coverage[key] ?? 0) + 1; } }
      for (const record of options.records ?? []) { const input: DecisionInputV2 = record.features, hidden = base.hidden(input), outcome = record.actualOutcome, targets: Record<Exclude<Head, 'rank'>, number> = { quality: outcome.quality, success: Number(outcome.success), acceptance: Number(outcome.accepted), cost: clamp(outcome.cost / 100), latency: clamp(outcome.latency / 60_000), escalation: Number(outcome.escalated), satisfaction: clamp(outcome.satisfaction ?? (Number(outcome.accepted) - Number(outcome.undone) * .5 - Number(outcome.corrected) * .25)), regret: clamp(Math.max(0, 1 - record.reward / 10)) }; for (const head of heads.filter(value => value !== 'rank') as Exclude<Head, 'rank'>[]) { const error = targets[head] - sigmoid(linear(mutable.output[head], hidden, mutable.outputBias[head])); mutable.output[head].forEach((_, index) => mutable.output[head][index] += rate * .25 * error * hidden[index]); mutable.outputBias[head] += rate * .25 * error; } const key = `${input.context.operation}|${input.context.deviceClass}|${input.candidate.model}|${input.candidate.provider}`; mutable.coverage[key] = (mutable.coverage[key] ?? 0) + 1; }
    }
    return new CompactNeuralDecisionRankerV2(options.version ?? 'neural-ranker-v2.1', base.encoder, new DecisionConstraintLayer(), new DecisionCalibrationV2(), immutable(mutable)); }
  distill(samples: readonly DecisionInputV2[]): DistilledModelV2 { const pairs: PairwiseExampleV2[] = []; for (let index = 0; index + 1 < samples.length; index += 2) { const prediction = this.rankPairwise(samples[index], samples[index + 1]); pairs.push({ context: samples[index].context, left: samples[index], right: samples[index + 1], preferred: prediction.preferred, source: 'COUNTERFACTUAL', weight: prediction.confidence }); } const student = CompactNeuralDecisionRankerV2.train(pairs, [], { version: `${this.version()}-student`, epochs: 8 }); const fidelity = mean(pairs.map(pair => Number(student.rankPairwise(pair.left, pair.right).preferred === pair.preferred))); return immutable({ teacherVersion: this.version(), student, sampleCount: samples.length, fidelity }); }
}
