import { immutable } from './immutable';
import type { DecisionModelV1, ModelManifest, ModelMetrics, ModelStatus } from './types';
type Entry = Readonly<{ manifest: ModelManifest; model: DecisionModelV1 }>;
export class DecisionModelRegistry {
  private entries = new Map<string, Entry>();
  register(model: DecisionModelV1, metadata: Omit<ModelManifest, 'modelVersion' | 'status'> & { status?: ModelStatus }) { if (this.entries.has(model.version())) throw new Error(`Model ${model.version()} is already registered`); const entry = immutable({ model, manifest: { ...metadata, modelVersion: model.version(), status: metadata.status ?? 'CANDIDATE' } }); this.entries.set(model.version(), entry); return entry.manifest; }
  get(version: string) { return this.entries.get(version); }
  list() { return immutable([...this.entries.values()].map(entry => entry.manifest)); }
  active() { return [...this.entries.values()].find(entry => entry.manifest.status === 'ACTIVE'); }
  transition(version: string, status: ModelStatus) { const entry = this.required(version); const allowed: Record<ModelStatus, readonly ModelStatus[]> = { CANDIDATE: ['CANARY', 'REJECTED'], CANARY: ['ACTIVE', 'REJECTED', 'ROLLED_BACK'], ACTIVE: ['DEPRECATED', 'ROLLED_BACK'], DEPRECATED: [], REJECTED: [], ROLLED_BACK: [] }; if (!allowed[entry.manifest.status].includes(status)) throw new Error(`Invalid model transition ${entry.manifest.status} -> ${status}`); if (status === 'ACTIVE') for (const [key, existing] of this.entries) if (existing.manifest.status === 'ACTIVE') this.entries.set(key, immutable({ ...existing, manifest: { ...existing.manifest, status: 'DEPRECATED' } })); const changed = immutable({ ...entry, manifest: { ...entry.manifest, status } }); this.entries.set(version, changed); return changed.manifest; }
  promote(version: string) { return this.transition(version, 'ACTIVE'); }
  rollback(version: string) { const rolled = this.transition(version, 'ROLLED_BACK'); const parent = this.entries.get(rolled.parentModel ?? ''); if (parent && ['DEPRECATED', 'CANARY'].includes(parent.manifest.status)) this.entries.set(parent.manifest.modelVersion, immutable({ ...parent, manifest: { ...parent.manifest, status: 'ACTIVE' } })); return rolled; }
  evaluateCanary(version: string, baseline: ModelMetrics, thresholds = { qualityDrop: .03, acceptanceDrop: .03, costIncrease: .1, latencyIncrease: .1, regretIncrease: .03 }) { const entry = this.required(version), metrics = entry.manifest.metrics; const bad = metrics.qualityPredictionError > baseline.qualityPredictionError + thresholds.qualityDrop || metrics.acceptancePredictionError > baseline.acceptancePredictionError + thresholds.acceptanceDrop || metrics.costPredictionError > baseline.costPredictionError * (1 + thresholds.costIncrease) || metrics.latencyPredictionError > baseline.latencyPredictionError * (1 + thresholds.latencyIncrease) || metrics.decisionRegret > baseline.decisionRegret + thresholds.regretIncrease; return bad ? this.rollback(version) : this.promote(version); }
  private required(version: string) { const entry = this.entries.get(version); if (!entry) throw new Error(`Unknown model ${version}`); return entry; }
}
