import { DecisionFeatureEncoderV1 } from './DecisionFeatureEncoderV1';
import { immutable, clamp, round } from './immutable';
import type { ActualOutcome, DecisionCandidate, DecisionContext, DecisionDatasetRecord, DecisionHistoryFeatures, UtilityPolicy } from './types';

export interface DecisionExperience { context: DecisionContext; candidate: DecisionCandidate; decision?: string; actualOutcome: ActualOutcome; history?: Partial<DecisionHistoryFeatures>; timestamp?: number; modelVersion?: string }
export const DEFAULT_REWARD_POLICY: UtilityPolicy = immutable({ quality: .25, success: .2, acceptance: .2, latency: .1, cost: .1, escalation: .05, privacy: .05, unnecessaryAI: .05 });
export class DecisionDatasetBuilder {
  constructor(private readonly encoder = new DecisionFeatureEncoderV1(), private readonly now: () => number = () => Date.now()) {}
  reward(outcome: ActualOutcome, context: DecisionContext, candidate: DecisionCandidate, policy: Partial<UtilityPolicy> = {}): number {
    const p = { ...DEFAULT_REWARD_POLICY, ...policy }; const speed = 1 - clamp(outcome.latency / Math.max(1, context.latencyTarget)); const efficiency = 1 - clamp(outcome.cost / Math.max(.001, context.budget));
    const privacy = context.privacyMode === 'LOCAL_ONLY' ? Number(candidate.executionTarget === 'LOCAL') : 1;
    return round(p.quality * clamp(outcome.quality) + p.success * Number(Boolean(outcome.success)) + p.acceptance * Number(Boolean(outcome.accepted)) + p.latency * speed + p.cost * efficiency + p.privacy * privacy - p.escalation * Number(Boolean(outcome.escalated)) - p.unnecessaryAI * Number(Boolean(outcome.unnecessaryAI)));
  }
  build(experiences: readonly DecisionExperience[]): readonly DecisionDatasetRecord[] { return immutable(experiences.map((item) => ({ features: this.encoder.encode(item.context, item.candidate, item.history), context: immutable({ ...item.context }), candidate: immutable({ ...item.candidate }), decision: item.decision ?? item.candidate.id, actualOutcome: immutable({ ...item.actualOutcome }), reward: this.reward(item.actualOutcome, item.context, item.candidate), timestamp: item.timestamp ?? item.context.timestamp ?? this.now(), modelVersion: item.modelVersion ?? 'baseline-v0', projectId: item.context.projectId ?? 'unknown-project', deviceId: item.context.deviceId ?? 'unknown-device' }))); }
  fromOutcomes(outcomes: readonly Record<string, unknown>[]): readonly DecisionDatasetRecord[] { return this.build(outcomes.map((raw, index) => { const metadata = (raw.metadata ?? {}) as Record<string, unknown>; const target = String(raw.selectedTarget ?? raw.target ?? 'LOCAL'); return { context: { operation: String(raw.operation ?? raw.operationId ?? 'unknown'), intent: String(metadata.intent ?? 'unknown'), goal: String(metadata.goal ?? 'unknown'), deviceClass: String(raw.deviceClass ?? 'unknown'), platform: String(raw.platform ?? 'unknown'), projectType: String(metadata.projectType ?? 'unknown'), privacyMode: String(raw.policy ?? metadata.privacyMode ?? 'STANDARD'), budget: Number(metadata.budget ?? raw.estimatedCloudCost ?? 1), latencyTarget: Number(metadata.latencyTarget ?? 10000), qualityTarget: Number(metadata.qualityTarget ?? .7), projectId: String((raw.scope as Record<string, unknown> | undefined)?.projectId ?? metadata.projectId ?? `project-${index}`), deviceId: String(metadata.deviceId ?? raw.deviceClass ?? 'unknown'), timestamp: Number(raw.timestamp ?? this.now()) }, candidate: { id: String(raw.model ?? `candidate-${index}`), executionTarget: (['LOCAL','CLOUD','HYBRID'].includes(target) ? target : 'LOCAL') as 'LOCAL', model: String(raw.model ?? 'unknown'), provider: String(raw.provider ?? 'unknown'), runtime: String(metadata.runtime ?? 'unknown'), estimatedQuality: Number(raw.baselineQuality ?? raw.actualQuality ?? raw.quality ?? .5), estimatedLatency: Number(raw.durationMs ?? raw.actualLatency ?? 0), estimatedCost: Number(raw.actualCost ?? 0), energy: Number(raw.energyWh ?? 0), memory: Number(raw.ramMb ?? 0), reliability: Number(metadata.reliability ?? .5) }, actualOutcome: { success: ['SUCCESS','ACCEPTED'].includes(String(raw.actualOutcome ?? raw.outcome)), quality: Number(raw.actualQuality ?? raw.quality ?? 0), latency: Number(raw.actualLatency ?? raw.durationMs ?? 0), cost: Number(raw.actualCost ?? 0), accepted: Boolean(raw.userAccepted) || String(raw.userReaction) === 'ACCEPTED', undone: Boolean(raw.undone) || String(raw.userReaction) === 'UNDO', corrected: Boolean(raw.corrected) || String(raw.userReaction) === 'CORRECTED', escalated: Boolean(metadata.escalated) }, timestamp: Number(raw.timestamp ?? this.now()), modelVersion: String(metadata.modelVersion ?? 'baseline-v0') }; })); }
}
