import { immutable } from './immutable';
import type { DecisionDatasetRecord } from './types';
import type { DecisionInputV2, ListwiseExampleV2, PairwiseExampleV2 } from './v2-types';
const input = (record: DecisionDatasetRecord): DecisionInputV2 => ({ ...record.features, recentOutcomes: [], device: { deviceId: record.deviceId, deviceClass: record.context.deviceClass, runtime: record.candidate.runtime, memoryMb: record.candidate.memory, imageMegapixels: 1, computeScore: .5, thermalPressure: 0, isNew: false } });
export class DecisionRankingDatasetBuilderV2 {
  pairwise(records: readonly DecisionDatasetRecord[]): readonly PairwiseExampleV2[] { const grouped = this.groups(records), result: PairwiseExampleV2[] = []; for (const rows of grouped.values()) for (let left = 0; left < rows.length; left++) for (let right = left + 1; right < rows.length; right++) { const difference = rows[left].reward - rows[right].reward; result.push({ context: rows[left].context, left: input(rows[left]), right: input(rows[right]), preferred: Math.abs(difference) < .001 ? 'TIE' : difference > 0 ? 'LEFT' : 'RIGHT', source: 'OUTCOME', weight: Math.min(2, Math.max(.1, Math.abs(difference))) }); } return immutable(result); }
  listwise(records: readonly DecisionDatasetRecord[]): readonly ListwiseExampleV2[] { return immutable([...this.groups(records).values()].filter(rows => rows.length > 1).map(rows => ({ context: rows[0].context, candidates: rows.map(input), relevance: rows.map(row => row.reward) }))); }
  humanPreference(left: DecisionDatasetRecord, right: DecisionDatasetRecord, selectedId: string): PairwiseExampleV2 { if (selectedId !== left.candidate.id && selectedId !== right.candidate.id) throw new Error('Selected candidate must belong to the preference pair'); return immutable({ context: left.context, left: input(left), right: input(right), preferred: selectedId === left.candidate.id ? 'LEFT' : 'RIGHT', source: 'HUMAN_PREFERENCE', weight: 1.5 }); }
  private groups(records: readonly DecisionDatasetRecord[]) { const groups = new Map<string, DecisionDatasetRecord[]>(); for (const record of records) { const key = `${record.projectId}|${record.context.operation}|${record.timestamp}`; const rows = groups.get(key) ?? []; rows.push(record); groups.set(key, rows); } return groups; }
}
