import { DecisionFeatureEncoderV1 } from './DecisionFeatureEncoderV1';
import { DecisionModelEvaluator } from './DecisionModelEvaluator';
import { immutable, round } from './immutable';
import { TabularDecisionModelV1 } from './TabularDecisionModelV1';
import type { DecisionDatasetRecord, ModelMetrics } from './types';
export interface DatasetSplit { train: readonly DecisionDatasetRecord[]; validation: readonly DecisionDatasetRecord[]; test: readonly DecisionDatasetRecord[] }
export interface TrainingResult { model: TabularDecisionModelV1; split: DatasetSplit; metrics: Readonly<ModelMetrics> }
export class DecisionTrainerV1 {
  constructor(private readonly encoder = new DecisionFeatureEncoderV1(), private readonly evaluator = new DecisionModelEvaluator(), private readonly now: () => number = () => Date.now()) {}
  validate(records: readonly DecisionDatasetRecord[]): readonly string[] { const errors: string[] = []; records.forEach((r, i) => { if (r.features.length !== this.encoder.featureNames.length) errors.push(`record ${i}: feature length`); if (!r.projectId || !r.deviceId) errors.push(`record ${i}: split identity`); if (r.features.some((v) => !Number.isFinite(v))) errors.push(`record ${i}: non-finite feature`); }); return immutable(errors); }
  split(records: readonly DecisionDatasetRecord[]): DatasetSplit { const projects = [...new Set(records.map((r) => r.projectId))].sort(); const devices = [...new Set(records.map((r) => r.deviceId))].sort(); const projectBucket = (id: string) => projects.indexOf(id) % 10; const deviceBucket = (id: string) => devices.indexOf(id) % 10; const ordered = [...records].sort((a, b) => a.timestamp - b.timestamp); const cutoff = ordered[Math.floor(ordered.length * .8)]?.timestamp ?? Infinity; const test = ordered.filter((r) => projectBucket(r.projectId) >= 8 || deviceBucket(r.deviceId) >= 8 || r.timestamp >= cutoff); const validation = ordered.filter((r) => !test.includes(r) && (projectBucket(r.projectId) >= 6 || deviceBucket(r.deviceId) >= 6)); const train = ordered.filter((r) => !test.includes(r) && !validation.includes(r)); return immutable({ train, validation, test }); }
  train(records: readonly DecisionDatasetRecord[], modelVersion = 'v1'): TrainingResult { const errors = this.validate(records); if (errors.length) throw new Error(`Invalid decision dataset: ${errors.join(', ')}`); const split = this.split(records); const source = split.train.length ? split.train : records; const centroid = this.encoder.featureNames.map((_, i) => round(source.reduce((sum, row) => sum + row.features[i], 0) / Math.max(1, source.length))); const model = new TabularDecisionModelV1({ trainingCentroid: centroid, metadata: { modelVersion, datasetVersion: `dataset-v1-${records.length}`, createdAt: this.now() } }, this.encoder); const metrics = this.evaluator.evaluate(model, split.test.length ? split.test : records); return immutable({ model, split, metrics }); }
}
