import { DecisionConstraintLayer } from './DecisionConstraintLayer';
import { DecisionRepresentationEncoderV2 } from './DecisionRepresentationEncoderV2';
import { immutable, mean } from './immutable';
import type { DecisionFeaturesV2, ListwiseExample, MultiHeadPredictionV2, PairwisePreference, UncertaintyV2 } from './types';

const clamp = (n: number) => Math.max(0, Math.min(1, n));
const sigmoid = (n: number) => 1 / (1 + Math.exp(-Math.max(-20, Math.min(20, n))));
export interface NeuralDecisionRankerContract { predict(features: DecisionFeaturesV2): MultiHeadPredictionV2; compare(a: DecisionFeaturesV2, b: DecisionFeaturesV2): number; rank(candidates: readonly DecisionFeaturesV2[]): readonly DecisionFeaturesV2[]; trainPairwise(examples: readonly PairwisePreference[]): unknown; trainListwise(examples: readonly ListwiseExample[]): unknown; version(): string }

export class NeuralDecisionRanker implements NeuralDecisionRankerContract {
  private weights: number[] = []; private evidence = 0;
  constructor(private readonly encoder = new DecisionRepresentationEncoderV2(), private readonly modelVersion = 'neural-decision-ranker-v2.0.0', private readonly gate = new DecisionConstraintLayer()) {}
  version() { return this.modelVersion; }
  private vector(features: DecisionFeaturesV2) { return this.encoder.encode(features); }
  private score(features: DecisionFeaturesV2) { const representation = this.vector(features); if (!this.weights.length) this.weights = representation.vector.map((_, i) => ((i * 17) % 11 - 5) / 100); return representation.vector.reduce((sum, value, index) => sum + value * (this.weights[index] ?? 0), 0) + features.candidate.estimatedQuality * 1.5 + features.candidate.reliability - features.candidate.estimatedCost / Math.max(1, features.context.budget) - features.candidate.estimatedLatency / Math.max(1, features.context.latencyTarget) * .25; }
  uncertainty(features: DecisionFeaturesV2): UncertaintyV2 { const representation = this.vector(features), aleatoric = clamp((1 - features.candidate.reliability) * .7 + features.history.undoRate * .3), epistemic = clamp((1 - representation.coverage) * (this.evidence < 20 ? 1 : .6)), oodScore = clamp(representation.coldStart.length / 4 * .7 + epistemic * .3), confidence = clamp(1 - mean([aleatoric, epistemic, oodScore])); return immutable({ aleatoric, epistemic, dataCoverage: representation.coverage, oodScore, confidence, critical: oodScore >= .8, recommendedAction: oodScore >= .8 ? (features.context.privacyMode === 'LOCAL_ONLY' ? 'LOCAL_FIRST' : 'SHOW_PREVIEW') : undefined }); }
  predict(features: DecisionFeaturesV2): MultiHeadPredictionV2 { const utility = this.score(features), uncertaintyV2 = this.uncertainty(features), quality = clamp(features.candidate.estimatedQuality * .75 + sigmoid(utility) * .25), successProbability = clamp(features.candidate.reliability * .65 + features.history.modelSuccessRate * .35), acceptanceProbability = clamp(quality * .5 + features.history.acceptanceRate * .35 + (1 - features.history.undoRate) * .15), satisfaction = clamp(acceptanceProbability * .45 + quality * .3 + (1 - features.history.undoRate) * .15 + (features.preferences ? mean(Object.values(features.preferences)) * .1 : .05)); const cost = Math.max(0, features.candidate.estimatedCost), latency = Math.max(0, features.candidate.estimatedLatency), escalationProbability = clamp(1 - successProbability), expectedUtility = utility + satisfaction; return immutable({ quality, successProbability, acceptanceProbability, latency, cost, escalationProbability, satisfaction, regret: clamp(1 - sigmoid(expectedUtility)), expectedUtility, predictionConfidence: uncertaintyV2.confidence, calibration: uncertaintyV2.confidence, uncertainty: 1 - uncertaintyV2.confidence, ood: uncertaintyV2.oodScore >= .8, recommendedAction: uncertaintyV2.recommendedAction, uncertaintyV2 }); }
  compare(a: DecisionFeaturesV2, b: DecisionFeaturesV2) { return sigmoid(this.score(a) - this.score(b)); }
  rank(candidates: readonly DecisionFeaturesV2[]) { return immutable([...candidates].sort((a, b) => { const ga = this.gate.evaluate(a.context, a.candidate).allowed, gb = this.gate.evaluate(b.context, b.candidate).allowed; return Number(gb) - Number(ga) || this.compare(b, a) - this.compare(a, b) || a.candidate.id.localeCompare(b.candidate.id); })); }
  trainPairwise(examples: readonly PairwisePreference[], learningRate = .08) { for (const example of examples) { const a = this.vector(example.preferred).vector, b = this.vector(example.rejected).vector; if (!this.weights.length) this.weights = a.map(() => 0); const error = 1 - sigmoid(a.reduce((sum, value, i) => sum + (value - (b[i] ?? 0)) * (this.weights[i] ?? 0), 0)); const sourceWeight = example.source === 'HUMAN_PREFERENCE' ? .7 : 1; this.weights = this.weights.map((weight, i) => weight + learningRate * error * (a[i] - (b[i] ?? 0)) * (example.weight ?? 1) * sourceWeight); this.evidence++; } return immutable({ examples: examples.length, evidence: this.evidence, objective: 'pairwise-logistic' }); }
  trainListwise(examples: readonly ListwiseExample[], learningRate = .04) { let pairs = 0; for (const list of examples) for (let i = 0; i < list.candidates.length; i++) for (let j = 0; j < list.candidates.length; j++) if ((list.relevance[i] ?? 0) > (list.relevance[j] ?? 0)) { this.trainPairwise([{ preferred: list.candidates[i], rejected: list.candidates[j], source: 'OUTCOME', weight: (list.relevance[i] ?? 0) - (list.relevance[j] ?? 0) }], learningRate); pairs++; } return immutable({ lists: examples.length, pairs, objective: 'listwise-soft-rank' }); }
  distill(examples: readonly DecisionFeaturesV2[]) { const values = examples.map(item => this.predict(item).expectedUtility); return immutable({ teacher: this.version(), student: 'compact-linear-student-v2', samples: examples.length, meanTeacherUtility: mean(values), weights: this.weights }); }
}
