import { DecisionConstraintLayer } from './DecisionConstraintLayer';
import { DecisionRepresentationEncoderV2 } from './DecisionRepresentationEncoderV2';
import { clamp, immutable, mean } from './immutable';
import type { DecisionCandidateV1, DecisionContextV1, DecisionDatasetRecord, DecisionFeaturesV1, DecisionHistoryV1, DecisionModelExplanation, DecisionModelV1, MultiHeadPrediction, UtilityPolicy } from './types';

const HISTORY: DecisionHistoryV1 = Object.freeze({ modelSuccessRate: .5, providerSuccessRate: .5, deviceSpecificSuccessRate: .5, cloudAvoidance: .5, acceptanceRate: .5, undoRate: 0, sampleCount: 0 });
const POLICY: UtilityPolicy = Object.freeze({ quality: 3, success: 2, acceptance: 1.5, latency: 1, cost: 1, escalation: .5 });
type LearnedState = Readonly<{ weights: readonly number[]; bias: number; sampleCount: number; residual: number }>;
export interface PairwisePreference { readonly preferred: DecisionFeaturesV1; readonly rejected: DecisionFeaturesV1; readonly weight?: number; readonly signal?: 'OUTCOME' | 'HUMAN_PREFERENCE' }

/** Replaceable pairwise/listwise ranking contract. */
export interface NeuralDecisionRankerContract {
  rankPairwise(a: DecisionFeaturesV1, b: DecisionFeaturesV1): Readonly<{ winner: string; probabilityA: number; margin: number }>;
  rank(context: DecisionContextV1, candidates: readonly DecisionCandidateV1[], history?: Partial<DecisionHistoryV1>): ReturnType<DecisionModelV1['rank']>;
  predictList(items: readonly DecisionFeaturesV1[]): readonly Readonly<{ features: DecisionFeaturesV1; score: number; rank: number }>[];
}

/** Compact linear neural ranker over a nonlinear, interaction-aware representation. */
export class NeuralDecisionRanker implements DecisionModelV1, NeuralDecisionRankerContract {
  private readonly gate: DecisionConstraintLayer;
  constructor(private readonly modelVersion = 'decision-model-v2.0', private readonly state: LearnedState = { weights: [], bias: 0, sampleCount: 0, residual: .25 }, private readonly encoder = new DecisionRepresentationEncoderV2(), gate = new DecisionConstraintLayer()) { this.gate = gate; }
  static train(records: readonly DecisionDatasetRecord[], options: { modelVersion?: string; epochs?: number; learningRate?: number } = {}) {
    if (!records.length) throw new Error('Training dataset cannot be empty');
    const grouped = new Map<string, DecisionDatasetRecord[]>(); for (const row of records) { const rows = grouped.get(row.projectId) ?? []; rows.push(row); grouped.set(row.projectId, rows); }
    const preferences: PairwisePreference[] = [];
    for (const rows of grouped.values()) for (let i = 0; i < rows.length; i++) for (let j = i + 1; j < rows.length; j++) if (rows[i].reward !== rows[j].reward) preferences.push({ preferred: rows[i].reward > rows[j].reward ? rows[i].features : rows[j].features, rejected: rows[i].reward > rows[j].reward ? rows[j].features : rows[i].features, signal: 'OUTCOME' });
    return this.trainPairwise(preferences, { ...options, sampleCount: records.length });
  }
  static trainPairwise(preferences: readonly PairwisePreference[], options: { modelVersion?: string; epochs?: number; learningRate?: number; sampleCount?: number } = {}) {
    if (!preferences.length) return new NeuralDecisionRanker(options.modelVersion);
    const encoder = new DecisionRepresentationEncoderV2(), length = encoder.encode(preferences[0].preferred).vector.length, weights = Array(length).fill(0), learningRate = options.learningRate ?? .08;
    for (let epoch = 0; epoch < (options.epochs ?? 24); epoch++) for (const pair of preferences) { const a = encoder.encode(pair.preferred).vector, b = encoder.encode(pair.rejected).vector, margin = weights.reduce((sum, weight, index) => sum + weight * (a[index] - b[index]), 0), error = 1 / (1 + Math.exp(margin)); for (let index = 0; index < length; index++) weights[index] += learningRate * (pair.weight ?? 1) * error * (a[index] - b[index]); }
    return new NeuralDecisionRanker(options.modelVersion ?? 'decision-model-v2.0', { weights: immutable(weights), bias: 0, sampleCount: options.sampleCount ?? preferences.length, residual: 1 / Math.sqrt(preferences.length + 1) }, encoder);
  }
  private score(features: DecisionFeaturesV1) { const vector = this.encoder.encode(features).vector; return this.state.bias + vector.reduce((sum, value, index) => sum + value * (this.state.weights[index] ?? 0), 0); }
  predict(features: DecisionFeaturesV1, policy: Partial<UtilityPolicy> = {}): MultiHeadPrediction {
    const { candidate, history, context } = features, cold = (history.sampleCount ?? 0) < 5, coverage = clamp((history.sampleCount ?? 0) / 25), learned = 1 / (1 + Math.exp(-this.score(features))), quality = clamp(candidate.estimatedQuality * .55 + learned * .25 + history.modelSuccessRate * .2), successProbability = clamp(candidate.reliability * .55 + history.providerSuccessRate * .25 + learned * .2), acceptanceProbability = clamp(quality * .45 + history.acceptanceRate * .35 + learned * .2), satisfaction = clamp(acceptanceProbability * .5 + quality * .3 + (1 - history.undoRate) * .2), cost = Math.max(0, candidate.estimatedCost), latency = Math.max(0, candidate.estimatedLatency), escalationProbability = clamp(1 - successProbability), aleatoric = clamp(this.state.residual), epistemic = clamp((1 - coverage) * .8), oodScore = clamp((cold ? .35 : 0) + Number(!candidate.runtimeSupported) * .7), uncertainty = clamp(aleatoric * .45 + epistemic * .45 + oodScore * .1), weights = { ...POLICY, ...policy };
    const expectedUtility = weights.quality * quality + weights.success * successProbability + weights.acceptance * acceptanceProbability - weights.cost * clamp(cost / Math.max(context.budget, .01)) - weights.latency * clamp(latency / Math.max(context.latencyTarget, 1)) - weights.escalation * escalationProbability;
    const recommendedAction = uncertainty > .8 ? 'FALLBACK_TO_HEURISTIC' : uncertainty > .62 ? 'ASK_USER' : uncertainty > .45 ? 'SHOW_PREVIEW' : undefined;
    return immutable({ quality, successProbability, acceptanceProbability, satisfaction, regret: clamp(1 - satisfaction), latency, cost, escalationProbability, expectedUtility, predictionConfidence: clamp(1 - uncertainty), calibration: clamp(1 - aleatoric), uncertainty, aleatoricUncertainty: aleatoric, epistemicUncertainty: epistemic, dataCoverage: coverage, oodScore, ood: oodScore > .65, confidenceByHead: { quality: clamp(1 - aleatoric), acceptance: clamp(1 - uncertainty), cost: .9, latency: .9, utility: clamp(1 - uncertainty) }, recommendedAction });
  }
  rankPairwise(a: DecisionFeaturesV1, b: DecisionFeaturesV1) { const margin = this.predict(a).expectedUtility - this.predict(b).expectedUtility, probabilityA = 1 / (1 + Math.exp(-margin)); return immutable({ winner: probabilityA >= .5 ? a.candidate.id : b.candidate.id, probabilityA, margin }); }
  predictList(items: readonly DecisionFeaturesV1[]) { return immutable(items.map(features => ({ features, score: this.predict(features).expectedUtility, rank: 0 })).sort((a, b) => b.score - a.score || a.features.candidate.id.localeCompare(b.features.candidate.id)).map((row, index) => ({ ...row, rank: index + 1 }))); }
  rank(context: DecisionContextV1, candidates: readonly DecisionCandidateV1[], history: Partial<DecisionHistoryV1> = {}, policy: Partial<UtilityPolicy> = {}) { return immutable(candidates.map(candidate => { const constraint = this.gate.evaluate(context, candidate), prediction = this.predict({ context, candidate, history: { ...HISTORY, ...history } }, policy); return { candidate, prediction, excluded: !constraint.allowed, exclusions: constraint.exclusions, rank: 0 }; }).sort((a, b) => Number(a.excluded) - Number(b.excluded) || b.prediction.expectedUtility - a.prediction.expectedUtility || a.candidate.id.localeCompare(b.candidate.id)).map((row, index) => ({ ...row, rank: index + 1 }))); }
  counterfactual(selected: DecisionFeaturesV1, alternative: DecisionFeaturesV1) { const selectedPrediction = this.predict(selected), alternativePrediction = this.predict(alternative); return immutable({ selected: selectedPrediction, alternative: alternativePrediction, utilityDelta: alternativePrediction.expectedUtility - selectedPrediction.expectedUtility, preferred: alternativePrediction.expectedUtility > selectedPrediction.expectedUtility ? alternative.candidate.id : selected.candidate.id }); }
  calibrate(records: readonly DecisionDatasetRecord[]) { const error = mean(records.map(row => Math.abs(this.predict(row.features).acceptanceProbability - Number(row.actualOutcome.accepted)))); return immutable({ version: `${this.version()}:calibration`, sampleCount: records.length, qualityConfidence: clamp(1 - error), acceptanceConfidence: clamp(1 - error), costConfidence: .9, latencyConfidence: .9, utilityConfidence: clamp(1 - error), reliabilityCurve: [0, .25, .5, .75, 1].map(bin => immutable({ predicted: bin, observed: clamp(bin + error * (bin < .5 ? 1 : -1)) })) }); }
  distill(records: readonly DecisionDatasetRecord[], version = `${this.version()}-student`) { const synthetic = records.map(row => ({ ...row, reward: this.predict(row.features).expectedUtility })); return NeuralDecisionRanker.train(synthetic, { modelVersion: version, epochs: 8 }); }
  estimateReward(features: DecisionFeaturesV1, policy?: Partial<UtilityPolicy>) { return this.predict(features, policy).expectedUtility; } estimateQuality(features: DecisionFeaturesV1) { return this.predict(features).quality; } estimateCost(features: DecisionFeaturesV1) { return this.predict(features).cost; } estimateLatency(features: DecisionFeaturesV1) { return this.predict(features).latency; } estimateAcceptance(features: DecisionFeaturesV1) { return this.predict(features).acceptanceProbability; }
  explain(features: DecisionFeaturesV1): DecisionModelExplanation { const prediction = this.predict(features), representation = this.encoder.encode(features); return immutable({ modelVersion: this.version(), topInfluentialFeatures: representation.vector.map((value, index) => ({ feature: `representation.${index}`, value, influence: Math.abs(value * (this.state.weights[index] ?? 0)) })).sort((a, b) => b.influence - a.influence).slice(0, 8), candidateScores: [{ candidateId: features.candidate.id, utility: prediction.expectedUtility }], predictedOutcomes: prediction, constraintExclusions: this.gate.evaluate(features.context, features.candidate).exclusions, finalUtility: prediction.expectedUtility, summary: [this.state.sampleCount < 5 ? 'Cold-start global representation and device profile.' : 'Pairwise neural representation ranking.', `Encoder ${this.encoder.version}.`] }); }
  version() { return this.modelVersion; }
}
