import { DecisionConstraintLayer } from './DecisionConstraintLayer';
import { DecisionRepresentationEncoderV2 } from './DecisionRepresentationEncoderV2';
import { clamp, immutable, mean } from './immutable';
import type { DecisionCandidateV1, DecisionContextV1, DecisionFeaturesV1, DecisionHistoryV1, PairwisePreference, UtilityPolicy } from './types';

const HISTORY: DecisionHistoryV1 = Object.freeze({ modelSuccessRate: .5, providerSuccessRate: .5, deviceSpecificSuccessRate: .5, cloudAvoidance: .5, acceptanceRate: .5, undoRate: 0 });
const sigmoid = (value: number) => 1 / (1 + Math.exp(-Math.max(-20, Math.min(20, value))));
export interface NeuralRankerState { readonly weights: readonly number[]; readonly bias: number; readonly examples: number; readonly modelVersion: string }

/** Compact pairwise learner over the nonlinear, fused v2 representation. */
export class NeuralDecisionRanker {
  private readonly gate: DecisionConstraintLayer;
  constructor(readonly state: NeuralRankerState = { weights: [], bias: 0, examples: 0, modelVersion: 'neural-ranker-v2.1' }, readonly encoder = new DecisionRepresentationEncoderV2(), gate = new DecisionConstraintLayer()) { this.gate = gate; }
  score(features: DecisionFeaturesV1) { const vector = this.encoder.encode(features).fused; return this.state.bias + vector.reduce((sum, value, index) => sum + value * (this.state.weights[index] ?? 0), 0); }
  compare(a: DecisionFeaturesV1, b: DecisionFeaturesV1) { const margin = this.score(a) - this.score(b); return immutable({ preferred: margin >= 0 ? a.candidate.id : b.candidate.id, probabilityA: sigmoid(margin), margin }); }
  train(pairs: readonly PairwisePreference[], options: { epochs?: number; learningRate?: number; modelVersion?: string } = {}) { if (!pairs.length) throw new Error('Pairwise training data cannot be empty'); const size = this.encoder.encode(pairs[0].preferred).fused.length, weights = [...this.state.weights, ...Array(size).fill(0)].slice(0, size); let bias = this.state.bias; for (let epoch = 0; epoch < (options.epochs ?? 20); epoch++) for (const pair of pairs) { const a = this.encoder.encode(pair.preferred).fused, b = this.encoder.encode(pair.rejected).fused, error = 1 - sigmoid(a.reduce((sum, value, i) => sum + (value - b[i]) * weights[i], bias)); const rate = (options.learningRate ?? .05) * (pair.weight ?? 1); weights.forEach((_, i) => weights[i] += rate * error * (a[i] - b[i])); bias += rate * error * .001; } return new NeuralDecisionRanker({ weights, bias, examples: this.state.examples + pairs.length, modelVersion: options.modelVersion ?? this.state.modelVersion }, this.encoder, this.gate); }
  trainListwise(lists: readonly (readonly DecisionFeaturesV1[])[], options = {}) { const pairs: PairwisePreference[] = []; for (const list of lists) for (let i = 0; i < list.length; i++) for (let j = i + 1; j < list.length; j++) pairs.push({ preferred: list[i], rejected: list[j], source: 'OUTCOME', weight: 1 / (j - i) }); return pairs.length ? this.train(pairs, options) : this; }
  rank(context: DecisionContextV1, candidates: readonly DecisionCandidateV1[], history: Partial<DecisionHistoryV1> = {}) { return immutable(candidates.map(candidate => { const features = { context, candidate, history: { ...HISTORY, ...history } }, constraint = this.gate.evaluate(context, candidate); return { candidate, features, score: this.score(features), excluded: !constraint.allowed, exclusions: constraint.exclusions }; }).sort((a, b) => Number(a.excluded) - Number(b.excluded) || b.score - a.score || a.candidate.id.localeCompare(b.candidate.id)).map((item, index) => ({ ...item, rank: index + 1 }))); }
  uncertainty(features: DecisionFeaturesV1) { const representation = this.encoder.encode(features), epistemic = clamp(1 / Math.sqrt(this.state.examples + 1) + (1 - representation.coverage) * .5), aleatoric = clamp((1 - features.candidate.reliability + features.history.undoRate) / 2), oodScore = clamp((representation.coldStart.length / 4) * .7 + epistemic * .3); return immutable({ aleatoric, epistemic, dataCoverage: representation.coverage, oodScore, confidence: clamp(1 - mean([aleatoric, epistemic, oodScore])), critical: oodScore > .8, action: oodScore > .8 ? 'FALLBACK_TO_HEURISTIC' as const : oodScore > .6 ? 'SHOW_PREVIEW' as const : undefined }); }
  distill(samples: readonly DecisionFeaturesV1[]) { return immutable({ teacherVersion: this.state.modelVersion, studentType: 'compact-linear', weights: this.state.weights.map(value => Number(value.toFixed(5))), bias: Number(mean(samples.map(sample => this.score(sample))).toFixed(5)), sampleCount: samples.length }); }
}

export class MultiTaskDecisionHeadsV2 {
  predict(features: DecisionFeaturesV1, ranker: NeuralDecisionRanker, policy: Partial<UtilityPolicy> = {}) { const u = ranker.uncertainty(features), quality = clamp((features.candidate.estimatedQuality * 2 + features.history.modelSuccessRate) / 3), successProbability = clamp((features.candidate.reliability + features.history.providerSuccessRate) / 2), acceptanceProbability = clamp((quality + features.history.acceptanceRate + (features.preferenceSignals?.styleAlignment ?? .5)) / 3), satisfaction = clamp((acceptanceProbability * 2 + (1 - features.history.undoRate) + quality) / 4), latency = Math.max(0, features.candidate.estimatedLatency), cost = Math.max(0, features.candidate.estimatedCost), escalationProbability = clamp(1 - successProbability), regret = clamp(1 - satisfaction), p = { quality: 3, success: 2, acceptance: 1.5, latency: 1, cost: 1, escalation: .5, ...policy }, expectedUtility = p.quality * quality + p.success * successProbability + p.acceptance * acceptanceProbability - p.latency * clamp(latency / Math.max(1, features.context.latencyTarget)) - p.cost * clamp(cost / Math.max(.01, features.context.budget)) - p.escalation * escalationProbability + ranker.score(features); return immutable({ quality, successProbability, acceptanceProbability, latency, cost, escalationProbability, satisfaction, regret, expectedUtility, predictionConfidence: u.confidence, calibration: u.confidence, uncertainty: mean([u.aleatoric, u.epistemic]), aleatoricUncertainty: u.aleatoric, epistemicUncertainty: u.epistemic, dataCoverage: u.dataCoverage, oodScore: u.oodScore, ood: u.critical, recommendedAction: u.action }); }
}
