import { DecisionFeatureEncoderV1, FEATURE_NAMES } from './DecisionFeatureEncoderV1';
import { clamp, immutable, round } from './immutable';
import { DEFAULT_REWARD_POLICY } from './DecisionDatasetBuilder';
import type { DecisionCandidate, DecisionConstraints, DecisionContext, DecisionHistoryFeatures, DecisionModelExplanation, DecisionModelV1, DecisionPrediction, DecisionPredictions, ModelMetadata, UtilityPolicy } from './types';

export interface TabularModelConfig { metadata?: Partial<ModelMetadata>; weights?: Partial<Record<keyof DecisionPredictions, readonly number[]>>; uncertaintyThreshold?: number; oodDistance?: number; trainingCentroid?: readonly number[] }
export const decisionConstraintExclusions = (candidate: DecisionCandidate, context: DecisionContext, constraints: DecisionConstraints): readonly string[] => { const reasons: string[] = []; const quarantined = candidate.quarantined || constraints.quarantinedModels?.includes(candidate.model); if (quarantined) reasons.push('QUARANTINED_MODEL'); if (candidate.supported === false || (constraints.supportedRuntimes && !constraints.supportedRuntimes.includes(candidate.runtime))) reasons.push('UNSUPPORTED_RUNTIME'); if (candidate.estimatedCost > (constraints.budget ?? context.budget)) reasons.push('BUDGET_EXCEEDED'); if (candidate.executionTarget === 'CLOUD' && (context.privacyMode === 'LOCAL_ONLY' || constraints.cloudAllowed === false || candidate.cloudPermitted === false)) reasons.push('CLOUD_FORBIDDEN'); return immutable(reasons); };
export class TabularDecisionModelV1 implements DecisionModelV1 {
  private readonly encoder: DecisionFeatureEncoderV1; private readonly metadata: ModelMetadata; private readonly threshold: number; private readonly oodDistance: number; private readonly centroid?: readonly number[];
  constructor(config: TabularModelConfig = {}, encoder = new DecisionFeatureEncoderV1()) { this.encoder = encoder; this.threshold = config.uncertaintyThreshold ?? .42; this.oodDistance = config.oodDistance ?? .42; this.centroid = config.trainingCentroid; this.metadata = immutable({ featureSchemaVersion: encoder.schemaVersion, datasetVersion: 'dataset-v1', trainingConfigVersion: 'tabular-v1', modelVersion: 'v1', metrics: {}, createdAt: 0, ...config.metadata }); }
  private outcomes(context: DecisionContext, candidate: DecisionCandidate, history: Partial<DecisionHistoryFeatures> = {}): DecisionPredictions { const reliability = clamp(candidate.reliability); const model = clamp(history.modelSuccessRate ?? reliability); const provider = clamp(history.providerSuccessRate ?? reliability); const device = clamp(history.deviceSpecificSuccessRate ?? reliability); const acceptance = clamp((history.acceptanceRate ?? .5) * .5 + candidate.estimatedQuality * .35 + reliability * .15 - (history.undoRate ?? 0) * .25); return immutable({ quality: round(clamp(candidate.estimatedQuality * .72 + model * .18 + provider * .1)), successProbability: round(clamp(reliability * .4 + model * .25 + provider * .2 + device * .15)), acceptanceProbability: round(acceptance), latency: round(Math.max(0, candidate.estimatedLatency * (1.1 - device * .2))), cost: round(Math.max(0, candidate.estimatedCost)), escalationProbability: round(clamp(1 - reliability * .55 - device * .25 + (candidate.executionTarget === 'LOCAL' ? .1 : 0))) }); }
  estimateReward(o: DecisionPredictions, policy: Partial<UtilityPolicy> = {}): number { const p = { ...DEFAULT_REWARD_POLICY, ...policy }; return round(p.quality * o.quality + p.success * o.successProbability + p.acceptance * o.acceptanceProbability - p.latency * clamp(o.latency / 60000) - p.cost * clamp(o.cost / 100) - p.escalation * o.escalationProbability); }
  private diagnostics(vector: readonly number[]): { uncertainty: number; ood: boolean } { if (!this.centroid || this.centroid.length !== vector.length) return { uncertainty: .25, ood: false }; const distance = Math.sqrt(vector.reduce((sum, value, i) => sum + (value - (this.centroid?.[i] ?? 0)) ** 2, 0) / vector.length); return { uncertainty: round(clamp(distance * 1.5)), ood: distance > this.oodDistance }; }
  predict(context: DecisionContext, candidate: DecisionCandidate, history: Partial<DecisionHistoryFeatures> = {}): DecisionPrediction { const vector = this.encoder.encode(context, candidate, history); const outcomes = this.outcomes(context, candidate, history); const d = this.diagnostics(vector); const exclusions = decisionConstraintExclusions(candidate, context, {}); const utility = exclusions.length ? -1 : this.estimateReward(outcomes); const action = d.ood ? 'FALLBACK_TO_HEURISTIC' : d.uncertainty > this.threshold ? (context.privacyMode === 'LOCAL_ONLY' ? 'LOCAL_FIRST' : 'SHOW_PREVIEW') : 'EXECUTE'; const explanation = this.makeExplanation(vector, outcomes, utility, exclusions); return immutable({ candidate: immutable({ ...candidate }), outcomes, expectedUtility: utility, predictionConfidence: round(1 - d.uncertainty), calibration: round(clamp(1 - Math.abs(outcomes.successProbability - candidate.reliability))), uncertainty: d.uncertainty, ood: d.ood, action, explanation }); }
  rank(context: DecisionContext, candidates: readonly DecisionCandidate[], history: Partial<DecisionHistoryFeatures> = {}, constraints: DecisionConstraints = {}): readonly DecisionPrediction[] { return immutable(candidates.map((candidate) => { const base = this.predict(context, candidate, history); const exclusions = decisionConstraintExclusions(candidate, context, constraints); return exclusions.length ? immutable({ ...base, expectedUtility: -1, action: 'FALLBACK_TO_HEURISTIC' as const, explanation: immutable({ ...base.explanation, constraintExclusions: exclusions, finalUtility: -1 }) }) : base; }).sort((a, b) => b.expectedUtility - a.expectedUtility || a.candidate.id.localeCompare(b.candidate.id))); }
  private makeExplanation(vector: readonly number[], outcomes: DecisionPredictions, utility: number, exclusions: readonly string[]): DecisionModelExplanation { const top = vector.map((value, index) => ({ feature: FEATURE_NAMES[index], contribution: round(Math.abs(value - .5)) })).sort((a, b) => b.contribution - a.contribution || a.feature.localeCompare(b.feature)).slice(0, 5); return immutable({ topInfluentialFeatures: top, candidateScores: { utility }, predictedOutcomes: outcomes, constraintExclusions: exclusions, finalUtility: utility }); }
  explain(context: DecisionContext, candidate: DecisionCandidate, history: Partial<DecisionHistoryFeatures> = {}): DecisionModelExplanation { return this.predict(context, candidate, history).explanation; }
  estimateQuality(c: DecisionContext, x: DecisionCandidate, h: Partial<DecisionHistoryFeatures> = {}): number { return this.outcomes(c, x, h).quality; }
  estimateCost(c: DecisionContext, x: DecisionCandidate, h: Partial<DecisionHistoryFeatures> = {}): number { return this.outcomes(c, x, h).cost; }
  estimateLatency(c: DecisionContext, x: DecisionCandidate, h: Partial<DecisionHistoryFeatures> = {}): number { return this.outcomes(c, x, h).latency; }
  estimateAcceptance(c: DecisionContext, x: DecisionCandidate, h: Partial<DecisionHistoryFeatures> = {}): number { return this.outcomes(c, x, h).acceptanceProbability; }
  version(): ModelMetadata { return this.metadata; }
}

export class HeuristicBaselineModel extends TabularDecisionModelV1 { constructor() { super({ metadata: { modelVersion: 'v0', trainingConfigVersion: 'adaptive-heuristic-v0' } }); } }
