export type ExecutionTarget = 'LOCAL' | 'CLOUD' | 'HYBRID';
export type PrivacyMode = 'NORMAL' | 'PRIVACY_FIRST' | 'LOCAL_ONLY' | 'OFFLINE_ONLY';
export type ModelStatus = 'TRAINING' | 'VALIDATING' | 'SHADOW' | 'CANDIDATE' | 'CANARY' | 'ACTIVE' | 'DEGRADED' | 'ROLLBACK' | 'RETIRED' | 'DEPRECATED' | 'REJECTED' | 'ROLLED_BACK';
export type UncertaintyAction = 'ASK_USER' | 'LOCAL_FIRST' | 'SHOW_PREVIEW' | 'FALLBACK_TO_HEURISTIC';

export interface DecisionContextV1 { operation: string; intent: string; goal: string; deviceClass: string; platform: string; projectType: string; privacyMode: PrivacyMode; budget: number; latencyTarget: number; qualityTarget: number; projectId?: string; deviceId?: string; timestamp?: number }
export interface DecisionCandidateV1 { id: string; executionTarget: ExecutionTarget; model: string; provider: string; runtime: string; estimatedQuality: number; estimatedLatency: number; estimatedCost: number; energy: number; memory: number; reliability: number; quarantined?: boolean; trusted?: boolean; runtimeSupported?: boolean; outboundDataAllowed?: boolean }
export interface DecisionHistoryV1 { modelSuccessRate: number; providerSuccessRate: number; deviceSpecificSuccessRate: number; cloudAvoidance: number; acceptanceRate: number; undoRate: number }
export interface DecisionFeaturesV1 { context: DecisionContextV1; candidate: DecisionCandidateV1; history: DecisionHistoryV1 }
export interface ActualDecisionOutcome { quality: number; success: boolean; accepted: boolean; latency: number; cost: number; escalated: boolean; undone?: boolean; corrected?: boolean; goalCompletion?: number; satisfaction?: number; risk?: number; unnecessaryAI?: boolean }
export interface DecisionDatasetRecord { id: string; features: DecisionFeaturesV1; context: DecisionContextV1; candidate: DecisionCandidateV1; decision: string; actualOutcome: ActualDecisionOutcome; reward: number; timestamp: number; modelVersion: string; projectId: string; deviceId: string }
export interface RewardPolicy { goalCompletion: number; quality: number; satisfaction: number; costEfficiency: number; speed: number; privacy: number; risk: number; unnecessaryAI: number }
export interface UtilityPolicy { quality: number; success: number; acceptance: number; latency: number; cost: number; escalation: number }
export interface MultiHeadPrediction { quality: number; successProbability: number; acceptanceProbability: number; latency: number; cost: number; escalationProbability: number; expectedUtility: number; predictionConfidence: number; calibration: number; uncertainty: number; ood: boolean; recommendedAction?: UncertaintyAction }
export interface InfluentialFeature { feature: string; value: number; influence: number }
export interface DecisionModelExplanation { modelVersion: string; topInfluentialFeatures: readonly InfluentialFeature[]; candidateScores: readonly { candidateId: string; utility: number }[]; predictedOutcomes: MultiHeadPrediction; constraintExclusions: readonly string[]; finalUtility: number; summary: readonly string[] }
export interface RankedDecisionCandidate { candidate: DecisionCandidateV1; prediction: MultiHeadPrediction; rank: number; excluded: boolean; exclusions: readonly string[] }
export interface DecisionModelV1 { predict(features: DecisionFeaturesV1, policy?: Partial<UtilityPolicy>): MultiHeadPrediction; rank(context: DecisionContextV1, candidates: readonly DecisionCandidateV1[], history?: Partial<DecisionHistoryV1>, policy?: Partial<UtilityPolicy>): readonly RankedDecisionCandidate[]; estimateReward(features: DecisionFeaturesV1, policy?: Partial<UtilityPolicy>): number; estimateQuality(features: DecisionFeaturesV1): number; estimateCost(features: DecisionFeaturesV1): number; estimateLatency(features: DecisionFeaturesV1): number; estimateAcceptance(features: DecisionFeaturesV1): number; explain(features: DecisionFeaturesV1): DecisionModelExplanation; version(): string }
export interface ModelMetrics { rankingQuality: number; predictionError: number; acceptancePredictionError: number; qualityPredictionError: number; costPredictionError: number; latencyPredictionError: number; decisionRegret: number; cloudSavings: number; localSuccess: number; stability: number }
export interface ModelManifest { featureSchemaVersion: string; datasetVersion: string; trainingConfigVersion: string; modelVersion: string; metrics: ModelMetrics; parentModel: string | null; createdAt: number; status: ModelStatus }
export interface ConstraintPolicy { budget: number; privacyMode: PrivacyMode; cloudAllowed: boolean; allowedRuntimes?: readonly string[]; allowedProviders?: readonly string[] }
export interface DatasetSplit { train: readonly DecisionDatasetRecord[]; validation: readonly DecisionDatasetRecord[]; test: readonly DecisionDatasetRecord[] }

export interface HistoricalOutcomeV2 { operation: string; deviceClass: string; model: string; provider: string; quality: number; accepted: boolean; latency: number; cost: number; timestamp: number }
export interface DecisionFeaturesV2 extends DecisionFeaturesV1 { goals?: readonly string[]; constraints?: readonly string[]; preferences?: Readonly<Record<string, number>>; qualityRequirements?: Readonly<Record<string, number>>; recentOutcomes?: readonly HistoricalOutcomeV2[] }
export interface DecisionRepresentationV2 { schemaVersion: string; encoderVersion: string; vector: readonly number[]; blocks: Readonly<Record<string, readonly number[]>>; coverage: number; coldStart: readonly ('NEW_DEVICE' | 'NEW_OPERATION' | 'NEW_MODEL' | 'NEW_PROVIDER')[] }
export interface UncertaintyV2 { aleatoric: number; epistemic: number; dataCoverage: number; oodScore: number; confidence: number; critical: boolean; recommendedAction?: UncertaintyAction }
export interface MultiHeadPredictionV2 extends MultiHeadPrediction { satisfaction: number; regret: number; uncertaintyV2: UncertaintyV2 }
export interface PairwisePreference { preferred: DecisionFeaturesV2; rejected: DecisionFeaturesV2; source: 'OUTCOME' | 'HUMAN_PREFERENCE'; weight?: number }
export interface ListwiseExample { candidates: readonly DecisionFeaturesV2[]; relevance: readonly number[] }
export interface VersionLineageV2 { datasetVersion: string; featureSchemaVersion: string; encoderVersion: string; trainingConfigVersion: string; modelVersion: string; calibrationVersion: string; benchmarkVersion: string }

export type VisualEncoderTarget = 'LOCAL' | 'CLOUD';
export type VisualOperation = 'NONE' | 'SEGMENTATION' | 'RELIGHTING' | 'UPSCALE' | 'BACKGROUND_REPLACEMENT' | 'GENERATION';
export interface VisualAnalysisInput { width: number; height: number; composition?: Readonly<Record<string, number>>; subjectCount?: number; facePresence?: number; objectClasses?: readonly string[]; lighting?: Readonly<Record<string, number>>; colorDistribution?: readonly number[]; backgroundComplexity?: number; estimatedQuality?: number; depthCues?: number; segmentationComplexity?: number; visualStyle?: readonly string[]; sourceAssetId?: string }
export interface VisualGoal { direction: string; styles?: readonly string[]; referenceFeatures?: Partial<VisualFeatures> }
export interface VisualFeatures { schemaVersion: 'visual-features-v1'; encoderTarget: VisualEncoderTarget; composition: Readonly<Record<string, number>>; subjectCount: number; facePresence: number; objectClasses: readonly string[]; lighting: Readonly<Record<string, number>>; colorDistribution: readonly number[]; backgroundComplexity: number; estimatedQuality: number; resolution: Readonly<{ width: number; height: number; megapixels: number }>; depthCues: number; segmentationComplexity: number; visualStyle: readonly string[]; requestedStyleSimilarity: number }
export interface VisualEncodingPolicy { privacyMode: PrivacyMode; cloudAnalysisAllowed: boolean; outboundImageAllowed: boolean }
export interface VisualQualityPrediction { technicalQuality: number; visualCoherence: number; identityPreservation: number; compositionQuality: number }
export interface VisualGoalAlignmentResult { similarity: number; gap: number; matchedStyles: readonly string[]; missingStyles: readonly string[] }
export interface OperationNeed { operation: VisualOperation; probability: number; needed: boolean; reason: string }
export interface VisualCounterfactualResult { baselineOperation: VisualOperation; alternativeOperation: VisualOperation; qualityDelta: number; costDelta: number; latencyDelta: number; privacyDelta: number; preferred: VisualOperation }
export interface DecisionFeaturesV3 extends DecisionFeaturesV2 { visual: VisualFeatures; visualGoal?: VisualGoal }
export interface DecisionRepresentationV3 extends DecisionRepresentationV2 { schemaVersion: 'decision-representation-v3'; blocks: DecisionRepresentationV2['blocks'] & Readonly<{ visual: readonly number[]; visualGoal: readonly number[] }>; visualQuality: VisualQualityPrediction; goalAlignment: VisualGoalAlignmentResult; operationNeeds: readonly OperationNeed[] }
