export type ExecutionTarget = 'LOCAL' | 'CLOUD' | 'HYBRID';
export type PrivacyMode = 'NORMAL' | 'PRIVACY_FIRST' | 'LOCAL_ONLY' | 'OFFLINE_ONLY';
export type ModelStatus = 'CANDIDATE' | 'CANARY' | 'ACTIVE' | 'DEPRECATED' | 'REJECTED' | 'ROLLED_BACK';
export type UncertaintyAction = 'ASK_USER' | 'LOCAL_FIRST' | 'SHOW_PREVIEW' | 'FALLBACK_TO_HEURISTIC';

export interface DecisionContextV1 { operation: string; intent: string; goal: string; deviceClass: string; platform: string; projectType: string; privacyMode: PrivacyMode; budget: number; latencyTarget: number; qualityTarget: number; projectId?: string; deviceId?: string; timestamp?: number }
export interface DecisionCandidateV1 { id: string; executionTarget: ExecutionTarget; model: string; provider: string; runtime: string; estimatedQuality: number; estimatedLatency: number; estimatedCost: number; energy: number; memory: number; reliability: number; quarantined?: boolean; trusted?: boolean; runtimeSupported?: boolean; outboundDataAllowed?: boolean }
export interface DecisionHistoryV1 { modelSuccessRate: number; providerSuccessRate: number; deviceSpecificSuccessRate: number; cloudAvoidance: number; acceptanceRate: number; undoRate: number }
export interface DecisionFeaturesV1 { context: DecisionContextV1; candidate: DecisionCandidateV1; history: DecisionHistoryV1 }
export interface ActualDecisionOutcome { quality: number; success: boolean; accepted: boolean; latency: number; cost: number; escalated: boolean; undone?: boolean; corrected?: boolean; goalCompletion?: number; satisfaction?: number; risk?: number; unnecessaryAI?: boolean }
export interface DecisionDatasetRecord { id: string; features: DecisionFeaturesV1; context: DecisionContextV1; candidate: DecisionCandidateV1; decision: string; actualOutcome: ActualDecisionOutcome; reward: number; timestamp: number; modelVersion: string; projectId: string; deviceId: string }
export interface RewardPolicy { goalCompletion: number; quality: number; satisfaction: number; costEfficiency: number; speed: number; privacy: number; risk: number; unnecessaryAI: number }
export interface UtilityPolicy { quality: number; success: number; acceptance: number; latency: number; cost: number; escalation: number }
export interface MultiHeadPrediction { quality: number; successProbability: number; acceptanceProbability: number; latency: number; cost: number; escalationProbability: number; expectedUtility: number; predictionConfidence: number; calibration: number; uncertainty: number; ood: boolean; recommendedAction?: UncertaintyAction }
export interface InfluentialFeature { feature: string; value: number; influence: number }
export interface DecisionModelExplanation { modelVersion: string; topInfluentialFeatures: readonly InfluentialFeature[]; candidateScores: readonly { candidateId: string; utility: number }[]; predictedOutcomes: MultiHeadPrediction; constraintExclusions: readonly string[]; finalUtility: number; summary: readonly string[] }
export interface RankedDecisionCandidate { candidate: DecisionCandidateV1; prediction: MultiHeadPrediction; rank: number; excluded: boolean; exclusions: readonly string[] }
export interface DecisionModelV1 { predict(features: DecisionFeaturesV1, policy?: Partial<UtilityPolicy>): MultiHeadPrediction; rank(context: DecisionContextV1, candidates: readonly DecisionCandidateV1[], history?: Partial<DecisionHistoryV1>, policy?: Partial<UtilityPolicy>): readonly RankedDecisionCandidate[]; estimateReward(features: DecisionFeaturesV1, policy?: Partial<UtilityPolicy>): number; estimateQuality(features: DecisionFeaturesV1): number; estimateCost(features: DecisionFeaturesV1): number; estimateLatency(features: DecisionFeaturesV1): number; estimateAcceptance(features: DecisionFeaturesV1): number; explain(features: DecisionFeaturesV1): DecisionModelExplanation; version(): string }
export interface ModelMetrics { rankingQuality: number; predictionError: number; acceptancePredictionError: number; qualityPredictionError: number; costPredictionError: number; latencyPredictionError: number; decisionRegret: number; cloudSavings: number; localSuccess: number; stability: number }
export interface ModelManifest { featureSchemaVersion: string; datasetVersion: string; trainingConfigVersion: string; modelVersion: string; metrics: ModelMetrics; parentModel: string | null; createdAt: number; status: ModelStatus }
export interface ConstraintPolicy { budget: number; privacyMode: PrivacyMode; cloudAllowed: boolean; allowedRuntimes?: readonly string[]; allowedProviders?: readonly string[] }
export interface DatasetSplit { train: readonly DecisionDatasetRecord[]; validation: readonly DecisionDatasetRecord[]; test: readonly DecisionDatasetRecord[] }
