import { immutable, mean } from './immutable';
import type { OperationNeed, VisualCounterfactualResult, VisualFeatures, VisualGoal, VisualGoalAlignmentResult, VisualOperation, VisualQualityPrediction } from './types';
const clamp = (n: number) => Math.max(0, Math.min(1, Number.isFinite(n) ? n : 0));
const words = (goal?: VisualGoal) => new Set((goal?.styles ?? goal?.direction.split(/[^\p{L}\p{N}]+/u) ?? []).map(x => x.toLowerCase()).filter(Boolean));

export class VisualQualityHead {
  predict(v: VisualFeatures): VisualQualityPrediction { const compositionQuality = mean([v.composition.balance, v.composition.focus, 1 - Math.abs(v.composition.negativeSpace - .4)]); return immutable({ technicalQuality: clamp(v.estimatedQuality * .7 + Math.min(1, v.resolution.megapixels / 8) * .2 + v.lighting.exposure * .1), visualCoherence: clamp(mean([v.lighting.uniformity, 1 - v.backgroundComplexity * .35, v.depthCues])), identityPreservation: clamp(v.facePresence ? .65 + v.estimatedQuality * .25 - v.segmentationComplexity * .1 : .9), compositionQuality: clamp(compositionQuality) }); }
}
export class VisualGoalAlignment {
  evaluate(v: VisualFeatures, goal?: VisualGoal): VisualGoalAlignmentResult { const desired = words(goal), actual = new Set(v.visualStyle); const matched = [...desired].filter(x => actual.has(x)).sort(), missing = [...desired].filter(x => !actual.has(x)).sort(); const similarity = desired.size ? clamp((matched.length / desired.size + v.requestedStyleSimilarity) / 2) : v.requestedStyleSimilarity; return immutable({ similarity, gap: clamp(1 - similarity), matchedStyles: matched, missingStyles: missing }); }
}
export class OperationNeedPredictor {
  predict(v: VisualFeatures, goal?: VisualGoal): readonly OperationNeed[] { const alignment = new VisualGoalAlignment().evaluate(v, goal), lowResolution = clamp(1 - v.resolution.megapixels), scores: Record<Exclude<VisualOperation, 'NONE'>, [number, string]> = { SEGMENTATION: [clamp(v.segmentationComplexity * .6 + v.backgroundComplexity * .4), 'Foreground isolation complexity'], RELIGHTING: [clamp((1 - v.lighting.exposure) * .55 + (1 - v.lighting.uniformity) * .45), 'Lighting does not meet the quality target'], UPSCALE: [lowResolution, 'Resolution is below the useful output target'], BACKGROUND_REPLACEMENT: [clamp(v.backgroundComplexity * .45 + alignment.gap * .35), 'Background conflicts with the requested direction'], GENERATION: [clamp(alignment.gap * .55 + (1 - v.estimatedQuality) * .2), 'Large visual-goal gap may require synthesis'] }; const needs = Object.entries(scores).map(([operation, [probability, reason]]) => immutable({ operation: operation as VisualOperation, probability, needed: probability >= .6, reason })); if (!needs.some(item => item.needed)) return immutable([{ operation: 'NONE', probability: clamp(1 - Math.max(...needs.map(x => x.probability))), needed: true, reason: 'The image already satisfies the requested outcome' }, ...needs]); return immutable(needs); }
}
export class VisualCounterfactual {
  compare(localQuality: VisualQualityPrediction, cloudQuality: VisualQualityPrediction, costs = { local: 0, cloud: 1 }, latencies = { local: 1, cloud: 5 }): VisualCounterfactualResult { const local = mean(Object.values(localQuality)), cloud = mean(Object.values(cloudQuality)), qualityDelta = cloud - local, costDelta = costs.cloud - costs.local, latencyDelta = latencies.cloud - latencies.local, privacyDelta = -1; const preferred = qualityDelta > .12 && costDelta <= 1 ? 'GENERATION' : 'NONE'; return immutable({ baselineOperation: 'NONE', alternativeOperation: 'GENERATION', qualityDelta, costDelta, latencyDelta, privacyDelta, preferred }); }
}
