// SubscriptionPlans — provider-neutral default catalog. Future custom plans can
// use the SubscriptionPlan entity and follow this exact model.
export const DEFAULT_PLANS = [
  { id: 'free', name: 'Free', description: 'Essential image editing.', monthlyPrice: 0, yearlyPrice: 0, currency: 'USD', includedCredits: 500, maxProjects: 3, maxStorage: 1, maxImageResolution: 2048, maxQueueLength: 1, priorityLevel: 'normal', features: ['ai_editing', 'scene_memory'], trialAvailable: false, trialDays: 0, isActive: true, metadata: {} },
  { id: 'plus', name: 'Plus', description: 'More room for everyday creative work.', monthlyPrice: 12, yearlyPrice: 120, currency: 'USD', includedCredits: 1500, maxProjects: 25, maxStorage: 10, maxImageResolution: 4096, maxQueueLength: 2, priorityLevel: 'normal', features: ['ai_editing', 'virtual_tryon', 'scene_memory', 'recipe_chains'], trialAvailable: true, trialDays: 7, isActive: true, metadata: {} },
  { id: 'pro', name: 'Pro', description: 'Advanced AI tools for professionals.', monthlyPrice: 29, yearlyPrice: 290, currency: 'USD', includedCredits: 5000, maxProjects: 100, maxStorage: 50, maxImageResolution: 6144, maxQueueLength: 5, priorityLevel: 'high', features: ['ai_editing', 'virtual_tryon', 'ai_agent', 'recipe_chains', 'premium_recipes', 'scene_memory', 'high_resolution_export', 'priority_queue'], trialAvailable: true, trialDays: 14, isActive: true, metadata: {} },
  { id: 'studio', name: 'Studio', description: 'High-volume commercial production.', monthlyPrice: 79, yearlyPrice: 790, currency: 'USD', includedCredits: 15000, maxProjects: 500, maxStorage: 250, maxImageResolution: 8192, maxQueueLength: 10, priorityLevel: 'priority', features: ['ai_editing', 'virtual_tryon', 'ai_agent', 'recipe_chains', 'premium_recipes', 'scene_memory', 'batch_processing', 'high_resolution_export', 'priority_queue', 'commercial_license'], trialAvailable: true, trialDays: 14, isActive: true, metadata: {} },
  { id: 'enterprise', name: 'Enterprise', description: 'Custom limits and organization-scale support.', monthlyPrice: 0, yearlyPrice: 0, currency: 'USD', includedCredits: 50000, maxProjects: 10000, maxStorage: 2000, maxImageResolution: 8192, maxQueueLength: 25, priorityLevel: 'priority', features: ['ai_editing', 'virtual_tryon', 'ai_agent', 'recipe_chains', 'premium_recipes', 'scene_memory', 'batch_processing', 'high_resolution_export', 'priority_queue', 'commercial_license'], trialAvailable: false, trialDays: 0, isActive: true, metadata: { custom: true } },
];

export const getPlan = (id) => DEFAULT_PLANS.find((plan) => plan.id === id) || DEFAULT_PLANS[0];
export const getPlanIndex = (id) => DEFAULT_PLANS.findIndex((plan) => plan.id === id);