export const modules = {
  common: { appName: 'ШІ Фоторедактор', save: 'Зберегти', cancel: 'Скасувати', delete: 'Видалити', edit: 'Редагувати', close: 'Закрити', create: 'Створити', apply: 'Застосувати', retry: 'Повторити', confirm: 'Підтвердити', back: 'Назад', next: 'Далі', done: 'Готово', loading: 'Завантаження…', search: 'Пошук', add: 'Додати', remove: 'Прибрати', rename: 'Перейменувати', duplicate: 'Дублювати', download: 'Завантажити', favorite: 'В обране', archive: 'В архів', restore: 'Відновити', signOut: 'Вийти', empty: 'Тут поки порожньо', minutes: '{count} хв', seconds: '{seconds}с' },
  editor: { title: 'Редактор', undo: 'Скасувати', redo: 'Повторити', restoreOriginal: 'Повернути оригінал', detectObjects: 'Знайти обʼєкти', detecting: 'Пошук обʼєктів…', prompt: 'Запит', creativeStudio: 'Креатив-студія', recipes: 'Рецепти', aiAgent: 'ШІ-агент', fashion: 'Мода', outfits: 'Образи', before: 'До', after: 'Після', accept: 'Прийняти', discard: 'Відхилити', objects: 'Обʼєкти', versions: 'Версії', newVersion: 'Нова версія', sceneMemory: 'Памʼять сцени', workspace: 'Робоча область', jobCenter: 'Центр завдань', instructionPlaceholder: 'Опишіть зміну…', projectNotFound: 'Проєкт не знайдено' },
  projects: { title: 'Проєкти', newProject: 'Новий проєкт', upload: 'Завантажити зображення', empty: 'Проєктів ще немає — завантажте зображення.', open: 'Відкрити', processing: 'Обробка', draft: 'Чернетка', completed: 'Готово' },
  recipes: { title: 'Рецепти', favorite: 'Обране', popular: 'Популярні', recent: 'Нещодавні', recommended: 'Рекомендовані', run: 'Запустити рецепт', use: 'Використати', searchPlaceholder: 'Пошук рецептів…' },
  workspace: { title: 'Робоча область', auto: 'Автовизначення', manual: 'Вручну', switch: 'Змінити область', recommendations: 'Рекомендації', mostUsed: 'Найчастіше' },
  automation: { title: 'Студія автоматизації', subtitle: 'Створюйте багаторазові процеси редагування без коду.', library: 'Бібліотека автоматизацій', templateGallery: 'Галерея шаблонів', builder: 'Конструктор', history: 'Історія виконання', run: 'Запустити', queuing: 'У черзі…', save: 'Зберегти', trigger: 'Тригер', conditions: 'Умови', condition: 'Умова', actions: 'Дії', action: 'Дія', schedule: 'Розклад', variables: 'Змінні', estimatedCredits: 'Оцінка кредитів', estimatedTime: 'Оцінка часу', emptyBuilder: 'Оберіть шаблон або створіть автоматизацію.', emptyLibrary: 'Збережіть шаблон, щоб наповнити бібліотеку.', noRuns: 'Запусків ще немає.', mostExecuted: 'Найчастіше', successRate: 'Успіх {rate}%', failureRate: 'Помилки {rate}%', describePlaceholder: 'Опишіть цей процес', actionsCount: '{count} дій', untitled: 'Автоматизація без назви', scheduleImmediate: 'Негайно', scheduleScheduled: 'За розкладом', scheduleDaily: 'Щодня', scheduleWeekly: 'Щотижня', scheduleManual: 'Лише вручну', containsPerson: 'Містить людину', containsVehicle: 'Містить транспорт', containsProduct: 'Містить товар', containsAnimal: 'Містить тварину', containsText: 'Містить текст' },
  fashion: { title: 'Мода', wardrobe: 'Гардероб', garments: 'Одяг', outfits: 'Образи', addGarment: 'Додати річ', collections: 'Колекції', tryOn: 'Примірка', searchPlaceholder: 'Пошук у гардеробі…', empty: 'Ваш гардероб порожній.' },
  billing: { title: 'Оплата', subscription: 'Підписка', plan: 'Тариф', credits: 'Кредити', upgrade: 'Покращити', currentPlan: 'Поточний тариф', usage: 'Використання', renew: 'Поновлення {date}' },
  settings: { title: 'Налаштування', account: 'Обліковий запис', appearance: 'Оформлення', appearanceHint: 'Перемикання світлої та темної теми', language: 'Мова', languageHint: 'Оберіть мову інтерфейсу', performance: 'Продуктивність', loadingPerformance: 'Завантаження налаштувань продуктивності…' },
  errors: { generic: 'Щось пішло не так.', network: 'Помилка мережі — перевірте зʼєднання.', offline: 'Ви офлайн. Зміни синхронізуються після підключення.', timeout: 'Час очікування вичерпано. Спробуйте ще раз.', provider: 'Провайдер ШІ не зміг виконати запит.', validation: 'Виправте виділені поля.', credits: 'Недостатньо кредитів для цієї операції.', subscription: 'Ваш тариф не дозволяє цю дію.' },
  notifications: { title: 'Сповіщення', markAllRead: 'Позначити всі як прочитані', empty: 'Немає сповіщень.', completed: 'Генерацію завершено', failed: 'Помилка генерації', saved: 'Зміну збережено' },
  jobs: { title: 'Центр завдань', queued: 'У черзі', running: 'Виконується', waiting: 'Очікування', completed: 'Завершено', failed: 'Помилка', cancelled: 'Скасовано', retrying: 'Повтор', cancel: 'Скасувати', pause: 'Пауза', resume: 'Продовжити', empty: 'Немає активних завдань.' },
  creative: { title: 'Креатив-студія', goal: 'Мета', ideas: 'Ідеї', moodBoards: 'Мудборди', strategy: 'Стратегія', generate: 'Згенерувати ідеї', apply: 'Застосувати стратегію' },
  brand: { title: 'Бренд-студія', profile: 'Профіль бренду', colors: 'Кольори', fonts: 'Шрифти', voice: 'Тон', guidelines: 'Гайдлайни' },
  assets: { title: 'Бібліотека ресурсів', collections: 'Колекції', pinned: 'Закріплені', smart: 'Розумні', searchPlaceholder: 'Пошук ресурсів…', empty: 'Ресурсів ще немає.', details: 'Деталі' },
};
export default modules;