import { immutable } from './immutable';
import type { EvolutionDependencies, KnowledgeClaim, ReasoningProgram, ReasoningProgramName, WorldKnowledgeVersion } from './types';
export class WorldKnowledgeEvolution {
  constructor(private readonly dependencies: EvolutionDependencies) {}
  create(claims: readonly KnowledgeClaim[]): WorldKnowledgeVersion { return immutable({ id: this.dependencies.nextId(), version: 1, claims: [...claims], added: claims.map((item) => item.key), strengthened: [], deprecated: [], createdAt: this.dependencies.now() }); }
  evolve(parent: WorldKnowledgeVersion, claims: readonly KnowledgeClaim[]): WorldKnowledgeVersion { const previous = new Map(parent.claims.map((item) => [item.key, item])); const current = new Map(claims.map((item) => [item.key, item])); const added = claims.filter((item) => !previous.has(item.key)).map((item) => item.key); const strengthened = claims.filter((item) => item.confidence > (previous.get(item.key)?.confidence ?? item.confidence)).map((item) => item.key); const deprecated = parent.claims.filter((item) => !current.has(item.key)).map((item) => item.key); return immutable({ id: this.dependencies.nextId(), version: parent.version + 1, parentId: parent.id, claims: [...claims], added, strengthened, deprecated, createdAt: this.dependencies.now() }); }
}
const programs: Readonly<Record<ReasoningProgramName, readonly string[]>> = { LUXURY: ['identify premium cues', 'shape light', 'verify identity'], PORTRAIT: ['protect face', 'balance composition', 'verify quality'], FASHION: ['read styling', 'shape narrative', 'check brand'], MARKETING: ['identify audience', 'clarify message', 'predict response'], BRAND: ['extract identity', 'check consistency', 'reject drift'], REPAIR: ['locate defect', 'minimize change', 'validate restoration'], CREATIVE: ['diverge', 'combine', 'rank novelty'], MINIMAL: ['remove noise', 'preserve intent', 'stop early'], EXPLORATION: ['list unknowns', 'generate alternatives', 'simulate'], VERIFICATION: ['collect evidence', 'challenge claim', 'confirm'] };
export class ReasoningLibrary {
  all(): readonly ReasoningProgram[] { const names = Object.keys(programs).sort() as ReasoningProgramName[]; return immutable(names.map((name) => ({ id: `reasoning:${name.toLowerCase()}`, name, steps: programs[name], compatibleWith: names.filter((other) => other !== name) }))); }
  compose(names: readonly ReasoningProgramName[]): readonly string[] { const library = new Map(this.all().map((item) => [item.name, item])); return immutable(names.flatMap((name) => { const program = library.get(name); if (!program) throw new Error(`Unknown reasoning program ${name}`); return program.steps; })); }
}
