export const modules = {
  common: { appName: 'Editor de Fotos IA', save: 'Salvar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar', close: 'Fechar', create: 'Criar', apply: 'Aplicar', retry: 'Tentar novamente', confirm: 'Confirmar', back: 'Voltar', next: 'Próximo', done: 'Concluído', loading: 'Carregando…', search: 'Buscar', add: 'Adicionar', remove: 'Remover', rename: 'Renomear', duplicate: 'Duplicar', download: 'Baixar', favorite: 'Favorito', archive: 'Arquivar', restore: 'Restaurar', signOut: 'Sair', empty: 'Nada aqui ainda', minutes: '{count} min', seconds: '{seconds}s' },
  editor: { title: 'Editor', undo: 'Desfazer', redo: 'Refazer', restoreOriginal: 'Restaurar original', detectObjects: 'Detectar objetos', detecting: 'Detectando objetos…', prompt: 'Instrução', creativeStudio: 'Estúdio Criativo', recipes: 'Receitas', aiAgent: 'Agente IA', fashion: 'Moda', outfits: 'Looks', before: 'Antes', after: 'Depois', accept: 'Aceitar', discard: 'Descartar', objects: 'Objetos', versions: 'Versões', newVersion: 'Nova versão', sceneMemory: 'Memória da cena', workspace: 'Área de trabalho', jobCenter: 'Central de tarefas', instructionPlaceholder: 'Descreva sua edição…', projectNotFound: 'Projeto não encontrado' },
  projects: { title: 'Projetos', newProject: 'Novo projeto', upload: 'Enviar imagem', empty: 'Nenhum projeto ainda — envie uma imagem para começar.', open: 'Abrir', processing: 'Processando', draft: 'Rascunho', completed: 'Concluído' },
  recipes: { title: 'Receitas', favorite: 'Favorito', popular: 'Populares', recent: 'Recentes', recommended: 'Recomendadas', run: 'Executar receita', use: 'Usar', searchPlaceholder: 'Buscar receitas…' },
  workspace: { title: 'Área de trabalho', auto: 'Detecção automática', manual: 'Manual', switch: 'Trocar área', recommendations: 'Recomendações', mostUsed: 'Mais usada' },
  automation: { title: 'Estúdio de Automação', subtitle: 'Crie fluxos de edição reutilizáveis sem escrever código.', library: 'Biblioteca de automações', templateGallery: 'Galeria de modelos', builder: 'Construtor', history: 'Histórico de execução', run: 'Executar', queuing: 'Na fila…', save: 'Salvar', trigger: 'Gatilho', conditions: 'Condições', condition: 'Condição', actions: 'Ações', action: 'Ação', schedule: 'Agendamento', variables: 'Variáveis', estimatedCredits: 'Créditos estimados', estimatedTime: 'Tempo estimado', emptyBuilder: 'Escolha um modelo ou crie uma automação.', emptyLibrary: 'Salve um modelo para sua biblioteca.', noRuns: 'Nenhuma execução ainda.', mostExecuted: 'Mais executada', successRate: 'Sucesso {rate}%', failureRate: 'Falhas {rate}%', describePlaceholder: 'Descreva este fluxo', actionsCount: '{count} ações', untitled: 'Automação sem título', scheduleImmediate: 'Imediato', scheduleScheduled: 'Agendado', scheduleDaily: 'Diário', scheduleWeekly: 'Semanal', scheduleManual: 'Somente manual', containsPerson: 'Contém pessoa', containsVehicle: 'Contém veículo', containsProduct: 'Contém produto', containsAnimal: 'Contém animal', containsText: 'Contém texto' },
  fashion: { title: 'Moda', wardrobe: 'Guarda-roupa', garments: 'Peças', outfits: 'Looks', addGarment: 'Adicionar peça', collections: 'Coleções', tryOn: 'Provador virtual', searchPlaceholder: 'Buscar no guarda-roupa…', empty: 'Seu guarda-roupa está vazio.' },
  billing: { title: 'Faturamento', subscription: 'Assinatura', plan: 'Plano', credits: 'Créditos', upgrade: 'Fazer upgrade', currentPlan: 'Plano atual', usage: 'Uso', renew: 'Renova em {date}' },
  settings: { title: 'Configurações', account: 'Conta', appearance: 'Aparência', appearanceHint: 'Alternar entre modo claro e escuro', language: 'Idioma', languageHint: 'Escolha o idioma da interface', performance: 'Desempenho', loadingPerformance: 'Carregando configurações de desempenho…' },
  errors: { generic: 'Algo deu errado.', network: 'Erro de rede — verifique sua conexão.', offline: 'Você está offline. As alterações serão sincronizadas ao reconectar.', timeout: 'A solicitação expirou. Tente novamente.', provider: 'O provedor de IA não pôde concluir a solicitação.', validation: 'Corrija os campos destacados.', credits: 'Você não tem créditos suficientes para esta operação.', subscription: 'Seu plano não permite esta ação.' },
  notifications: { title: 'Notificações', markAllRead: 'Marcar tudo como lido', empty: 'Sem notificações.', completed: 'Geração concluída', failed: 'Falha na geração', saved: 'Edição salva' },
  jobs: { title: 'Central de tarefas', queued: 'Na fila', running: 'Em execução', waiting: 'Aguardando', completed: 'Concluído', failed: 'Falhou', cancelled: 'Cancelado', retrying: 'Tentando novamente', cancel: 'Cancelar', pause: 'Pausar', resume: 'Retomar', empty: 'Nenhuma tarefa ativa.' },
  creative: { title: 'Estúdio Criativo', goal: 'Objetivo', ideas: 'Ideias', moodBoards: 'Painéis de inspiração', strategy: 'Estratégia', generate: 'Gerar ideias', apply: 'Aplicar estratégia' },
  brand: { title: 'Estúdio da Marca', profile: 'Perfil da marca', colors: 'Cores', fonts: 'Fontes', voice: 'Tom', guidelines: 'Diretrizes' },
  assets: { title: 'Biblioteca de recursos', collections: 'Coleções', pinned: 'Fixados', smart: 'Inteligentes', searchPlaceholder: 'Buscar recursos…', empty: 'Nenhum recurso ainda.', details: 'Detalhes' },
};
export default modules;