import { EventTimeline } from './EventTimeline';
import { immutable, rounded } from './immutable';
import { IntelligenceStateMachine } from './IntelligenceStateMachine';
import { MessageBus } from './MessageBus';
import { CapabilityRegistry } from './PluginRegistry';
import { IntelligenceHealthMonitor, ReplayKernel, SnapshotEngine } from './replay';
import { CognitiveBudget, IntelligenceScheduler } from './scheduling';
import { IntelligenceSessionManager } from './SessionManager';
import { UnifiedBlackboard } from './UnifiedBlackboard';
import type { IntelligenceMetrics, KernelDependencies, KernelRunRequest, KernelRunResult, KernelScope, PluginContext } from './types';

export class CreativeIntelligenceKernel {
  readonly bus: MessageBus; readonly blackboard: UnifiedBlackboard; readonly registry: CapabilityRegistry;
  private readonly timeline: EventTimeline; private readonly scheduler = new IntelligenceScheduler(); private readonly budget = new CognitiveBudget(); private readonly stateMachine: IntelligenceStateMachine; private readonly sessions: IntelligenceSessionManager; private readonly snapshots: SnapshotEngine; private readonly replayKernel = new ReplayKernel(); private readonly health = new IntelligenceHealthMonitor();
  constructor(private readonly dependencies: KernelDependencies) { this.bus = new MessageBus(dependencies); this.blackboard = new UnifiedBlackboard(dependencies); this.registry = new CapabilityRegistry(dependencies); this.timeline = new EventTimeline(dependencies); this.stateMachine = new IntelligenceStateMachine(dependencies); this.sessions = new IntelligenceSessionManager(dependencies); this.snapshots = new SnapshotEngine(dependencies); }

  run(raw: KernelRunRequest): KernelRunResult {
    this.validate(raw); const request = immutable(structuredClone(raw)); const registrations = this.registry.all(); const capabilities = request.requestedCapabilities ?? this.inferCapabilities(`${request.objective} ${request.prompt}`); const prePlan = this.scheduler.plan({ objective: request.objective, capabilities, registrations, reasoningPoints: request.reasoningPoints }); const allocation = this.budget.allocate(request.reasoningPoints, prePlan.map((item) => item.pluginId), Object.fromEntries(prePlan.map((item) => [item.pluginId, Math.max(1, item.capabilities.length)]))); let session = this.sessions.create(request, request.objective, { ...(request.workspace ?? {}), prompt: request.prompt, seed: request.seed }, allocation); const context: PluginContext = immutable({ tenantId: request.tenantId, projectId: request.projectId, userId: request.userId, sessionId: session.id, objective: request.objective });
    const goal = this.timeline.append({ ...context, type: 'GOAL_CREATED', data: { objective: request.objective } }); this.blackboard.write({ ...context, channel: 'DIRECTOR', author: 'KERNEL', key: 'objective', value: request.objective });
    for (const item of prePlan) { const plugin = this.registry.get(item.pluginId).plugin; plugin.initialize(context); plugin.observe(context, this.bus.history(session.id, request)); plugin.reason(context, item.budget); for (const publication of plugin.publish(context)) { const message = this.bus.publish({ ...context, topic: publication.topic, sender: plugin.id, payload: publication.payload }); this.timeline.append({ ...context, type: 'MESSAGE_PUBLISHED', parentIds: [goal.id], data: { messageId: message.id, topic: message.topic } }); if (publication.blackboard) this.blackboard.write({ ...context, author: plugin.id, ...publication.blackboard }); } plugin.sleep(context); this.timeline.append({ ...context, type: 'MODULE_LIFECYCLE', data: { pluginId: plugin.id, state: 'SLEEPING' } }); }
    const transitions = this.stateMachine.run('kernel-run'); const terminal = transitions.at(-1)!.to; const metrics = this.metrics(prePlan.length, transitions.length, this.bus.history(session.id, request).length); session = this.sessions.update(session, { timeline: this.timeline.history(session.id, request), state: terminal, metrics }); const health = this.health.evaluate(metrics); const snapshot = this.snapshots.capture(session, this.blackboard.snapshot(session.id, request), this.bus.history(session.id, request), transitions); const replay = this.replayKernel.frames(snapshot, request); return immutable({ session, plan: prePlan, health, snapshot, replay });
  }
  shutdown(sessionId: string, scope: KernelScope): void { const session = this.sessions.get(sessionId, scope); const context = immutable({ ...scope, sessionId, objective: session.objective }); for (const registration of this.registry.all()) registration.plugin.shutdown(context); }
  replay(snapshotId: string, sessionId: string, sequence: number, scope: KernelScope) { const snapshot = this.snapshots.restore(sessionId, sequence, scope); if (snapshot.id !== snapshotId) throw new Error('Snapshot identity mismatch'); const frames = this.replayKernel.frames(snapshot, scope); const context = immutable({ ...scope, sessionId, objective: snapshot.session.objective }); for (const registration of this.registry.all()) registration.plugin.replay(context, snapshot.session.timeline); return frames; }
  private inferCapabilities(text: string) { const capabilities = new Set<string>(['RANKING', 'VALIDATION']); if (/portrait|passport|портрет|паспорт/i.test(text)) { capabilities.add('COMPOSITION'); capabilities.add('VISION'); } if (/luxury|campaign|brand|люкс|кампан|бренд/i.test(text)) { capabilities.add('BRAND'); capabilities.add('STYLE'); capabilities.add('DEBATE'); capabilities.add('LEARNING'); } return [...capabilities]; }
  private metrics(modules: number, states: number, messages: number): IntelligenceMetrics { const base = rounded(.45 + Math.min(.45, modules * .05)); return immutable({ reasoning: base, memory: rounded(.5 + messages * .04), planning: rounded(.5 + modules * .04), debate: rounded(.45 + messages * .03), learning: rounded(.5 + messages * .02), reflection: rounded(states / 12), simulation: base, director: base, decision: base, meta: rounded((base + .7) / 2) }); }
  private validate(input: KernelRunRequest) { if (!input.tenantId || !input.projectId || !input.userId) throw new Error('Complete kernel scope is required'); if (!input.objective.trim() || !input.prompt.trim()) throw new Error('Objective and prompt are required'); if (!Number.isInteger(input.reasoningPoints) || input.reasoningPoints < 0) throw new Error('Reasoning points must be a non-negative integer'); }
}
