import { immutable } from './immutable';
import { IntelligenceDependencyGraph } from './DependencyGraph';
import type { Capability, CognitiveBudgetAllocation, ExecutionPlanItem, PluginRegistration } from './types';

export class CognitiveBudget {
  allocate(total: number, pluginIds: readonly string[], weights: Readonly<Record<string, number>> = {}): CognitiveBudgetAllocation { if (!Number.isInteger(total) || total < 0) throw new Error('Reasoning budget must be a non-negative integer'); const unique = [...new Set(pluginIds)]; const rawWeights = unique.map((id) => Math.max(0, weights[id] ?? 1)); const sum = rawWeights.reduce((a, b) => a + b, 0); const shares: Record<string, number> = Object.fromEntries(unique.map((id) => [id, 0])); if (sum > 0) { let allocated = 0; unique.forEach((id, index) => { const share = index === unique.length - 1 ? total - allocated : Math.floor(total * rawWeights[index] / sum); shares[id] = share; allocated += share; }); } const allocated = Object.values(shares).reduce((a, b) => a + b, 0); return immutable({ total, allocated, remaining: total - allocated, shares }); }
}
export class IntelligenceScheduler {
  constructor(private readonly graph = new IntelligenceDependencyGraph(), private readonly budgets = new CognitiveBudget()) {}
  plan(input: { objective: string; capabilities: readonly Capability[]; registrations: readonly PluginRegistration[]; reasoningPoints: number }): readonly ExecutionPlanItem[] { const active = input.registrations.filter((item) => item.status === 'ACTIVE'); const relevant = active.filter((item) => !input.capabilities.length || item.plugin.capabilities.some((capability) => input.capabilities.includes(capability))); const required = this.includeDependencies(relevant, active); const nodes = this.graph.build(required); const order = this.graph.topological(nodes); const complexity = /luxury|campaign|research|complex|люкс|кампан|исслед/i.test(input.objective) ? 2 : 1; const weights = Object.fromEntries(required.map((item) => [item.plugin.id, Math.max(1, item.plugin.capabilities.length * complexity)])); const budget = this.budgets.allocate(input.reasoningPoints, order, weights); return immutable(order.map((pluginId, index) => { const registration = required.find((item) => item.plugin.id === pluginId)!; const points = budget.shares[pluginId]; return { pluginId, kind: registration.plugin.kind, capabilities: registration.plugin.capabilities, order: index, iterations: Math.max(1, Math.ceil(points / 50)), budget: points, reason: `Selected for ${registration.plugin.capabilities.join(', ')}` }; })); }
  private includeDependencies(selected: readonly PluginRegistration[], all: readonly PluginRegistration[]): readonly PluginRegistration[] { const selectedIds = new Set(selected.map((item) => item.plugin.id)); let changed = true; while (changed) { changed = false; for (const item of all) if (selectedIds.has(item.plugin.id)) for (const dependency of item.plugin.dependencies) if (!selectedIds.has(dependency)) { selectedIds.add(dependency); changed = true; } } return all.filter((item) => selectedIds.has(item.plugin.id)); }
}
