export const modules = {
  common: { appName: 'AI フォトエディター', save: '保存', cancel: 'キャンセル', delete: '削除', edit: '編集', close: '閉じる', create: '作成', apply: '適用', retry: '再試行', confirm: '確認', back: '戻る', next: '次へ', done: '完了', loading: '読み込み中…', search: '検索', add: '追加', remove: '削除', rename: '名前を変更', duplicate: '複製', download: 'ダウンロード', favorite: 'お気に入り', archive: 'アーカイブ', restore: '復元', signOut: 'サインアウト', empty: 'ここにはまだ何もありません', minutes: '{count}分', seconds: '{seconds}秒' },
  editor: { title: 'エディター', undo: '元に戻す', redo: 'やり直す', restoreOriginal: '元の画像に戻す', detectObjects: 'オブジェクトを検出', detecting: 'オブジェクトを検出中…', prompt: 'プロンプト', creativeStudio: 'クリエイティブスタジオ', recipes: 'レシピ', aiAgent: 'AI エージェント', fashion: 'ファッション', outfits: 'コーデ', before: '編集前', after: '編集後', accept: '適用', discard: '破棄', objects: 'オブジェクト', versions: 'バージョン', newVersion: '新しいバージョン', sceneMemory: 'シーンメモリ', workspace: 'ワークスペース', jobCenter: 'ジョブセンター', instructionPlaceholder: '編集内容を入力…', projectNotFound: 'プロジェクトが見つかりません' },
  projects: { title: 'プロジェクト', newProject: '新規プロジェクト', upload: '画像をアップロード', empty: 'まだプロジェクトがありません。画像をアップロードして始めましょう。', open: '開く', processing: '処理中', draft: '下書き', completed: '完了' },
  recipes: { title: 'レシピ', favorite: 'お気に入り', popular: '人気', recent: '最近', recommended: 'おすすめ', run: 'レシピを実行', use: '使用', searchPlaceholder: 'レシピを検索…' },
  workspace: { title: 'ワークスペース', auto: '自動検出', manual: '手動', switch: 'ワークスペースを切替', recommendations: 'おすすめ', mostUsed: '最も使用' },
  automation: { title: 'オートメーションスタジオ', subtitle: 'コードを書かずに再利用可能な編集ワークフローを構築。', library: 'オートメーションライブラリ', templateGallery: 'テンプレートギャラリー', builder: 'ビルダー', history: '実行履歴', run: '実行', queuing: 'キューに追加中…', save: '保存', trigger: 'トリガー', conditions: '条件', condition: '条件', actions: 'アクション', action: 'アクション', schedule: 'スケジュール', variables: '変数', estimatedCredits: '推定クレジット', estimatedTime: '推定時間', emptyBuilder: 'テンプレートを選ぶか、オートメーションを作成してください。', emptyLibrary: 'テンプレートを保存してライブラリを作成しましょう。', noRuns: 'まだ実行がありません。', mostExecuted: '最も実行', successRate: '成功 {rate}%', failureRate: '失敗 {rate}%', describePlaceholder: 'このワークフローを説明', actionsCount: '{count}件のアクション', untitled: '無題のオートメーション', scheduleImmediate: '即時', scheduleScheduled: 'スケジュール', scheduleDaily: '毎日', scheduleWeekly: '毎週', scheduleManual: '手動のみ', containsPerson: '人物を含む', containsVehicle: '車両を含む', containsProduct: '製品を含む', containsAnimal: '動物を含む', containsText: 'テキストを含む' },
  fashion: { title: 'ファッション', wardrobe: 'ワードローブ', garments: '衣類', outfits: 'コーデ', addGarment: '衣類を追加', collections: 'コレクション', tryOn: '試着', searchPlaceholder: 'ワードローブを検索…', empty: 'ワードローブは空です。' },
  billing: { title: '請求', subscription: 'サブスクリプション', plan: 'プラン', credits: 'クレジット', upgrade: 'アップグレード', currentPlan: '現在のプラン', usage: '使用状況', renew: '{date}に更新' },
  settings: { title: '設定', account: 'アカウント', appearance: '外観', appearanceHint: 'ライト／ダークモードを切り替え', language: '言語', languageHint: 'インターフェースの言語を選択', performance: 'パフォーマンス', loadingPerformance: 'パフォーマンス設定を読み込み中…' },
  errors: { generic: '問題が発生しました。', network: 'ネットワークエラー — 接続を確認してください。', offline: 'オフラインです。再接続時に同期されます。', timeout: 'リクエストがタイムアウトしました。もう一度お試しください。', provider: 'AI プロバイダーがリクエストを完了できませんでした。', validation: 'ハイライトされた項目を修正してください。', credits: 'この操作に必要なクレジットが不足しています。', subscription: 'お使いのプランではこの操作は許可されていません。' },
  notifications: { title: '通知', markAllRead: 'すべて既読にする', empty: '通知はありません。', completed: '生成が完了しました', failed: '生成に失敗しました', saved: '編集を保存しました' },
  jobs: { title: 'ジョブセンター', queued: 'キュー', running: '実行中', waiting: '待機中', completed: '完了', failed: '失敗', cancelled: 'キャンセル', retrying: '再試行中', cancel: 'キャンセル', pause: '一時停止', resume: '再開', empty: 'アクティブなジョブはありません。' },
  creative: { title: 'クリエイティブスタジオ', goal: '目標', ideas: 'アイデア', moodBoards: 'ムードボード', strategy: '戦略', generate: 'アイデアを生成', apply: '戦略を適用' },
  brand: { title: 'ブランドスタジオ', profile: 'ブランドプロフィール', colors: 'カラー', fonts: 'フォント', voice: 'トーン', guidelines: 'ガイドライン' },
  assets: { title: 'アセットライブラリ', collections: 'コレクション', pinned: 'ピン留め', smart: 'スマート', searchPlaceholder: 'アセットを検索…', empty: 'まだアセットがありません。', details: '詳細' },
};
export default modules;