import { CreativeCostAuthority, type ActualCost, type CostEstimate, type CostPolicy } from '../cost/contracts';
import { canonicalIdempotencyKey, createOperationInstance, immutable, validateDefinition, type CreativeOperationDefinition, type CreativeOperationIdentity, type CreativeOperationInstance, type ExecutionIntent } from '../operations/contracts';
import { buildBillingEvent, ExecutionAuthorizationPolicy, type AuthorizationChecks, type BillingEvent, type BillingReservation, type BillingTransactionAuthority, type ExecutionAuthorization, type UnifiedOperationOutcome } from './contracts';
import { transitionLifecycle, type OperationLifecycleState } from './lifecycle';

type State = { definition: CreativeOperationDefinition; instance?: CreativeOperationInstance; estimate?: CostEstimate; authorization?: ExecutionAuthorization; reservation?: BillingReservation; outcome?: Readonly<Record<string, unknown>>; actualCost?: ActualCost; billingEvent?: BillingEvent; lifecycle: OperationLifecycleState };
export type CreativeOperationAuthorityDependencies = Readonly<{ billing: BillingTransactionAuthority; now?: () => string; id?: () => string; execute?: (instance: CreativeOperationInstance, authorization: ExecutionAuthorization) => Promise<Readonly<Record<string, unknown>>> }>;

/** A contract facade; planning, execution and financial mutation remain delegated. */
export class CreativeOperationAuthority {
  readonly #records = new Map<string, State>(); readonly #definitions = new Map<string, CreativeOperationDefinition>();
  readonly #cost = new CreativeCostAuthority(); readonly #policy = new ExecutionAuthorizationPolicy();
  readonly #now: () => string; readonly #id: () => string;
  constructor(private readonly dependencies: CreativeOperationAuthorityDependencies) { this.#now = dependencies.now ?? (() => new Date().toISOString()); this.#id = dependencies.id ?? (() => globalThis.crypto.randomUUID()); }
  define(definition: CreativeOperationDefinition) { validateDefinition(definition); const key = `${definition.operationId}@${definition.version}`; if (this.#definitions.has(key)) throw new Error(`Operation already defined: ${key}`); const value = immutable(structuredClone(definition)); this.#definitions.set(key, value); return value; }
  instantiate(input: Readonly<{ identity: CreativeOperationIdentity; parameters: Readonly<Record<string, unknown>>; inputArtifacts?: readonly string[]; executionIntent: ExecutionIntent; idempotencyKey: string }>) {
    const definition = this.#definitions.get(`${input.identity.operationId}@${input.identity.operationVersion}`); if (!definition) throw new Error('Operation definition is not registered');
    const instance = createOperationInstance({ ...input, definition, createdAt: this.#now() }); const key = canonicalIdempotencyKey(instance); const replay = this.#records.get(key); if (replay?.instance) return replay.instance;
    this.#records.set(key, { definition, instance, lifecycle: 'VALIDATED' }); return instance;
  }
  estimate(instance: CreativeOperationInstance, input: Parameters<CreativeCostAuthority['estimate']>[0]) { const r = this.#require(instance); const value = this.#cost.estimate(input); r.estimate = value; r.lifecycle = transitionLifecycle(r.lifecycle, 'ESTIMATED'); return value; }
  authorize(instance: CreativeOperationInstance, input: Readonly<{ checks: AuthorizationChecks; policyVersion: string; expiresAt: string; costPolicy: CostPolicy }>) {
    const r = this.#require(instance); if (!r.estimate) throw new Error('Cost estimate is required before authorization'); const preflight = this.#cost.preflight(r.estimate, input.costPolicy);
    const value = this.#policy.authorize({ ...input, authorizationId: this.#id(), budgetWarning: preflight.budgetStatus === 'WARNING', checks: { ...input.checks, budgetAllowed: input.checks.budgetAllowed && preflight.allowed } }); r.authorization = value; r.lifecycle = transitionLifecycle(r.lifecycle, value.allowed ? 'AUTHORIZED' : 'REJECTED'); return value;
  }
  async reserve(instance: CreativeOperationInstance) { const r = this.#authorized(instance); if (!r.estimate) throw new Error('Cost estimate is required'); if (r.reservation) return r.reservation;
    r.reservation = !r.definition.billable || r.estimate.worstCaseCredits === 0 ? immutable({ reservationId: `free:${canonicalIdempotencyKey(instance)}`, status: 'RESERVED' as const }) : await this.dependencies.billing.reserve({ identity: instance.identity, authorizationId: r.authorization!.authorizationId, amount: r.estimate.worstCaseCredits, idempotencyKey: canonicalIdempotencyKey(instance) }); r.lifecycle = transitionLifecycle(r.lifecycle, 'RESERVED'); return r.reservation; }
  async execute(instance: CreativeOperationInstance) { const r = this.#authorized(instance); if (!r.reservation) throw new Error('Reservation is required before execution'); if (r.lifecycle === 'UNKNOWN') throw new Error('Unknown execution requires recovery resolution'); r.lifecycle = transitionLifecycle(r.lifecycle, 'DISPATCHED'); if (!this.dependencies.execute) return immutable({ status: 'DISPATCHED' }); try { r.lifecycle = transitionLifecycle(r.lifecycle, 'RUNNING'); return this.recordOutcome(instance, await this.dependencies.execute(instance, r.authorization!)); } catch (error) { r.lifecycle = transitionLifecycle(r.lifecycle, 'FAILED'); throw error; } }
  recordOutcome(instance: CreativeOperationInstance, outcome: Readonly<Record<string, unknown>>) { const r = this.#require(instance); r.outcome = immutable(structuredClone(outcome)); if (r.lifecycle === 'DISPATCHED') r.lifecycle = transitionLifecycle(r.lifecycle, 'RUNNING'); if (r.lifecycle === 'RUNNING') r.lifecycle = transitionLifecycle(r.lifecycle, 'VERIFYING'); return r.outcome; }
  recordActualCost(instance: CreativeOperationInstance, cost: ActualCost) { const r = this.#require(instance); r.actualCost = immutable(structuredClone(cost)); return r.actualCost; }
  buildBillingEvent(instance: CreativeOperationInstance, amount: number, creditUnit = 'CREDIT') { const r = this.#authorized(instance); if (!r.reservation || !r.actualCost) throw new Error('Reservation and actual cost are required before billing'); r.billingEvent = buildBillingEvent({ billingEventId: this.#id(), identity: instance.identity, authorization: r.authorization!, reservation: r.reservation, billableAmount: amount, creditUnit, occurredAt: this.#now() }); return r.billingEvent; }
  async release(instance: CreativeOperationInstance, reason: string) { const r = this.#require(instance); if (!r.reservation) throw new Error('Reservation is required'); r.reservation = r.reservation.reservationId.startsWith('free:') ? immutable({ ...r.reservation, status: 'RELEASED' as const }) : await this.dependencies.billing.release(r.reservation.reservationId, reason); r.lifecycle = transitionLifecycle(r.lifecycle, 'RELEASED'); return r.reservation; }
  async commit(instance: CreativeOperationInstance) { const r = this.#authorized(instance); if (!r.billingEvent || !r.reservation) throw new Error('Billing event is required before commit'); if (r.reservation.status === 'UNKNOWN') throw new Error('Unknown billing outcome cannot be committed automatically'); r.reservation = r.reservation.reservationId.startsWith('free:') ? immutable({ ...r.reservation, status: 'COMMITTED' as const }) : await this.dependencies.billing.commit(r.reservation.reservationId); r.lifecycle = transitionLifecycle(r.lifecycle, 'COMMITTED'); return r.reservation; }
  inspect(instance: CreativeOperationInstance) { return this.snapshot(instance); } snapshot(instance: CreativeOperationInstance) { return immutable(structuredClone(this.#require(instance))); } debug() { return immutable({ definitions: this.#definitions.size, instances: this.#records.size, lifecycles: [...this.#records.values()].map(x => x.lifecycle) }); }
  unifiedOutcome(instance: CreativeOperationInstance, ids: Readonly<{ executionId: string; providerExecutionId?: string; localExecutionId?: string }>): UnifiedOperationOutcome { const r = this.#authorized(instance); if (!r.estimate || !r.actualCost || !r.billingEvent) throw new Error('Unified outcome is incomplete'); return immutable({ operationId: instance.operationId, ...ids, authorizationId: r.authorization!.authorizationId, estimatedCost: r.estimate, actualCost: r.actualCost, billableCredits: r.billingEvent.billableAmount }); }
  #require(instance: CreativeOperationInstance) { const r = this.#records.get(canonicalIdempotencyKey(instance)); if (!r) throw new Error('Unknown operation instance'); return r; }
  #authorized(instance: CreativeOperationInstance) { const r = this.#require(instance); if (!r.authorization?.allowed || new Date(r.authorization.expiresAt).getTime() <= new Date(this.#now()).getTime()) throw new Error('Valid execution authorization is required'); return r; }
}
