// RecipeLibrary — the built-in recipe catalog. Each recipe follows the Recipe Model.
// structuredPrompt: { action, target, attributes, preserve } — consumed by the Recipe Engine.
const r = (recipe) => ({
  requiredObjects: 0, supportedObjectTypes: [], variables: [], qualityLevel: 'standard',
  credits: 30, recommendedProvider: 'reve', isPremium: false, version: '1.0', previewImage: null,
  ...recipe,
});

export const RECIPE_LIBRARY = [
  // --- Hair ---
  r({ id: 'hair_change_color', name: 'Change Hair Color', description: 'Recolor hair naturally', icon: 'Palette', category: 'hair', tags: ['hair', 'color'], requiredObjects: 1, supportedObjectTypes: ['hair', 'person', 'woman', 'man'], variables: ['hair_color'], defaultPrompt: 'Change the hair color to {{hair_color}}, keeping natural texture, shine and individual strands', structuredPrompt: { action: 'recolor', target: 'hair', attributes: ['natural texture', 'realistic shine'], preserve: ['face', 'hairstyle'] } }),
  r({ id: 'hair_long', name: 'Long Hair', description: 'Make hair longer', icon: 'Scissors', category: 'hair', tags: ['hair', 'length'], requiredObjects: 1, supportedObjectTypes: ['hair', 'person', 'woman', 'man'], variables: ['hair_length'], defaultPrompt: 'Make the hair {{hair_length}} with a natural flow and realistic volume', structuredPrompt: { action: 'restyle', target: 'hair', attributes: ['natural flow'], preserve: ['face', 'hair color'] } }),
  r({ id: 'hair_curly', name: 'Curly Hair', description: 'Add natural curls', icon: 'Scissors', category: 'hair', tags: ['hair', 'curls'], requiredObjects: 1, supportedObjectTypes: ['hair', 'person', 'woman', 'man'], defaultPrompt: 'Make the hair naturally curly with soft, defined curls', structuredPrompt: { action: 'restyle', target: 'hair', attributes: ['soft defined curls'], preserve: ['face', 'hair color', 'length'] } }),
  r({ id: 'hair_improve', name: 'Improve Hair', description: 'Healthy, polished hair', icon: 'Scissors', category: 'hair', tags: ['hair', 'enhance'], requiredObjects: 1, supportedObjectTypes: ['hair', 'person', 'woman', 'man', 'face'], defaultPrompt: 'Improve the hair: make it look healthy, neatly styled and shiny, taming frizz and flyaways', structuredPrompt: { action: 'enhance', target: 'hair', attributes: ['healthy shine', 'tamed frizz'], preserve: ['hair color', 'hairstyle', 'face'] } }),
  r({ id: 'hair_straight', name: 'Straight Hair', description: 'Smooth, straight hair', icon: 'Scissors', category: 'hair', tags: ['hair', 'straight'], requiredObjects: 1, supportedObjectTypes: ['hair', 'person', 'woman', 'man'], defaultPrompt: 'Make the hair perfectly straight and smooth with a healthy shine', structuredPrompt: { action: 'restyle', target: 'hair', attributes: ['smooth', 'healthy shine'], preserve: ['face', 'hair color', 'length'] } }),
  // --- Face / Skin / Eyes / Lips ---
  r({ id: 'face_remove_wrinkles', name: 'Remove Wrinkles', description: 'Soften wrinkles naturally', icon: 'Sparkles', category: 'face', tags: ['face', 'wrinkles', 'retouch'], requiredObjects: 1, supportedObjectTypes: ['face', 'person', 'woman', 'man'], variables: ['intensity'], defaultPrompt: 'Reduce facial wrinkles with a {{intensity}} effect while keeping natural skin texture and pores', structuredPrompt: { action: 'retouch', target: 'face', attributes: ['natural skin texture'], preserve: ['identity', 'expression'] } }),
  r({ id: 'skin_smooth', name: 'Smooth Skin', description: 'Even out skin naturally', icon: 'Sparkles', category: 'skin', tags: ['skin', 'retouch'], requiredObjects: 1, supportedObjectTypes: ['face', 'skin', 'person', 'woman', 'man'], variables: ['skin_smoothness'], defaultPrompt: 'Smooth and even out the skin with a {{skin_smoothness}} effect, removing blemishes but keeping realistic pores', structuredPrompt: { action: 'retouch', target: 'skin', attributes: ['even tone', 'realistic pores'], preserve: ['identity', 'skin color'] } }),
  r({ id: 'face_whiten_teeth', name: 'Whiten Teeth', description: 'Natural teeth whitening', icon: 'Smile', category: 'face', tags: ['teeth', 'smile'], requiredObjects: 1, supportedObjectTypes: ['face', 'person', 'woman', 'man'], defaultPrompt: 'Whiten the teeth to a natural bright white without changing their shape', structuredPrompt: { action: 'whiten', target: 'teeth', attributes: ['natural white'], preserve: ['smile shape', 'lips'] } }),
  r({ id: 'face_smile', name: 'Add Smile', description: 'Natural friendly smile', icon: 'Smile', category: 'face', tags: ['smile', 'expression'], requiredObjects: 1, supportedObjectTypes: ['face', 'person', 'woman', 'man'], variables: ['smile_strength'], defaultPrompt: 'Add a {{smile_strength}} natural smile that fits the face', structuredPrompt: { action: 'expression', target: 'face', attributes: ['natural smile'], preserve: ['identity', 'eyes'] } }),
  r({ id: 'eyes_enhance', name: 'Eye Enhancement', description: 'Brighter, sharper eyes', icon: 'Eye', category: 'eyes', tags: ['eyes', 'enhance'], requiredObjects: 1, supportedObjectTypes: ['face', 'eyes', 'person', 'woman', 'man'], defaultPrompt: 'Enhance the eyes: brighten the whites slightly, sharpen the iris detail and add a subtle catchlight', structuredPrompt: { action: 'enhance', target: 'eyes', attributes: ['iris detail', 'catchlight'], preserve: ['eye color', 'identity'] } }),
  r({ id: 'lips_color', name: 'Lip Color', description: 'Natural lip tint', icon: 'Heart', category: 'lips', tags: ['lips', 'makeup'], requiredObjects: 1, supportedObjectTypes: ['face', 'lips', 'person', 'woman'], variables: ['object_color'], defaultPrompt: 'Tint the lips {{object_color}} with a natural, softly blended finish', structuredPrompt: { action: 'recolor', target: 'lips', attributes: ['soft blend'], preserve: ['lip shape', 'identity'] } }),
  // --- Clothing / Shoes / Accessories ---
  r({ id: 'clothing_recolor', name: 'Recolor Clothing', description: 'Change garment color', icon: 'Shirt', category: 'clothing', tags: ['clothing', 'color'], requiredObjects: 1, supportedObjectTypes: ['shirt', 'dress', 'jacket', 'clothing', 'pants', 'coat', 't-shirt', 'suit'], variables: ['object_color'], defaultPrompt: 'Change the garment color to {{object_color}}, keeping fabric texture, folds and shadows realistic', structuredPrompt: { action: 'recolor', target: 'clothing', attributes: ['fabric texture', 'realistic folds'], preserve: ['fit', 'style'] } }),
  r({ id: 'clothing_material', name: 'Change Material', description: 'Swap fabric material', icon: 'Shirt', category: 'clothing', tags: ['clothing', 'material'], requiredObjects: 1, supportedObjectTypes: ['shirt', 'dress', 'jacket', 'clothing', 'pants', 'coat', 'suit'], variables: ['material'], isPremium: true, defaultPrompt: 'Change the garment material to {{material}} with realistic texture, drape and light response', structuredPrompt: { action: 'material', target: 'clothing', attributes: ['realistic drape'], preserve: ['fit', 'color tone'] } }),
  r({ id: 'clothing_replace_top', name: 'Replace Shirt', description: 'Swap the top for a new one', icon: 'Shirt', category: 'clothing', tags: ['clothing', 'shirt', 'replace'], requiredObjects: 1, supportedObjectTypes: ['shirt', 't-shirt', 'top', 'blouse', 'clothing', 'jacket', 'person'], variables: ['object_color', 'material'], defaultPrompt: 'Replace the shirt with a stylish {{object_color}} {{material}} top that fits the person naturally, with realistic folds and correct body fit', structuredPrompt: { action: 'replace', target: 'shirt', attributes: ['natural fit', 'realistic folds'], preserve: ['body pose', 'skin', 'other clothing'] } }),
  r({ id: 'clothing_change_pants', name: 'Change Pants', description: 'New pants style and color', icon: 'Shirt', category: 'clothing', tags: ['clothing', 'pants', 'replace'], requiredObjects: 1, supportedObjectTypes: ['pants', 'jeans', 'trousers', 'shorts', 'skirt', 'clothing', 'person'], variables: ['object_color', 'material'], defaultPrompt: 'Change the pants to well-fitted {{object_color}} {{material}} pants with a natural drape and correct proportions', structuredPrompt: { action: 'replace', target: 'pants', attributes: ['natural drape', 'correct fit'], preserve: ['body pose', 'shoes', 'top'] } }),
  r({ id: 'accessories_add', name: 'Add Accessories', description: 'Stylish complementary accessories', icon: 'Watch', category: 'accessories', tags: ['accessories', 'style', 'add'], requiredObjects: 1, supportedObjectTypes: ['person', 'woman', 'man'], defaultPrompt: 'Add tasteful fashion accessories that complement the outfit — such as a watch, subtle jewelry or a belt — placed naturally and realistically', structuredPrompt: { action: 'add', target: 'accessories', attributes: ['tasteful', 'natural placement'], preserve: ['outfit', 'pose', 'identity'] } }),
  r({ id: 'shoes_recolor', name: 'Recolor Shoes', description: 'Change shoe color', icon: 'Footprints', category: 'shoes', tags: ['shoes', 'color'], requiredObjects: 1, supportedObjectTypes: ['shoes', 'sneakers', 'boots', 'heels'], variables: ['object_color'], defaultPrompt: 'Change the shoes to {{object_color}}, keeping material texture and stitching detail', structuredPrompt: { action: 'recolor', target: 'shoes', attributes: ['material texture'], preserve: ['shape', 'laces'] } }),
  r({ id: 'accessories_remove', name: 'Remove Accessory', description: 'Cleanly remove an accessory', icon: 'Watch', category: 'accessories', tags: ['remove', 'cleanup'], requiredObjects: 1, supportedObjectTypes: ['glasses', 'hat', 'watch', 'bag', 'jewelry', 'necklace', 'earrings'], defaultPrompt: 'Remove this accessory completely and reconstruct what is naturally behind it', structuredPrompt: { action: 'remove', target: 'accessory', attributes: ['clean reconstruction'], preserve: ['surrounding area'] } }),
  // --- Background / Sky ---
  r({ id: 'bg_blur', name: 'Blur Background', description: 'Portrait-style bokeh', icon: 'Image', category: 'background', tags: ['background', 'blur', 'bokeh'], variables: ['intensity'], defaultPrompt: 'Blur the background with a {{intensity}} photographic bokeh, keeping the subject perfectly sharp', structuredPrompt: { action: 'blur', target: 'background', attributes: ['photographic bokeh'], preserve: ['subject sharpness'] } }),
  r({ id: 'bg_replace', name: 'Replace Background', description: 'New scene behind subject', icon: 'Image', category: 'background', tags: ['background', 'replace'], variables: ['background_scene'], isPremium: true, defaultPrompt: 'Replace the background with a {{background_scene}} scene, matching the lighting and perspective of the subject', structuredPrompt: { action: 'replace', target: 'background', attributes: ['matched lighting', 'matched perspective'], preserve: ['subject'] } }),
  r({ id: 'bg_studio', name: 'Studio Background', description: 'Clean studio backdrop', icon: 'Image', category: 'background', tags: ['background', 'studio', 'product'], defaultPrompt: 'Replace the background with a clean, seamless white studio backdrop with soft professional lighting', structuredPrompt: { action: 'replace', target: 'background', attributes: ['seamless white', 'soft lighting'], preserve: ['subject'] } }),
  r({ id: 'sky_sunset', name: 'Sunset Sky', description: 'Dramatic sunset sky', icon: 'Cloud', category: 'sky', tags: ['sky', 'sunset'], variables: ['time_of_day'], defaultPrompt: 'Replace the sky with a beautiful {{time_of_day}} sky and adjust the scene lighting to match', structuredPrompt: { action: 'replace', target: 'sky', attributes: ['matched scene lighting'], preserve: ['foreground', 'horizon line'] } }),
  r({ id: 'sky_weather', name: 'Change Weather', description: 'New weather mood', icon: 'Cloud', category: 'sky', tags: ['sky', 'weather'], variables: ['weather'], defaultPrompt: 'Change the weather to {{weather}} with consistent lighting and atmosphere across the whole scene', structuredPrompt: { action: 'weather', target: 'scene', attributes: ['consistent atmosphere'], preserve: ['composition', 'subjects'] } }),
  // --- Nature / Architecture / Food / Pets / Vehicles / Objects ---
  r({ id: 'nature_greener', name: 'Lush Greenery', description: 'Vibrant healthy plants', icon: 'Trees', category: 'nature', tags: ['nature', 'plants'], defaultPrompt: 'Make the vegetation lush, green and healthy with vibrant natural color', structuredPrompt: { action: 'enhance', target: 'vegetation', attributes: ['vibrant green'], preserve: ['scene layout'] } }),
  r({ id: 'arch_facade', name: 'Fresh Facade', description: 'Clean building exterior', icon: 'Building2', category: 'architecture', tags: ['building', 'restore'], requiredObjects: 1, supportedObjectTypes: ['building', 'house', 'wall', 'facade'], defaultPrompt: 'Refresh the building facade: clean surfaces, repaired paint, no dirt or damage', structuredPrompt: { action: 'restore', target: 'building', attributes: ['clean surfaces'], preserve: ['architecture', 'style'] } }),
  r({ id: 'food_appetizing', name: 'Appetizing Food', description: 'Menu-ready food shot', icon: 'UtensilsCrossed', category: 'food', tags: ['food', 'restaurant'], requiredObjects: 1, supportedObjectTypes: ['food', 'plate', 'dish', 'meal'], defaultPrompt: 'Make the food look fresh and appetizing with rich color, appealing texture and a subtle glisten', structuredPrompt: { action: 'enhance', target: 'food', attributes: ['rich color', 'fresh look'], preserve: ['plating', 'dish contents'] } }),
  r({ id: 'pets_groomed', name: 'Groomed Pet', description: 'Clean, fluffy coat', icon: 'PawPrint', category: 'pets', tags: ['pet', 'fur'], requiredObjects: 1, supportedObjectTypes: ['dog', 'cat', 'pet', 'animal'], defaultPrompt: 'Make the pet look freshly groomed with a clean, fluffy, healthy coat', structuredPrompt: { action: 'enhance', target: 'pet', attributes: ['healthy coat'], preserve: ['breed features', 'pose'] } }),
  r({ id: 'vehicle_recolor', name: 'Recolor Vehicle', description: 'New paint color', icon: 'Car', category: 'vehicles', tags: ['car', 'color'], requiredObjects: 1, supportedObjectTypes: ['car', 'truck', 'vehicle', 'motorcycle', 'bike'], variables: ['object_color'], defaultPrompt: 'Repaint the vehicle {{object_color}} with a realistic glossy finish, keeping reflections and trim intact', structuredPrompt: { action: 'recolor', target: 'vehicle', attributes: ['glossy finish', 'realistic reflections'], preserve: ['trim', 'wheels', 'windows'] } }),
  r({ id: 'vehicle_remove_reflections', name: 'Remove Reflections', description: 'Clean distracting reflections', icon: 'Car', category: 'vehicles', tags: ['car', 'reflections', 'cleanup'], requiredObjects: 1, supportedObjectTypes: ['car', 'truck', 'vehicle', 'motorcycle'], defaultPrompt: 'Remove distracting reflections from the vehicle body and windows, keeping natural highlights and the true paint color', structuredPrompt: { action: 'cleanup', target: 'vehicle', attributes: ['natural highlights'], preserve: ['paint color', 'body shape', 'trim'] } }),
  r({ id: 'vehicle_gloss', name: 'Increase Gloss', description: 'Showroom paint shine', icon: 'Car', category: 'vehicles', tags: ['car', 'gloss', 'paint'], requiredObjects: 1, supportedObjectTypes: ['car', 'truck', 'vehicle', 'motorcycle'], variables: ['intensity'], defaultPrompt: 'Increase the gloss of the vehicle paint with a {{intensity}} showroom-quality shine and deep, wet-look finish', structuredPrompt: { action: 'enhance', target: 'vehicle', attributes: ['showroom shine', 'deep finish'], preserve: ['paint color', 'body shape'] } }),
  r({ id: 'vehicle_clean_wheels', name: 'Clean Wheels', description: 'Spotless rims and tires', icon: 'Car', category: 'vehicles', tags: ['car', 'wheels', 'cleanup'], requiredObjects: 1, supportedObjectTypes: ['car', 'truck', 'vehicle', 'motorcycle', 'wheel'], defaultPrompt: 'Make the wheels spotless: clean shiny rims, deep black dressed tires, no brake dust or dirt', structuredPrompt: { action: 'cleanup', target: 'wheels', attributes: ['shiny rims', 'dressed tires'], preserve: ['wheel design', 'vehicle'] } }),
  r({ id: 'object_remove', name: 'Remove Object', description: 'Erase and fill naturally', icon: 'Box', category: 'objects', tags: ['remove', 'cleanup'], requiredObjects: 1, defaultPrompt: 'Remove this object completely and reconstruct the background behind it naturally', structuredPrompt: { action: 'remove', target: 'object', attributes: ['seamless fill'], preserve: ['surroundings'] } }),
  r({ id: 'object_recolor', name: 'Recolor Object', description: 'Change any object color', icon: 'Box', category: 'objects', tags: ['color'], requiredObjects: 1, variables: ['object_color'], defaultPrompt: 'Change this object to {{object_color}}, keeping its material, texture and shading realistic', structuredPrompt: { action: 'recolor', target: 'object', attributes: ['realistic shading'], preserve: ['shape', 'material'] } }),
  // --- Lighting / Color / Professional / Social / Restoration / Creative ---
  r({ id: 'light_golden', name: 'Golden Hour Light', description: 'Warm cinematic light', icon: 'Sun', category: 'lighting', tags: ['lighting', 'warm'], variables: ['intensity'], defaultPrompt: 'Relight the scene with {{intensity}} warm golden hour light and soft natural shadows', structuredPrompt: { action: 'relight', target: 'scene', attributes: ['golden hour', 'soft shadows'], preserve: ['composition', 'subjects'] } }),
  r({ id: 'light_improve', name: 'Improve Lighting', description: 'Balanced flattering light', icon: 'Sun', category: 'lighting', tags: ['lighting', 'enhance'], variables: ['intensity'], defaultPrompt: 'Improve the lighting with a {{intensity}} effect: balanced exposure, soft flattering light on the subject and clean shadow detail', structuredPrompt: { action: 'relight', target: 'scene', attributes: ['balanced exposure', 'soft light'], preserve: ['composition', 'colors', 'subjects'] } }),
  r({ id: 'color_pop', name: 'Color Boost', description: 'Vivid balanced colors', icon: 'Palette', category: 'color', tags: ['color', 'vibrance'], variables: ['brightness', 'contrast'], defaultPrompt: 'Enhance the colors: {{brightness}} brightness lift and {{contrast}} contrast boost with vivid but natural saturation', structuredPrompt: { action: 'grade', target: 'image', attributes: ['natural saturation'], preserve: ['skin tones'] } }),
  r({ id: 'pro_headshot', name: 'Pro Headshot', description: 'LinkedIn-ready portrait', icon: 'Briefcase', category: 'professional', tags: ['portrait', 'linkedin', 'headshot'], isPremium: true, credits: 40, defaultPrompt: 'Turn this into a professional corporate headshot: clean neutral background, soft studio lighting, polished but natural retouch', structuredPrompt: { action: 'transform', target: 'portrait', attributes: ['studio lighting', 'neutral background'], preserve: ['identity', 'expression'] } }),
  r({ id: 'social_instagram', name: 'Instagram Glow', description: 'Feed-ready aesthetic', icon: 'Share2', category: 'social', tags: ['instagram', 'aesthetic'], defaultPrompt: 'Apply a trendy social media aesthetic: soft glow, gentle warm tones and creamy background separation', structuredPrompt: { action: 'grade', target: 'image', attributes: ['soft glow', 'warm tones'], preserve: ['subject', 'composition'] } }),
  r({ id: 'restore_old_photo', name: 'Restore Old Photo', description: 'Fix damage and fading', icon: 'Wand2', category: 'restoration', tags: ['restore', 'old', 'repair'], isPremium: true, credits: 40, defaultPrompt: 'Restore this photo: repair scratches and damage, remove fading and noise, recover natural colors and sharpness', structuredPrompt: { action: 'restore', target: 'image', attributes: ['damage repair', 'color recovery'], preserve: ['original content', 'faces'] } }),
  r({ id: 'detail_sharpen', name: 'Increase Sharpness', description: 'Crisper fine detail', icon: 'Focus', category: 'restoration', tags: ['sharpen', 'detail', 'enhance'], variables: ['intensity'], defaultPrompt: 'Increase the overall image sharpness with a {{intensity}} effect, enhancing fine detail without halos or noise', structuredPrompt: { action: 'enhance', target: 'image', attributes: ['fine detail', 'no halos'], preserve: ['composition', 'colors', 'subjects'] } }),
  r({ id: 'creative_painting', name: 'Oil Painting', description: 'Classic painted look', icon: 'Paintbrush', category: 'creative', tags: ['art', 'painting'], variables: ['intensity'], defaultPrompt: 'Transform the image into an oil painting with {{intensity}} visible brush strokes and rich canvas texture', structuredPrompt: { action: 'stylize', target: 'image', attributes: ['brush strokes', 'canvas texture'], preserve: ['composition', 'subjects'] } }),
];