import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { once } from 'node:events';
import test from 'node:test';
import sharp from 'sharp';
import { createCreativeCore, type CreativeCoreDependencies, type ExecuteInput } from '../server/core/composition/createCreativeCore.ts';
import { createCreativeHttpHandler } from '../server/core/http/creativeHttpHandler.ts';
import { nodeHttpAdapter } from '../server/core/http/nodeHttpAdapter.ts';
import type { CreativeArtifact, ProductionOutcome } from '../src/platform/creative/canonical/contracts.ts';
import type { PixelImage } from '../src/platform/creative/pipeline/ControlledLocalEdit.ts';

const scope = { tenantId: 'tenant-controlled', userId: 'user-controlled', projectId: 'project-controlled' };
const rgba = (width: number, height: number, pixel: readonly number[] = [17, 31, 47, 255]): PixelImage => ({ width, height, data: new Uint8ClampedArray(width * height * 4).map((_, index) => pixel[index % 4]), format: 'raw', orientation: 1 });
const maskValue = (width: number, height: number, bounds: { x: number; y: number; width: number; height: number }, feather = false) => { const alpha = new Uint8Array(width * height); for (let y = bounds.y; y < bounds.y + bounds.height; y++) for (let x = bounds.x; x < bounds.x + bounds.width; x++) alpha[y * width + x] = feather && (x === bounds.x || y === bounds.y || x === bounds.x + bounds.width - 1 || y === bounds.y + bounds.height - 1) ? 128 : 255; return { width, height, source: 'USER' as const, alpha }; };
const artifact = (id: string, role: 'ORIGINAL' | 'MASK', value: unknown, image?: CreativeArtifact['image']): CreativeArtifact => ({ id, kind: role === 'MASK' ? 'mask' : 'image', value, producerOperationId: 'upload', scope, state: 'AVAILABLE', role, image });

type Failure = 'NONE' | 'DEFINITIVE' | 'UNKNOWN';
function fixture(input: Readonly<{ original: CreativeArtifact; mask?: CreativeArtifact; failure?: Failure; invalidBoundary?: boolean }>) {
  const stored = new Map([input.original, ...(input.mask ? [input.mask] : [])].map(item => [item.id, item])); const billing: string[] = []; const providerRequests: { operationType: string; artifacts: readonly CreativeArtifact[] }[] = []; let outcome: ProductionOutcome | undefined;
  const dependencies: CreativeCoreDependencies = {
    auth: { verify: async token => token === 'valid' ? { tenantId: scope.tenantId, userId: scope.userId } : undefined },
    artifacts: { projectBelongsTo: async (id, identity) => id === scope.projectId && identity.userId === scope.userId, resolveArtifact: async (id, requested) => requested.userId === scope.userId ? stored.get(id) : undefined, resolveLegacyUrl: async () => undefined }, telemetry: { record: () => undefined }, trustedAssetHosts: ['assets.example.test'], maxCredits: 10,
    platform: {
      decision: { decide: async request => ({ requestId: request.id, goal: request.intent, constraints: [] }) },
      planning: { plan: async request => { const controlled = request.metadata?.editCapability === 'CONTROLLED_LOCAL_EDIT'; return { requestId: request.id, operations: [{ id: 'canonical-edit', type: controlled ? 'CONTROLLED_LOCAL_EDIT' : 'GLOBAL_EDIT', requiredArtifacts: (request.inputArtifacts ?? []).map(item => item.id), produces: ['image'], providerId: 'forged-planner-provider', cost: { credits: 1, aiCalls: 1 }, input: { instruction: request.intent, preserveMode: request.metadata?.preserveMode, haloPixels: 0, boundaryMeanDeltaLimit: input.invalidBoundary ? 0 : undefined } }] }; } },
      routeSelector: { select: () => 'PROVIDER' }, targetSelector: { select: () => 'CLOUD' }, providerSelector: { select: () => ({ allowed: true, reasonCode: 'PROVIDER_SELECTED', providerId: 'deterministic', selectionId: 'synthetic-controlled:deterministic' }) }, capabilityAdmission: { admit: () => ({ allowed: true, reasonCode: 'CAPABILITY_SUPPORTED', capabilityId: 'synthetic-controlled-test-runtime' }) }, securityGate: { authorize: () => true }, recovery: { decide: () => 'MARK_UNKNOWN' }, providers: { isAvailable: () => true, fallback: () => undefined },
      runtime: { execute: async request => { assert.equal(request.operation.providerId, 'deterministic'); providerRequests.push({ operationType: request.operation.type, artifacts: request.artifacts as readonly CreativeArtifact[] }); if (input.failure === 'DEFINITIVE') throw new Error('provider rejected request'); if (input.failure === 'UNKNOWN') throw Object.assign(new Error('provider result pending'), { code: 'PROVIDER_RESULT_UNKNOWN' }); const roi = request.artifacts.find(item => item.metadata?.artifactRole === 'ROI_INPUT')?.value as PixelImage | undefined; if (!roi) return { artifacts: [{ id: 'global-result', kind: 'image', value: rgba(2, 2) }] }; return { artifacts: [{ id: 'raw-provider-result', kind: 'image', value: rgba(roi.width, roi.height, [230, 20, 40, 255]) }] }; } },
      billing: { reserve: async () => { billing.push('reserve'); return { reservationId: 'reservation', status: 'RESERVED' }; }, commit: async id => { billing.push('commit'); return { reservationId: id, status: 'COMMITTED' }; }, release: async id => { billing.push('release'); return { reservationId: id, status: 'RELEASED' }; } }, telemetry: { record: value => { outcome = value; } }, now: (() => { let now = 1_900_000_000_000; return () => ++now; })(), id: (() => { let id = 0; return () => `generated-${++id}`; })(),
    },
  };
  return { dependencies, billing, providerRequests, outcome: () => outcome };
}

async function execute(f: ReturnType<typeof fixture>, body: ExecuteInput) {
  const core = createCreativeCore(f.dependencies); const server = createServer(nodeHttpAdapter(createCreativeHttpHandler(core))); server.listen(0, '127.0.0.1'); await once(server, 'listening'); const address = server.address(); assert(address && typeof address === 'object');
  const response = await fetch(`http://127.0.0.1:${address.port}/api/core/creative/execute`, { method: 'POST', headers: { authorization: 'Bearer valid', 'content-type': 'application/json' }, body: JSON.stringify(body) }); const accepted = await response.json() as { executionId: string }; let error: unknown; try { await core.wait({ tenantId: scope.tenantId, userId: scope.userId }, accepted.executionId); } catch (cause) { error = cause; } await new Promise<void>(resolve => server.close(() => resolve())); return { response, error, outcome: f.outcome() };
}
const body = (suffix: string, preserveMode: 'STRICT' | 'BALANCED' | 'CREATIVE' = 'STRICT'): ExecuteInput => ({ clientRequestId: `controlled-${suffix}`, projectId: scope.projectId, artifactId: 'original', maskArtifactIds: ['mask'], selectedObjectIds: ['selected-object'], intent: 'replace selected object locally', preserveMode, budget: { credits: 1 } });

test('HTTP canonical controlled edit routes selection, sends only ROI, records lineage, composites and commits once', async () => {
  const original = artifact('original', 'ORIGINAL', rgba(6000, 4000), { width: 6000, height: 4000, format: 'raw', orientation: 1 }); const selection = artifact('mask', 'MASK', maskValue(6000, 4000, { x: 2400, y: 1200, width: 1200, height: 1600 })); const f = fixture({ original, mask: selection }); const result = await execute(f, body('vertical'));
  assert.equal(result.response.status, 202); assert.equal(result.outcome?.status, 'SUCCESS'); assert.deepEqual(f.billing, ['reserve', 'commit']); assert.equal(f.providerRequests.length, 1); assert.equal(f.providerRequests[0].operationType, 'CONTROLLED_LOCAL_EDIT'); const providerInput = f.providerRequests[0].artifacts.find(item => item.metadata?.artifactRole === 'ROI_INPUT')?.value as PixelImage; assert.ok(providerInput.width >= 1200 && providerInput.width < 2000); assert.ok(providerInput.height >= 1600 && providerInput.height < 2400); assert.notDeepEqual([providerInput.width, providerInput.height], [6000, 4000]);
  const artifacts = result.outcome!.artifacts; assert.deepEqual(artifacts.filter(item => item.state === 'FINAL').map(item => item.role), ['COMPOSITE']); assert.deepEqual(artifacts.map(item => item.role), ['ORIGINAL', 'MASK', 'ROI_INPUT', 'PATCH', 'VERIFIED_PATCH', 'COMPOSITE']); const final = artifacts.find(item => item.role === 'COMPOSITE')!.value as PixelImage; assert.deepEqual([final.width, final.height], [6000, 4000]); assert.deepEqual(Array.from(final.data.slice(0, 4)), Array.from((original.value as PixelImage).data.slice(0, 4))); assert.deepEqual(Array.from(final.data.slice((1200 * 6000 + 2400) * 4, (1200 * 6000 + 2400) * 4 + 4)), [230, 20, 40, 255]);
});

test('global edit remains a separate canonical operation', async () => { const original = artifact('original', 'ORIGINAL', rgba(2, 2)); const f = fixture({ original }); const result = await execute(f, { clientRequestId: 'global', projectId: scope.projectId, artifactId: 'original', intent: 'change the whole image', budget: { credits: 1 } }); assert.equal(result.outcome?.status, 'SUCCESS'); assert.equal(f.providerRequests[0].operationType, 'GLOBAL_EDIT'); });

test('canonical preserve modes protect outside pixels and STRICT is the object-edit default', async () => { for (const mode of ['STRICT', 'BALANCED', 'CREATIVE'] as const) { const originalImage = rgba(12, 10, [9, 19, 29, 99]); const f = fixture({ original: artifact('original', 'ORIGINAL', originalImage), mask: artifact('mask', 'MASK', maskValue(12, 10, { x: 4, y: 3, width: 3, height: 4 })) }); const request = body(mode.toLowerCase(), mode); if (mode === 'STRICT') delete (request as { preserveMode?: string }).preserveMode; const result = await execute(f, request); assert.equal(result.outcome?.status, 'SUCCESS'); const composite = result.outcome!.artifacts.find(item => item.role === 'COMPOSITE')!.value as PixelImage; assert.deepEqual(Array.from(composite.data.slice(0, 4)), [9, 19, 29, 99]); assert.equal((result.outcome!.artifacts.find(item => item.role === 'COMPOSITE')!.metadata?.integrityMetrics as { preserveMode: string }).preserveMode, mode); } });

test('verification failure makes one paid call, creates no final artifact and does not retry', async () => { const original = rgba(8, 8); const f = fixture({ original: artifact('original', 'ORIGINAL', original), mask: artifact('mask', 'MASK', maskValue(8, 8, { x: 2, y: 2, width: 4, height: 4 }, true)), invalidBoundary: true }); const result = await execute(f, body('verify-fail')); assert.equal(result.outcome?.status, 'FAILED'); assert.equal(result.outcome?.verification.valid, false); assert.equal(f.providerRequests.length, 1); assert.equal(result.outcome?.artifacts.some(item => item.state === 'FINAL'), false); assert.deepEqual(f.billing, ['reserve', 'release']); });

test('definitive failure releases while UNKNOWN keeps reservation without retry', async () => { for (const failure of ['DEFINITIVE', 'UNKNOWN'] as const) { const f = fixture({ original: artifact('original', 'ORIGINAL', rgba(8, 8)), mask: artifact('mask', 'MASK', maskValue(8, 8, { x: 2, y: 2, width: 3, height: 3 })), failure }); const result = await execute(f, body(failure)); assert.equal(f.providerRequests.length, 1); assert.deepEqual(f.billing, failure === 'DEFINITIVE' ? ['reserve', 'release'] : ['reserve']); assert.equal(result.outcome?.status, failure === 'UNKNOWN' ? 'UNKNOWN' : 'FAILED'); } });

test('real JPEG decode preserves orientation, selection location, resolution and decoded outside pixels', async () => { const width = 20, height = 12; const source = rgba(width, height); for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) { const offset = (y * width + x) * 4; source.data[offset] = x * 9; source.data[offset + 1] = y * 13; } const encoded = await sharp(Buffer.from(source.data), { raw: { width, height, channels: 4 } }).jpeg().withMetadata({ orientation: 1 }).toBuffer(); const decoded = await sharp(encoded).rotate().ensureAlpha().raw().toBuffer({ resolveWithObject: true }); const original = rgba(decoded.info.width, decoded.info.height); original.data.set(decoded.data); const f = fixture({ original: artifact('original', 'ORIGINAL', original, { width, height, format: 'jpeg', orientation: 1 }), mask: artifact('mask', 'MASK', maskValue(width, height, { x: 7, y: 4, width: 5, height: 3 })) }); const result = await execute(f, body('jpeg')); const final = result.outcome!.artifacts.find(item => item.role === 'COMPOSITE')!.value as PixelImage; assert.deepEqual([final.width, final.height, final.orientation], [width, height, 1]); assert.deepEqual(Array.from(final.data.slice(0, 4)), Array.from(original.data.slice(0, 4))); assert.deepEqual(Array.from(final.data.slice((4 * width + 7) * 4, (4 * width + 7) * 4 + 4)), [230, 20, 40, 255]); });

test('real PNG alpha survives canonical controlled composition outside selection', async () => { const width = 9, height = 7, source = rgba(width, height, [40, 80, 120, 64]); const encoded = await sharp(Buffer.from(source.data), { raw: { width, height, channels: 4 } }).png().toBuffer(); const decoded = await sharp(encoded).ensureAlpha().raw().toBuffer({ resolveWithObject: true }); const original = rgba(width, height); original.data.set(decoded.data); const f = fixture({ original: artifact('original', 'ORIGINAL', original, { width, height, format: 'png', orientation: 1, alpha: true }), mask: artifact('mask', 'MASK', maskValue(width, height, { x: 3, y: 2, width: 2, height: 3 })) }); const result = await execute(f, body('png-alpha')); const final = result.outcome!.artifacts.find(item => item.role === 'COMPOSITE')!.value as PixelImage; assert.deepEqual(Array.from(final.data.slice(0, 4)), [40, 80, 120, 64]); assert.equal(final.data[(2 * width + 3) * 4 + 3], 255); });
