import assert from 'node:assert/strict';
import test from 'node:test';
import { CreativeExecutionService } from '../server/core/application/creativeExecutionService.ts';
import { createCreativeExecuteHandler } from '../server/core/http/creativeExecuteHandler.ts';
import type { BillingTransactionAuthority } from '../src/platform/creative/authority/contracts.ts';
import { TransactionBillingAuthorityAdapter } from '../server/core/billing/TransactionBillingAuthorityAdapter.ts';
import { TransactionService } from '../server/transactions/application/transactionService.ts';
import { InMemoryTransactionStore } from '../server/transactions/infrastructure/memory/inMemoryTransactionStore.ts';

const auth = { tenantId: 'tenant-a', userId: 'user-a' }; const command = { projectId: 'project-a', instruction: 'make the product blue', inputArtifactId: 'artifact-a', clientRequestId: 'client-1' };
function fixture(options: { runtime?: 'success'|'failure'|'unknown'; security?: boolean; scope?: boolean; estimated?: number; budget?: number } = {}) { const calls = { decision: 0, plan: 0, security: 0, reserve: 0, runtime: 0, verify: 0, commit: 0, release: 0, unknown: 0 }; const billing: BillingTransactionAuthority = { reserve: async () => { calls.reserve++; return { reservationId: 'reservation-1', status: 'RESERVED' }; }, commit: async id => { calls.commit++; return { reservationId: id, status: 'COMMITTED' }; }, release: async id => { calls.release++; return { reservationId: id, status: 'RELEASED' }; }, unknown: async id => { calls.unknown++; return { reservationId: id, status: 'UNKNOWN' }; } }; const service = new CreativeExecutionService({ creditsPerEdit: options.estimated ?? 1, hardBudgetCredits: options.budget, ownsArtifacts: async () => options.scope !== false, platform: { billing, decision: { decide: async request => { calls.decision++; return { requestId: request.id, goal: request.intent, constraints: [] }; } }, planning: { plan: async (request) => { calls.plan++; return { requestId: request.id, operations: [{ id: 'image-edit', type: 'image-edit', providerId: 'fal', produces: ['image'] }] }; } }, targetSelector: { select: () => 'CLOUD' }, securityGate: { authorize: () => { calls.security++; return options.security !== false; } }, runtime: { execute: async () => { calls.runtime++; if (options.runtime === 'unknown') throw Object.assign(new Error('lost response'), { code: 'PROVIDER_RESULT_UNKNOWN', unknownOutcome: true }); if (options.runtime === 'failure') throw new Error('definitive provider failure'); return { artifacts: [{ id: 'result', kind: 'image', value: { url: 'https://assets.example/result.png' } }] }; } }, providers: { isAvailable: () => true, fallback: () => undefined }, verifier: { verify: async () => { calls.verify++; return { stepId: 'image-edit', valid: true, checks: ['image'], errors: [] }; } }, recovery: { decide: () => 'MARK_UNKNOWN' }, now: (() => { let n = 1; return () => n++; })() } }); return { calls, service, handler: createCreativeExecuteHandler(service) }; }
test('success traverses HTTP, canonical facade, reserve, runtime, verify and commit exactly once', async () => { const f = fixture(); const response = await f.handler({ body: command, auth }); assert.equal(response.status, 200); assert.equal((response.body as any).status, 'SUCCESS'); assert.deepEqual(f.calls, { decision: 1, plan: 1, security: 1, reserve: 1, runtime: 1, verify: 1, commit: 1, release: 0, unknown: 0 }); });
test('definitive provider failure releases and never commits', async () => { const f = fixture({ runtime: 'failure' }); const response = await f.handler({ body: command, auth }); assert.equal((response.body as any).status, 'FAILED'); assert.equal(f.calls.reserve, 1); assert.equal(f.calls.release, 1); assert.equal(f.calls.commit, 0); });
test('unknown is first-class, stays reserved and never retries', async () => { const f = fixture({ runtime: 'unknown' }); const response = await f.handler({ body: command, auth }); assert.equal(response.status, 202); assert.equal((response.body as any).status, 'UNKNOWN'); assert.equal(f.calls.runtime, 1); assert.equal(f.calls.unknown, 1); assert.equal(f.calls.commit, 0); assert.equal(f.calls.release, 0); });
test('concurrent duplicate requests share one billable execution', async () => { const f = fixture(); const [a,b] = await Promise.all([f.handler({ body: command, auth }), f.handler({ body: command, auth })]); assert.equal((a.body as any).executionId, (b.body as any).executionId); assert.equal(f.calls.runtime, 1); assert.equal(f.calls.reserve, 1); });
test('security denial stops before reservation and provider', async () => { const f = fixture({ security: false }); const response = await f.handler({ body: command, auth }); assert.equal(response.status, 500); assert.equal(f.calls.reserve, 0); assert.equal(f.calls.runtime, 0); });
test('hard budget denial stops before reservation and provider', async () => { const f = fixture({ estimated: 3, budget: 1 }); await f.handler({ body: command, auth }); assert.equal(f.calls.reserve, 0); assert.equal(f.calls.runtime, 0); });
test('artifact scope isolation fails closed', async () => { const f = fixture({ scope: false }); const response = await f.handler({ body: command, auth }); assert.equal(response.status, 403); assert.equal(f.calls.security, 0); assert.equal(f.calls.reserve, 0); });
test('validation and authentication return structured public errors', async () => { const f = fixture(); const invalid = await f.handler({ body: {}, auth }); const anonymous = await f.handler({ body: command }); assert.equal(invalid.status, 400); assert.equal((invalid.body as any).code, 'validation_error'); assert.equal(anonymous.status, 401); assert.equal(JSON.stringify([invalid, anonymous]).includes('stack'), false); });
test('cancellation is owned by canonical facade', async () => { const f = fixture(); const result = await f.service.execute(command, auth); f.service.cancel(result.executionId); assert.equal(f.service.status(result.executionId), 'SKIPPED'); });
test('public outcome never contains provider secrets', async () => { process.env.FAL_KEY = 'do-not-leak'; const f = fixture(); const response = await f.handler({ body: command, auth }); assert.equal(JSON.stringify(response).includes('do-not-leak'), false); assert.equal(JSON.stringify(response).includes('FAL_KEY'), false); });
test('billing bridge delegates balance mutation to server transactions', async () => { const store = new InMemoryTransactionStore(); store.setWallet(auth.userId, 10); const adapter = new TransactionBillingAuthorityAdapter(new TransactionService(store, { now: () => new Date('2026-01-01T00:00:00.000Z') }), store); const reservation = await adapter.reserve({ identity: { operationId: 'edit', operationVersion: '1', operationFamily: 'image', ...auth, projectId: command.projectId, requestId: 'request-1' }, authorizationId: 'authorization-1', amount: 2, idempotencyKey: 'billing-key' }); assert.deepEqual(store.getWallet(auth.userId), { balance: 10, reserved: 2, spent: 0 }); await adapter.commit(reservation.reservationId); assert.deepEqual(store.getWallet(auth.userId), { balance: 8, reserved: 0, spent: 2 }); });
