import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import test from "node:test";
import { AdaptiveHeuristicEngine, CreativeCausalLearningEngine, CounterfactualDecisionEngine, DecisionCompressionEngine,
  DecisionExplainabilityV5, DecisionEvolutionScore, DecisionReflectionEngine, DomainCreativeExpert, ExpertCouncil,
  HumanTasteModel, InMemoryDecisionReplayBuffer } from "../src/platform/creative/decision/intelligence/core/index";

const scope = Object.freeze({ userId: "u", tenantId: "t", projectId: "p" });
const deps = () => { let id = 0; return { createId: () => `id-${++id}`, now: () => 42 }; };

test("causal learning records directed support and counter evidence", () => { const engine = new CreativeCausalLearningEngine(deps()); engine.learn(scope, [{ cause: "Lighting", effect: "Contrast", supported: true }, { cause: "Contrast", effect: "Luxury", supported: true }]); const graph = engine.learn(scope, [{ cause: "Lighting", effect: "Contrast", supported: false }]); const link = graph.links.find(({ cause }) => cause === "Lighting")!; assert.equal(link.support, 1); assert.equal(link.counterEvidence, 1); assert.deepEqual(engine.path(scope, "Lighting", "Luxury").map(({ effect }) => effect), ["Contrast", "Luxury"]); });
test("counterfactuals deterministically reject an inefficient AI gain", () => { const engine = new CounterfactualDecisionEngine(); const input = [{ id: "local", mode: "LOCAL" as const, quality: 89, credits: 0 }, { id: "ai", mode: "AI" as const, quality: 92, credits: 10 }]; assert.deepEqual(engine.analyze(input[0], input), engine.analyze(input[0], input)); assert.equal(engine.analyze(input[0], input).comparisons[0].justified, false); });
test("taste model separates objective quality and preference", () => { const result = new HumanTasteModel().assess({ exposure: .98, sharpness: .98 }, { warm: 1 }, { warm: .2 }); assert.equal(result.technicalQuality, .98); assert.ok(result.creativePreference < .3); });
test("reflection is immutable and can recommend removing AI", () => { const result = new DecisionReflectionEngine(deps()).reflect(scope, { decisionId: "d", contributions: { light: 1, noise: -1, ai: 0 }, selected: { id: "ai", mode: "AI", quality: 90, credits: 10 }, alternatives: [{ id: "local", mode: "LOCAL", quality: 90, credits: 0 }] }); assert.equal(result.canRemoveAI, true); assert.equal(Object.isFrozen(result.helped), true); });
test("expert council aggregates domain-only opinions", () => { const council = new ExpertCouncil([new DomainCreativeExpert("light", "LIGHTING", "lighting"), new DomainCreativeExpert("cost", "COST", "cost")]); const result = council.evaluate({ lighting: .9, cost: .1 }); assert.equal(result.opinions.length, 2); assert.ok(result.score > .8); });
test("compression isolates all three scope dimensions", () => { const engine = new DecisionCompressionEngine(deps()); const base = { ...scope, archetype: "Portrait Enhancement", operations: ["light"], quality: .8, accepted: true }; const result = engine.compress(scope, [{ ...base, id: "1" }, { ...base, id: "2" }, { ...base, id: "foreign", userId: "other" }]); assert.equal(result[0].support, 2); assert.equal(Object.isFrozen(result), true); });
test("adaptive heuristics explain bounded deterministic changes", () => { const input = [{ name: "quality", weight: .5, evidence: 3, version: 1, explanation: "seed" }]; const engine = new AdaptiveHeuristicEngine(); assert.deepEqual(engine.adapt(input, { quality: 1 }), engine.adapt(input, { quality: 1 })); assert.match(engine.adapt(input, { quality: 1 })[0].explanation, /sqrt/); });
test("v5 explainability contains the complete ordered chain", () => { const engine = new DecisionExplainabilityV5(); const stages = engine.flatten(engine.build({ Prompt: "portrait" })).map(({ stage }) => stage); assert.equal(stages.length, 17); assert.deepEqual(stages.slice(-3), ["Learning", "Creative DNA", "Decision Model"]); });
test("evolution score includes nine bounded dimensions", () => { const result = new DecisionEvolutionScore().calculate({ learning: 1, stability: 1, creativity: 1, adaptability: 1, costEfficiency: 1, goalCompletion: 1, tasteAlignment: 1, technicalQuality: 1, confidence: 1 }); assert.equal(result.score, 1); assert.equal(Object.keys(result.dimensions).length, 9); });
test("replay buffer is immutable and scope isolated", () => { const replay = new InMemoryDecisionReplayBuffer(deps()); replay.add(scope, { prompt: "x" }, { accepted: true }); assert.equal(replay.sample(scope, 10).length, 1); assert.equal(replay.sample({ ...scope, projectId: "other" }, 10).length, 0); assert.equal(Object.isFrozen(replay.sample(scope, 10)[0]), true); });
test("v5 core has no forbidden imports", () => { const directory = `${process.cwd()}/src/platform/creative/decision/intelligence/core/`; const forbidden = /from\s+["'][^"']*(workflow|runtime|provider|billing|gateway|memory\/|application|editing|pipeline|experience|organization)/i; readdirSync(directory).filter((file) => file.endsWith(".ts")).forEach((file) => assert.doesNotMatch(readFileSync(`${directory}${file}`, "utf8"), forbidden, file)); });
