import assert from 'node:assert/strict';
import test from 'node:test';
import { CompactNeuralDecisionRankerV2, CreativeDecisionModel, DecisionCalibrationV2, DecisionConstraintLayer, DecisionDatasetBuilder, DecisionFeatureEncoderV1, DecisionModelEvaluator, DecisionModelRegistry, DecisionRankingDatasetBuilderV2, DecisionRepresentationEncoderV2, DecisionTrainerV1, HeuristicBaselineModel, ModelGovernanceV2, TabularDecisionModelV1, calculateReward, decisionRegret } from '../src/platform/creative/model';
import type { DecisionCandidateV1, DecisionContextV1, DecisionDatasetRecord, DecisionFeaturesV1 } from '../src/platform/creative/model';

const context = (projectId = 'p1', privacyMode: DecisionContextV1['privacyMode'] = 'NORMAL'): DecisionContextV1 => ({ operation: 'upscale', intent: 'repair', goal: 'quality', deviceClass: 'desktop', platform: 'web', projectType: 'portrait', privacyMode, budget: 10, latencyTarget: 5000, qualityTarget: .8, projectId, deviceId: `device-${projectId}`, timestamp: 1 });
const candidate = (id = 'local', target: DecisionCandidateV1['executionTarget'] = 'LOCAL'): DecisionCandidateV1 => ({ id, executionTarget: target, model: `model-${id}`, provider: target === 'LOCAL' ? 'local' : 'cloud', runtime: 'WEBGPU', estimatedQuality: id === 'good' ? .95 : .7, estimatedLatency: 1000, estimatedCost: target === 'LOCAL' ? 0 : 2, energy: .2, memory: 1024, reliability: .9 });
const features = (id = 'local'): DecisionFeaturesV1 => ({ context: context(), candidate: candidate(id), history: { modelSuccessRate: .8, providerSuccessRate: .8, deviceSpecificSuccessRate: .7, cloudAvoidance: .7, acceptanceRate: .8, undoRate: .1 } });
const records = (): readonly DecisionDatasetRecord[] => Array.from({ length: 15 }, (_, index) => { const input = features(index % 2 ? 'good' : `candidate-${index}`); const projectId = `project-${Math.floor(index / 3)}`; return { id: `r${index}`, features: { ...input, context: context(projectId) }, context: context(projectId), candidate: input.candidate, decision: input.candidate.id, actualOutcome: { quality: index % 2 ? .95 : .6, success: index % 3 !== 0, accepted: index % 2 === 1, latency: 800 + index * 10, cost: index % 2, escalated: false }, reward: index % 2 ? 5 : 2, timestamp: index, modelVersion: 'v0', projectId, deviceId: `device-${projectId}` }; });

test('dataset builder creates immutable ML records', () => { const data = new DecisionDatasetBuilder({}, () => 10).fromOutcomes([{ operation: 'upscale', selectedTarget: 'LOCAL', actualOutcome: 'SUCCESS', actualCost: 0, actualQuality: .9, actualLatency: 12, userReaction: 'ACCEPTED' }]); assert.equal(data.length, 1); assert.equal(data[0].features.context.operation, 'upscale'); assert.ok(Object.isFrozen(data)); assert.ok(Number.isFinite(data[0].reward)); });
test('encoder is deterministic, normalized and versioned', () => { const encoder = new DecisionFeatureEncoderV1(), a = encoder.encode(features()), b = encoder.encode(features()); assert.deepEqual(a, b); assert.equal(a.length, encoder.featureNames.length); assert.ok(a.every(value => value >= 0 && value <= 1)); assert.equal(encoder.schemaVersion, 'decision-features-v1'); });
test('constraint gate preserves hard security boundaries', () => { const gate = new DecisionConstraintLayer(); assert.deepEqual(gate.evaluate(context('p', 'LOCAL_ONLY'), candidate('cloud', 'CLOUD')).exclusions, ['PRIVACY_LOCAL_ONLY']); assert.ok(!gate.evaluate(context(), { ...candidate(), quarantined: true }).allowed); assert.ok(!gate.evaluate(context(), { ...candidate(), runtimeSupported: false }).allowed); assert.ok(!gate.evaluate(context(), { ...candidate('expensive'), estimatedCost: 11 }).allowed); });
test('tabular model trains six heads and ranks deterministically', () => { const model = TabularDecisionModelV1.train(records(), { modelVersion: 'v1' }); const prediction = model.predict(features()); assert.ok(prediction.quality >= 0 && prediction.quality <= 1); assert.ok(prediction.acceptanceProbability >= 0); assert.equal(model.version(), 'v1'); assert.equal(model.rank(context(), [candidate('b'), candidate('a')]).length, 2); assert.deepEqual(model.rank(context(), [candidate('b'), candidate('a')]), model.rank(context(), [candidate('b'), candidate('a')])); });
test('trainer split prevents project leakage', () => { const split = new DecisionTrainerV1().split(records()); const train = new Set(split.train.map(item => item.projectId)), validation = new Set(split.validation.map(item => item.projectId)), heldOut = new Set(split.test.map(item => item.projectId)); assert.ok([...train].every(id => !validation.has(id) && !heldOut.has(id))); assert.ok([...validation].every(id => !heldOut.has(id))); });
test('registry enforces canary lifecycle and rollback', () => { const registry = new DecisionModelRegistry(), model = new HeuristicBaselineModel(), metrics = new DecisionModelEvaluator().evaluate(model, records()); registry.register(model, { featureSchemaVersion: 'v1', datasetVersion: 'v1', trainingConfigVersion: 'v1', metrics, parentModel: null, createdAt: 1 }); registry.transition(model.version(), 'CANARY'); assert.equal(registry.promote(model.version()).status, 'ACTIVE'); });
test('facade shadow never controls execution', () => { const facade = new CreativeDecisionModel(); const result = facade.shadow(features()); assert.equal(result.mode, 'MODEL_SHADOW'); assert.equal(result.executedBy, 'heuristic-baseline-v0'); assert.equal(facade.benchmark().length, 30); });
test('reward and regret are policy aware', () => { const reward = calculateReward({ quality: .9, success: true, accepted: true, latency: 100, cost: 0, escalated: false }, context()); assert.ok(reward > 0); assert.equal(decisionRegret(2, 5), 3); assert.equal(decisionRegret(5, 2), 0); });

test('v2 representation fuses independent blocks and explicit interactions', () => { const representation = new DecisionRepresentationEncoderV2().encode({ ...features('good'), preferences: { styleAlignment: .9 }, device: { isNew: false, imageMegapixels: 12 } }); assert.equal(representation.schemaVersion, 'decision-representation-v2'); assert.deepEqual(representation.blocks.map(block => block.name), ['context', 'candidate', 'history', 'device', 'goal', 'constraint', 'sequence', 'preference', 'interaction']); assert.ok(representation.values.every(value => value >= 0 && value <= 1)); assert.ok(Object.isFrozen(representation.blocks[0].values)); });
test('v2 sequence context is bounded, relevant and avoids raw user data', () => { const recentOutcomes = Array.from({ length: 20 }, (_, timestamp) => ({ operation: timestamp % 2 ? 'upscale' : 'other', deviceClass: 'desktop', model: 'm', provider: 'p', target: 'LOCAL' as const, quality: .8, accepted: true, satisfaction: .9, cost: 0, latency: 10, timestamp })), representation = new DecisionRepresentationEncoderV2().encode({ ...features(), recentOutcomes }); const sequence = representation.blocks.find(block => block.name === 'sequence'); assert.equal(sequence?.values.length, 6); assert.equal(sequence?.values[0], 1); assert.ok(!JSON.stringify(representation).includes('userId')); });
test('v2 neural model exposes multitask heads and uncertainty decomposition', () => { const prediction = new CompactNeuralDecisionRankerV2().predict({ ...features('good'), recentOutcomes: [] }); for (const key of ['quality', 'successProbability', 'acceptanceProbability', 'cost', 'latency', 'escalationProbability', 'satisfaction', 'regret']) assert.ok(Number.isFinite(prediction[key as keyof typeof prediction] as number)); assert.ok(prediction.uncertaintyV2.epistemic >= 0); assert.ok(prediction.calibrationHeads.utility > 0); });
test('pairwise and listwise inference are deterministic', () => { const model = new CompactNeuralDecisionRankerV2(), left = { ...features('good'), recentOutcomes: [] }, right = { ...features('cheap'), recentOutcomes: [] }; assert.deepEqual(model.rankPairwise(left, right), model.rankPairwise(left, right)); const ranking = model.predictList([left, right]); assert.equal(ranking.length, 2); assert.deepEqual(ranking, model.predictList([left, right])); });
test('pairwise dataset preserves human preference separately', () => { const rows = records().slice(0, 2).map(row => ({ ...row, timestamp: 1, projectId: 'same', context: context('same') })), builder = new DecisionRankingDatasetBuilderV2(), preference = builder.humanPreference(rows[0], rows[1], rows[1].candidate.id); assert.equal(builder.pairwise(rows).length, 1); assert.equal(builder.listwise(rows).length, 1); assert.equal(preference.source, 'HUMAN_PREFERENCE'); assert.equal(preference.preferred, 'RIGHT'); });
test('neural training learns pairwise and listwise coverage', () => { const left = { ...features('good'), recentOutcomes: [] }, right = { ...features('cheap'), recentOutcomes: [] }, trained = CompactNeuralDecisionRankerV2.train([{ context: context(), left, right, preferred: 'LEFT', source: 'HUMAN_PREFERENCE', weight: 2 }], [{ context: context(), candidates: [left, right], relevance: [2, 1] }], { epochs: 30 }); const result = trained.rankPairwise(left, right); assert.ok(result.leftProbability > .5); assert.ok(trained.predict(left).uncertaintyV2.epistemic < 1); });
test('counterfactual reports decomposed deltas without executing', () => { const result = new CompactNeuralDecisionRankerV2().counterfactual({ ...features('good') }, { ...features('alternative') }); assert.ok(Number.isFinite(result.utilityDelta)); assert.ok(Number.isFinite(result.acceptanceDelta)); assert.match(result.recommendation, /Prefer|Keep|Equivalent/); });
test('critical uncertainty and security exclusions cannot win list ranking', () => { const model = new CompactNeuralDecisionRankerV2(), unsafe = { ...features('cloud'), context: context('p', 'LOCAL_ONLY'), candidate: { ...candidate('cloud', 'CLOUD'), quarantined: true } }, safe = { ...features('local'), context: context('p', 'LOCAL_ONLY'), candidate: candidate('local') }; const ranking = model.predictList([unsafe, safe]); const unsafeRow = ranking.find(row => row.candidate.id === 'cloud'); assert.ok(unsafeRow?.excluded); assert.ok(unsafeRow?.exclusions.includes('PRIVACY_LOCAL_ONLY')); assert.ok(unsafeRow?.exclusions.includes('MODEL_QUARANTINED')); });
test('calibration fits independent heads and produces reliability curves', () => { const model = new CompactNeuralDecisionRankerV2(), predictions = [model.predict({ ...features('a') }), model.predict({ ...features('b') })], calibration = new DecisionCalibrationV2().fit(predictions, [{ quality: .8, acceptance: 1, cost: 0, latency: 1000, utility: 4 }, { quality: .4, acceptance: 0, cost: 2, latency: 2000, utility: 2 }]); assert.equal(calibration.reliabilityCurve([.1, .9], [0, 1]).length, 10); assert.ok(calibration.heads().acceptance > 0); });
test('distillation records teacher lineage and fidelity', () => { const model = new CompactNeuralDecisionRankerV2(), distilled = model.distill([{ ...features('a') }, { ...features('b') }, { ...features('c') }, { ...features('d') }]); assert.equal(distilled.teacherVersion, model.version()); assert.equal(distilled.sampleCount, 4); assert.ok(distilled.fidelity >= 0 && distilled.fidelity <= 1); });
test('governance requires every production promotion invariant', () => { const governance = new ModelGovernanceV2(() => 1), metric = { decisionRegret: .1, acceptance: .8, satisfaction: .8, cloudAvoidance: .8, cost: 1, latency: 10, quality: .8, stability: 1, oodSafety: 1, calibration: .9, rankingQuality: .9, unnecessaryAI: 0, securityViolations: 0 }; governance.register({ datasetVersion: 'd2', featureSchemaVersion: 'f2', encoderVersion: 'e2', trainingConfigVersion: 't2', modelVersion: 'm2', calibrationVersion: 'c2', benchmarkVersion: 'b2', parentModel: 'v1', createdAt: 1, anonymized: true }); governance.transition('m2', 'VALIDATING', 'trained'); governance.transition('m2', 'SHADOW', 'validated'); governance.transition('m2', 'CANARY', 'shadow won'); assert.equal(governance.promote('m2', { candidate: metric, baseline: { ...metric, rankingQuality: .8 }, privacyInvariant: true, securityInvariant: true }).status, 'ACTIVE'); });
test('public facade exposes v2 representation, ranking and three-version shadow', () => { const facade = new CreativeDecisionModel(), left = { ...features('a') }, right = { ...features('b') }; assert.equal(facade.encode(left).schemaVersion, 'decision-representation-v2'); assert.ok(facade.rankPairwise(left, right)); assert.equal(facade.predictList([left, right]).length, 2); assert.ok('v2Prediction' in facade.shadow(left)); assert.equal(facade.compareVersions([left]).length, 1); });

// 250 named deterministic cases protect schema stability, bounded outputs and input immutability.
for (let index = 0; index < 250; index++) test(`decision model invariant ${String(index + 1).padStart(3, '0')}`, () => { const input = features(`case-${index}`), before = JSON.stringify(input), encoded = new DecisionFeatureEncoderV1().encode(input), prediction = new HeuristicBaselineModel().predict(input); assert.equal(encoded.length, 26); assert.ok(encoded.every(value => Number.isFinite(value))); assert.ok(prediction.quality >= 0 && prediction.quality <= 1); assert.equal(JSON.stringify(input), before); });

for (let index = 0; index < 60; index++) test(`v2 representation and inference invariant ${String(index + 1).padStart(3, '0')}`, () => { const input = { ...features(`v2-${index}`), context: context(`scope-${index}`, index % 5 === 0 ? 'LOCAL_ONLY' : 'NORMAL'), preferences: { qualityBias: (index % 10) / 10, styleAlignment: .7 }, device: { isNew: index % 3 === 0, imageMegapixels: index + 1 }, recentOutcomes: [] }, before = JSON.stringify(input), model = new CompactNeuralDecisionRankerV2(`v2-test-${index}`), representation = model.encode(input), prediction = model.predict(input); assert.ok(representation.blocks.some(block => block.name === 'interaction')); assert.ok(prediction.satisfaction >= 0 && prediction.satisfaction <= 1); assert.ok(prediction.regret >= 0 && prediction.regret <= 1); assert.equal(JSON.stringify(input), before); assert.ok(Object.isFrozen(prediction.uncertaintyV2)); });
