import assert from 'node:assert/strict';
import test from 'node:test';
import { CreativeDecisionModel, DecisionRepresentationEncoderV2, NeuralDecisionRanker } from '../src/platform/creative/model';
import type { DecisionCandidateV1, DecisionContextV1, DecisionFeaturesV1 } from '../src/platform/creative/model';

const context: DecisionContextV1 = { operation: 'upscale', intent: 'restore', goal: 'quality', style: 'editorial', deviceClass: 'desktop', deviceId: 'new-device', platform: 'web', projectType: 'portrait', privacyMode: 'LOCAL_ONLY', budget: 5, latencyTarget: 5_000, qualityTarget: .9, imageWidth: 2048, imageHeight: 2048 };
const candidate = (id: string, quality: number, target: DecisionCandidateV1['executionTarget'] = 'LOCAL'): DecisionCandidateV1 => ({ id, executionTarget: target, model: `model-${id}`, provider: target === 'LOCAL' ? 'local' : 'cloud', runtime: 'WEBGPU', estimatedQuality: quality, estimatedLatency: quality * 2_000, estimatedCost: target === 'LOCAL' ? 0 : 3, energy: .2, memory: 2048, reliability: quality });
const features = (id: string, quality: number, target: DecisionCandidateV1['executionTarget'] = 'LOCAL'): DecisionFeaturesV1 => ({ context, candidate: candidate(id, quality, target), history: { modelSuccessRate: .7, providerSuccessRate: .8, deviceSpecificSuccessRate: .5, cloudAvoidance: .8, acceptanceRate: .75, undoRate: .1, sampleCount: 2, relevantOutcomes: [{ operation: 'upscale', quality: .8, accepted: true, latency: 900, cost: 0, timestamp: 2 }] } });

test('v2 representation exposes independent blocks, interactions and version', () => { const result = new DecisionRepresentationEncoderV2().encode(features('a', .8)); assert.equal(result.version, 'decision-representation-v2.0'); assert.deepEqual(result.blocks.map(block => block.name), ['context', 'goal', 'constraint', 'candidate', 'device', 'history']); assert.equal(result.interactions.length, 6); assert.ok(Object.isFrozen(result.vector)); });
test('pairwise preference learning and listwise ranking are deterministic', () => { const good = features('good', .95), poor = features('poor', .3), model = NeuralDecisionRanker.trainPairwise(Array.from({ length: 20 }, () => ({ preferred: good, rejected: poor }))); assert.equal(model.rankPairwise(good, poor).winner, 'good'); assert.deepEqual(model.predictList([poor, good]), model.predictList([poor, good])); assert.equal(model.predictList([poor, good])[0].features.candidate.id, 'good'); });
test('v2 uncertainty separates coverage dimensions and recommends safe fallback', () => { const prediction = new NeuralDecisionRanker().predict(features('cold', .7)); assert.ok(prediction.aleatoricUncertainty !== undefined); assert.ok(prediction.epistemicUncertainty !== undefined); assert.ok(prediction.dataCoverage !== undefined); assert.ok(prediction.confidenceByHead?.quality !== undefined); });
test('security constraints remain outside neural ranking', () => { const ranking = new NeuralDecisionRanker().rank(context, [candidate('cloud', .99, 'CLOUD'), candidate('local', .5)]); assert.equal(ranking.find(row => row.candidate.id === 'cloud')?.excluded, true); assert.deepEqual(ranking.find(row => row.candidate.id === 'cloud')?.exclusions, ['PRIVACY_LOCAL_ONLY']); });
test('public v2 facade supports encoding, pairwise, listwise and counterfactual APIs', () => { const facade = new CreativeDecisionModel(new NeuralDecisionRanker()), low = features('low', .4), high = features('high', .9); assert.ok(facade.encode(high).vector.length > 26); assert.equal(facade.rankPairwise(high, low).winner, 'high'); assert.equal(facade.predictList([low, high]).length, 2); assert.equal(facade.counterfactual(low, high).preferred, 'high'); });

for (let index = 0; index < 45; index++) test(`v2 deterministic immutable inference ${String(index + 1).padStart(2, '0')}`, () => { const input = features(`candidate-${index}`, .5 + index / 100), before = JSON.stringify(input), model = new NeuralDecisionRanker(), a = model.predict(input), b = model.predict(input); assert.deepEqual(a, b); assert.equal(JSON.stringify(input), before); assert.ok(a.predictionConfidence >= 0 && a.predictionConfidence <= 1); assert.ok(a.satisfaction !== undefined && a.satisfaction >= 0 && a.satisfaction <= 1); });
