import assert from 'node:assert/strict';
import test from 'node:test';
import { ArtifactLifecycleManager, ConcurrencyGate, CostProtection, CreativeProductionRuntime, DependencyCircuitBreaker, MemoryProductionStateStore, ProductionLoadContract, ProductionReadinessScore, RecoveryPolicyEngine, SlidingWindowRateLimiter, deepFreeze, productionError, sanitize, withTimeout, type ProductionDependencies, type ProductionExecutor, type ProductionRequest } from '../src/platform/creative/production/index.ts';

const scope = { tenantId: 'tenant', projectId: 'project', userId: 'user', deviceId: 'device' };
const bytes = new Uint8Array([1, 2, 3]);
const image = { id: 'artifact', mimeType: 'image/png' as const, bytes, width: 10, height: 10, hash: 'hash', createdAt: 1, metadata: {} };
const result = (local = true, credits = 0) => ({ status: 'COMPLETED' as const, finalArtifact: image, metadata: {}, executionSnapshot: { runId: 'run', intent: 'SMART_UPSCALE' as const, plan: ['upscale' as const], processingPath: [local ? 'LOCAL' as const : 'FAL' as const], accounting: [] }, costSummary: { cloudCredits: credits, cloudCost: credits, localOperations: local ? 1 : 0, deviceTimeMs: local ? 10 : 0, energyEstimateWh: 0, creditsSaved: local ? 1 : 0 }, explanation: 'structured', telemetry: [] });
const request = (overrides: Partial<ProductionRequest> = {}): ProductionRequest => ({ idempotencyKey: 'key', requestId: 'request', sessionId: 'session', scope, operation: 'upscale', prompt: 'upscale', artifact: image, privacyMode: 'NORMAL', userConsent: true, billable: false, estimatedCredits: 0, provider: 'local', retrySemantics: 'SAFE_TO_RETRY', ...overrides });
const budget = { remainingCredits: 100, operationCostCeiling: 100, dailyLimitRemaining: 100, projectLimitRemaining: 100, userLimitRemaining: 100, exceedAction: 'BLOCK' as const };
const dependencies = (executor: ProductionExecutor, overrides: Partial<ProductionDependencies> = {}): ProductionDependencies => { let tick = 0; return { executor, budget, now: () => ++tick, id: () => `id-${++tick}`, hash: async () => 'hash', ...overrides }; };
const success: ProductionExecutor = { execute: async (_request, context) => ({ result: result(), local: true, qualityAccepted: true, providerExecutionId: undefined, attempt: context.attemptId }) as never };

test('same scope and idempotency key returns the same completed execution without a second AI call', async () => { let calls = 0; const runtime = new CreativeProductionRuntime(dependencies({ execute: async () => { calls++; return { result: result(false, 2), local: false, qualityAccepted: true, providerExecutionId: 'provider-1' }; } })); const first = await runtime.start(request({ billable: true, provider: 'fal', estimatedCredits: 2, retrySemantics: 'REQUIRES_DEDUPLICATION' })); const second = await runtime.start(request({ billable: true, provider: 'fal', estimatedCredits: 2, retrySemantics: 'REQUIRES_DEDUPLICATION' })); assert.equal(first.executionId, second.executionId); assert.equal(calls, 1); });
test('concurrent duplicates share one in-flight billable execution', async () => { let calls = 0; const runtime = new CreativeProductionRuntime(dependencies({ execute: async () => { calls++; await Promise.resolve(); return { result: result(false, 1), local: false, qualityAccepted: true, providerExecutionId: 'p' }; } })); const billable = request({ billable: true, provider: 'fal', estimatedCredits: 1, retrySemantics: 'REQUIRES_DEDUPLICATION' }); const [a, b] = await Promise.all([runtime.start(billable), runtime.start(billable)]); assert.equal(a.executionId, b.executionId); assert.equal(calls, 1); });
test('different idempotency keys create different executions', async () => { const runtime = new CreativeProductionRuntime(dependencies(success)); const a = await runtime.start(request()); const b = await runtime.start(request({ idempotencyKey: 'key-2' })); assert.notEqual(a.executionId, b.executionId); });
test('lost billable provider response becomes UNKNOWN and is never automatically retried', async () => { let calls = 0; const runtime = new CreativeProductionRuntime(dependencies({ execute: async () => { calls++; throw productionError('NETWORK_ERROR', 'LOST_RESPONSE', true, 'response lost'); } })); const state = await runtime.start(request({ billable: true, provider: 'fal', estimatedCredits: 1, retrySemantics: 'REQUIRES_DEDUPLICATION' })); assert.equal(state.status, 'UNKNOWN'); assert.equal(state.recovery[0].action, 'MARK_UNKNOWN'); await assert.rejects(runtime.recover(state.executionId, 'RETRY')); assert.equal(calls, 1); });
test('hard budget guard runs before the executor', async () => { let calls = 0; const runtime = new CreativeProductionRuntime(dependencies({ execute: async () => { calls++; return { result: result(), local: true, qualityAccepted: true }; } }, { budget: { ...budget, remainingCredits: 1 } })); await assert.rejects(runtime.start(request({ estimatedCredits: 2, billable: true, provider: 'fal', retrySemantics: 'REQUIRES_DEDUPLICATION' })), error => (error as { category: string }).category === 'BUDGET_ERROR'); assert.equal(calls, 0); });
test('LOCAL_ONLY blocks outbound image data and emits a security event', async () => { let calls = 0; const runtime = new CreativeProductionRuntime(dependencies({ execute: async () => { calls++; return { result: result(), local: true, qualityAccepted: true }; } })); const state = await runtime.start(request({ privacyMode: 'LOCAL_ONLY', provider: 'fal' })); assert.equal(state.status, 'FAILED'); assert.equal(calls, 0); assert.equal(runtime.coordinator.securityEvents(state.executionId)[0].type, 'OUTBOUND_DATA_BLOCKED'); });
test('logical replay is offline while provider replay requires policy and rejects paid replay', async () => { const runtime = new CreativeProductionRuntime(dependencies(success)); const state = await runtime.start(request()); assert.deepEqual(await runtime.replay(state.executionId), state); await assert.rejects(runtime.replay(state.executionId, 'PROVIDER')); assert.deepEqual(await runtime.replay(state.executionId, 'PROVIDER', true), state); });
test('debugger and trace redact secret-like metadata', async () => { const runtime = new CreativeProductionRuntime(dependencies(success)); const state = await runtime.start(request({ metadata: { apiKey: 'secret', authorization: 'bearer' } })); const debug = await runtime.inspect(state.executionId); assert.equal(/secret|bearer/.test(JSON.stringify(debug)), false); assert.equal(Object.isFrozen(debug), true); });
test('production facade exposes lifecycle, health, metrics, snapshot, recovery, and readiness', async () => { const runtime = new CreativeProductionRuntime(dependencies(success)); const state = await runtime.start(request()); assert.equal((await runtime.status(state.executionId)).status, 'COMPLETED'); assert.equal((await runtime.snapshot(state.executionId)).executionId, state.executionId); assert.equal(runtime.health().status, 'HEALTHY'); assert.equal(runtime.metrics().qualityAcceptanceRate, 1); assert.ok(['BETA', 'PRODUCTION_READY'].includes(runtime.coordinator.readiness().level)); assert.ok(runtime.trace(state.executionId).length >= 5); });
test('structured timeout returns TIMEOUT instead of an arbitrary exception', async () => { await assert.rejects(withTimeout(1, () => new Promise(() => {})), error => (error as { category: string }).category === 'TIMEOUT'); });
test('cost preflight accounts for worst-case retries and fallback', () => { const value = new CostProtection().preflight(2, 2, 3, { ...budget, operationCostCeiling: 8 }); assert.equal(value.worstCaseCredits, 9); assert.equal(value.decision, 'BLOCK'); });
test('artifact lifecycle rejects cross-scope and corrupted/non-ready artifacts', () => { const manager = new ArtifactLifecycleManager(); let record = manager.create(image, scope, 'user', 0, 10); record = manager.transition(record, 'VALIDATING'); record = manager.transition(record, 'READY'); assert.equal(manager.assertUsable(record, scope, 1), true); assert.throws(() => manager.assertUsable(record, { ...scope, projectId: 'other' }, 1)); assert.throws(() => manager.assertUsable(record, scope, 11)); });
test('coordinator quarantines a corrupted artifact before the executor sees it', async () => { let calls = 0; const runtime = new CreativeProductionRuntime(dependencies({ execute: async () => { calls++; return { result: result(), local: true, qualityAccepted: true }; } }, { hash: async () => 'different' })); await assert.rejects(runtime.start(request()), error => (error as { category: string }).category === 'ARTIFACT_ERROR'); assert.equal(calls, 0); });
test('recovery decisions are capability and semantic based, not provider named', () => { const policy = new RecoveryPolicyEngine(); assert.equal(policy.decide({ category: 'NETWORK_ERROR', semantics: 'SAFE_TO_RETRY', fallbackAvailable: false, checkpoint: false, providerResultUnknown: false }), 'RETRY'); assert.equal(policy.decide({ category: 'PROVIDER_ERROR', semantics: 'REQUIRES_DEDUPLICATION', fallbackAvailable: true, checkpoint: false, providerResultUnknown: false }), 'FALLBACK'); assert.equal(policy.decide({ category: 'PROVIDER_ERROR', semantics: 'UNSAFE_TO_RETRY', fallbackAvailable: false, checkpoint: false, providerResultUnknown: false }), 'ABORT'); });
test('circuit breaker transitions CLOSED OPEN HALF_OPEN CLOSED', () => { let now = 0; const breaker = new DependencyCircuitBreaker(2, 10, () => now); breaker.failure(); breaker.failure(); assert.equal(breaker.snapshot().state, 'OPEN'); assert.equal(breaker.allow(), false); now = 11; assert.equal(breaker.allow(), true); assert.equal(breaker.snapshot().state, 'HALF_OPEN'); breaker.success(); assert.equal(breaker.snapshot().state, 'CLOSED'); });
test('concurrency gate rejects excess work and releases capacity', async () => { const gate = new ConcurrencyGate(); let release!: () => void; const first = gate.run('local', 1, () => new Promise<void>(resolve => { release = resolve; })); await Promise.resolve(); await assert.rejects(gate.run('local', 1, async () => undefined)); release(); await first; assert.equal(gate.active('local'), 0); });
test('readiness critical security dimensions are blocking', () => { const dimensions = { reliability: 1, security: .2, observability: 1, recovery: 1, costSafety: 1, privacy: 1, determinism: 1, artifactIntegrity: 1, providerStability: 1, localRuntimeStability: 1 }; assert.equal(new ProductionReadinessScore().calculate(dimensions).level, 'BLOCKED'); });
test('load contract defines deterministic 10, 50, and 100 concurrent scenarios without external AI', () => { const load = new ProductionLoadContract(); assert.deepEqual(load.scenarios().map(x => x.concurrent), [10, 50, 100]); assert.deepEqual(load.plan(100, 8), { concurrent: 100, maximumActive: 8, waves: 13, externalAI: false }); });

const categories = ['idempotency', 'duplicates', 'unknown-result', 'recovery', 'rate-limit', 'concurrency', 'timeout', 'circuit-breaker', 'budget', 'artifact-lifecycle', 'privacy-audit', 'security-events', 'telemetry', 'tracing', 'logical-replay', 'provider-replay', 'provider-timeout', 'provider-500', 'network-loss', 'artifact-corruption', 'local-oom', 'thermal-shutdown', 'missing-model', 'lost-callback', 'duplicate-callback', 'deep-immutability', 'determinism', 'scope-isolation'] as const;
// 28 production-hardening categories × 8 deterministic variants = 224 focused invariant tests.
for (const category of categories) for (let variant = 1; variant <= 8; variant++) test(`${category} production invariant ${variant}`, async () => {
  if (category === 'rate-limit') { let now = 0; const limiter = new SlidingWindowRateLimiter({ requestsPerMinute: variant, concurrentExecutions: 1, aiCallsPerMinute: 1, localInferencePerMinute: 1, downloadBytesPerMinute: 10 }, () => now); for (let i = 0; i < variant; i++) assert.equal(limiter.acquire('key', 'request'), true); assert.equal(limiter.acquire('key', 'request'), false); now = 60_001; assert.equal(limiter.acquire('key', 'request'), true); }
  else if (category === 'circuit-breaker') { let now = 0; const breaker = new DependencyCircuitBreaker(variant, 5, () => now); for (let i = 0; i < variant; i++) breaker.failure(); assert.equal(breaker.snapshot().state, 'OPEN'); now = 6; assert.equal(breaker.allow(), true); }
  else if (category === 'budget') { const value = new CostProtection().preflight(variant, 0, 0, { ...budget, remainingCredits: variant - 1 }); assert.equal(value.decision, 'BLOCK'); }
  else if (category === 'deep-immutability') { const value = deepFreeze({ nested: [{ variant }] }); assert.equal(Object.isFrozen(value), true); assert.equal(Object.isFrozen(value.nested[0]), true); }
  else if (category === 'determinism') { const policy = new RecoveryPolicyEngine(); const input = { category: 'NETWORK_ERROR' as const, semantics: 'SAFE_TO_RETRY' as const, fallbackAvailable: false, checkpoint: false, providerResultUnknown: false }; assert.equal(policy.decide(input), policy.decide(input)); }
  else if (category === 'scope-isolation') { const store = new MemoryProductionStateStore(); assert.equal(await store.getByIdempotency({ ...scope, userId: `other-${variant}` }, 'key'), undefined); }
  else if (category === 'security-events') { const cleaned = sanitize({ token: `secret-${variant}`, safe: variant }); assert.deepEqual(cleaned, { safe: variant }); }
  else if (category === 'artifact-lifecycle' || category === 'artifact-corruption') { const manager = new ArtifactLifecycleManager(); const record = manager.create({ ...image, id: `a-${variant}` }, scope, 'owner', 0, variant); assert.equal(record.state, 'CREATED'); assert.throws(() => manager.assertUsable(record, scope, 0)); }
  else if (category === 'recovery' || category === 'unknown-result' || category === 'lost-callback') { const action = new RecoveryPolicyEngine().decide({ category: 'NETWORK_ERROR', semantics: 'REQUIRES_DEDUPLICATION', fallbackAvailable: false, checkpoint: false, providerResultUnknown: true }); assert.equal(action, 'MARK_UNKNOWN'); }
  else if (category === 'timeout' || category === 'provider-timeout') { const error = productionError('TIMEOUT', `TIMEOUT_${variant}`, true, 'timed out'); assert.equal(error.category, 'TIMEOUT'); assert.equal(Object.isFrozen(error), true); }
  else { const frozen = deepFreeze({ category, variant, correlation: { requestId: `r-${variant}`, executionId: `e-${variant}` } }); assert.equal(Object.isFrozen(frozen), true); assert.equal(frozen.variant, variant); }
});

test('production implementation stays inside integration scope and has no forbidden infrastructure imports', async () => { const { readdir, readFile } = await import('node:fs/promises'); const files = await readdir('src/platform/creative/production'); const forbidden = ['/billing/', '/application/', '/ui/', 'node:fs', 'node:http', 'process.env', 'apiKey']; for (const file of files.filter(name => name.endsWith('.ts'))) { const source = await readFile(`src/platform/creative/production/${file}`, 'utf8'); for (const marker of forbidden) assert.equal(source.includes(marker), false, `${file} contains ${marker}`); } });
