import assert from 'node:assert/strict';
import test from 'node:test';
import { BundleOptimizer, CreativeModelDistribution, DEFAULT_DISTRIBUTION_POLICY, DETERMINISTIC_DEVICE_PROFILES, PROFILE_CAPABILITIES, classifyDevice, type BundleProfile, type DeviceCapabilityProfile, type DistributionPolicy, type ModelManifest } from '../src/platform/creative/model-distribution/index.ts';

const device = (values: Partial<DeviceCapabilityProfile> = {}): DeviceCapabilityProfile => ({ platform: 'BROWSER', deviceClass: 'BROWSER', cpuCores: 8, ramMb: 16_384, gpu: 'measured', vramMb: 4096, npu: 'UNKNOWN', architecture: 'arm64', browser: 'test', webgpu: true, wasm: true, webnn: false, cuda: false, directml: false, metal: false, vulkan: false, storageFreeBytes: 5e9, batteryPercent: 90, powerState: 'BATTERY', thermalState: 'NORMAL', network: 'ONLINE', tier: 'HIGH', ramPressure: 'NORMAL', backgroundRestricted: false, ...values });
const model = (id: string, capability = 'segmentation', values: Partial<ModelManifest> = {}): ModelManifest => ({ modelId: id, version: '1.0.0', family: 'test', capabilities: [capability], modelFormat: 'ONNX', runtime: 'WEBGPU', sizeBytes: 10_000_000, requiredRam: 512, requiredVram: 256, supportedPlatforms: ['BROWSER'], supportedAccelerators: ['WEBGPU'], estimatedLatency: 100, qualityScore: .9, energyScore: .9, privacyLevel: 'PRIVATE', license: 'Apache-2.0', publisher: 'trusted', downloadUri: `https://models.example/${id}`, sha256: 'a'.repeat(64), signature: 'signed', status: 'AVAILABLE', stabilityScore: .99, ...values });
const policy = (values: Partial<DistributionPolicy> = {}): DistributionPolicy => ({ ...DEFAULT_DISTRIBUTION_POLICY, ...values, weights: { ...DEFAULT_DISTRIBUTION_POLICY.weights, ...(values.weights ?? {}) } });
const context = (values: Record<string, unknown> = {}) => ({ device: device(), telemetry: [], usage: [], policy: policy(), ...values } as Parameters<BundleOptimizer['optimize']>[2]);

const categories = ['bundle-minimal','bundle-balanced','bundle-creator','bundle-privacy','bundle-offline','device-browser-high','device-wasm','device-android-low','device-android-mid','device-android-high','device-android-flagship','device-desktop-cpu','device-desktop-integrated','device-desktop-mid','device-desktop-high','telemetry-quality','telemetry-speed','storage-budget','compatibility-platform','compatibility-ram','compatibility-vram','determinism','immutability','explainable-score'] as const;
for (const category of categories) for (let variant = 1; variant <= 9; variant += 1) test(`${category} simulated case ${variant}`, () => {
  const optimizer = new BundleOptimizer(); const catalog = [model(`segment-${variant}`), model(`ocr-${variant}`, 'ocr')];
  if (category.startsWith('bundle-')) { const profile = category.slice(7).toUpperCase().replace('PRIVACY', 'PRIVACY_FIRST') as BundleProfile; const result = optimizer.optimize(profile, catalog, context({ offline: profile === 'OFFLINE' })); assert.equal(result.bundle.profile, profile); assert.ok(PROFILE_CAPABILITIES[profile].length >= 3); }
  if (category === 'device-browser-high') assert.equal(classifyDevice(device(DETERMINISTIC_DEVICE_PROFILES.browserWebGpuHigh)), 'BROWSER_WEBGPU_HIGH');
  if (category === 'device-wasm') assert.equal(classifyDevice(device(DETERMINISTIC_DEVICE_PROFILES.browserWasmOnly)), 'BROWSER_WASM_ONLY');
  if (category === 'device-android-low') assert.equal(classifyDevice(device({ platform: 'ANDROID', deviceClass: 'MOBILE', ramMb: 2048, vramMb: 0 })), 'ANDROID_LOW');
  if (category === 'device-android-mid') assert.equal(classifyDevice(device(DETERMINISTIC_DEVICE_PROFILES.androidMid)), 'ANDROID_MID');
  if (category === 'device-android-high') assert.equal(classifyDevice(device({ platform: 'ANDROID', deviceClass: 'MOBILE', ramMb: 8192, vramMb: 2048 })), 'ANDROID_HIGH');
  if (category === 'device-android-flagship') assert.equal(classifyDevice(device(DETERMINISTIC_DEVICE_PROFILES.pixelFlagship)), 'ANDROID_FLAGSHIP');
  if (category === 'device-desktop-cpu') assert.equal(classifyDevice(device({ platform: 'LINUX', deviceClass: 'DESKTOP', vramMb: 0, metal: false })), 'DESKTOP_CPU');
  if (category === 'device-desktop-integrated') assert.equal(classifyDevice(device({ platform: 'MACOS', deviceClass: 'DESKTOP', vramMb: 1024, metal: true })), 'DESKTOP_INTEGRATED_GPU');
  if (category === 'device-desktop-mid') assert.equal(classifyDevice(device({ platform: 'WINDOWS', deviceClass: 'DESKTOP', vramMb: 6144 })), 'DESKTOP_MID_GPU');
  if (category === 'device-desktop-high') assert.equal(classifyDevice(device(DETERMINISTIC_DEVICE_PROFILES.rtxDesktop)), 'DESKTOP_HIGH_GPU');
  if (category === 'telemetry-quality') { const r = optimizer.optimize('MINIMAL', [model('a'), model('b')], context({ telemetry: [{ modelId:'b',quality:.99,latencyMs:100,successRate:.99,cloudAvoidance:.8,cloudSavings:.8,energy:.1,thermalImpact:.1,samples:99 }] })); assert.equal(r.bundle.models[0].manifest.modelId, 'b'); }
  if (category === 'telemetry-speed') { const r = optimizer.optimize('MINIMAL', [model('a'), model('b')], context({ telemetry: [{ modelId:'a',quality:.9,latencyMs:50,successRate:.9,cloudAvoidance:.7,cloudSavings:.7,energy:.1,thermalImpact:.1,samples:99 },{ modelId:'b',quality:.91,latencyMs:8400,successRate:.9,cloudAvoidance:.71,cloudSavings:.71,energy:.5,thermalImpact:.5,samples:99 }] })); assert.equal(r.bundle.models[0].manifest.modelId, 'a'); }
  if (category === 'storage-budget') assert.equal(optimizer.optimize('MINIMAL', catalog, context({ policy: policy({ storageBudget: 500_000_000 }), device: device({ storageFreeBytes: 1 }) })).bundle.models.length, 0);
  if (category === 'compatibility-platform') assert.equal(optimizer.optimize('MINIMAL', [model('x')], context({ device: device({ platform:'ANDROID',deviceClass:'MOBILE' }) })).rejected.length, 1);
  if (category === 'compatibility-ram') assert.equal(optimizer.optimize('MINIMAL', [model('x','segmentation',{requiredRam:20_000})], context()).rejected.length, 1);
  if (category === 'compatibility-vram') assert.equal(optimizer.optimize('MINIMAL', [model('x','segmentation',{requiredVram:20_000})], context()).rejected.length, 1);
  if (category === 'determinism') assert.deepEqual(optimizer.optimize('BALANCED', catalog, context()), optimizer.optimize('BALANCED', catalog, context()));
  if (category === 'immutability') assert.ok(Object.isFrozen(optimizer.optimize('BALANCED', catalog, context()).bundle.models));
  if (category === 'explainable-score') assert.match(optimizer.optimize('BALANCED', catalog, context()).bundle.models[0].reasons.join(' '), /quality.*speed.*cloud savings/);
});

function distribution(deviceValues: Partial<DeviceCapabilityProfile> = {}, policyValues: Partial<DistributionPolicy> = {}) { let now = 0; const files = new Map<string,Uint8Array>(); const catalog = [model('segment')]; return new CreativeModelDistribution({ localAI: { id:()=> 'id', clock:()=>++now, random:()=>.5, deviceProvider:{signals:async()=>device(deviceValues)}, runtimeProbe:{detect:async(kind)=>kind === 'WEBGPU'}, fetch:{fetch:async()=>new Uint8Array(10_000_000)}, storage:{freeBytes:async()=>5e9,read:async(id)=>files.get(id),write:async(id,bytes)=>{files.set(id,bytes)},remove:async(id)=>{files.delete(id)}}, hash:{sha256:async()=> 'a'.repeat(64)}, signatureVerifier:{verify:async()=>true}, modelCatalog:catalog }, bandwidthBytesPerSecond:()=>1_000_000 }, { policy:policy(policyValues), telemetry:[{modelId:'segment',quality:.9,latencyMs:100,successRate:.96,cloudAvoidance:.72,cloudSavings:.45,energy:.1,thermalImpact:.1,samples:100}], scope:{tenantId:'t',projectId:'p',userId:'u'} }); }

test('facade performs analyzed, proposed, consented, verified installation flow', async()=>{ const app=distribution(); await app.analyzeDevice(); const bundle=await app.recommendBundle('MINIMAL'); const proposal=app.propose(bundle); await app.installBundle(bundle,{proposalId:proposal.proposalId,approved:true,scope:{tenantId:'t',projectId:'p',userId:'u'}}); assert.equal(app.inspect('segment')?.status,'INSTALLED'); assert.equal(app.snapshot().trustStatus.segment,true); });
test('large installation cannot be hidden from user', async()=>{ const app=distribution(); await app.analyzeDevice(); const bundle=await app.recommendBundle(); await assert.rejects(app.installBundle(bundle),/consent/); });
test('battery policy defers installation', async()=>{ const app=distribution({batteryPercent:5}); await app.analyzeDevice(); const bundle=await app.recommendBundle(); const proposal=app.propose(); await assert.rejects(app.installBundle(bundle,{proposalId:proposal.proposalId,approved:true,scope:{tenantId:'t',projectId:'p',userId:'u'}}),/battery/); });
test('network policy defers metered download', async()=>{ const app=distribution({network:'METERED'}); await app.analyzeDevice(); const bundle=await app.recommendBundle(); const proposal=app.propose(); await assert.rejects(app.installBundle(bundle,{proposalId:proposal.proposalId,approved:true,scope:{tenantId:'t',projectId:'p',userId:'u'}}),/network/); });
test('cross-scope consent is rejected', async()=>{ const app=distribution(); await app.analyzeDevice(); const bundle=await app.recommendBundle(); const proposal=app.propose(); await assert.rejects(app.installBundle(bundle,{proposalId:proposal.proposalId,approved:true,scope:{tenantId:'other',projectId:'p',userId:'u'}}),/Cross-scope/); });
test('snapshots are deeply immutable and explain decisions', async()=>{ const app=distribution(); await app.analyzeDevice(); await app.recommendBundle(); const snapshot=app.snapshot(); assert.ok(Object.isFrozen(snapshot.timeline)); assert.match(app.explain().join(' '),/cloud savings/); });
test('adaptive policy separates preview and final quality', async()=>{ const app=distribution(); await app.analyzeDevice(); await app.recommendBundle(); assert.equal(app.adaptivePolicy()[0].preview,'LOCAL'); });
