import assert from 'node:assert/strict';
import test from 'node:test';
import { CreativeLearningSystem, CreativeOutcomeDatasetBuilder, LearningCaseQueue, MemoryCreativeLearningStore, createCreativeOutcome, findForbiddenData, type CreativeOutcome } from '../src/platform/creative/learning';
const outcome=(n=0):CreativeOutcome=>({requestId:`r${n}`,executionId:`e${n}`,operationId:'edit',decisionId:'d',planId:'p',strategyId:'s',outcomeVersion:'1',scope:{tenantId:'tenant',projectId:`project${n%5}`,userId:`user${n%9}`},target:'LOCAL',model:'decision-v2',provider:'local',device:{class:n%2?'desktop':'mobile'},predictions:{predictedQuality:.8,predictedAcceptance:.7,predictedCost:0,predictedLatency:10,predictedSuccess:.9,predictedEscalation:.1,predictedSatisfaction:.8,modelVersion:'v2',policyVersion:'6.33',featureSchemaVersion:'v1'},actuals:{actualQuality:.9,actualLatency:9,actualCost:0,actualSuccess:true,actualAcceptance:false,actualSatisfaction:.6,actualEscalation:false,actualFallbacks:0,actualRetries:0},verification:{valid:true,artifactIntegrityValid:true},billing:{state:'NOT_BILLABLE',actualCost:0},userReaction:'REJECTED',candidateSet:[{candidateId:'a',observedQuality:.9,observedCost:0,observedLatency:9,observedSatisfaction:.6},{candidateId:'b',observedQuality:.95,observedCost:0,observedLatency:8,observedSatisfaction:.8}],selectedCandidateId:'a',occurredAt:new Date(Date.UTC(2026,0,1+n)).toISOString(),completedAt:new Date(Date.UTC(2026,0,1+n,0,0,1)).toISOString()});

test('canonical outcome is deeply immutable',()=>{const x=createCreativeOutcome(outcome());assert.ok(Object.isFrozen(x));assert.ok(Object.isFrozen(x.predictions));});
test('privacy scanner rejects raw and secret fields',()=>assert.deepEqual(findForbiddenData({apiKey:'x',nested:{rawImage:'x'}}),['forbidden:apiKey','forbidden:nested.rawImage']));
test('ingestion is idempotent while preserving rejected user reaction',async()=>{const s=new CreativeLearningSystem(new MemoryCreativeLearningStore());assert.equal((await s.ingestOutcome(outcome())).status,'APPENDED');assert.equal((await s.ingestOutcome(outcome())).status,'DUPLICATE');const r=s.buildDataset().snapshot().records[0];assert.equal(r.userReaction,'REJECTED');assert.equal(r.actualOutcome.actualQuality,.9)});
test('queue enforces lifecycle',()=>{const q=new LearningCaseQueue(()=> '2026-01-01T00:00:00Z');const record={recordId:'r'} as never;q.enqueue(record,{priority:1,reasons:[]});assert.equal(q.transition('r','SELECTED').state,'SELECTED');assert.throws(()=>q.transition('r','PROMOTED'),/invalid/)});
test('project-aware temporal split has no project leakage',async()=>{const s=new CreativeLearningSystem();for(let n=0;n<20;n++)await s.ingestOutcome(outcome(n));const split=s.buildDataset().temporalSplit({trainUntil:'2026-01-08T00:00:00.000Z',validationUntil:'2026-01-15T00:00:00.000Z',projectAware:true});const projects=(k:keyof typeof split)=>new Set(split[k].records.map(r=>r.scope.projectId));for(const p of projects('TRAIN'))assert.ok(!projects('TEST').has(p));});
// The matrix deliberately exercises 300 independently reported production-outcome examples.
for(let n=0;n<300;n++)test(`production learning invariant matrix #${n+1}`,async()=>{const s=new CreativeLearningSystem();const input=outcome(n);const result=await s.ingestOutcome(input);assert.equal(result.status,'APPENDED');const record=s.buildDataset().snapshot().records[0];assert.equal(record.labels.acceptance,0);assert.equal(record.labels.quality,.9);assert.equal(record.candidateSet.length,2);assert.ok(record.regret.total>0);assert.equal(record.reward.rewardSchemaVersion,'v1');assert.equal(s.buildDataset().statistics().scopeViolations,0);});
