import assert from 'node:assert/strict';
import test from 'node:test';
import { CloudVisualEncoder, CreativeDecisionModel, DecisionCalibrationV2, DecisionConstraintLayer, DecisionDatasetBuilder, DecisionFeatureEncoderV1, DecisionModelEvaluator, DecisionModelRegistry, DecisionRepresentationEncoderV2, DecisionRepresentationEncoderV3, DecisionTrainerV1, HeuristicBaselineModel, LocalVisualEncoder, NeuralDecisionRanker, OperationNeedPredictor, TabularDecisionModelV1, VisualCounterfactual, VisualGoalAlignment, VisualQualityHead, calculateReward, decisionRegret } from '../src/platform/creative/model';
import type { DecisionCandidateV1, DecisionContextV1, DecisionDatasetRecord, DecisionFeaturesV1 } from '../src/platform/creative/model';

const context = (projectId = 'p1', privacyMode: DecisionContextV1['privacyMode'] = 'NORMAL'): DecisionContextV1 => ({ operation: 'upscale', intent: 'repair', goal: 'quality', deviceClass: 'desktop', platform: 'web', projectType: 'portrait', privacyMode, budget: 10, latencyTarget: 5000, qualityTarget: .8, projectId, deviceId: `device-${projectId}`, timestamp: 1 });
const candidate = (id = 'local', target: DecisionCandidateV1['executionTarget'] = 'LOCAL'): DecisionCandidateV1 => ({ id, executionTarget: target, model: `model-${id}`, provider: target === 'LOCAL' ? 'local' : 'cloud', runtime: 'WEBGPU', estimatedQuality: id === 'good' ? .95 : .7, estimatedLatency: 1000, estimatedCost: target === 'LOCAL' ? 0 : 2, energy: .2, memory: 1024, reliability: .9 });
const features = (id = 'local'): DecisionFeaturesV1 => ({ context: context(), candidate: candidate(id), history: { modelSuccessRate: .8, providerSuccessRate: .8, deviceSpecificSuccessRate: .7, cloudAvoidance: .7, acceptanceRate: .8, undoRate: .1 } });
const records = (): readonly DecisionDatasetRecord[] => Array.from({ length: 15 }, (_, index) => { const input = features(index % 2 ? 'good' : `candidate-${index}`); const projectId = `project-${Math.floor(index / 3)}`; return { id: `r${index}`, features: { ...input, context: context(projectId) }, context: context(projectId), candidate: input.candidate, decision: input.candidate.id, actualOutcome: { quality: index % 2 ? .95 : .6, success: index % 3 !== 0, accepted: index % 2 === 1, latency: 800 + index * 10, cost: index % 2, escalated: false }, reward: index % 2 ? 5 : 2, timestamp: index, modelVersion: 'v0', projectId, deviceId: `device-${projectId}` }; });

test('dataset builder creates immutable ML records', () => { const data = new DecisionDatasetBuilder({}, () => 10).fromOutcomes([{ operation: 'upscale', selectedTarget: 'LOCAL', actualOutcome: 'SUCCESS', actualCost: 0, actualQuality: .9, actualLatency: 12, userReaction: 'ACCEPTED' }]); assert.equal(data.length, 1); assert.equal(data[0].features.context.operation, 'upscale'); assert.ok(Object.isFrozen(data)); assert.ok(Number.isFinite(data[0].reward)); });
test('encoder is deterministic, normalized and versioned', () => { const encoder = new DecisionFeatureEncoderV1(), a = encoder.encode(features()), b = encoder.encode(features()); assert.deepEqual(a, b); assert.equal(a.length, encoder.featureNames.length); assert.ok(a.every(value => value >= 0 && value <= 1)); assert.equal(encoder.schemaVersion, 'decision-features-v1'); });
test('constraint gate preserves hard security boundaries', () => { const gate = new DecisionConstraintLayer(); assert.deepEqual(gate.evaluate(context('p', 'LOCAL_ONLY'), candidate('cloud', 'CLOUD')).exclusions, ['PRIVACY_LOCAL_ONLY']); assert.ok(!gate.evaluate(context(), { ...candidate(), quarantined: true }).allowed); assert.ok(!gate.evaluate(context(), { ...candidate(), runtimeSupported: false }).allowed); assert.ok(!gate.evaluate(context(), { ...candidate('expensive'), estimatedCost: 11 }).allowed); });
test('tabular model trains six heads and ranks deterministically', () => { const model = TabularDecisionModelV1.train(records(), { modelVersion: 'v1' }); const prediction = model.predict(features()); assert.ok(prediction.quality >= 0 && prediction.quality <= 1); assert.ok(prediction.acceptanceProbability >= 0); assert.equal(model.version(), 'v1'); assert.equal(model.rank(context(), [candidate('b'), candidate('a')]).length, 2); assert.deepEqual(model.rank(context(), [candidate('b'), candidate('a')]), model.rank(context(), [candidate('b'), candidate('a')])); });
test('trainer split prevents project leakage', () => { const split = new DecisionTrainerV1().split(records()); const train = new Set(split.train.map(item => item.projectId)), validation = new Set(split.validation.map(item => item.projectId)), heldOut = new Set(split.test.map(item => item.projectId)); assert.ok([...train].every(id => !validation.has(id) && !heldOut.has(id))); assert.ok([...validation].every(id => !heldOut.has(id))); });
test('registry enforces canary lifecycle and rollback', () => { const registry = new DecisionModelRegistry(), model = new HeuristicBaselineModel(), metrics = new DecisionModelEvaluator().evaluate(model, records()); registry.register(model, { featureSchemaVersion: 'v1', datasetVersion: 'v1', trainingConfigVersion: 'v1', metrics, parentModel: null, createdAt: 1 }); registry.transition(model.version(), 'CANARY'); assert.equal(registry.promote(model.version()).status, 'ACTIVE'); });
test('facade shadow never controls execution', () => { const facade = new CreativeDecisionModel(); const result = facade.shadow(features()); assert.equal(result.mode, 'MODEL_SHADOW'); assert.equal(result.executedBy, 'heuristic-baseline-v0'); assert.equal(facade.benchmark().length, 30); });
test('reward and regret are policy aware', () => { const reward = calculateReward({ quality: .9, success: true, accepted: true, latency: 100, cost: 0, escalated: false }, context()); assert.ok(reward > 0); assert.equal(decisionRegret(2, 5), 3); assert.equal(decisionRegret(5, 2), 0); });
test('v2 representation is modular, versioned and cold-start aware', () => { const encoded = new DecisionRepresentationEncoderV2().encode(features()); assert.equal(encoded.schemaVersion, 'decision-representation-v2'); assert.deepEqual(Object.keys(encoded.blocks), ['context', 'candidate', 'device', 'goal', 'constraint', 'history']); assert.ok(encoded.coldStart.includes('NEW_MODEL')); assert.ok(Object.isFrozen(encoded)); });
test('v2 ranker supports pairwise, listwise, uncertainty and distillation', () => { const ranker = new NeuralDecisionRanker(), a = features('good'), b = features('cheap'); const before = ranker.compare(a, b); ranker.trainPairwise([{ preferred: a, rejected: b, source: 'OUTCOME' }]); ranker.trainListwise([{ candidates: [a, b], relevance: [1, 0] }]); assert.ok(before >= 0 && before <= 1); assert.equal(ranker.rank([b, a]).length, 2); assert.ok(ranker.predict(a).uncertaintyV2.confidence >= 0); assert.equal(ranker.distill([a, b]).samples, 2); });
test('v2 facade exposes counterfactual and separate calibration', () => { const facade = new CreativeDecisionModel(), a = features('good'), b = features('cheap'); assert.equal(facade.encode(a).encoderVersion, 'decision-encoder-v2.0.0'); assert.equal(facade.predictList([a, b]).length, 2); assert.ok(Number.isFinite(facade.counterfactual(a, b).utilityDelta)); const prediction = new NeuralDecisionRanker().predict(a); assert.equal(facade.calibrate([prediction], [{ quality: .9 }]).sampleCount, 1); assert.equal(new DecisionCalibrationV2().reliability([.8], [1]).length, 10); });

const visualInput = { width: 1200, height: 800, composition: { balance: .8, focus: .9, negativeSpace: .4 }, subjectCount: 1, facePresence: .9, objectClasses: ['person'], lighting: { exposure: .75, contrast: .7, uniformity: .8 }, colorDistribution: [.2, .4, .8], backgroundComplexity: .2, estimatedQuality: .85, depthCues: .8, segmentationComplexity: .25, visualStyle: ['luxury', 'commercial'], sourceAssetId: 'private-asset' };
const visualGoal = { direction: 'luxury commercial photography', styles: ['luxury', 'commercial'] };
test('local visual encoder emits structured privacy-safe features', () => { const encoded = new LocalVisualEncoder().encode(visualInput, visualGoal); assert.equal(encoded.encoderTarget, 'LOCAL'); assert.equal(encoded.requestedStyleSimilarity, 1); assert.equal(encoded.resolution.megapixels, .96); assert.equal('sourceAssetId' in encoded, false); assert.ok(Object.isFrozen(encoded)); });
test('cloud visual encoder is blocked by privacy and outbound policy', () => { const cloud = new CloudVisualEncoder(); assert.throws(() => cloud.encode(visualInput, visualGoal, { privacyMode: 'LOCAL_ONLY', cloudAnalysisAllowed: true, outboundImageAllowed: true }), /forbidden/); assert.throws(() => cloud.encode(visualInput, visualGoal, { privacyMode: 'NORMAL', cloudAnalysisAllowed: true, outboundImageAllowed: false }), /forbidden/); assert.equal(cloud.encode(visualInput, visualGoal, { privacyMode: 'NORMAL', cloudAnalysisAllowed: true, outboundImageAllowed: true }).encoderTarget, 'CLOUD'); });
test('v3 fusion includes visual quality, alignment and operation need without bypassing candidate constraints', () => { const visual = new LocalVisualEncoder().encode(visualInput, visualGoal), encoded = new DecisionRepresentationEncoderV3().encode({ ...features(), visual, visualGoal }); assert.equal(encoded.schemaVersion, 'decision-representation-v3'); assert.ok(encoded.vector.length > new DecisionRepresentationEncoderV2().encode(features()).vector.length); assert.equal(encoded.goalAlignment.gap, 0); assert.ok(encoded.visualQuality.identityPreservation > .5); assert.ok(encoded.operationNeeds.some(need => need.operation === 'NONE' && need.needed)); assert.equal(new DecisionConstraintLayer().evaluate(context('v3', 'LOCAL_ONLY'), candidate('cloud', 'CLOUD')).allowed, false); });
test('visual heads expose bounded goal gap, needs and local/cloud counterfactual', () => { const visual = new LocalVisualEncoder().encode({ ...visualInput, width: 320, height: 200, estimatedQuality: .3, visualStyle: ['snapshot'] }, visualGoal); const quality = new VisualQualityHead().predict(visual), alignment = new VisualGoalAlignment().evaluate(visual, visualGoal), needs = new OperationNeedPredictor().predict(visual, visualGoal), counterfactual = new VisualCounterfactual().compare(quality, { technicalQuality: .95, visualCoherence: .95, identityPreservation: .9, compositionQuality: .9 }); assert.ok(alignment.gap > .5); assert.ok(needs.some(need => need.operation === 'UPSCALE' && need.needed)); assert.equal(counterfactual.alternativeOperation, 'GENERATION'); assert.ok(Object.values(quality).every(value => value >= 0 && value <= 1)); });

// 250 named deterministic cases protect schema stability, bounded outputs and input immutability.
for (let index = 0; index < 250; index++) test(`decision model invariant ${String(index + 1).padStart(3, '0')}`, () => { const input = features(`case-${index}`), before = JSON.stringify(input), encoded = new DecisionFeatureEncoderV1().encode(input), prediction = new HeuristicBaselineModel().predict(input); assert.equal(encoded.length, 26); assert.ok(encoded.every(value => Number.isFinite(value))); assert.ok(prediction.quality >= 0 && prediction.quality <= 1); assert.equal(JSON.stringify(input), before); });

// V2 matrix covers deterministic interaction encoding, bounded heads, OOD safety and immutability.
for (let index = 0; index < 50; index++) test(`decision model v2 invariant ${String(index + 1).padStart(3, '0')}`, () => { const input = features(`v2-${index}`), before = JSON.stringify(input), encoder = new DecisionRepresentationEncoderV2(), ranker = new NeuralDecisionRanker(encoder), first = encoder.encode(input), second = encoder.encode(input), prediction = ranker.predict(input); assert.deepEqual(first, second); assert.ok(first.vector.every(Number.isFinite)); assert.ok(prediction.satisfaction >= 0 && prediction.satisfaction <= 1); assert.ok(prediction.uncertaintyV2.oodScore >= 0 && prediction.uncertaintyV2.oodScore <= 1); assert.equal(JSON.stringify(input), before); });
