import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import { ActiveReasoningEngine, CognitivePerformanceModel, CognitiveReflectionEngine, CognitiveReplayStudio, CognitiveWorkspace, CreativeDiscoveryEngineV2, CuriosityScheduler, DynamicAttentionController, EmergentStrategyGenerator, EvidenceNetwork, ExperimentPlanner, HeuristicAttentionEncoder, HeuristicEvidenceEncoder, HeuristicHypothesisEncoder, HeuristicMemoryEncoder, HeuristicPlanningEncoder, HeuristicReasoningEncoder, HeuristicReflectionEncoder, HeuristicSimulationEncoder, HeuristicThoughtEncoder, HeuristicWorkspaceEncoder, HypothesisArena, KnowledgeGapDetector, MemoryCompressor, MentalSimulationEngine, ReasoningLoop, SelfMonitoringEngine, ThinkingProgramComposer, UnifiedCognitiveTimelineV2, immutable } from '../src/platform/creative/cognition';
import type { AttentionDistribution, Evidence, Thought, V2Dependencies, WorkspaceData, WorkspaceHypothesis } from '../src/platform/creative/cognition';

const deps = (): V2Dependencies => { let id = 0; return { nextId: () => `v2-${++id}`, now: () => 123456, random: () => .5 }; };
const scope = { tenantId: 'tenant', projectId: 'project', userId: 'user' };
const attention = immutable({ QUALITY: .1, BRAND: .1, COMPOSITION: .1, COST: .1, RISK: .1, CREATIVITY: .1, EMOTION: .1, STORY: .1, IDENTITY: .1, CONSISTENCY: .1 }) as AttentionDistribution;
const workspaceData = (): WorkspaceData => immutable({ goals: ['quality'], intentSpace: ['portrait'], thoughts: [], evidence: [], hypotheses: [], attention, workingThoughtIds: [], openQuestions: ['lighting?'], unknowns: ['lighting'], contradictionIds: [], experiments: [], insights: [], plans: [], decisionCandidates: [] });
const hypothesis = (id: string, overrides = {}): WorkspaceHypothesis => immutable({ id, statement: id, confidence: .7, evidenceIds: [], counterEvidenceIds: [], expectedGain: .4, verification: 'UNVERIFIED', support: .7, contradictions: .1, predictedValue: .7, survivalScore: 0, ...overrides });
const evidence = (id: string): Evidence => immutable({ id, claim: id, source: 'test', strength: .8, reliability: .9, createdAt: 1 });
const thought = (id: string, tag = 'pattern'): Thought => immutable({ id, type: 'IDEA', content: id, createdAt: 1, saliency: .7, signals: { novelty: .5, importance: .7, risk: .2, goalImpact: .8, confidence: .7, urgency: .3 }, tags: [tag] });

test('workspace creates immutable revision zero', () => { const result = new CognitiveWorkspace(deps()).create(scope, workspaceData()); assert.equal(result.revision, 0); assert.throws(() => (result.data.goals as string[]).push('x')); });
test('workspace revision preserves previous snapshot', () => { const workspace = new CognitiveWorkspace(deps()); const zero = workspace.create(scope, workspaceData()); const one = workspace.revise(zero, scope, { unknowns: [] }); assert.equal(one.revision, 1); assert.deepEqual(zero.data.unknowns, ['lighting']); });
test('workspace snapshots specific revisions', () => { const workspace = new CognitiveWorkspace(deps()); const zero = workspace.create(scope, workspaceData()); workspace.revise(zero, scope, { goals: ['quality', 'identity'] }); assert.deepEqual(workspace.snapshot(zero.id, 0, scope), zero); });
test('workspace replay returns every revision', () => { const workspace = new CognitiveWorkspace(deps()); const zero = workspace.create(scope, workspaceData()); const one = workspace.revise(zero, scope, { goals: ['two'] }); workspace.revise(one, scope, { unknowns: [] }); assert.equal(workspace.replay(zero.id, scope).length, 3); });
test('workspace diff reports changed collections', () => { const workspace = new CognitiveWorkspace(deps()); const zero = workspace.create(scope, workspaceData()); const one = workspace.revise(zero, scope, { goals: ['two'], unknowns: [] }); assert.deepEqual(workspace.diff(zero, one, scope).changed, ['goals', 'unknowns']); });
test('workspace rejects stale revision writes', () => { const workspace = new CognitiveWorkspace(deps()); const zero = workspace.create(scope, workspaceData()); workspace.revise(zero, scope, { unknowns: [] }); assert.throws(() => workspace.revise(zero, scope, {}), /revision conflict/); });
test('workspace tenant isolation', () => { const workspace = new CognitiveWorkspace(deps()); const zero = workspace.create(scope, workspaceData()); assert.throws(() => workspace.replay(zero.id, { ...scope, tenantId: 'other' }), /scope/); });
test('workspace project isolation', () => { const workspace = new CognitiveWorkspace(deps()); const zero = workspace.create(scope, workspaceData()); assert.throws(() => workspace.snapshot(zero.id, 0, { ...scope, projectId: 'other' }), /scope/); });
test('workspace user isolation', () => { const workspace = new CognitiveWorkspace(deps()); const zero = workspace.create(scope, workspaceData()); assert.throws(() => workspace.revise(zero, { ...scope, userId: 'other' }, {}), /scope/); });

test('active reasoning records eight independent cycles', () => { const workspace = new CognitiveWorkspace(deps()).create(scope, workspaceData()); const cycles = new ActiveReasoningEngine(deps()).reason(workspace); assert.deepEqual(cycles.map((item) => item.action), ['OBSERVE', 'ANALYZE', 'COMPARE', 'HYPOTHESIZE', 'CHALLENGE', 'REFINE', 'REFLECT', 'DECIDE']); assert.ok(cycles.every((item) => item.outputRevision === item.inputRevision + 1)); });
test('reasoning loop records transition metadata', () => { const transitions = new ReasoningLoop(deps()).run('new evidence'); assert.equal(transitions.length, 9); assert.equal(transitions[0].from, 'OBSERVE'); assert.equal(transitions.at(-1)?.to, 'FINALIZE'); assert.ok(transitions.every((item) => item.reason && item.trigger && item.at)); });
test('thinking program is composed from task signals', () => { const program = new ThinkingProgramComposer(deps()).compose({ explore: true, verificationRisk: .8, optimize: true, creative: true, constraints: ['budget'], goals: ['brand emotion'] }); assert.deepEqual(program.modules, ['EXPLORATION', 'VERIFICATION', 'BRAND', 'EMOTION', 'CREATIVITY', 'COST', 'OPTIMIZATION', 'SAFETY', 'REFLECTION', 'LEARNING']); });

test('dynamic attention increases pressured dimension', () => { const result = new DynamicAttentionController().redistribute(attention, { dimension: 'QUALITY', pressure: .3 }); assert.ok(result.QUALITY > attention.QUALITY); assert.ok(result.COST < attention.COST); });
test('dynamic attention remains normalized and immutable', () => { const result = new DynamicAttentionController().redistribute(attention, { dimension: 'RISK', pressure: .2 }); assert.ok(Math.abs(Object.values(result).reduce((a, b) => a + b, 0) - 1) < .000001); assert.throws(() => (result as Record<string, number>).RISK = 0); });
test('hypothesis arena eliminates weak candidates', () => { const survivors = new HypothesisArena().compete([hypothesis('strong'), hypothesis('weak', { confidence: .1, support: .1, predictedValue: .1, contradictions: .9 })]); assert.deepEqual(survivors.map((item) => item.id), ['strong']); });
test('evidence network accepts typed relations', () => { const result = new EvidenceNetwork().build([evidence('a'), evidence('b')], [{ id: 'r', from: 'a', to: 'b', type: 'SUPPORTS', strength: .8 }]); assert.equal(result.relations[0].type, 'SUPPORTS'); });
test('evidence network rejects dangling relations', () => assert.throws(() => new EvidenceNetwork().build([evidence('a')], [{ id: 'r', from: 'a', to: 'missing', type: 'REQUIRES', strength: .5 }]), /unknown node/));

test('experiment planner predicts without execution', () => { const result = new ExperimentPlanner(deps()).plan('lighting', { quality: .6, cost: .2, satisfaction: .5 }); assert.equal(result.status, 'PLANNED'); assert.equal(result.expectedQuality, .65); });
test('curiosity explores highest priority unknown', () => assert.deepEqual(new CuriosityScheduler().decide({ unknowns: ['lighting', 'brand'], fatigue: .2, explored: 0, budget: 2 }).target, 'lighting'));
test('curiosity stops when fatigued', () => assert.equal(new CuriosityScheduler().decide({ unknowns: ['lighting'], fatigue: .9, explored: 0, budget: 2 }).explore, false));
test('mental simulation produces all five scenarios', () => assert.deepEqual(new MentalSimulationEngine(deps()).simulate(.5, .5).map((item) => item.strategy), ['LOCAL', 'HYBRID', 'AI', 'HYBRID_AI', 'NO_AI']));
test('reflection reports eliminated hypotheses', () => { const cycles = new ActiveReasoningEngine(deps()).reason(new CognitiveWorkspace(deps()).create(scope, workspaceData())); const result = new CognitiveReflectionEngine(deps()).reflect({ cycles, before: [hypothesis('alive'), hypothesis('dead')], after: [hypothesis('alive')], unknowns: ['lighting'] }); assert.deepEqual(result.eliminatedHypotheses, ['dead']); assert.deepEqual(result.verifyLater, ['lighting']); });

test('self monitoring returns bounded adaptive metrics', () => { const cycles = new ActiveReasoningEngine(deps()).reason(new CognitiveWorkspace(deps()).create(scope, workspaceData())); const metrics = new SelfMonitoringEngine().monitor({ cycles, attention, contradictions: 1, hypothesesBefore: 4, hypothesesAfter: 2 }); assert.ok(Object.values(metrics).every((value) => value >= 0 && value <= 1)); assert.equal(metrics.hypothesisCollapse, .5); });
test('memory compressor creates reasoning macros', () => { const macros = new MemoryCompressor(deps()).compress([thought('one'), thought('two'), thought('three', 'other')]); assert.equal(macros.length, 2); assert.deepEqual(macros.find((item) => item.pattern === 'pattern')?.sourceThoughtIds, ['one', 'two']); });
test('knowledge gaps separate known assumed and unknown', () => { const gaps = new KnowledgeGapDetector().detect({ evidence: [evidence('lighting')], hypotheses: [hypothesis('assumed')], questions: ['lighting?', 'brand?'] }); assert.deepEqual(gaps.known, ['lighting']); assert.deepEqual(gaps.assumed, ['assumed']); assert.deepEqual(gaps.unknown, ['brand?']); });
test('discovery v2 exposes five creative scores', () => { const result = new CreativeDiscoveryEngineV2().score({ novelty: .8, expectation: .4, actual: .9, rarity: .7, risk: .2, reward: .8 }); assert.equal(Object.keys(result).length, 5); assert.ok(result.creativePotential > .6); });
test('emergent strategy derives new principles', () => { const result = new EmergentStrategyGenerator(deps()).generate([hypothesis('soft-light', { survivalScore: .9 })], { known: [], assumed: [], unknown: ['identity'] }); assert.match(result.name, /soft-light/); assert.deepEqual(result.principles, ['soft-light', 'Verify identity']); });
test('cognitive performance exposes six efficiencies', () => { const metrics = { thinkingDepth: .8, reasoningWidth: .7, attentionEntropy: .8, contradictionRate: .1, confidenceDrift: .1, hypothesisCollapse: .2, cognitiveFatigue: .2 }; const result = new CognitivePerformanceModel().evaluate(metrics, { completedPlans: 2, totalPlans: 3, insights: 1, alternatives: 2, resourceUsed: .3 }); assert.equal(Object.keys(result).length, 6); });

test('timeline v2 contains the complete reasoning chain', () => assert.deepEqual(new UnifiedCognitiveTimelineV2(deps()).build().map((item) => item.kind), ['THOUGHT', 'HYPOTHESIS', 'EVIDENCE', 'DEBATE', 'SIMULATION', 'EXPERIMENT', 'REFLECTION', 'LEARNING', 'DECISION']));
test('replay studio seeks rewinds replaces and repeats', () => { const studio = new CognitiveReplayStudio(); const cursor = studio.open('session', new UnifiedCognitiveTimelineV2(deps()).build()); const sought = studio.seek(cursor, 5); assert.equal(studio.rewind(sought, 2).position, 3); assert.equal(studio.replaceHypothesis(cursor, 'changed').events[1].referenceId, 'changed'); assert.equal(studio.repeat(sought).position, 0); });
test('replay studio compares reasoning versions', () => { const studio = new CognitiveReplayStudio(); const cursor = studio.open('session', new UnifiedCognitiveTimelineV2(deps()).build()); const changed = studio.replaceHypothesis(cursor, 'changed'); assert.equal(studio.compare(cursor, cursor).identical, true); assert.deepEqual(studio.compare(cursor, changed).differences, [1]); });

test('all ten future encoders are deterministic', () => { const workspace = new CognitiveWorkspace(deps()).create(scope, workspaceData()); const cycles = new ActiveReasoningEngine(deps()).reason(workspace); const h = hypothesis('h'); const e = evidence('e'); const t = thought('t'); const reflection = new CognitiveReflectionEngine(deps()).reflect({ cycles, before: [], after: [], unknowns: [] }); const scenario = new MentalSimulationEngine(deps()).simulate(.5, .5)[0]; const macro = new MemoryCompressor(deps()).compress([t])[0]; const vectors = [new HeuristicReasoningEncoder().encode(cycles), new HeuristicWorkspaceEncoder().encode(workspace), new HeuristicThoughtEncoder().encode(t), new HeuristicHypothesisEncoder().encode(h), new HeuristicEvidenceEncoder().encode(e), new HeuristicReflectionEncoder().encode(reflection), new HeuristicPlanningEncoder().encode({ id: 'p', steps: ['x'], confidence: .7 }), new HeuristicSimulationEncoder().encode(scenario), new HeuristicAttentionEncoder().encode(attention), new HeuristicMemoryEncoder().encode(macro)]; assert.equal(vectors.length, 10); assert.ok(vectors.every((vector) => Object.isFrozen(vector) && vector.every(Number.isFinite))); });
test('same inputs and DI produce byte-identical adaptive results', () => { const make = () => { const d = deps(); const workspace = new CognitiveWorkspace(d).create(scope, workspaceData()); return { cycles: new ActiveReasoningEngine(d).reason(workspace), loop: new ReasoningLoop(d).run('evidence'), simulation: new MentalSimulationEngine(d).simulate(.5, .5) }; }; assert.deepEqual(make(), make()); });
test('forbidden dependencies are absent from cognition imports', () => { const forbidden = [/\/decision/i, /\/director/i, /\/studio/i, /\/meta/i, /\/orchestrator/i, /\/workflow/i, /\/runtime/i, /\/provider/i, /\/billing/i, /\/gateway/i, /\/application/i, /react/i, /base44/i, /persistence/i]; for (const file of readdirSync('src/platform/creative/cognition')) { if (!file.endsWith('.ts')) continue; const imports = readFileSync(join('src/platform/creative/cognition', file), 'utf8').split('\n').filter((line) => /^import|^export .* from/.test(line)).join('\n'); for (const pattern of forbidden) assert.equal(pattern.test(imports), false, `${file} imports ${pattern}`); } });
