import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import { AutonomousResearchLayer, CognitiveEvolutionEngine, CognitiveRegressionDetector, CreativeConstitution, DecisionGenomeEngine, HeuristicDecisionModel, HeuristicEvolution, IntelligenceBenchmarkPlatform, IntelligenceObservatory, ReasoningLibrary, StrategyEvolutionEngine, WorldKnowledgeEvolution, immutable } from '../src/platform/creative/evolution';
import type { BenchmarkScenario, DecisionGenome, EvolutionDependencies, HeuristicGenes, PerformanceVector } from '../src/platform/creative/evolution';

const dependencies = (): EvolutionDependencies => { let id = 0; return { nextId: () => `evo-${++id}`, now: () => 123456, random: () => .6 }; };
const scope = { tenantId: 'tenant', projectId: 'project', userId: 'user' };
const metrics = (value: number): PerformanceVector => immutable({ quality: value, reasoning: value, planning: value, creativity: value, cost: value, brand: value, composition: value, stability: value });
const genes = (value: number): HeuristicGenes => immutable({ LIGHTING: value, COMPOSITION: value, CREATIVITY: value, RISK: value, BRAND: value, COST: value, EMOTION: value });
const genome = (id: string, outcome = .7): DecisionGenome => immutable({ id, goal: 'luxury', intent: 'campaign', reasoning: ['light'], operations: ['local-light'], evaluation: metrics(outcome), reflection: ['worked'], outcome, parentIds: [], generation: 1 });
const scenarios: readonly BenchmarkScenario[] = [{ id: 's1', domain: 'luxury', difficulty: .8, expected: metrics(.7) }, { id: 's2', domain: 'portrait', difficulty: .5, expected: metrics(.8) }];

test('evolution engine registers ordered versions', () => { const engine = new CognitiveEvolutionEngine(dependencies()); const v1 = engine.register(scope, 'REASONING', metrics(.7), 'initial'); const v2 = engine.register(scope, 'REASONING', metrics(.8), 'improve', v1.id); assert.equal(v1.version, 1); assert.equal(v2.version, 2); assert.deepEqual(engine.history('REASONING', scope).map((item) => item.id), [v1.id, v2.id]); });
test('evolution promotes a better candidate', () => { const engine = new CognitiveEvolutionEngine(dependencies()); const v1 = engine.register(scope, 'PLANNING', metrics(.5), 'base'); const v2 = engine.register(scope, 'PLANNING', metrics(.7), 'better', v1.id); assert.equal(engine.evaluate(v1.id, v2.id, scope).status, 'ACTIVE'); });
test('evolution rejects a regression', () => { const engine = new CognitiveEvolutionEngine(dependencies()); const v1 = engine.register(scope, 'DEBATE', metrics(.8), 'base'); const v2 = engine.register(scope, 'DEBATE', metrics(.6), 'worse', v1.id); assert.equal(engine.evaluate(v1.id, v2.id, scope).status, 'REJECTED'); });
test('evolution detects per-metric regression', () => { const engine = new CognitiveEvolutionEngine(dependencies()); const v1 = engine.register(scope, 'STRATEGY', metrics(.8), 'base'); const changed = { ...metrics(.8), creativity: .9, quality: .75 }; const v2 = engine.register(scope, 'STRATEGY', changed, 'mixed', v1.id); const result = engine.compare(v1.id, v2.id, scope); assert.equal(result.deltas.creativity, .1); assert.equal(result.regressed, true); });
test('evolution enforces tenant isolation', () => { const engine = new CognitiveEvolutionEngine(dependencies()); const version = engine.register(scope, 'REASONING', metrics(.7), 'base'); assert.deepEqual(engine.history('REASONING', { ...scope, tenantId: 'other' }), []); assert.throws(() => engine.compare(version.id, version.id, { ...scope, tenantId: 'other' }), /scope/); });
test('evolution enforces project isolation', () => { const engine = new CognitiveEvolutionEngine(dependencies()); const version = engine.register(scope, 'REASONING', metrics(.7), 'base'); assert.throws(() => engine.compare(version.id, version.id, { ...scope, projectId: 'other' }), /scope/); });
test('evolution enforces user isolation', () => { const engine = new CognitiveEvolutionEngine(dependencies()); const version = engine.register(scope, 'REASONING', metrics(.7), 'base'); assert.throws(() => engine.compare(version.id, version.id, { ...scope, userId: 'other' }), /scope/); });

test('heuristic evolution creates generations', () => { const evolution = new HeuristicEvolution(dependencies()); const first = evolution.seed(genes(.5)); const second = evolution.mutate(first, .1); assert.equal(second.generation, 2); assert.deepEqual(second.parentIds, [first.id]); assert.equal(second.genes.LIGHTING, .6); });
test('heuristic crossover alternates genes', () => { const evolution = new HeuristicEvolution(dependencies()); const child = evolution.crossover(evolution.seed(genes(.2)), evolution.seed(genes(.8))); assert.equal(child.genes.LIGHTING, .2); assert.equal(child.genes.COMPOSITION, .8); });
test('heuristic evolution selects best generation', () => { const evolution = new HeuristicEvolution(dependencies()); const low = evolution.score(evolution.seed(genes(.2)), [.2, .3]); const high = evolution.score(evolution.seed(genes(.8)), [.8, .9]); assert.equal(evolution.best([low, high]).id, high.id); });

test('strategy evolution maintains parent children tree', () => { const engine = new StrategyEvolutionEngine(dependencies()); const root = engine.create('Luxury', { performance: .7, support: .8, confidence: .8, roi: .2 }); const child = engine.create('Luxury Fashion', { performance: .8, support: .7, confidence: .8, roi: .3 }, root.id); const tree = engine.tree(root.id); assert.deepEqual(tree.map((item) => item.id), [root.id, child.id]); assert.deepEqual(tree[0].childIds, [child.id]); });
test('strategy evolution activates effective strategy', () => { const engine = new StrategyEvolutionEngine(dependencies()); const node = engine.create('Product', { performance: .8, support: .8, confidence: .7, roi: .2 }); assert.equal(engine.evaluate(node.id).status, 'ACTIVE'); });
test('strategy evolution rejects weak strategy', () => { const engine = new StrategyEvolutionEngine(dependencies()); const node = engine.create('Weak', { performance: .4, support: .2, confidence: .8, roi: -.1 }); assert.equal(engine.evaluate(node.id).status, 'REJECTED'); });

test('decision genomes find similar decisions', () => { const engine = new DecisionGenomeEngine(dependencies()); const target = genome('target'); const similar = { ...genome('similar'), operations: ['local-light', 'crop'] }; const different = { ...genome('different'), goal: 'repair', intent: 'restore', reasoning: ['damage'], operations: ['heal'] }; assert.equal(engine.findSimilar(target, [similar, different])[0].genomeId, 'similar'); });
test('decision genome crossover combines reasoning and operations', () => { const engine = new DecisionGenomeEngine(dependencies()); const child = engine.crossover(genome('a', .8), { ...genome('b', .6), reasoning: ['brand'], operations: ['crop'] }); assert.deepEqual(child.reasoning, ['light', 'brand']); assert.deepEqual(child.parentIds, ['a', 'b']); });
test('decision genome mutation preserves parent lineage', () => { const engine = new DecisionGenomeEngine(dependencies()); const parent = genome('a'); const child = engine.mutate(parent, 'contrast'); assert.deepEqual(child.parentIds, ['a']); assert.ok(child.operations.includes('contrast')); });

test('benchmark calculates six IQ scores', () => { const result = new IntelligenceBenchmarkPlatform(dependencies()).run('v1', scenarios, (scenario) => scenario.expected); assert.equal(result.scenarioCount, 2); assert.equal(result.creativeIQ, 75); assert.equal(result.reasoningIQ, 75); assert.equal(result.compositionIQ, 75); });
test('regression detector blocks three percent loss', () => { const platform = new IntelligenceBenchmarkPlatform(dependencies()); const baseline = platform.run('v1', scenarios, () => metrics(.8)); const candidate = platform.run('v2', scenarios, () => metrics(.75)); const findings = new CognitiveRegressionDetector().detect(baseline, candidate); assert.ok(findings.every((item) => item.severity === 'BLOCKING')); assert.equal(new CognitiveRegressionDetector().acceptable(findings), false); });
test('regression detector accepts improvements', () => { const platform = new IntelligenceBenchmarkPlatform(dependencies()); const baseline = platform.run('v1', scenarios, () => metrics(.7)); const candidate = platform.run('v2', scenarios, () => metrics(.8)); assert.equal(new CognitiveRegressionDetector().acceptable(new CognitiveRegressionDetector().detect(baseline, candidate)), true); });

test('world knowledge versions report changes', () => { const evolution = new WorldKnowledgeEvolution(dependencies()); const first = evolution.create([{ key: 'soft-light', value: 'helps luxury', confidence: .6, updatedAt: 1 }, { key: 'old', value: 'old', confidence: .4, updatedAt: 1 }]); const second = evolution.evolve(first, [{ key: 'soft-light', value: 'helps luxury', confidence: .9, updatedAt: 2 }, { key: 'identity', value: 'preserve', confidence: .8, updatedAt: 2 }]); assert.deepEqual(second.added, ['identity']); assert.deepEqual(second.strengthened, ['soft-light']); assert.deepEqual(second.deprecated, ['old']); });
test('reasoning library exposes ten composable programs', () => { const library = new ReasoningLibrary(); assert.equal(library.all().length, 10); assert.deepEqual(library.compose(['LUXURY', 'VERIFICATION']).slice(0, 3), ['identify premium cues', 'shape light', 'verify identity']); });

test('autonomous research generates and ranks alternatives', () => { const result = new AutonomousResearchLayer(dependencies()).research('Can AI be removed?', 20); assert.equal(result.alternatives.length, 20); assert.equal(result.winnerId, result.alternatives[0].id); assert.ok(result.alternatives.every((item, index, array) => index === 0 || array[index - 1].score >= item.score)); });
test('creative constitution contains eight principles', () => assert.equal(new CreativeConstitution().principles.length, 8));
test('creative constitution rejects identity violation', () => { const result = new CreativeConstitution().assess({ PRESERVE_IDENTITY: false }); assert.equal(result.compliant, false); assert.deepEqual(result.violations, ['PRESERVE_IDENTITY']); });
test('intelligence observatory calculates overall health', () => { const result = new IntelligenceObservatory(dependencies()).snapshot(scope, { moduleStates: { reasoning: 'HEALTHY', planning: 'WATCH' }, activeHeuristics: ['light-v2'], generation: 16, reasoningQuality: .8, activeStrategies: ['luxury-v3'], stability: .9, confidenceDistribution: [.7, .8], workingMemoryLoad: .3 }); assert.equal(result.overallHealth, .725); assert.equal(result.generation, 16); });

test('heuristic decision model exposes future model API', () => { const result = new HeuristicDecisionModel().evaluate(genome('decision')); assert.ok(['LOCAL', 'HYBRID', 'AI', 'DEFER'].includes(result.strategy)); assert.ok(result.confidence >= 0 && result.confidence <= 1); assert.equal(result.explanation.length, 2); });
test('heuristic decision model is deterministic', () => assert.deepEqual(new HeuristicDecisionModel().evaluate(genome('decision')), new HeuristicDecisionModel().evaluate(genome('decision'))));
test('evolution outputs are deeply immutable', () => { const engine = new CognitiveEvolutionEngine(dependencies()); const version = engine.register(scope, 'REFLECTION', metrics(.7), 'initial'); assert.throws(() => (version.metrics as Record<string, number>).quality = 0); });
test('all ID time and randomness sources use dependency injection', () => { const fixed = { nextId: () => 'fixed', now: () => 77, random: () => .9 }; const version = new CognitiveEvolutionEngine(fixed).register(scope, 'EXPLORATION', metrics(.5), 'x'); const genomeResult = new HeuristicEvolution(fixed).seed(genes(.5)); assert.equal(version.id, 'fixed'); assert.equal(version.createdAt, 77); assert.equal(genomeResult.createdAt, 77); });
test('identical input and DI produce identical evolution output', () => { const run = () => { const engine = new CognitiveEvolutionEngine(dependencies()); const base = engine.register(scope, 'REASONING', metrics(.5), 'base'); const next = engine.register(scope, 'REASONING', metrics(.7), 'next', base.id); return engine.compare(base.id, next.id, scope); }; assert.deepEqual(run(), run()); });
test('evolution layer has no forbidden imports', () => { const forbidden = [/from ['"].*creative\/decision/i, /from ['"].*\/director/i, /from ['"].*\/studio/i, /from ['"].*\/meta/i, /from ['"].*\/orchestrator/i, /from ['"].*\/workflow/i, /from ['"].*\/runtime/i, /from ['"].*\/provider/i, /from ['"].*\/billing/i, /from ['"].*\/gateway/i, /from ['"].*\/application/i, /from ['"].*\/memory/i, /from ['"]react/i, /from ['"]@base44/i, /from ['"].*\/persistence/i]; for (const file of readdirSync('src/platform/creative/evolution')) { if (!file.endsWith('.ts')) continue; const imports = readFileSync(join('src/platform/creative/evolution', file), 'utf8').split('\n').filter((line) => /^import|^export .* from/.test(line)).join('\n'); for (const pattern of forbidden) assert.equal(pattern.test(imports), false, `${file} imports ${pattern}`); } });
