import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import { CapabilityRegistry, CognitiveBudget, CreativeIntelligenceKernel, EventTimeline, IntelligenceDependencyGraph, IntelligenceHealthMonitor, IntelligenceScheduler, IntelligenceSessionManager, IntelligenceStateMachine, MessageBus, ReplayKernel, SnapshotEngine, UnifiedBlackboard } from '../src/platform/creative/kernel';
import type { Capability, IntelligenceMetrics, IntelligencePlugin, KernelDependencies, KernelRunRequest, PluginContext, TimelineEvent } from '../src/platform/creative/kernel';

const dependencies = (): KernelDependencies => { let id = 0; return { nextId: () => `kernel-${++id}`, now: () => 1000, random: () => .5 }; };
const scope = { tenantId: 'tenant', projectId: 'project', userId: 'user' };
const request = (overrides = {}): KernelRunRequest => ({ ...scope, objective: 'Luxury campaign', prompt: 'Create a luxury brand campaign', workspace: { current: 'draft' }, reasoningPoints: 500, seed: 'fixed-seed', ...overrides });
const lifecycle: string[] = [];
const plugin = (id: string, kind: string, capabilities: readonly Capability[], dependencies: readonly string[] = [], publications = true): IntelligencePlugin => ({ id, kind, capabilities, dependencies, initialize: () => lifecycle.push(`${id}:initialize`), observe: (_context, messages) => lifecycle.push(`${id}:observe:${messages.length}`), reason: (_context, budget) => lifecycle.push(`${id}:reason:${budget}`), publish: () => { lifecycle.push(`${id}:publish`); return publications ? [{ topic: `${id}.result`, payload: { useful: true }, blackboard: { channel: kind === 'META' ? 'META' : 'DECISION', key: `${id}.result`, value: true } }] : []; }, sleep: () => lifecycle.push(`${id}:sleep`), replay: () => lifecycle.push(`${id}:replay`), shutdown: () => lifecycle.push(`${id}:shutdown`) });

test('message bus publishes an immutable message', () => { const bus = new MessageBus(dependencies()); const result = bus.publish({ ...scope, sessionId: 'session', topic: 'composition', sender: 'director', payload: { need: true } }); assert.equal(result.sequence, 0); assert.throws(() => (result.payload as Record<string, unknown>).need = false); });
test('message bus delivers topic subscriptions', () => { const bus = new MessageBus(dependencies()); const received: string[] = []; bus.subscribe('topic', 'studio', (message) => received.push(message.id)); const message = bus.publish({ ...scope, sessionId: 's', topic: 'topic', sender: 'director', payload: {} }); assert.deepEqual(received, [message.id]); });
test('message bus unsubscribe stops delivery', () => { const bus = new MessageBus(dependencies()); let received = 0; const unsubscribe = bus.subscribe('topic', 'studio', () => received++); unsubscribe(); bus.publish({ ...scope, sessionId: 's', topic: 'topic', sender: 'director', payload: {} }); assert.equal(received, 0); });
test('message history is scoped by tenant', () => { const bus = new MessageBus(dependencies()); bus.publish({ ...scope, sessionId: 's', topic: 'x', sender: 'a', payload: {} }); assert.deepEqual(bus.history('s', { ...scope, tenantId: 'other' }), []); });
test('message history filters topic', () => { const bus = new MessageBus(dependencies()); bus.publish({ ...scope, sessionId: 's', topic: 'x', sender: 'a', payload: {} }); bus.publish({ ...scope, sessionId: 's', topic: 'y', sender: 'a', payload: {} }); assert.equal(bus.history('s', scope, 'y').length, 1); });

test('blackboard accepts all seven channels', () => { const board = new UnifiedBlackboard(dependencies()); const channels = ['DECISION', 'DIRECTOR', 'STUDIO', 'META', 'EVOLUTION', 'RESEARCH', 'REFLECTION'] as const; channels.forEach((channel) => board.write({ ...scope, sessionId: 's', channel, author: 'plugin', key: channel, value: true })); assert.deepEqual(board.read('s', scope).map((entry) => entry.channel), channels); });
test('blackboard increments revisions', () => { const board = new UnifiedBlackboard(dependencies()); const first = board.write({ ...scope, sessionId: 's', channel: 'DECISION', author: 'd', key: 'mode', value: 'LOCAL' }); const second = board.write({ ...scope, sessionId: 's', channel: 'META', author: 'm', key: 'confidence', value: .8 }); assert.equal(first.revision, 1); assert.equal(second.revision, 2); });
test('blackboard latest finds newest key', () => { const board = new UnifiedBlackboard(dependencies()); board.write({ ...scope, sessionId: 's', channel: 'DECISION', author: 'd', key: 'mode', value: 'LOCAL' }); board.write({ ...scope, sessionId: 's', channel: 'DECISION', author: 'd', key: 'mode', value: 'AI' }); assert.equal(board.latest('s', scope, 'mode')?.value, 'AI'); });
test('blackboard restores historical revision', () => { const board = new UnifiedBlackboard(dependencies()); board.write({ ...scope, sessionId: 's', channel: 'DECISION', author: 'd', key: 'one', value: 1 }); board.write({ ...scope, sessionId: 's', channel: 'META', author: 'm', key: 'two', value: 2 }); assert.equal(board.snapshot('s', scope, 1).entries.length, 1); });
test('blackboard isolates project and user', () => { const board = new UnifiedBlackboard(dependencies()); board.write({ ...scope, sessionId: 's', channel: 'DECISION', author: 'd', key: 'x', value: 1 }); assert.equal(board.read('s', { ...scope, projectId: 'other' }).length, 0); assert.equal(board.read('s', { ...scope, userId: 'other' }).length, 0); });

test('capability registry registers and finds plugins', () => { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('director', 'DIRECTOR', ['VISION', 'BRAND'])); assert.deepEqual(registry.find(['BRAND']).map((item) => item.plugin.id), ['director']); });
test('capability selection requires every capability', () => { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('director', 'DIRECTOR', ['VISION'])); assert.deepEqual(registry.find(['VISION', 'BRAND']), []); });
test('disabled plugins are excluded', () => { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('director', 'DIRECTOR', ['VISION'])); registry.setStatus('director', 'DISABLED'); assert.deepEqual(registry.find(['VISION']), []); });
test('plugins can be disconnected', () => { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('director', 'DIRECTOR', ['VISION'])); registry.unregister('director'); assert.deepEqual(registry.all(), []); });
test('duplicate plugin IDs are rejected', () => { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('same', 'DIRECTOR', ['VISION'])); assert.throws(() => registry.register(plugin('same', 'STUDIO', ['DEBATE'])), /already registered/); });

test('dependency graph returns topological order', () => { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('director', 'DIRECTOR', ['BRAND'])); registry.register(plugin('studio', 'STUDIO', ['DEBATE'], ['director'])); registry.register(plugin('decision', 'DECISION', ['RANKING'], ['studio'])); const graph = new IntelligenceDependencyGraph(); assert.deepEqual(graph.topological(graph.build(registry.all())), ['director', 'studio', 'decision']); });
test('dependency graph rejects cycles', () => { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('a', 'A', ['BRAND'], ['b'])); registry.register(plugin('b', 'B', ['STYLE'], ['a'])); assert.throws(() => new IntelligenceDependencyGraph().build(registry.all()), /cycle/); });
test('dependency graph rejects missing dependency', () => { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('a', 'A', ['BRAND'], ['missing'])); assert.throws(() => new IntelligenceDependencyGraph().build(registry.all()), /Unknown plugin dependency/); });

test('cognitive budget allocates all points', () => { const result = new CognitiveBudget().allocate(500, ['director', 'decision', 'studio', 'meta', 'evolution'], { director: 120, decision: 90, studio: 160, meta: 60, evolution: 70 }); assert.equal(result.allocated, 500); assert.equal(result.remaining, 0); assert.equal(Object.values(result.shares).reduce((a, b) => a + b, 0), 500); });
test('cognitive budget is deterministic with rounding remainder', () => assert.deepEqual(new CognitiveBudget().allocate(10, ['a', 'b', 'c']), { total: 10, allocated: 10, remaining: 0, shares: { a: 3, b: 3, c: 4 } }));
test('cognitive budget rejects invalid values', () => assert.throws(() => new CognitiveBudget().allocate(-1, ['a']), /non-negative integer/));

test('scheduler selects portrait capabilities and their declared dependencies', () => { const registry = registryWithPlugins(); const result = new IntelligenceScheduler().plan({ objective: 'Portrait', capabilities: ['VISION', 'COMPOSITION', 'RANKING', 'VALIDATION'], registrations: registry.all(), reasoningPoints: 300 }); assert.deepEqual(result.map((item) => item.pluginId), ['director', 'composition', 'studio', 'decision', 'lighting', 'meta']); });
test('scheduler selects luxury intelligence modules', () => { const registry = registryWithPlugins(); const result = new IntelligenceScheduler().plan({ objective: 'Luxury campaign', capabilities: ['BRAND', 'STYLE', 'DEBATE', 'RANKING', 'VALIDATION', 'LEARNING'], registrations: registry.all(), reasoningPoints: 500 }); assert.deepEqual(result.map((item) => item.pluginId), ['director', 'brand', 'studio', 'decision', 'meta', 'evolution']); });
test('scheduler excludes unrelated active modules', () => { const registry = registryWithPlugins(); const result = new IntelligenceScheduler().plan({ objective: 'Rank', capabilities: ['RANKING'], registrations: registry.all(), reasoningPoints: 100 }); assert.deepEqual(result.map((item) => item.pluginId), ['director', 'studio', 'decision']); });
test('scheduler assigns iterations and budget', () => { const result = new IntelligenceScheduler().plan({ objective: 'Complex research campaign', capabilities: ['RESEARCH'], registrations: registryWithPlugins().all(), reasoningPoints: 160 }); assert.ok(result.every((item) => item.iterations >= 1 && item.budget >= 0)); });

IntelligenceStateMachine.states.slice(1).forEach((state, index) => test(`state transition ${index + 1} reaches ${state}`, () => { const machine = new IntelligenceStateMachine(dependencies()); const transition = machine.transition(IntelligenceStateMachine.states[index], state, 'reason', 'trigger', .8); assert.equal(transition.to, state); assert.equal(transition.createdAt, 1000); }));
test('state machine rejects skipped states', () => assert.throws(() => new IntelligenceStateMachine(dependencies()).transition('IDLE', 'REASON', 'skip', 'test', .5), /Invalid/));
test('state machine full run ends complete', () => { const run = new IntelligenceStateMachine(dependencies()).run('session'); assert.equal(run.length, 11); assert.equal(run.at(-1)?.to, 'COMPLETE'); });

test('timeline builds event graph', () => { const timeline = new EventTimeline(dependencies()); const goal = timeline.append({ ...scope, sessionId: 's', type: 'GOAL_CREATED' }); const decision = timeline.append({ ...scope, sessionId: 's', type: 'DECISION', parentIds: [goal.id] }); const graph = timeline.graph('s', scope); assert.deepEqual(graph.edges, [{ from: goal.id, to: decision.id }]); });
test('timeline is scope isolated', () => { const timeline = new EventTimeline(dependencies()); timeline.append({ ...scope, sessionId: 's', type: 'LEARNING' }); assert.deepEqual(timeline.history('s', { ...scope, tenantId: 'other' }), []); });

test('kernel creates a complete intelligence session', () => { lifecycle.length = 0; const kernel = kernelWithPlugins(); const result = kernel.run(request()); assert.equal(result.session.state, 'COMPLETE'); assert.equal(result.session.objective, 'Luxury campaign'); assert.equal(result.session.budget.total, 500); });
test('kernel runs common plugin lifecycle', () => { lifecycle.length = 0; kernelWithPlugins().run(request({ requestedCapabilities: ['RANKING'] })); assert.ok(lifecycle.some((item) => item.endsWith(':initialize'))); assert.ok(lifecycle.some((item) => item.includes(':observe:'))); assert.ok(lifecycle.some((item) => item.includes(':reason:'))); assert.ok(lifecycle.some((item) => item.endsWith(':publish'))); assert.ok(lifecycle.some((item) => item.endsWith(':sleep'))); });
test('kernel routes plugin output through bus and blackboard', () => { const kernel = kernelWithPlugins(); const result = kernel.run(request({ requestedCapabilities: ['RANKING'] })); assert.ok(kernel.bus.history(result.session.id, scope).length > 0); assert.ok(kernel.blackboard.read(result.session.id, scope).length > 1); });
test('kernel output is deeply immutable', () => { const result = kernelWithPlugins().run(request()); assert.throws(() => (result.plan as unknown[]).push({})); assert.throws(() => (result.session.workspace as Record<string, unknown>).current = 'changed'); });
test('kernel is deterministic for identical prompt DI workspace budget and seed', () => { const run = () => kernelWithPlugins().run(request()); assert.deepEqual(run(), run()); });
test('kernel shutdown invokes every plugin', () => { lifecycle.length = 0; const kernel = kernelWithPlugins(); const result = kernel.run(request({ requestedCapabilities: ['RANKING'] })); lifecycle.length = 0; kernel.shutdown(result.session.id, scope); assert.equal(lifecycle.filter((item) => item.endsWith(':shutdown')).length, kernel.registry.all().length); });
test('kernel validates complete scope', () => assert.throws(() => kernelWithPlugins().run(request({ tenantId: '' })), /scope/));
test('kernel validates objective and prompt', () => assert.throws(() => kernelWithPlugins().run(request({ objective: '' })), /Objective/));

test('snapshot engine captures and restores exact state', () => { const result = kernelWithPlugins().run(request()); const restored = new ReplayKernel().frames(result.snapshot, scope); assert.deepEqual(restored, result.replay); });
test('kernel replay enforces snapshot identity', () => { const kernel = kernelWithPlugins(); const result = kernel.run(request()); assert.throws(() => kernel.replay('wrong', result.session.id, 0, scope), /identity/); });
test('kernel replay enforces tenant isolation', () => { const kernel = kernelWithPlugins(); const result = kernel.run(request()); assert.throws(() => kernel.replay(result.snapshot.id, result.session.id, 0, { ...scope, tenantId: 'other' }), /scope/); });
test('kernel replay calls plugin replay lifecycle', () => { lifecycle.length = 0; const kernel = kernelWithPlugins(); const result = kernel.run(request()); lifecycle.length = 0; kernel.replay(result.snapshot.id, result.session.id, 0, scope); assert.equal(lifecycle.filter((item) => item.endsWith(':replay')).length, kernel.registry.all().length); });
test('replay frames include messages blackboard events states and snapshot', () => { const result = kernelWithPlugins().run(request()); assert.ok(result.replay.some((frame) => frame.message)); assert.ok(result.replay.some((frame) => frame.blackboard)); assert.ok(result.replay.some((frame) => frame.event)); assert.ok(result.replay.some((frame) => frame.state)); assert.equal(result.replay.at(-1)?.snapshotId, result.snapshot.id); });

test('health reports ten dimensions and overall', () => { const metrics: IntelligenceMetrics = { reasoning: .8, memory: .8, planning: .8, debate: .8, learning: .8, reflection: .8, simulation: .8, director: .8, decision: .8, meta: .8 }; const health = new IntelligenceHealthMonitor().evaluate(metrics); assert.equal(Object.keys(health.dimensions).length, 10); assert.equal(health.overall, .8); assert.equal(health.status, 'HEALTHY'); });
test('forbidden imports are absent', () => { const forbidden = [/from ['"].*\/decision/i, /from ['"].*\/director/i, /from ['"].*\/studio/i, /from ['"].*\/meta/i, /from ['"].*\/cognition/i, /from ['"].*\/evolution/i, /from ['"].*\/workflow/i, /from ['"].*\/runtime/i, /from ['"].*\/provider/i, /from ['"].*\/billing/i, /from ['"].*\/gateway/i, /from ['"].*\/application/i, /from ['"]react/i, /from ['"]@base44/i]; for (const file of readdirSync('src/platform/creative/kernel')) { if (!file.endsWith('.ts')) continue; const imports = readFileSync(join('src/platform/creative/kernel', file), 'utf8').split('\n').filter((line) => /^import|^export .* from/.test(line)).join('\n'); for (const pattern of forbidden) assert.equal(pattern.test(imports), false, `${file}: ${pattern}`); } });

function registryWithPlugins() { const registry = new CapabilityRegistry(dependencies()); registry.register(plugin('director', 'DIRECTOR', ['VISION', 'BRAND', 'STYLE'])); registry.register(plugin('composition', 'COMPOSITION', ['COMPOSITION'], ['director'])); registry.register(plugin('lighting', 'LIGHTING', ['VISION'], ['composition'])); registry.register(plugin('brand', 'BRAND', ['BRAND'], ['director'])); registry.register(plugin('studio', 'STUDIO', ['DEBATE', 'CONSENSUS'], ['director'])); registry.register(plugin('decision', 'DECISION', ['RANKING', 'OPTIMIZATION', 'SIMULATION'], ['studio'])); registry.register(plugin('meta', 'META', ['VALIDATION', 'GOVERNANCE', 'REFLECTION'], ['decision'])); registry.register(plugin('evolution', 'EVOLUTION', ['LEARNING'], ['meta'])); registry.register(plugin('research', 'RESEARCH', ['RESEARCH'], ['director'])); return registry; }
function kernelWithPlugins() { const kernel = new CreativeIntelligenceKernel(dependencies()); for (const registration of registryWithPlugins().all()) kernel.registry.register(registration.plugin); return kernel; }
