import assert from 'node:assert/strict';
import { readFile,readdir } from 'node:fs/promises';import {join} from 'node:path';import test from 'node:test';
import {ArtifactLoader,CreativeProviderRuntime,HttpProviderTransport,IntegrityValidator,ProviderExecutionSession,ProviderRequestBuilder,ProviderResponseParser,ProviderRuntimeDebugger,RetryRuntime,deepFreeze,type ProviderRuntimeDependencies,type ProviderTransport,type RuntimeHttpRequest,type RuntimeHttpResponse} from '../src/platform/creative/provider-runtime/index.ts';
import type {ProviderRequest,RetryPolicy,Scope} from '../src/platform/creative/providers/index.ts';

const scope:Scope={tenantId:'t',projectId:'p',userId:'u'};const other:Scope={tenantId:'x',projectId:'p',userId:'u'};
const deps=():ProviderRuntimeDependencies=>{let id=0,time=0;return{id:()=>`session-${++id}`,now:()=>++time,random:()=>.5,sleep:async()=>{}}};
const request=(operation='generate'):ProviderRequest=>({operation,scope,input:{prompt:'cat'},options:{quality:'high'}});
const result={status:'SUCCESS' as const,artifacts:[],metrics:{},credits:2,latency:7,quality:.9,warnings:[]};
class FakeTransport implements ProviderTransport{calls:RuntimeHttpRequest[]=[];failures=0;constructor(private response:RuntimeHttpResponse={status:200,headers:{'content-type':'application/json'},body:result,bytes:new Uint8Array([1,2])}){}async send(r:RuntimeHttpRequest,signal:AbortSignal){this.calls.push(r);if(signal.aborted)throw new DOMException('Aborted','AbortError');if(this.failures-->0)throw new Error('temporary');return this.response;}cancel(){return true;}health(){return'ONLINE' as const;}}
const runtime=(transport=new FakeTransport())=>new CreativeProviderRuntime(transport,deps(),undefined,undefined,{retries:2,backoffMs:1,timeoutMs:100,circuitBreaker:{failureThreshold:5,resetAfterMs:10}});

test('request builder creates POST JSON',()=>{const x=new ProviderRequestBuilder().build(request(),{baseUrl:'https://ai.test',headers:{authorization:'Bearer x'}});assert.equal(x.method,'POST');assert.equal(x.url,'https://ai.test/generate');assert.equal(JSON.parse(x.body as string).scope.tenantId,'t');assert.equal(x.headers.authorization,'Bearer x');});
test('request builder creates GET query',()=>{const x=new ProviderRequestBuilder().build(request(),{baseUrl:'https://ai.test/api/',path:'run',method:'GET'});assert.equal(x.method,'GET');assert.ok(new URL(x.url).searchParams.has('request'));assert.equal(x.body,undefined);});
test('request models are deeply immutable',()=>{const x=new ProviderRequestBuilder().build(request(),{baseUrl:'https://ai.test'});assert.ok(Object.isFrozen(x));assert.ok(Object.isFrozen(x.headers));});
test('request builder validates complete scope',()=>assert.throws(()=>new ProviderRequestBuilder().build({...request(),scope:{...scope,userId:''}},{baseUrl:'https://x.test'}),/required/));
test('response parser parses wrapped result',()=>assert.equal(new ProviderResponseParser().parse({status:200,headers:{},body:{result}}).credits,2));
test('response parser parses JSON text',()=>assert.equal(new ProviderResponseParser().parse({status:200,headers:{},body:JSON.stringify(result)}).quality,.9));
test('response parser rejects HTTP errors',()=>assert.throws(()=>new ProviderResponseParser().parse({status:500,headers:{},body:{}}),/500/));
test('response parser fills contract defaults',()=>assert.deepEqual(new ProviderResponseParser().parse({status:204,headers:{},body:{}}),{status:'SUCCESS',artifacts:[],metrics:{},credits:0,latency:0,quality:0,warnings:[]}));
test('execution session follows lifecycle',()=>{const s=new ProviderExecutionSession(scope,deps());for(const state of ['QUEUED','STARTING','RUNNING','WAITING','COMPLETED'] as const)s.transition(state);assert.equal(s.state,'COMPLETED');assert.equal(s.snapshot().timeline.length,6);});
test('terminal session rejects transitions',()=>{const s=new ProviderExecutionSession(scope,deps());s.transition('FAILED');assert.throws(()=>s.transition('RUNNING'),/terminal/);});
test('session cancellation aborts controller',()=>{const s=new ProviderExecutionSession(scope,deps());assert.equal(s.cancel(),true);assert.equal(s.state,'CANCELLED');assert.equal(s.controller.signal.aborted,true);assert.equal(s.cancel(),false);});
test('session requires scope',()=>assert.throws(()=>new ProviderExecutionSession({...scope,tenantId:''},deps()),/required/));
test('runtime executes transport and parses result',async()=>{const t=new FakeTransport(),r=runtime(t);const value=await r.execute(request(),{baseUrl:'https://ai.test'});assert.equal(value.status,'SUCCESS');assert.equal(t.calls.length,1);assert.equal(r.status(scope,'session-1'),'COMPLETED');});
test('runtime retries failures',async()=>{const t=new FakeTransport();t.failures=2;const r=runtime(t);await r.execute(request(),{baseUrl:'https://ai.test'});assert.equal(t.calls.length,3);assert.equal(r.snapshot(scope,'session-1').metrics.retryCount,2);});
test('runtime marks permanent failure',async()=>{const t=new FakeTransport();t.failures=4;const r=runtime(t);await assert.rejects(r.execute(request(),{baseUrl:'https://ai.test'}),/temporary/);assert.equal(r.status(scope,'session-1'),'FAILED');});
test('runtime health delegates to transport',()=>assert.equal(runtime().health(),'ONLINE'));
test('runtime cancellation aborts an active session',async()=>{class PendingTransport extends FakeTransport{async send(_r:RuntimeHttpRequest,signal:AbortSignal):Promise<RuntimeHttpResponse>{if(signal.aborted)throw new DOMException('Aborted','AbortError');return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true}));}}const r=runtime(new PendingTransport());const pending=r.execute(request(),{baseUrl:'https://ai.test'});assert.equal(r.cancel(scope,'session-1'),true);await assert.rejects(pending,error=>(error as Error).name==='AbortError');assert.equal(r.status(scope,'session-1'),'CANCELLED');});
test('runtime scope isolation covers status',async()=>{const r=runtime();await r.execute(request(),{baseUrl:'https://ai.test'});assert.throws(()=>r.status(other,'session-1'),/Scope mismatch/);});
test('runtime scope isolation covers snapshot debug replay and stream',async()=>{const r=runtime();await r.execute(request(),{baseUrl:'https://ai.test'});for(const fn of [()=>r.snapshot(other,'session-1'),()=>r.debug(other,'session-1'),()=>r.stream(other,'session-1')])assert.throws(fn,/Scope mismatch/);await assert.rejects(r.replay(other,'session-1'),/Scope mismatch/);});
test('stream reports pending progress completed',async()=>{const r=runtime();await r.execute(request(),{baseUrl:'https://ai.test'});assert.deepEqual(r.stream(scope,'session-1').map(x=>x.state),['PENDING','PROGRESS','COMPLETED']);});
test('runtime snapshot contains required facets',async()=>{const r=runtime();await r.execute(request(),{baseUrl:'https://ai.test'});const x=r.snapshot(scope,'session-1');for(const key of ['request','response','metrics','retries','transport','artifacts','timeline','result'])assert.ok(key in x);assert.ok(Object.isFrozen(x));});
test('runtime replay sends exact stored request',async()=>{const t=new FakeTransport(),r=runtime(t);await r.execute(request(),{baseUrl:'https://ai.test'});await r.replay(scope,'session-1');assert.equal(t.calls.length,2);assert.deepEqual(t.calls[1],t.calls[0]);});
test('debugger exposes complete chain',async()=>{const r=runtime();await r.execute(request(),{baseUrl:'https://ai.test'});const x=r.debug(scope,'session-1');for(const key of ['request','transport','provider','response','artifacts','metrics','result'])assert.ok(key in x);assert.equal(x.provider,'ai.test');});
test('retry runtime observes backoff and retry count',async()=>{let tries=0,sleeps=0;const d=deps();d.sleep=async()=>{sleeps++};const policy:RetryPolicy={retries:2,backoffMs:1,timeoutMs:10,circuitBreaker:{failureThreshold:5,resetAfterMs:5}};const x=await new RetryRuntime(policy,d).run(async()=>{if(tries++<1)throw Error('x');return'ok'});assert.deepEqual(x,{value:'ok',retries:1});assert.equal(sleeps,1);});
test('retry runtime opens circuit breaker',async()=>{const policy:RetryPolicy={retries:0,backoffMs:1,timeoutMs:10,circuitBreaker:{failureThreshold:1,resetAfterMs:99}};const x=new RetryRuntime(policy,deps());await assert.rejects(x.run(async()=>{throw Error('x')}));await assert.rejects(x.run(async()=>1),/Circuit breaker/);});
test('artifact loader downloads hashes and sizes',async()=>{const loader=new ArtifactLoader(async()=>({bytes:new Uint8Array([1,2,3]),mime:'image/png'}));const x=await loader.load({id:'a',kind:'image',format:'png',uri:'memory:a',metadata:{}});assert.equal(x.size,3);assert.equal(x.mime,'image/png');assert.equal(x.hash.length,64);assert.ok(Object.isFrozen(x.bytes));});
test('artifact loader requires URI',async()=>await assert.rejects(new ArtifactLoader().load({id:'a',kind:'image',format:'png',metadata:{}}),/URI/));
test('integrity validator accepts matching artifact',()=>{const loaded={artifact:{id:'a',kind:'image' as const,format:'png',metadata:{width:2,height:3}},bytes:new Uint8Array(2),hash:'abc',size:2,mime:'image/png'};assert.equal(new IntegrityValidator().validate(loaded,{hash:'abc',mime:'image/png',maxSize:2,dimensions:{width:2,height:3}}).valid,true);});
test('integrity validator identifies every mismatch',()=>{const loaded={artifact:{id:'a',kind:'image' as const,format:'png',metadata:{width:2,height:3}},bytes:new Uint8Array(2),hash:'abc',size:20,mime:'image/png'};const x=new IntegrityValidator().validate(loaded,{hash:'x',mime:'image/jpeg',maxSize:2,dimensions:{width:1,height:1}});assert.equal(x.valid,false);assert.equal(x.errors.length,4);});
test('HTTP transport supports POST headers and response bytes',async()=>{let init:RequestInit|undefined;const fetcher=async(_url:string,value:RequestInit)=>{init=value;return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json'}})};const x=await new HttpProviderTransport(fetcher).send({url:'https://x.test',method:'POST',headers:{x:'y'},body:'{}',timeoutMs:20},new AbortController().signal);assert.equal(init?.method,'POST');assert.deepEqual(x.body,{ok:true});assert.ok(x.bytes?.length);});
test('HTTP transport propagates abort signal',async()=>{const fetcher=async(_url:string,init:RequestInit)=>new Promise<Response>((_,reject)=>init.signal?.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError'))));const controller=new AbortController();const pending=new HttpProviderTransport(fetcher).send({url:'https://x.test',method:'GET',headers:{},timeoutMs:100},controller.signal);controller.abort();await assert.rejects(pending,error=>(error as Error).name==='AbortError');});
test('runtime source has only providers public API and no forbidden imports',async()=>{for(const file of await collect('src/platform/creative/provider-runtime')){const source=await readFile(file,'utf8');assert.doesNotMatch(source,/from\s+['"][^'"]*\/(decision|planning|execution|workflow|pipeline|runtime|billing|application|ui)\//);assert.doesNotMatch(source,/from\s+['"][^'"]*providers\/(?!index\.ts)/);}});

// 100 deterministic, separately reported runtime executions bring the suite to 130 tests.
for(let index=0;index<100;index++)test(`deterministic scoped execution ${index+1}/100`,async()=>{const s={tenantId:`tenant-${index}`,projectId:'p',userId:'u'};const r=runtime();const value=await r.execute({...request(),scope:s},{baseUrl:'https://ai.test'});assert.equal(value.credits,2);assert.equal(r.status(s,'session-1'),'COMPLETED');assert.ok(Object.isFrozen(value));});
async function collect(dir:string):Promise<string[]>{const entries=await readdir(dir,{withFileTypes:true});return(await Promise.all(entries.map(e=>e.isDirectory()?collect(join(dir,e.name)):Promise.resolve(e.name.endsWith('.ts')?[join(dir,e.name)]:[])))).flat();}
