import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import { CreativeIntelligenceRuntime, DependencyCache, RuntimeDeterminismValidator, RuntimeExecutionGraphBuilder, RuntimeInvariantValidator, RuntimeOptimizer, RuntimeProfiler, RuntimeSandbox, TransactionalBlackboard, stableHash } from '../src/platform/creative/runtime';
import type { Capability, IntelligencePlugin, PluginContext } from '../src/platform/creative/kernel';
import type { RuntimeCreateRequest, RuntimeDependencies } from '../src/platform/creative/runtime';

const dependencies = (): RuntimeDependencies => { let id = 0; let time = 1000; return { nextId: () => `runtime-${++id}`, now: () => time++, random: () => .5 }; };
const fixedDependencies = (): RuntimeDependencies => { let id = 0; return { nextId: () => `runtime-${++id}`, now: () => 1000, random: () => .5 }; };
const scope = { tenantId: 'tenant', projectId: 'project', userId: 'user' };
const request = (overrides = {}): RuntimeCreateRequest => ({ ...scope, objective: 'Luxury campaign', prompt: 'Create campaign', seed: 'seed', budget: 500, capabilities: ['BRAND', 'COST', 'SIMULATION'], initialState: { identity: 'keep' }, ...overrides });
const calls: string[] = [];
const makePlugin = (id: string, capabilities: readonly Capability[], pluginDependencies: readonly string[] = [], fail = () => false): IntelligencePlugin => ({ id, kind: id.toUpperCase(), capabilities, dependencies: pluginDependencies, initialize: () => calls.push(`${id}:initialize`), observe: (_context, messages) => calls.push(`${id}:observe:${messages.length}`), reason: () => { calls.push(`${id}:reason`); if (fail()) throw new Error(`${id} failed`); }, publish: () => [{ topic: `${id}.output`, payload: { id }, blackboard: { channel: 'DECISION', key: `${id}.result`, value: { useful: true } } }], sleep: () => calls.push(`${id}:sleep`), replay: () => calls.push(`${id}:replay`), shutdown: () => calls.push(`${id}:shutdown`) });
const runtime = (deps = dependencies()) => { const value = new CreativeIntelligenceRuntime(deps); value.register(makePlugin('director', ['BRAND']), .8); value.register(makePlugin('cost', ['COST']), .7); value.register(makePlugin('simulation', ['SIMULATION'], ['director']), .6); value.register(makePlugin('composition', ['COMPOSITION']), .5); return value; };

test('runtime creates a scoped session', () => { const value = runtime(); const session = value.createSession(request()); assert.equal(session.status, 'CREATED'); assert.equal(session.objective, 'Luxury campaign'); assert.deepEqual({ tenantId: session.tenantId, projectId: session.projectId, userId: session.userId }, scope); });
test('runtime session stores deterministic graph budget and seed', () => { const session = runtime(fixedDependencies()).createSession(request()); assert.equal(session.seed, 'seed'); assert.equal(session.budget, 500); assert.equal(session.graph.id, 'runtime-1'); });
test('runtime rejects incomplete scope', () => assert.throws(() => runtime().createSession(request({ tenantId: '' })), /scope/));
test('runtime rejects invalid budget', () => assert.throws(() => runtime().createSession(request({ budget: -1 })), /budget/));
test('runtime rejects empty objective', () => assert.throws(() => runtime().createSession(request({ objective: '' })), /Objective/));

const coreKinds = ['GOAL', 'INTENT', 'HYPOTHESIS', 'DEBATE', 'SIMULATION', 'REFLECTION', 'DECISION', 'COMMIT'] as const;
coreKinds.forEach((kind) => test(`execution graph contains ${kind}`, () => { const graph = new RuntimeExecutionGraphBuilder(dependencies()).build([]); assert.ok(graph.nodes.some((node) => node.kind === kind)); }));
test('execution graph is a valid DAG', () => { const builder = new RuntimeExecutionGraphBuilder(dependencies()); const graph = builder.build([makePlugin('a', ['BRAND']), makePlugin('b', ['COST'], ['a'])]); const validator = new RuntimeInvariantValidator(); validator.validateGraph(graph); assert.ok(validator.topological(graph).indexOf('plugin:a') < validator.topological(graph).indexOf('plugin:b')); });
test('execution graph rejects plugin dependency cycle', () => { const graph = new RuntimeExecutionGraphBuilder(dependencies()).build([makePlugin('a', ['BRAND'], ['b']), makePlugin('b', ['COST'], ['a'])]); assert.throws(() => new RuntimeInvariantValidator().validateGraph(graph), /cycle/); });
test('execution graph rejects orphan dependencies', () => { const graph = new RuntimeExecutionGraphBuilder(dependencies()).build([makePlugin('a', ['BRAND'], ['missing'])]); assert.throws(() => new RuntimeInvariantValidator().validateGraph(graph), /Orphan/); });

test('runtime executes graph to completion', () => { calls.length = 0; const value = runtime(); const session = value.createSession(request()); const result = value.run(session.id, scope); assert.equal(result.session.status, 'COMPLETED'); assert.equal(result.session.completedNodeIds.length, result.session.graph.nodes.length); });
test('runtime executes common plugin lifecycle in sandbox', () => { calls.length = 0; const value = runtime(); const session = value.createSession(request({ capabilities: ['BRAND'] })); value.run(session.id, scope); assert.deepEqual(calls.filter((call) => call.startsWith('director:')), ['director:initialize', 'director:observe:0', 'director:reason', 'director:sleep']); });
test('lazy evaluation skips unrequested composition', () => { calls.length = 0; const value = runtime(); const session = value.createSession(request({ capabilities: ['BRAND'] })); const result = value.run(session.id, scope); assert.equal(calls.some((call) => call.startsWith('composition:')), false); assert.ok(result.events.some((event) => event.type === 'NODE_SKIPPED' && event.pluginId === 'composition')); });
test('disabled plugin is never executed', () => { calls.length = 0; const value = runtime(); value.setPluginEnabled('director', false); const session = value.createSession(request({ capabilities: ['BRAND'] })); value.run(session.id, scope); assert.equal(calls.some((call) => call.startsWith('director:')), false); });
test('sandbox gives plugin immutable context', () => { let frozen = false; const plugin = makePlugin('safe', ['BRAND']); const wrapped = { ...plugin, initialize: (context: PluginContext) => { frozen = Object.isFrozen(context); } }; new RuntimeSandbox(dependencies()).execute(wrapped, { ...scope, sessionId: 's', objective: 'x' }, [], 10); assert.equal(frozen, true); });

test('runtime pauses after a requested node', () => { const value = runtime(); const session = value.createSession(request()); const result = value.run(session.id, scope, { untilNodeId: 'debate' }); assert.equal(result.session.status, 'PAUSED'); assert.ok(result.session.completedNodeIds.includes('debate')); });
test('runtime resumes paused execution', () => { const value = runtime(); const session = value.createSession(request()); value.run(session.id, scope, { untilNodeId: 'debate' }); assert.equal(value.resume(session.id, scope).session.status, 'COMPLETED'); });
test('runtime public pause supports created session', () => { const value = runtime(); const session = value.createSession(request()); assert.equal(value.pause(session.id, scope).status, 'PAUSED'); });
test('runtime rejects pause after completion', () => { const value = runtime(); const session = value.createSession(request()); value.run(session.id, scope); assert.throws(() => value.pause(session.id, scope), /active/); });
test('runtime shutdown calls plugin shutdown', () => { calls.length = 0; const value = runtime(); const session = value.createSession(request()); value.shutdown(session.id, scope); assert.equal(calls.filter((call) => call.endsWith(':shutdown')).length, 4); });
test('shutdown session cannot run again', () => { const value = runtime(); const session = value.createSession(request()); value.shutdown(session.id, scope); assert.throws(() => value.run(session.id, scope), /shutdown/); });

test('dependency cache returns unchanged output', () => { const cache = new DependencyCache(); cache.put('brand', { intent: 'luxury' }, [], scope, 1); assert.equal(cache.get('brand', { intent: 'luxury' }, scope)?.hits, 1); });
test('dependency cache isolates tenant', () => { const cache = new DependencyCache(); cache.put('brand', { intent: 'luxury' }, [], scope, 1); assert.equal(cache.get('brand', { intent: 'luxury' }, { ...scope, tenantId: 'other' }), undefined); });
test('dependency cache invalidates one plugin', () => { const cache = new DependencyCache(); cache.put('brand', {}, [], scope, 1); cache.put('cost', {}, [], scope, 1); assert.equal(cache.invalidate('brand', scope), 1); assert.ok(cache.get('cost', {}, scope)); });
test('stable hash ignores object key order', () => assert.equal(stableHash({ a: 1, nested: { x: 2, y: 3 } }), stableHash({ nested: { y: 3, x: 2 }, a: 1 })));
test('second incremental run skips unchanged Brand', () => { calls.length = 0; const value = runtime(); const session = value.createSession(request()); value.run(session.id, scope); calls.length = 0; value.run(session.id, scope, { changedKeys: ['budget'] }); assert.equal(calls.some((call) => call.startsWith('director:')), false); assert.equal(calls.some((call) => call.startsWith('cost:')), true); });
test('repeated plugin evaluation uses cache', () => { const value = runtime(); const session = value.createSession(request()); value.run(session.id, scope); const result = value.run(session.id, scope, { changedKeys: ['unrelated'] }); assert.ok(result.metrics.skippedNodes > 0); });

test('blackboard transaction commit is atomic', () => { const board = new TransactionalBlackboard(dependencies()); const transaction = board.begin('s', scope); board.write(transaction.id, { ...scope, sessionId: 's', key: 'a', value: 1, author: 'x' }); board.write(transaction.id, { ...scope, sessionId: 's', key: 'b', value: 2, author: 'x' }); assert.equal(board.read('s', scope).length, 0); assert.equal(board.commit(transaction.id).length, 2); });
test('blackboard rollback discards staged writes', () => { const board = new TransactionalBlackboard(dependencies()); const transaction = board.begin('s', scope); board.write(transaction.id, { ...scope, sessionId: 's', key: 'a', value: 1, author: 'x' }); board.rollback(transaction.id); assert.deepEqual(board.read('s', scope), []); });
test('blackboard transaction rejects scope violation', () => { const board = new TransactionalBlackboard(dependencies()); const transaction = board.begin('s', scope); assert.throws(() => board.write(transaction.id, { ...scope, tenantId: 'other', sessionId: 's', key: 'a', value: 1, author: 'x' }), /scope/); });
test('blackboard detects concurrent transaction conflict', () => { const board = new TransactionalBlackboard(dependencies()); const one = board.begin('s', scope); const two = board.begin('s', scope); board.write(one.id, { ...scope, sessionId: 's', key: 'a', value: 1, author: 'x' }); board.write(two.id, { ...scope, sessionId: 's', key: 'b', value: 2, author: 'x' }); board.commit(one.id); assert.throws(() => board.commit(two.id), /conflict/); });
test('committed blackboard data is deeply immutable', () => { const board = new TransactionalBlackboard(dependencies()); const transaction = board.begin('s', scope); board.write(transaction.id, { ...scope, sessionId: 's', key: 'a', value: { nested: true }, author: 'x' }); const entry = board.commit(transaction.id)[0]; assert.throws(() => (entry.value as Record<string, boolean>).nested = false); });

test('checkpoint captures current runtime state', () => { const value = runtime(); const session = value.createSession(request()); value.run(session.id, scope, { untilNodeId: 'debate' }); const checkpoint = value.checkpoint(session.id, scope, 'After Debate'); assert.equal(checkpoint.label, 'After Debate'); assert.equal(checkpoint.session.status, 'PAUSED'); });
test('rollback restores checkpoint session', () => { const value = runtime(); const session = value.createSession(request()); value.run(session.id, scope, { untilNodeId: 'debate' }); const checkpoint = value.checkpoint(session.id, scope, 'After Debate'); value.resume(session.id, scope); const restored = value.rollback(session.id, scope, checkpoint.id); assert.equal(restored.session.status, 'PAUSED'); assert.deepEqual(restored.session.completedNodeIds, checkpoint.session.completedNodeIds); });
test('checkpoint access is scope isolated', () => { const value = runtime(); const session = value.createSession(request()); const checkpoint = value.checkpoint(session.id, scope, 'Start'); assert.throws(() => value.rollback(session.id, { ...scope, projectId: 'other' }, checkpoint.id), /scope/); });
test('runtime recovers a failed session and continues', () => { let fails = true; const value = new CreativeIntelligenceRuntime(dependencies()); value.register(makePlugin('unstable', ['BRAND'], [], () => { const current = fails; fails = false; return current; })); const session = value.createSession(request({ capabilities: ['BRAND'] })); assert.equal(value.run(session.id, scope).session.status, 'FAILED'); assert.equal(value.recover(session.id, scope).session.status, 'COMPLETED'); });

test('runtime metrics count blackboard writes and messages', () => { const value = runtime(); const session = value.createSession(request()); const result = value.run(session.id, scope); assert.ok(result.metrics.blackboardWrites > 0); assert.ok(result.metrics.messages > 0); });
test('runtime profiler identifies low-value plugin', () => { const profile = new RuntimeProfiler().profile([{ pluginId: 'x', elapsed: 1, outputCount: 0, valueScore: .1 }]); assert.equal(profile[0].classification, 'LOW_VALUE'); });
test('runtime profiler identifies bottleneck', () => { const profile = new RuntimeProfiler().profile([{ pluginId: 'x', elapsed: 150, outputCount: 1, valueScore: .8 }]); assert.equal(profile[0].classification, 'BOTTLENECK'); });
test('runtime trace connects plugin state blackboard message reasoning output', () => { const value = runtime(); const session = value.createSession(request()); const result = value.run(session.id, scope); assert.ok(result.trace.length > 0); assert.ok(result.trace.some((entry) => entry.plugin)); assert.ok(result.trace.some((entry) => entry.outputKey)); });
test('debug console contains all public sections', () => { const value = runtime(); const session = value.createSession(request()); value.run(session.id, scope); const debug = value.debug(session.id, scope); ['Session', 'Plugin', 'Messages', 'Reasoning', 'State', 'Budget', 'Timeline', 'Replay'].forEach((section) => assert.match(debug, new RegExp(section))); });

test('event stream sequence is valid', () => { const value = runtime(); const session = value.createSession(request()); const result = value.run(session.id, scope); new RuntimeInvariantValidator().validateEvents(result.events); });
test('blackboard invariant detects invalid revision', () => assert.throws(() => new RuntimeInvariantValidator().validateBlackboard([{ revision: 2, key: 'x' }]), /Invalid/));
test('event invariant detects duplicates', () => assert.throws(() => new RuntimeInvariantValidator().validateEvents([{ id: 'same', sequence: 0 }, { id: 'same', sequence: 1 }]), /Duplicated/));
test('event invariant detects invalid sequence', () => assert.throws(() => new RuntimeInvariantValidator().validateEvents([{ id: 'a', sequence: 1 }]), /sequence/));
test('optimizer skips irrelevant capability', () => { const node = new RuntimeExecutionGraphBuilder(dependencies()).build([makePlugin('brand', ['BRAND'])]).nodes.find((item) => item.pluginId)!; assert.equal(new RuntimeOptimizer().shouldRun(node, { requestedCapabilities: ['COST'], changedKeys: [], hasCache: false, plugin: { plugin: makePlugin('brand', ['BRAND']), enabled: true, valueScore: .5 } }).run, false); });

Array.from({ length: 8 }, (_, index) => index).forEach((index) => test(`determinism validation sample ${index + 1}`, () => { const validator = new RuntimeDeterminismValidator(); assert.equal(validator.compare({ seed: 'same', index }, { index, seed: 'same' }).deterministic, true); }));
test('runtime output is deterministic for same session inputs and DI', () => { const run = () => { const value = runtime(fixedDependencies()); const session = value.createSession(request()); return value.run(session.id, scope); }; assert.deepEqual(run(), run()); });
test('determinism validator detects changed output', () => assert.equal(new RuntimeDeterminismValidator().compare({ value: 1 }, { value: 2 }).deterministic, false));
test('runtime snapshots are deeply immutable', () => { const value = runtime(); const session = value.createSession(request()); const snapshot = value.run(session.id, scope); assert.throws(() => (snapshot.events as unknown[]).push({})); assert.throws(() => (snapshot.session.completedNodeIds as string[]).push('x')); });
test('session inspect enforces tenant isolation', () => { const value = runtime(); const session = value.createSession(request()); assert.throws(() => value.inspect(session.id, { ...scope, tenantId: 'other' }), /scope/); });
test('session inspect enforces project isolation', () => { const value = runtime(); const session = value.createSession(request()); assert.throws(() => value.inspect(session.id, { ...scope, projectId: 'other' }), /scope/); });
test('session inspect enforces user isolation', () => { const value = runtime(); const session = value.createSession(request()); assert.throws(() => value.inspect(session.id, { ...scope, userId: 'other' }), /scope/); });
test('all IDs time and randomness use RuntimeDependencies', () => { const value = new CreativeIntelligenceRuntime({ nextId: () => 'fixed', now: () => 77, random: () => .25 }); const session = value.createSession(request()); assert.equal(session.id, 'fixed'); assert.equal(session.createdAt, 77); });
test('runtime imports only kernel public contracts', () => { const forbidden = [/from ['"].*\/decision/i, /from ['"].*\/director/i, /from ['"].*\/studio/i, /from ['"].*\/meta/i, /from ['"].*\/cognition/i, /from ['"].*\/evolution/i, /from ['"].*\/workflow/i, /from ['"].*\/provider/i, /from ['"].*\/billing/i, /from ['"].*\/gateway/i, /from ['"].*\/application/i, /from ['"]react/i, /from ['"]@retired-runtime/i]; for (const file of readdirSync('src/platform/creative/runtime')) { if (!file.endsWith('.ts')) continue; const imports = readFileSync(join('src/platform/creative/runtime', file), 'utf8').split('\n').filter((line) => /^import|^export .* from/.test(line)).join('\n'); for (const pattern of forbidden) assert.equal(pattern.test(imports), false, `${file}: ${pattern}`); } });
