import assert from 'node:assert/strict'; import { readFileSync, readdirSync } from 'node:fs'; import { join } from 'node:path'; import test from 'node:test';
import { CognitiveComplexityEstimator, CognitiveResourceAllocator, CreativeIntelligenceHealthMonitor, CreativeIntelligenceScoreV3, DecisionStabilityAnalyzer, ExplainabilityValidator, HallucinationDetector, HeuristicGovernanceModel, KnowledgeCoverageAnalyzer, MetaCognitiveController, MetaConfidenceEngine, SelfMonitoringEngine, ThinkingBudgetManager } from '../src/platform/creative/meta';
const deps = () => { let n = 0; return { id: () => `id-${++n}`, now: () => 12345 }; };
const input = (overrides: Record<string, unknown> = {}) => ({ tenantId: 't', projectId: 'p', userId: 'u', prompt: 'Luxury fashion campaign', intent: 'campaign', goals: ['quality', 'brand'], domain: 'fashion', difficulty: .8, risk: .4, budget: 70, knownDependencies: ['camera'], observations: [{ source: 'DIRECTOR' as const, strategy: 'AI' as const, confidence: .88, reasons: ['brand evidence', 'visual evidence'], dependencies: ['camera'] }, { source: 'STUDIO' as const, strategy: 'AI' as const, confidence: .8, reasons: ['expert consensus'] }, { source: 'DECISION' as const, strategy: 'LOCAL' as const, confidence: .55, reasons: ['cost constraint'] }], ...overrides });

[['Brightness', .05], ['яркость', .05], ['Luxury campaign', .96], ['campaign Luxury', .96], ['simple crop', .22], ['research strategy', .42], ['one', .185], ['a b c d', .29]].forEach(([prompt, expected], i) => test(`complexity deterministic ${i + 1}`, () => assert.equal(new CognitiveComplexityEstimator().estimate(prompt as string), expected)));

const governanceCases: Array<[Record<string, unknown>, string]> = [[{ budget: 2 }, 'MINIMUM_COST'], [{ risk: .9 }, 'SCIENTIFIC'], [{ prompt: 'medical radiology', domain: 'medical' }, 'RESEARCH'], [{ difficulty: .95 }, 'MAXIMUM_QUALITY'], [{ difficulty: .1 }, 'FAST'], [{ difficulty: .5 }, 'BALANCED'], [{ requestedMode: 'EXPERIMENTAL' }, 'EXPERIMENTAL'], [{ requestedMode: 'PROFESSIONAL' }, 'PROFESSIONAL']];
governanceCases.forEach(([change, expected], i) => test(`governance mode ${i + 1}`, () => { const value = input(change); const coverage = new KnowledgeCoverageAnalyzer().analyze(value.domain, value.prompt); assert.equal(new HeuristicGovernanceModel().select(value, coverage), expected); }));

[['luxury fashion', 'KNOWN', .98], ['medical image', 'UNKNOWN', .15], ['unfamiliar object', 'PARTIALLY_KNOWN', .55], ['impossible request', 'IMPOSSIBLE', 0]].forEach(([prompt, state, score], i) => test(`knowledge and unknown classification ${i + 1}`, () => { const result = new KnowledgeCoverageAnalyzer().analyze(undefined, prompt as string); assert.equal(result.state, state); assert.equal(result.score, score); }));

Array.from({ length: 8 }, (_, i) => i).forEach((i) => test(`thinking budget bounds and monotonic case ${i + 1}`, () => { const manager = new ThinkingBudgetManager(); const low = manager.allocate({ budget: i * 10, risk: .1, difficulty: .1, goals: [] }, .9); const high = manager.allocate({ budget: 100, risk: .9, difficulty: .9, goals: ['x'] }, .2); assert.ok(low.iterations <= high.iterations); assert.ok(high.iterations <= 20); assert.ok(high.debateRounds <= 6); }));

[['Passport photo', [['QUALITY', .8], ['COMPOSITION', .2]]], ['Luxury campaign', [['DIRECTOR', .4], ['BRAND', .3], ['COMPOSITION', .2], ['COST', .1]]], ['crop image', [['DECISION', .5], ['QUALITY', .3], ['COST', .2]]]].forEach(([prompt, expected], i) => test(`resource allocation ${i + 1}`, () => { const result = new CognitiveResourceAllocator().allocate(prompt as string); assert.deepEqual(result.map((x) => [x.resource, x.share]), expected); assert.ok(Math.abs(result.reduce((sum, x) => sum + x.share, 0) - 1) < Number.EPSILON); }));

const hallucinationInputs: Array<[Record<string, unknown>, string]> = [[{ observations: [{ source: 'DECISION', strategy: 'AI', confidence: .7, reasons: [] }] }, 'UNSUPPORTED_CONCLUSION'], [{ goals: [], observations: [{ source: 'DECISION', strategy: 'AI', confidence: .7, reasons: ['reason'], operations: ['1', '2', '3', '4'] }] }, 'EXTRA_OPERATION'], [{ observations: [{ source: 'DECISION', strategy: 'AI', confidence: .7, reasons: ['reason'], dependencies: ['unknown'] }] }, 'UNKNOWN_DEPENDENCY'], [{ observations: [{ source: 'DECISION', strategy: 'AI', confidence: .95, reasons: ['short'] }] }, 'OVERCONFIDENCE'], [{ observations: [{ source: 'DECISION', strategy: 'AI', confidence: .7, reasons: ['probably works'] }] }, 'BOLD_ASSUMPTION']];
hallucinationInputs.forEach(([change, code], i) => test(`hallucination detection ${i + 1}`, () => assert.ok(new HallucinationDetector().detect(input(change) as never).some((x) => x.code === code))));

Array.from({ length: 5 }, (_, i) => i + 1).forEach((count) => test(`meta confidence confidence-of-confidence ${count}`, () => { const observations = Array.from({ length: count }, (_, i) => ({ source: 'DECISION' as const, strategy: 'LOCAL' as const, confidence: .7 + i * .01, reasons: ['one', 'two'] })); const result = new MetaConfidenceEngine().calculate(observations, .9, 0, 0); assert.ok(result.confidenceOfConfidence <= 1); assert.ok(result.confidenceOfConfidence > .7); assert.equal(result.evidence, 1); }));

Array.from({ length: 12 }, (_, i) => i).forEach((i) => test(`meta controller integration ${i + 1}`, () => { const first = new MetaCognitiveController(deps()).analyze(input()); const second = new MetaCognitiveController(deps()).analyze(input()); assert.deepEqual(first, second); assert.equal(first.trustedSource, 'DIRECTOR'); assert.equal(first.finalStrategy, 'AI'); assert.equal(first.timeline.length, 11); assert.equal(first.score.version, 3); assert.match(first.debugSnapshot, /Creative Intelligence Score/); }));

test('deep immutability protects nested output', () => { const result = new MetaCognitiveController(deps()).analyze(input()); assert.throws(() => (result.timeline as unknown[]).push({})); assert.throws(() => (result.allocation[0] as { share: number }).share = 0); assert.throws(() => (result.health.dimensions as Record<string, number>).meta = 0); });
test('replay reproduces thought process', () => { const controller = new MetaCognitiveController(deps()); const result = controller.analyze(input()); assert.deepEqual(controller.replay(result.id, { tenantId: 't', projectId: 'p', userId: 'u' }), result); });
test('tenant isolation', () => { const controller = new MetaCognitiveController(deps()); const result = controller.analyze(input()); assert.throws(() => controller.replay(result.id, { tenantId: 'other', projectId: 'p', userId: 'u' }), /scope/); });
test('project isolation', () => { const controller = new MetaCognitiveController(deps()); const result = controller.analyze(input()); assert.throws(() => controller.replay(result.id, { tenantId: 't', projectId: 'other', userId: 'u' }), /scope/); });
test('user isolation and scoped audit', () => { const controller = new MetaCognitiveController(deps()); controller.analyze(input()); assert.equal(controller.auditHistory({ tenantId: 't', projectId: 'p', userId: 'other' }).length, 0); });
test('dependency injection controls identifiers and time', () => { const result = new MetaCognitiveController({ id: () => 'fixed', now: () => 99 }).analyze(input()); assert.equal(result.id, 'fixed'); assert.ok(result.timeline.every((x) => x.at === 99)); });
test('forbidden imports are absent', () => { const forbidden = [/orchestrator/i, /workflow/i, /provider/i, /runtime/i, /gateway/i, /billing/i, /application/i, /react/i, /retired-runtime/i, /memory/i]; for (const file of readdirSync('src/platform/creative/meta')) { if (!file.endsWith('.ts')) continue; const imports = readFileSync(join('src/platform/creative/meta', file), 'utf8').split('\n').filter((line) => /^import|^export .* from/.test(line)).join('\n'); for (const pattern of forbidden) assert.equal(pattern.test(imports), false, `${file}: ${pattern}`); } });

test('stability responds to confidence margin', () => { const analyzer = new DecisionStabilityAnalyzer(); assert.ok(analyzer.analyze(input()).score > analyzer.analyze(input({ observations: [{ source: 'DIRECTOR', strategy: 'AI', confidence: .7, reasons: ['x'] }, { source: 'DECISION', strategy: 'LOCAL', confidence: .69, reasons: ['x'] }] }) as never).score); });
test('explainability rejects missing reasons', () => assert.equal(new ExplainabilityValidator().validate([{ source: 'DECISION', strategy: 'LOCAL', confidence: .8, reasons: [] }]).explainable, false));
test('self monitoring exposes seven metrics', () => assert.equal(Object.keys(new SelfMonitoringEngine().evaluate(input() as never)).length, 7));
test('health exposes eleven subsystems', () => { const metrics = new SelfMonitoringEngine().evaluate(input() as never); assert.equal(Object.keys(new CreativeIntelligenceHealthMonitor().evaluate(metrics, .9, .8).dimensions).length, 11); });
test('score v3 exposes twelve maturity dimensions', () => { const metrics = new SelfMonitoringEngine().evaluate(input() as never); assert.equal(Object.keys(new CreativeIntelligenceScoreV3().calculate(metrics, .9, .8, .7).dimensions).length, 12); });
