import assert from 'node:assert/strict';
import test from 'node:test';
import {
  CompactNeuralDecisionRanker, CreativeDecisionModel, DecisionBenchmarkV2, DecisionCalibrationV2,
  DecisionGovernanceV2, DecisionModelDistiller, DecisionModelV2, DecisionRepresentationEncoderV2,
} from '../src/platform/creative/model';

const context = (operation = 'UPSCALE', deviceClass = 'desktop') => ({ operation, intent: 'premium portrait', goal: 'high quality', deviceClass, platform: 'web', projectType: 'catalog', privacyMode: 'STANDARD', budget: 12, latencyTarget: 5000, qualityTarget: .82, projectId: 'p1', deviceId: deviceClass, timestamp: 100 });
const candidate = (id = 'local', target: 'LOCAL'|'CLOUD'|'HYBRID' = 'LOCAL', quality = .8) => ({ id, executionTarget: target, model: `model-${id}`, provider: target === 'LOCAL' ? 'device' : 'fal', runtime: target === 'LOCAL' ? 'webgpu' : 'api', estimatedQuality: quality, estimatedLatency: target === 'LOCAL' ? 1300 : 800, estimatedCost: target === 'LOCAL' ? 0 : 3, energy: 2, memory: 2048, reliability: .86 });
const input = (id = 'local') => ({ context: context(), candidate: candidate(id), history: { modelSuccessRate:.8, providerSuccessRate:.75, deviceSpecificSuccessRate:.7, acceptanceRate:.72, undoRate:.08 }, preferences: { styleAlignment:.9, qualityPreference:.8 } });

test('v2 representation has independently versioned fused blocks', () => { const encoded = new DecisionRepresentationEncoderV2().encode(input()); assert.match(encoded.encoderVersion, /v2/); assert.deepEqual(Object.keys(encoded.blocks), ['context','candidate','history','device','goal','constraint']); assert.ok(encoded.values.length > 80); });
test('v2 encoder learns explicit interactions', () => { const interactions = new DecisionRepresentationEncoderV2().encode(input()).interactions; assert.deepEqual(Object.keys(interactions).sort(), ['device×model','goal×style','localRuntime×imageSize','operation×model','privacy×target','qualityTarget×budget']); });
test('sequence context filters irrelevant private history and limits length', () => { const encoder = new DecisionRepresentationEncoderV2(); const outcomes = Array.from({length:20}, (_, i) => ({ operation:i%2?'OTHER':'UPSCALE', deviceClass:i%3?'phone':'desktop', model:'m', provider:'p', target:'LOCAL', success:true, accepted:true, quality:.8, latency:100, cost:0, timestamp:i })); const encoded = encoder.encode({ ...input(), recentOutcomes: outcomes }); assert.ok(encoded.coverage <= 1); assert.equal(encoded.blocks.history.length, 55); });
test('cold start identifies all unknown dimensions', () => { const encoder = new DecisionRepresentationEncoderV2(undefined, undefined, undefined, undefined, undefined, undefined, { knownDevices:new Set(['phone']), knownOperations:new Set(['REPAIR']), knownModels:new Set(['old']), knownProviders:new Set(['old']) }); assert.deepEqual(encoder.encode(input()).coldStartReasons, ['NEW_DEVICE','NEW_OPERATION','NEW_MODEL','NEW_PROVIDER']); });
test('same global context generalizes across unseen devices', () => { const encoder = new DecisionRepresentationEncoderV2(); const desktop = encoder.encode(input()); const phone = encoder.encode({ ...input(), context:context('UPSCALE','phone') }); assert.deepEqual(desktop.blocks.goal, phone.blocks.goal); assert.notDeepEqual(desktop.blocks.device, phone.blocks.device); });
test('compact neural ranker improves a pairwise preference', () => { const encoder = new DecisionRepresentationEncoderV2(); const a=encoder.encode(input('a')); const b=encoder.encode(input('b')); const ranker=new CompactNeuralDecisionRanker({inputSize:a.values.length,epochs:60,learningRate:.02}); const before=ranker.compare(a,b); ranker.trainPairwise([{preferred:a,other:b}]); assert.ok(ranker.compare(a,b)>before); });
test('listwise training validates list lengths', () => { const r=new DecisionRepresentationEncoderV2().encode(input()); const ranker=new CompactNeuralDecisionRanker({inputSize:r.values.length}); assert.throws(() => ranker.trainListwise([{representations:[r,r],relevance:[1]}]), /mismatch/); });
test('pairwise inference is deterministic', () => { const model=new DecisionModelV2(); assert.deepEqual(model.rankPairwise(context(),candidate('a'),candidate('b')),model.rankPairwise(context(),candidate('a'),candidate('b'))); });
test('v2 exposes eight independent multitask heads', () => assert.deepEqual(Object.keys(new DecisionModelV2().predict(input()).outcomes), ['quality','successProbability','acceptanceProbability','cost','latency','escalationProbability','satisfaction','regret']));
test('satisfaction remains distinct from technical quality', () => { const p=new DecisionModelV2().predict({ ...input(), history:{acceptanceRate:.1,undoRate:.9},preferences:{styleAlignment:.1} }); assert.notEqual(p.outcomes.satisfaction,p.outcomes.quality); });
test('critical OOD cannot execute', () => { const encoder=new DecisionRepresentationEncoderV2(undefined,undefined,undefined,undefined,undefined,undefined,{knownDevices:new Set(),knownOperations:new Set(),knownModels:new Set(),knownProviders:new Set()}); const p=new DecisionModelV2({encoder,criticalUncertainty:.6}).predict(input()); assert.equal(p.ood,true); assert.equal(p.action,'FALLBACK_TO_HEURISTIC'); });
test('uncertainty separates aleatoric epistemic and coverage', () => { const u=new DecisionModelV2().predict(input()).uncertaintyV2; assert.deepEqual(Object.keys(u), ['aleatoric','epistemic','dataCoverage','oodScore','predictionConfidence']); });
test('LOCAL_ONLY cloud remains security-excluded after neural inference', () => { const p=new DecisionModelV2().predict({ ...input('cloud'), context:{...context(),privacyMode:'LOCAL_ONLY'}, candidate:candidate('cloud','CLOUD') }); assert.equal(p.expectedUtility,-1); assert.ok(p.explanation.constraintExclusions.includes('CLOUD_FORBIDDEN')); });
test('quarantine runtime and budget remain external gates', () => { const p=new DecisionModelV2().predict({ ...input(), candidate:{...candidate(),quarantined:true,estimatedCost:50}, constraints:{supportedRuntimes:['native'],budget:2} }); assert.deepEqual(p.explanation.constraintExclusions,['QUARANTINED_MODEL','UNSUPPORTED_RUNTIME','BUDGET_EXCEEDED']); });
test('counterfactual returns every head delta', () => { const c=new DecisionModelV2().counterfactual(input(),candidate('cloud','CLOUD',.95)); assert.equal(Object.keys(c.outcomeDeltas).length,8); assert.equal(c.alternative.candidate.id,'cloud'); });
test('calibration creates nonempty reliability curves', () => { const model=new DecisionModelV2(); const prediction=model.predict(input()); const calibration=new DecisionCalibrationV2().fit([{prediction,actual:{quality:.8,accepted:true,cost:0,latency:1000,utility:.7}}]); assert.equal(calibration.reliabilityCurve[0].count,1); });
test('human preference is bounded separately from outcomes', () => { const model=new DecisionModelV2(); model.trainPairwise([{context:context(),preferred:candidate('a'),other:candidate('b'),source:'HUMAN_PREFERENCE',weight:100}]); assert.ok(model.rankPairwise(context(),candidate('a'),candidate('b')).probabilityPreferred>=.5); });
test('distillation reports teacher lineage and fidelity', () => { const model=new DecisionModelV2(); const rows=['a','b','c'].map(id=>model.encode(input(id))); const result=new DecisionModelDistiller({now:()=>7}).distill(model.ranker,rows); assert.equal(result.teacherVersion,'neural-ranker-v2'); assert.equal(result.createdAt,7); assert.ok(result.fidelity>=0&&result.fidelity<=1); });
test('governance blocks a one-metric promotion', () => { const governance=new DecisionGovernanceV2(()=>1); governance.register({datasetVersion:'d',featureSchemaVersion:'f',encoderVersion:'e',trainingConfigVersion:'t',modelVersion:'v2',calibrationVersion:'c',benchmarkVersion:'b'}); const baseline={safety:1,ranking:.7,acceptance:.7,satisfaction:.7,unnecessaryAI:.1,calibrationError:.1,privacyViolations:0,cost:2,latency:1,quality:.8,regret:.1,cloudAvoidance:.5,oodSafety:1,stability:.9}; assert.throws(()=>governance.promote('v2',baseline,{...baseline,ranking:.8,acceptance:.6}),/ACCEPTANCE_REGRESSION/); });
test('governance allows only simultaneous promotion conditions', () => { const g=new DecisionGovernanceV2(()=>2); g.register({datasetVersion:'d',featureSchemaVersion:'f',encoderVersion:'e',trainingConfigVersion:'t',modelVersion:'v2',calibrationVersion:'c',benchmarkVersion:'b'}); const b={safety:1,ranking:.7,acceptance:.7,satisfaction:.7,unnecessaryAI:.1,calibrationError:.1,privacyViolations:0,cost:2,latency:1,quality:.8,regret:.1,cloudAvoidance:.5,oodSafety:1,stability:.9}; assert.equal(g.promote('v2',b,{...b,ranking:.8,acceptance:.72}).state,'ACTIVE'); });
test('facade runs v2 in shadow without changing active decision', () => { const facade=new CreativeDecisionModel(); facade.shadow(facade.v2); const result=facade.predict(context(),candidate()); assert.equal(result.candidate.id,'local'); assert.equal(facade.snapshot().shadowDecisions.length,1); });
test('facade exposes pairwise listwise counterfactual and distillation', () => { const facade=new CreativeDecisionModel(); assert.ok(facade.rankPairwise(context(),candidate('a'),candidate('b')).margin>=0); assert.equal(facade.predictList({context:context(),candidates:[candidate('a'),candidate('b')]}).length,2); assert.equal(facade.counterfactual(input(),candidate('b')).alternative.candidate.id,'b'); assert.equal(facade.distill([input('a'),input('b')]).samples,2); });
test('benchmark compares heuristic v1 and v2 product metrics', () => { const benchmark=new DecisionBenchmarkV2(); const p=new DecisionModelV2().predict(input()); const metrics=benchmark.evaluate([{prediction:p,actualQuality:.8,accepted:true,satisfied:.8,unnecessaryAI:false,actualCost:0,actualLatency:1000,bestUtility:p.expectedUtility}]); assert.equal(metrics.privacyViolations,0); assert.equal(Object.keys(benchmark.compare(metrics,metrics,metrics)).length,3); });
test('all v2 outputs are deeply immutable', () => { const p=new DecisionModelV2().predict(input()); assert.throws(() => (p.outcomes.quality=0)); assert.throws(() => (p.representation.values[0]=0)); });

// 12 domains × 25 variants: 300 independent inference/security/generalization cases.
for(let domain=0;domain<12;domain++) for(let variant=0;variant<25;variant++) test(`v2 conformance ${domain+1}.${variant+1}`,()=>{
  const target=variant%3===0?'CLOUD':'LOCAL'; const privacyMode=variant%5===0?'LOCAL_ONLY':'STANDARD';
  const ctx={...context(`OP_${domain}`,`DEVICE_${variant%4}`),privacyMode,budget:variant+1,qualityTarget:variant/24};
  const c={...candidate(`${domain}-${variant}`,target,variant/24),estimatedCost:target==='CLOUD'?2:0}; const model=new DecisionModelV2();
  const first=model.predict({context:ctx,candidate:c,imageSize:{width:1000+variant,height:800}}); const second=model.predict({context:ctx,candidate:c,imageSize:{width:1000+variant,height:800}});
  assert.deepEqual(first,second); assert.equal(first.representation.encoderVersion,'decision-representation-v2.0'); assert.ok(Object.values(first.outcomes).every(Number.isFinite)); assert.ok(first.predictionConfidence>=0&&first.predictionConfidence<=1);
  if(privacyMode==='LOCAL_ONLY'&&target==='CLOUD'){ assert.equal(first.expectedUtility,-1); assert.notEqual(first.action,'EXECUTE'); }
});

test('offline benchmark runs against fixed anonymized outcome fixture', async () => {
  const fixture = (await import('./fixtures/decision-benchmark-v2.json', { with: { type: 'json' } })).default;
  assert.equal(fixture.datasetVersion, 'anonymized-outcomes-v2.1'); assert.equal(fixture.records.length, 10);
  const model = new DecisionModelV2(); const benchmark = new DecisionBenchmarkV2();
  const metrics = benchmark.evaluate(fixture.records.map((row) => { const prediction=model.predict({context:context(row.operation,row.deviceClass),candidate:candidate(row.id,row.target as 'LOCAL'|'CLOUD')}); return {prediction,actualQuality:row.quality,accepted:row.accepted,satisfied:row.satisfaction,unnecessaryAI:row.unnecessaryAI,actualCost:row.cost,actualLatency:row.latency,bestUtility:row.bestUtility}; }));
  assert.ok(metrics.quality > 0); assert.ok(metrics.oodSafety >= 0 && metrics.oodSafety <= 1);
});
