import assert from 'node:assert/strict';
import test from 'node:test';
import pg from 'pg';
import { CreativeLearningReplay, CreativeLearningSystem, PostgresCreativeLearningStore, toLearningRecord, validateCreativeOutcome, type CreativeLearningRecord, type CreativeOutcome } from '../src/platform/creative/learning';

const databaseUrl=process.env.DATABASE_URL;
if(!databaseUrl)throw new Error('DATABASE_URL is required: real PostgreSQL creative-learning tests cannot be skipped or mocked');
const admin=new pg.Pool({connectionString:databaseUrl,max:30});
const schema=`creative_learning_test_${process.pid}_${Date.now()}`;
const store=new PostgresCreativeLearningStore(admin,{schema,retentionPolicyVersion:'retention-v2',retentionDays:30});
const q=(name:string)=>`"${name}"`;
const outcome=(suffix='base',scope:Partial<CreativeOutcome['scope']>={}):CreativeOutcome=>({requestId:`request-${suffix}`,executionId:`execution-${suffix}`,operationId:'edit',decisionId:'decision',planId:'plan',strategyId:'strategy',outcomeVersion:'1',scope:{tenantId:'tenant-a',projectId:'project-a',userId:'user-a',...scope},target:'LOCAL',model:'model-v2',provider:'local',device:{class:'desktop'},predictions:{predictedQuality:.8,predictedAcceptance:.7,predictedCost:0,predictedLatency:10,predictedSuccess:.9,predictedEscalation:.1,predictedSatisfaction:.8,modelVersion:'model-v2',policyVersion:'policy-v1',featureSchemaVersion:'feature-v1'},actuals:{actualQuality:.9,actualLatency:9,actualCost:0,actualSuccess:true,actualAcceptance:true,actualSatisfaction:.9,actualEscalation:false,actualFallbacks:0,actualRetries:0},verification:{valid:true,artifactIntegrityValid:true},billing:{state:'NOT_BILLABLE',actualCost:0},userReaction:'ACCEPTED',candidateSet:[{candidateId:'a',observedQuality:.9},{candidateId:'b',observedQuality:.8}],selectedCandidateId:'a',occurredAt:'2026-01-01T00:00:00.000Z',completedAt:'2026-01-01T00:00:01.000Z'});
const count=async()=>Number((await admin.query(`SELECT count(*) FROM ${q(schema)}.creative_learning_records`)).rows[0].count);

test.before(async()=>{await store.migrate();await store.migrate()});
test.after(async()=>{await admin.query(`DROP SCHEMA IF EXISTS ${q(schema)} CASCADE`);await admin.end()});
test.beforeEach(async()=>{await admin.query(`TRUNCATE ${q(schema)}.creative_learning_records`)});

test('01 migration is repeatable and checksum protected',async()=>{const rows=await admin.query(`SELECT version,checksum FROM ${q(schema)}.creative_learning_migrations`);assert.equal(rows.rowCount,1);assert.match(rows.rows[0].checksum,/^[a-f0-9]{64}$/)});
test('02 same canonical identity x20 creates exactly one row',async()=>{const writes=await Promise.all(Array.from({length:20},()=>store.append(toLearningRecord(outcome()))));assert.equal(writes.filter(Boolean).length,1);assert.equal(await count(),1)});
test('03 request id is not canonical identity',async()=>{const a=outcome();const b={...outcome(),requestId:'another-request'};assert.equal(await store.append(toLearningRecord(a)),true);assert.equal(await store.append(toLearningRecord(b)),false)});
test('04 outcome version is part of identity',async()=>{const a=outcome();const b={...outcome(),outcomeVersion:'2'};await Promise.all([store.append(toLearningRecord(a)),store.append(toLearningRecord(b))]);assert.equal(await count(),2)});
test('05 four concurrent scopes do not collide',async()=>{const scopes=[['tenant-a','project-a','user-a'],['tenant-a','project-b','user-a'],['tenant-a','project-a','user-b'],['tenant-b','project-a','user-a']] as const;await Promise.all(scopes.map(([tenantId,projectId,userId],i)=>store.append(toLearningRecord(outcome(String(i),{tenantId,projectId,userId})))));assert.equal(await count(),4)});
test('06 tenant query is isolated',async()=>{await store.append(toLearningRecord(outcome('a')));await store.append(toLearningRecord(outcome('b',{tenantId:'tenant-b'})));assert.deepEqual((await store.list({tenantId:'tenant-a'})).map(r=>r.scope.tenantId),['tenant-a'])});
test('07 project query is isolated',async()=>{await store.append(toLearningRecord(outcome('a')));await store.append(toLearningRecord(outcome('b',{projectId:'project-b'})));assert.equal((await store.list({tenantId:'tenant-a',projectId:'project-a'})).length,1)});
test('08 user query is isolated',async()=>{await store.append(toLearningRecord(outcome('a')));await store.append(toLearningRecord(outcome('b',{userId:'user-b'})));assert.equal((await store.list({tenantId:'tenant-a',projectId:'project-a',userId:'user-a'})).length,1)});
test('09 failure after insert rolls transaction back',async()=>{const failing=new PostgresCreativeLearningStore(admin,{schema,afterInsert:()=>{throw new Error('injected failure')}});await assert.rejects(failing.append(toLearningRecord(outcome())),/injected failure/);assert.equal(await count(),0);assert.equal(await store.append(toLearningRecord(outcome('recovered'))),true)});
test('10 DB constraint rejects blank canonical scope',async()=>{await assert.rejects(admin.query(`INSERT INTO ${q(schema)}.creative_learning_records(tenant_id,project_id,user_id,execution_id,outcome_version,feature_schema_version,reward_schema_version,retention_policy_version,occurred_at,record) VALUES('','p','u','e','1','f','r','v',now(),'{}')`));assert.equal(await count(),0)});
test('11 DB constraint requires an object JSONB payload',async()=>{await assert.rejects(admin.query(`INSERT INTO ${q(schema)}.creative_learning_records(tenant_id,project_id,user_id,execution_id,outcome_version,feature_schema_version,reward_schema_version,retention_policy_version,occurred_at,record) VALUES('t','p','u','e','1','f','r','v',now(),'[]')`));assert.equal(await count(),0)});
test('12 durable record is visible through a new store instance',async()=>{await store.append(toLearningRecord(outcome()));const fresh=new PostgresCreativeLearningStore(admin,{schema});assert.equal((await fresh.list({tenantId:'tenant-a'})).length,1)});
test('13 reads expose committed rows only',async()=>{const client=await admin.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO ${q(schema)}.creative_learning_records(tenant_id,project_id,user_id,execution_id,outcome_version,feature_schema_version,reward_schema_version,retention_policy_version,occurred_at,record) VALUES('tenant-a','p','u','pending','1','f','r','v',now(),'{}')`);assert.equal((await store.list({tenantId:'tenant-a'})).length,0);await client.query('ROLLBACK')}finally{client.release()}});
test('14 persisted payload and returned nested values are immutable',async()=>{const input=outcome();const record=toLearningRecord(input);await store.append(record);input.predictions.predictedQuality=.1;input.actuals.actualQuality=.1;input.candidateSet[0].candidateId='changed';const saved=(await store.list({tenantId:'tenant-a'}))[0];assert.equal(saved.predictions.predictedQuality,.8);assert.equal(saved.actualOutcome.actualQuality,.9);assert.equal(saved.candidateSet[0].candidateId,'a');assert.ok(Object.isFrozen(saved.reward))});
test('15 retention and schema versions survive persistence',async()=>{await store.append(toLearningRecord(outcome()));const saved=(await store.list({tenantId:'tenant-a'}))[0];assert.equal(saved.retentionPolicyVersion,'retention-v2');assert.equal(saved.predictions.featureSchemaVersion,'feature-v1');assert.equal(saved.reward.rewardSchemaVersion,'v1');assert.ok(saved.createdAt);assert.ok(saved.expiresAt)});
test('16 durable dataset has canonical metadata',async()=>{await store.append(toLearningRecord(outcome()));const system=new CreativeLearningSystem(store);const snapshot=(await system.buildDurableDataset({tenantId:'tenant-a'},{version:'dataset-v3',now:()=> '2026-02-01T00:00:00Z'})).snapshot();assert.equal(snapshot.metadata.sampleCount,1);assert.equal(snapshot.metadata.scopePolicy,'TENANT');assert.equal(snapshot.metadata.version,'dataset-v3');assert.equal(snapshot.metadata.featureSchemaVersion,'feature-v1');assert.deepEqual(snapshot.metadata.sourcePeriod,{from:'2026-01-01T00:00:00.000Z',to:'2026-01-01T00:00:00.000Z'})});
test('17 scope-aware durable dataset does not leak',async()=>{for(let i=0;i<40;i++)await store.append(toLearningRecord(outcome(String(i),{projectId:`project-${i%2}`,userId:`user-${i%4}`})));const system=new CreativeLearningSystem(store);const records=(await system.buildDurableDataset({tenantId:'tenant-a',projectId:'project-0',userId:'user-0'})).snapshot().records;assert.ok(records.length>0);assert.ok(records.every(r=>r.scope.projectId==='project-0'&&r.scope.userId==='user-0'))});
test('18 replay is deterministic, read-only, and creates no row',async()=>{await store.append(toLearningRecord(outcome()));const records=await store.list({tenantId:'tenant-a'});const dataset={metadata:{datasetId:'d',version:'1',featureSchemaVersion:'feature-v1',sourcePeriod:{from:'',to:''},sampleCount:1,scopePolicy:'TENANT' as const,createdAt:''},records};const replay=new CreativeLearningReplay(),model={version:'offline-v1',predict:(r:CreativeLearningRecord)=>r.labels};assert.deepEqual(replay.replay(dataset,model),replay.replay(dataset,model));assert.equal(await count(),1)});
const invalidCases:[string,(o:CreativeOutcome)=>void][]=[['19 blank scope',o=>{o.scope.tenantId=' '}],['20 blank execution',o=>{o.executionId=' '}],['21 invalid numeric',o=>{o.actuals.actualCost=Number.NaN}],['22 invalid timestamp',o=>{o.occurredAt='never'}],['23 invalid billing',o=>{o.billing.state='UNKNOWN'}],['24 invalid candidate selection',o=>{o.selectedCandidateId='missing'}],['25 raw image',o=>{o.context={rawImage:'data'}}],['26 secret',o=>{o.context={apiKey:'secret'}}],['27 forbidden metadata',o=>{o.context={metadata:{x:1}}}]];
for(const [name,mutate] of invalidCases)test(name,async()=>{const value=outcome();mutate(value);assert.equal(validateCreativeOutcome(value).status,'REJECTED_FROM_LEARNING');const system=new CreativeLearningSystem(store);assert.equal((await system.ingestOutcome(value)).status,'REJECTED_FROM_LEARNING');assert.equal(await count(),0)});
