import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import test from "node:test";
import { BrandIdentityEngine, ColorPsychologyEngine, CompositionExpert, CreativeConsistencyEngine, CreativeConstraintEngine,
  CreativeDirectorDebugger, CreativeDirectorReview, CreativeDiversityEngine, CreativeEmotionEngine, CreativeExpertCouncil,
  CreativeIQ, CreativeInspirationEngine, CreativeNarrativeEngine, CreativeScorecard, CreativeVisionEngine,
  HeuristicCreativeDirector, HeuristicCreativeEmotionEncoder, HeuristicCreativeExpert, HeuristicCreativeImaginationEngine,
  HeuristicCreativeNarrativeEncoder, HeuristicCreativePlanner, HeuristicCreativeReasoner, HeuristicCreativeWorldModel,
  LightingPsychologyEngine, ProjectVisualMemory, StyleEvolutionEngine, StyleGenome, VisualLanguageEngine,
  type CreativeCandidate } from "../src/platform/creative/decision/intelligence/director/index";

const scope = Object.freeze({ userId: "user", tenantId: "tenant", projectId: "project" });
const dependencies = () => { let id = 0; return { createId: () => `id-${++id}`, now: () => 100, random: () => .25 }; };
const candidate = (id: string, attributes: Readonly<Record<string, number>>, extra: Partial<CreativeCandidate> = {}): CreativeCandidate => Object.freeze({ id, attributes: Object.freeze(attributes), ...extra });

test("vision translates a multilingual prompt into an immutable artistic direction", () => { const result = new CreativeVisionEngine(dependencies()).analyze(scope, "Сделай дорого, премиум и чисто"); assert.ok(result.style.includes("Luxury")); assert.ok(result.mood.includes("Elegant")); assert.equal(result.id, "id-1"); assert.equal(result.createdAt, 100); assert.equal(Object.isFrozen(result.visualDirection), true); });
test("visual language stores independent immutable weighted knowledge", () => { const engine = new VisualLanguageEngine(); assert.equal(engine.language("Luxury").signals[0].name, "Soft lighting"); assert.equal(engine.language("Fashion").signals[0].name, "High contrast"); assert.equal(Object.isFrozen(engine.all()), true); });
test("emotion produces recommendations and narrative produces a story arc", () => { const emotion = new CreativeEmotionEngine().analyze("Luxury warm portrait"); assert.ok(emotion.recommendations.includes("soft light")); const narrative = new CreativeNarrativeEngine().analyze("warm family portrait"); assert.deepEqual(narrative.arc, ["Warmth", "Connection", "Emotion"]); });
test("composition expert assesses eight dimensions without an image", () => { const result = new CompositionExpert().evaluate({ hierarchy: .9, balance: .8 }); assert.equal(Object.keys(result.dimensions).length, 8); assert.ok(result.recommendations.includes("Improve focus")); });
test("color and lighting psychology are immutable knowledge bases", () => { assert.equal(new ColorPsychologyEngine().analyze(["Gold"])[0].perception, "Luxury"); assert.equal(new LightingPsychologyEngine().analyze(["Cold"])[0].perception, "Technology"); assert.equal(Object.isFrozen(new ColorPsychologyEngine().all()), true); });
test("brand identity uses injected identity and is isolated by the complete scope", () => { const engine = new BrandIdentityEngine(dependencies()); const brand = engine.define(scope, { name: "B", preferredPalette: ["Gold"], preferredMood: ["Luxury"], preferredLighting: ["Soft"], preferredStyle: ["Minimal"], consistencyRules: ["Keep logo"] }); assert.equal(brand.id, "id-1"); assert.equal(engine.get({ ...scope, userId: "other" }), undefined); assert.equal(engine.evaluate(scope, candidate("c", {}, { colors: ["Gold"], styles: ["Minimal", "Luxury"], lighting: ["Soft"] })), 1); });
test("style evolution and project visual memory isolate tenant project and user", () => { const deps = dependencies(); const evolution = new StyleEvolutionEngine(deps); evolution.record(scope, "Minimal", .8); evolution.record(scope, "Luxury", .9); assert.deepEqual(evolution.history(scope).map(({ style }) => style), ["Minimal", "Luxury"]); assert.equal(evolution.history({ ...scope, tenantId: "x" }).length, 0); const memory = new ProjectVisualMemory(deps); memory.save(scope, { preferredMood: ["Warm"], preferredPalette: ["Gold"], preferredLighting: ["Soft"], preferredComposition: ["Balanced"], preferredStyle: ["Luxury"] }); assert.equal(memory.get(scope)?.version, 1); assert.equal(memory.get({ ...scope, projectId: "x" }), undefined); });
test("consistency and diversity assess a series on visual attributes", () => { const items = [candidate("a", { color: .1, composition: .2 }), candidate("b", { color: .9, composition: .8 })]; assert.ok(new CreativeConsistencyEngine().evaluate(items).score < .5); assert.ok(new CreativeDiversityEngine().evaluate(items).score > .6); });
test("inspiration combines styles deterministically", () => { const engine = new CreativeInspirationEngine(); const first = engine.combine(["Minimal", "Luxury"]); assert.deepEqual(first, engine.combine(["Minimal", "Luxury"])); assert.equal(first.name, "Luxury Minimal"); assert.equal(Object.isFrozen(first.direction), true); });
test("constraint engine parses and validates cost AI and preservation requirements", () => { const engine = new CreativeConstraintEngine(); const constraints = engine.parse("до 5 кредитов, без AI, не менять лицо, не менять одежду, оставить бренд"); assert.deepEqual([constraints.maxCredits, constraints.allowAI, constraints.preserveFace, constraints.preserveClothing, constraints.preserveBrand], [5, false, true, true, true]); assert.deepEqual(engine.validate(candidate("x", {}, { credits: 7, usesAI: true }), constraints), ["CREDIT_LIMIT", "AI_DISALLOWED"]); });
test("director review answers all eight internal review questions", () => { const review = new CreativeDirectorReview().review({ candidate: candidate("ai", { quality: .7, focus: .4 }, { credits: 10, usesAI: true, operations: ["1", "2", "3", "4", "5", "6", "7"] }), alternatives: [candidate("local", { quality: .8 }, { credits: 0, usesAI: false })], brandAlignment: .4, composition: .3 }); assert.equal(review.length, 8); assert.ok(review.every(({ reason, confidence, recommendation }) => reason && confidence && recommendation)); assert.equal(Object.isFrozen(review), true); });
test("expert council preserves domains and aggregates confidence-weighted opinions", () => { const council = new CreativeExpertCouncil([new HeuristicCreativeExpert("Composition", "COMPOSITION", "composition"), new HeuristicCreativeExpert("Cost", "COST", "cost", true), new HeuristicCreativeExpert("Narrative", "NARRATIVE", "narrative")]); const result = council.evaluate(candidate("x", { composition: .9, cost: .1, narrative: .8 })); assert.equal(result.opinions.length, 3); assert.ok(result.score > .8); });
test("scorecard and Creative IQ expose director-level multidimensional assessment", () => { const values = { luxury: .8, emotion: .8, composition: .8, narrative: .8, brand: .8, consistency: .8, creativity: .8, commercialValue: .8, technicalQuality: .8, tasteAlignment: .8, costEfficiency: .8 }; const card = new CreativeScorecard().calculate(values); assert.equal(Object.keys(card.dimensions).length, 11); assert.equal(new CreativeIQ().evaluate(card).level, "DIRECTOR"); });
test("style genome normalizes all eight artistic features", () => { const genome = new StyleGenome().encode("Luxury"); assert.equal(Object.keys(genome).length, 9); assert.ok(Math.abs(Object.entries(genome).filter(([key]) => key !== "style").reduce((sum, [, value]) => sum + Number(value), 0) - 1) < 1e-12); assert.equal(Object.isFrozen(genome), true); });
test("reasoning foundation contracts have deterministic heuristic implementations", () => { const vision = new CreativeVisionEngine(dependencies()).create(scope, "Luxury"); const context = { scope, vision, candidates: [candidate("b", { quality: .4 }), candidate("a", { quality: .8 })] }; assert.equal(new HeuristicCreativeDirector().direct(context).id, "a"); assert.deepEqual(new HeuristicCreativeReasoner().reason(context), new HeuristicCreativeReasoner().reason(context)); assert.ok(new HeuristicCreativePlanner().plan(context).length > 2); assert.equal(new HeuristicCreativeNarrativeEncoder().encode(new CreativeNarrativeEngine().analyze("car")).length, 2); assert.ok(new HeuristicCreativeEmotionEncoder().encode(new CreativeEmotionEngine().analyze("warm")).length); assert.equal(new HeuristicCreativeWorldModel().observe(scope, { light: .8 }).attributes.light, .8); assert.deepEqual(new HeuristicCreativeImaginationEngine().imagine(["Luxury", "Minimal"]), ["Luxury Minimal"]); });
test("debugger emits the complete deeply immutable director chain", () => { const debuggerV1 = new CreativeDirectorDebugger(); const root = debuggerV1.build({ Prompt: "Luxury" }); const stages = debuggerV1.flatten(root).map(({ stage }) => stage); assert.equal(stages.length, 14); assert.deepEqual(stages.slice(-3), ["Creative IQ", "Reasoning", "Recommendation"]); assert.equal(Object.isFrozen(root.next), true); });
test("all computations are repeatable", () => { const engine = new CreativeEmotionEngine(); assert.deepEqual(engine.analyze("Luxury Fashion"), engine.analyze("Luxury Fashion")); const genome = new StyleGenome(); assert.deepEqual(genome.combine(["Luxury", "Fashion"]), genome.combine(["Luxury", "Fashion"])); });
test("director layer contains no forbidden imports or browser API", () => { const directory = `${process.cwd()}/src/platform/creative/decision/intelligence/director`; const forbidden = /(?:from\s+["'][^"']*(?:core|application|memory|workflow|runtime|gateway|provider|billing|ui|editing|pipeline|experience|organization)|\b(?:window|document|navigator|fetch)\b)/i; readdirSync(directory).filter((file) => file.endsWith(".ts")).forEach((file) => assert.doesNotMatch(readFileSync(`${directory}/${file}`, "utf8"), forbidden, file)); });
