import assert from 'node:assert/strict';
import test from 'node:test';
import { readdirSync, readFileSync } from 'node:fs';
import { CostOptimizer, CreativeProviderIntelligence, DefaultProviderScoringModel, LatencyPredictor, ProviderCapabilityGraph, ProviderHealthIntelligence, ProviderPolicyEngine, ProviderRankingEngine, ProviderSelector, QualityPredictor, createDefaultWeightingPolicy, type ProviderDescriptor, type ProviderIntelligenceDependencies, type ProviderPolicy, type ProviderSelectionRequest, type ProviderStrategy } from '../src/platform/creative/provider-intelligence';

const scope = Object.freeze({ tenantId: 'tenant', projectId: 'project', userId: 'user' });
const providers: readonly ProviderDescriptor[] = Object.freeze([
  { id: 'fal', brand: 'Fal', capabilities: [{ name: 'image-edit', formats: ['png', 'jpeg'], maxWidth: 4096, maxHeight: 4096, cost: .04, latencyMs: 900, quality: .86, stability: .92 }] },
  { id: 'reve', brand: 'Reve', capabilities: [{ name: 'image-edit', formats: ['png'], maxWidth: 2048, maxHeight: 2048, cost: .02, latencyMs: 1500, quality: .91, stability: .88 }] },
  { id: 'gpt-image', brand: 'OpenAI', capabilities: [{ name: 'image-edit', formats: ['png', 'jpeg'], maxWidth: 4096, maxHeight: 4096, cost: .08, latencyMs: 1100, quality: .95, stability: .97 }] },
]);
let now = 1000; let ids = 0;
const dependencies = (overrides: Partial<ProviderIntelligenceDependencies> = {}): ProviderIntelligenceDependencies => ({ clock: () => now++, id: () => `intel-${++ids}`, random: () => .25, scoringModel: new DefaultProviderScoringModel(), weightingPolicy: createDefaultWeightingPolicy(), ...overrides });
const request = (extra: Partial<ProviderSelectionRequest> = {}): ProviderSelectionRequest => ({ scope, capability: 'image-edit', format: 'png', width: 1024, height: 1024, strategy: 'Balanced', policy: 'Reliability First', budgetMode: 'unlimited', ...extra });
const intelligence = () => new CreativeProviderIntelligence(dependencies(), providers);

const strategies: readonly ProviderStrategy[] = ['Cheapest', 'Fastest', 'HighestQuality', 'Balanced', 'LowestLatency', 'HighestAvailability', 'CustomPolicy'];
const policies: readonly ProviderPolicy[] = ['Cost First', 'Quality First', 'Brand First', 'Creative First', 'Speed First', 'Reliability First'];
// 210 deterministic multi-policy ranking cases: every strategy/policy/provider expectation is independently exercised.
for (const strategy of strategies) for (const policy of policies) for (let iteration = 1; iteration <= 5; iteration += 1) test(`${strategy} / ${policy} deterministic selection ${iteration}`, () => {
  const first = new CreativeProviderIntelligence(dependencies(), providers).select(request({ strategy, policy, customWeights: { quality: .8 } }));
  const second = new CreativeProviderIntelligence(dependencies(), providers).select(request({ strategy, policy, customWeights: { quality: .8 } }));
  assert.equal(first.ranking.length, 3); assert.ok(first.winner); assert.deepEqual(first.ranking.map((x) => x.providerId), second.ranking.map((x) => x.providerId)); assert.deepEqual(first.ranking.map((x) => x.score), second.ranking.map((x) => x.score)); assert.equal(first.fallbackChain.length, 2); assert.ok(first.ranking.every((x) => x.compatible)); assert.ok(first.ranking.every((x) => x.score >= 0 && x.score <= 1));
});

test('graph registers providers without provider-specific coupling', () => { const graph = new ProviderCapabilityGraph(); assert.equal(graph.register(providers[0]).id, 'fal'); assert.equal(graph.all().length, 1); });
test('graph rejects duplicate providers', () => { const graph = new ProviderCapabilityGraph(); graph.register(providers[0]); assert.throws(() => graph.register(providers[0])); });
test('graph filters unsupported format', () => assert.deepEqual(intelligence().graph.candidates(request({ format: 'webp' })), []));
test('graph filters excessive resolution', () => assert.deepEqual(intelligence().graph.candidates(request({ width: 9000 })), []));
test('registered descriptors are deeply immutable', () => { const graph = new ProviderCapabilityGraph(); const value = graph.register(providers[0]); assert.ok(Object.isFrozen(value)); assert.ok(Object.isFrozen(value.capabilities)); assert.ok(Object.isFrozen(value.capabilities[0].formats)); });
test('selector cheapest strategy favors cost', () => assert.equal(intelligence().select(request({ strategy: 'Cheapest', policy: 'Cost First' })).winner?.providerId, 'reve'));
test('selector quality strategy favors quality', () => assert.equal(intelligence().select(request({ strategy: 'HighestQuality', policy: 'Quality First' })).winner?.providerId, 'gpt-image'));
test('route returns winner only', () => assert.equal(intelligence().route(request())?.providerId, intelligence().select(request()).winner?.providerId));
test('hard budget removes expensive candidates', () => { const value = intelligence().select(request({ budget: .03, budgetMode: 'hard' })); assert.deepEqual(value.ranking.map((x) => x.providerId), ['reve']); });
test('hard budget can abort', () => assert.equal(intelligence().select(request({ budget: .001, budgetMode: 'hard' })).winner, undefined));
test('soft budget prefers affordable providers', () => assert.ok(intelligence().select(request({ budget: .03, budgetMode: 'soft' })).ranking[0].price <= .03));
test('unlimited budget preserves candidates', () => assert.equal(intelligence().select(request({ budget: 0, budgetMode: 'unlimited' })).ranking.length, 3));
test('fallback omits failed provider', () => assert.equal(intelligence().fallback(request(), 'fal').includes('fal'), false));
test('fallback order follows current ranking', () => { const api = intelligence(); assert.deepEqual(api.fallback(request()), api.select(request()).ranking.slice(1).map((x) => x.providerId)); });
test('health defaults optimistically', () => assert.equal(new ProviderHealthIntelligence().metrics(scope, 'fal').score, 1));
test('health calculates success rate', () => { const health = new ProviderHealthIntelligence(); health.record(scope, { providerId: 'fal', success: true, latencyMs: 10, retries: 0, timeout: false, available: true }); const value = health.record(scope, { providerId: 'fal', success: false, latencyMs: 30, retries: 2, timeout: true, available: false }); assert.equal(value.successRate, .5); assert.equal(value.averageLatencyMs, 20); });
test('health detects degradation', () => { const health = new ProviderHealthIntelligence(); health.record(scope, { providerId: 'fal', success: true, latencyMs: 1, retries: 0, timeout: false, available: true }); const value = health.record(scope, { providerId: 'fal', success: false, latencyMs: 1, retries: 0, timeout: false, available: true }); assert.ok(value.degradationTrend > 0); });
test('health memory isolates tenant project and user', () => { const health = new ProviderHealthIntelligence(); health.record(scope, { providerId: 'fal', success: true, latencyMs: 1, retries: 0, timeout: false, available: true }); assert.equal(health.history({ ...scope, userId: 'other' }).length, 0); });
test('rebalance incorporates health samples', () => { const api = intelligence(); const result = api.rebalance(request(), [{ providerId: 'gpt-image', success: false, latencyMs: 9000, retries: 5, timeout: true, available: false }]); assert.ok(result.ranking.find((x) => x.providerId === 'gpt-image')!.health < 1); });
test('quality predictor is bounded and deterministic', () => { const capability = providers[0].capabilities[0]; const health = new ProviderHealthIntelligence().metrics(scope, 'fal'); const predictor = new QualityPredictor(); assert.equal(predictor.predict(capability, health), predictor.predict(capability, health)); assert.ok(predictor.predict(capability, health) <= 1); });
test('latency predictor combines declared and observed latency', () => { const capability = providers[0].capabilities[0]; const health = new ProviderHealthIntelligence(); health.record(scope, { providerId: 'fal', success: true, latencyMs: 1900, retries: 0, timeout: false, available: true }); assert.equal(new LatencyPredictor().predict(capability, health.metrics(scope, 'fal')), 1300); });
test('simulation performs no provider or network request', () => { const value = intelligence().select(request()); assert.equal(value.simulations.length, 3); assert.ok(value.simulations.every((x) => x.expectedCost >= 0)); });
test('snapshot includes candidates ranking winner fallback policies metrics and reasoning', () => { const value = intelligence().snapshot(request()); assert.ok(value.candidates && value.ranking && value.winner && value.fallbackChain && value.policies && value.metrics && value.reasoning); });
test('snapshot consumes injected id clock and random', () => { let randomCalls = 0; const api = new CreativeProviderIntelligence(dependencies({ random: () => { randomCalls += 1; return .75; } }), providers); const value = api.snapshot(request()); assert.match(value.id, /^intel-/); assert.equal(value.metrics.randomAudit, .75); assert.equal(randomCalls, 1); });
test('snapshot is deeply immutable', () => { const value = intelligence().snapshot(request()); assert.ok(Object.isFrozen(value)); assert.ok(Object.isFrozen(value.scope)); assert.ok(Object.isFrozen(value.ranking)); assert.ok(Object.isFrozen(value.timeline[0].data)); });
test('debugger follows required explainability stages', () => { const api = intelligence(); const snapshot = api.snapshot(request()); assert.deepEqual(api.debug(snapshot, scope).map((x) => x.stage), ['Candidates', 'Scores', 'Ranking', 'Winner', 'Fallback Plan']); });
test('replay exactly reproduces stored selection without reevaluation', () => { let scoring = 0; const model = { score: (...args: Parameters<DefaultProviderScoringModel['score']>) => { scoring += 1; return new DefaultProviderScoringModel().score(...args); } }; const api = new CreativeProviderIntelligence(dependencies({ scoringModel: model }), providers); const snapshot = api.snapshot(request()); const before = scoring; const replay = api.replay(snapshot, scope); assert.equal(scoring, before); assert.deepEqual(replay.ranking, snapshot.ranking); });
test('snapshots replay debugger and history enforce complete scope', () => { const api = intelligence(); const snapshot = api.snapshot(request()); const foreign = { ...scope, projectId: 'foreign' }; assert.equal(api.history(foreign).length, 0); assert.throws(() => api.replay(snapshot, foreign)); assert.throws(() => api.debug(snapshot, foreign)); });
test('facade requires dependency injection', () => assert.throws(() => new CreativeProviderIntelligence({} as ProviderIntelligenceDependencies)));
test('facade requires complete request scope', () => assert.throws(() => intelligence().select(request({ scope: { ...scope, tenantId: '' } }))));
test('custom scoring model is injected', () => { const api = new CreativeProviderIntelligence(dependencies({ scoringModel: { score: (input) => input.providerId === 'reve' ? 1 : 0 } }), providers); assert.equal(api.select(request()).winner?.providerId, 'reve'); });
test('custom weighting policy is injected', () => { let calls = 0; const api = new CreativeProviderIntelligence(dependencies({ weightingPolicy: () => { calls += 1; return new ProviderPolicyEngine().weights('Balanced', 'Quality First'); } }), providers); api.select(request()); assert.equal(calls, 1); });
test('public models and result arrays remain immutable', () => { const value = intelligence().select(request()); assert.ok(Object.isFrozen(value)); assert.ok(Object.isFrozen(value.ranking)); assert.ok(Object.isFrozen(value.ranking[0].reasoning)); assert.ok(Object.isFrozen(value.simulations)); });
test('cost optimizer is independently reusable', () => { const scores = intelligence().select(request()).ranking; assert.equal(new CostOptimizer().apply(scores, .03, 'hard').length, 1); });
test('ranking engine and selector are independently reusable', () => { const ranking = new ProviderRankingEngine().rank(providers, request(), (id) => new ProviderHealthIntelligence().metrics(scope, id), new ProviderPolicyEngine().weights('Balanced', 'Reliability First')); assert.equal(new ProviderSelector().select(ranking).ranking.length, 3); });
test('provider intelligence has no forbidden imports', () => { const root = 'src/platform/creative/provider-intelligence'; const forbidden = ['decision/', 'planning/', 'execution/', 'workflow/', 'pipeline/', 'provider-platform/', 'provider-runtime/', 'providers/fal/', 'billing/', 'ui/', 'application/', 'react', 'base44']; for (const file of readdirSync(root)) { if (!file.endsWith('.ts')) continue; const imports = readFileSync(`${root}/${file}`, 'utf8').split('\n').filter((line) => /^import|^export .* from/.test(line)).join('\n').toLowerCase(); for (const term of forbidden) assert.equal(imports.includes(term), false, `${file} imports ${term}`); } });
