import assert from 'node:assert/strict';
import test from 'node:test';
import { CloudVisualEncoder, CreativeDecisionModel, LocalVisualEncoder, MultimodalDecisionModel, MultimodalFusionV3, OperationNeedPredictor, VisualGoalAlignmentEngine, VisualQualityHead } from '../src/platform/creative/model';

const context = (privacyMode='STANDARD', goal='luxury advertising photo') => ({operation:'ENHANCE',intent:'make this premium',goal,deviceClass:'desktop',platform:'web',projectType:'campaign',privacyMode,budget:12,latencyTarget:5000,qualityTarget:.85});
const candidate = (id='local', target:'LOCAL'|'CLOUD'|'HYBRID'='LOCAL') => ({id,executionTarget:target,model:`model-${id}`,provider:target==='LOCAL'?'device':'fal',runtime:target==='LOCAL'?'webgpu':'api',estimatedQuality:.86,estimatedLatency:1000,estimatedCost:target==='LOCAL'?0:3,energy:1,memory:1024,reliability:.9});
const observations = {composition:.82,subjectCount:1,facePresence:.9,objectClasses:['person'],lighting:'BALANCED' as const,colorDistribution:[.1,.1,.1,.1,.1,.1,.1,.1,.05,.025,.015,.01],backgroundComplexity:.2,estimatedQuality:.88,depthCues:.8,segmentationComplexity:.3,visualStyle:'LUXURY' as const,requestedStyleSimilarity:.9};
const local = () => new LocalVisualEncoder().encode({width:2400,height:1600,observations});
const input = () => ({context:context(),candidate:candidate(),visual:local(),history:{acceptanceRate:.8,modelSuccessRate:.85,deviceSpecificSuccessRate:.8}});

test('local encoder emits structured versioned visual features',()=>{const result=local();assert.equal(result.schemaVersion,'visual-features-v1');assert.equal(result.encoderVersion,'local-visual-encoder-v1');assert.equal(result.values.length,26);});
test('local encoder does not retain raw pixels',()=>{const rgba=new Uint8ClampedArray(16).fill(128);const result=new LocalVisualEncoder().encode({width:2,height:2,rgba});assert.equal('rgba' in result,false);assert.deepEqual(result.privacy,{rawImageRetained:false,rawImageTransmitted:false,featureOnly:true});});
test('local encoder validates pixel buffer boundaries',()=>assert.throws(()=>new LocalVisualEncoder().encode({width:2,height:2,rgba:new Uint8Array(3)}),/length/));
test('local encoder validates dimensions',()=>assert.throws(()=>new LocalVisualEncoder().encode({width:0,height:10}),/dimensions/));
test('pixel sampling produces lighting and color distribution',()=>{const rgba=new Uint8Array(4*100).fill(240);for(let i=3;i<rgba.length;i+=4)rgba[i]=255;const result=new LocalVisualEncoder().encode({width:10,height:10,rgba});assert.equal(result.observations.lighting,'BRIGHT');assert.equal(result.observations.colorDistribution.length,12);});
test('cloud encoder accepts only local feature representations',()=>{const result=new CloudVisualEncoder().encode({localRepresentation:local(),requestedStyle:'luxury'});assert.equal(result.source,'CLOUD');assert.equal(result.privacy.rawImageTransmitted,false);});
test('cloud encoder rejects recursively supplied cloud features',()=>{const encoder=new CloudVisualEncoder();const cloud=encoder.encode({localRepresentation:local()});assert.throws(()=>encoder.encode({localRepresentation:cloud}),/local feature-only/);});
test('cloud encoder applies an object vocabulary allowlist',()=>{const result=new CloudVisualEncoder().encode({localRepresentation:local(),allowedObjectVocabulary:[]});assert.deepEqual(result.observations.objectClasses,[]);});
test('fusion combines decision visual and cross-modal values',()=>{const result=new MultimodalFusionV3().encode(input());assert.equal(result.version,'decision-representation-v3.0');assert.equal(result.values.length,result.decisionValues.length+result.visualValues.length+6);});
test('fusion has six explicit cross-modal interactions',()=>assert.deepEqual(Object.keys(new MultimodalFusionV3().encode(input()).crossModalInteractions).sort(),['candidate×resolution','goal×visualStyle','operation×segmentation','privacy×visualSource','qualityTarget×visualQuality','runtime×visualComplexity']));
test('fusion rejects representations that claim retained raw images',()=>{const visual={...local(),privacy:{rawImageRetained:true as const,rawImageTransmitted:false as const,featureOnly:true as const}};assert.throws(()=>new MultimodalFusionV3().encode({...input(),visual}),/privacy-safe/);});
test('visual quality predicts four distinct dimensions',()=>{const result=new VisualQualityHead().predict(local());assert.deepEqual(Object.keys(result),['technicalQuality','visualCoherence','identityPreservation','compositionQuality']);assert.ok(Object.values(result).every(value=>value>=0&&value<=1));});
test('visual goal alignment recognizes requested luxury style',()=>{const result=new VisualGoalAlignmentEngine().align(context(),local());assert.equal(result.desiredStyle,'LUXURY');assert.equal(result.currentStyle,'LUXURY');assert.ok(result.similarity>.8);});
test('visual goal alignment reports style gap reasons',()=>{const visual=new LocalVisualEncoder().encode({width:1000,height:1000,observations:{...observations,visualStyle:'CATALOG',lighting:'DARK'}});const result=new VisualGoalAlignmentEngine().align(context(),visual);assert.ok(result.reasons.includes('STYLE_CATALOG_TO_LUXURY'));assert.ok(result.reasons.includes('LIGHTING_TOO_DARK'));});
test('operation predictor can conclude that AI is unnecessary',()=>{const ctx=context('STANDARD','preserve current image');const alignment=new VisualGoalAlignmentEngine().align(ctx,local());const result=new OperationNeedPredictor().predict(ctx,local(),alignment);assert.equal(result.recommendedAction,'NO_AI');assert.ok(result.unnecessaryAIProbability>.65);});
test('operation predictor identifies upscale need',()=>{const visual=new LocalVisualEncoder().encode({width:320,height:240,observations:{...observations,estimatedQuality:.2}});const ctx={...context(),operation:'UPSCALE'};const result=new OperationNeedPredictor().predict(ctx,visual,new VisualGoalAlignmentEngine().align(ctx,visual));assert.equal(result.operations.find(x=>x.operation==='UPSCALE')?.needed,true);});
test('operation predictor identifies relighting need',()=>{const visual=new LocalVisualEncoder().encode({width:1000,height:1000,observations:{...observations,lighting:'DARK'}});const result=new OperationNeedPredictor().predict({...context(),operation:'RELIGHT'},visual,new VisualGoalAlignmentEngine().align(context(),visual));assert.equal(result.operations.find(x=>x.operation==='RELIGHTING')?.needed,true);});
test('multimodal prediction adds visual heads without removing v2 heads',()=>{const result=new MultimodalDecisionModel().predict(input());assert.equal(Object.keys(result.outcomes).length,8);assert.equal(Object.keys(result.visualQuality).length,4);assert.equal(result.representationV3.version,'decision-representation-v3.0');});
test('multimodal ranking is deterministic and descending',()=>{const model=new MultimodalDecisionModel();const rows=model.rank({context:context(),visual:local()},[candidate('cloud','CLOUD'),candidate()]);assert.ok(rows[0].expectedUtility>=rows[1].expectedUtility);assert.deepEqual(rows,model.rank({context:context(),visual:local()},[candidate('cloud','CLOUD'),candidate()]));});
test('LOCAL_ONLY continues to block cloud execution',()=>{const result=new MultimodalDecisionModel().predict({...input(),context:context('LOCAL_ONLY'),candidate:candidate('cloud','CLOUD')});assert.equal(result.expectedUtility,-1);assert.ok(result.explanation.constraintExclusions.includes('CLOUD_FORBIDDEN'));});
test('LOCAL_ONLY also blocks cloud-derived visual features',()=>{const visual=new CloudVisualEncoder().encode({localRepresentation:local()});const result=new MultimodalDecisionModel().predict({...input(),context:context('LOCAL_ONLY'),visual});assert.equal(result.expectedUtility,-1);assert.ok(result.explanation.constraintExclusions.includes('CLOUD_VISUAL_FEATURES_FORBIDDEN'));});
test('quarantine remains outside multimodal scoring',()=>{const result=new MultimodalDecisionModel().predict({...input(),candidate:{...candidate(),quarantined:true}});assert.equal(result.expectedUtility,-1);assert.ok(result.explanation.constraintExclusions.includes('QUARANTINED_MODEL'));});
test('visual counterfactual compares local and cloud without executing',()=>{const result=new MultimodalDecisionModel().counterfactual(input(),candidate('cloud','CLOUD'));assert.equal(result.alternative.candidate.id,'cloud');assert.equal(Object.keys(result.visualQualityDelta).length,4);});
test('facade exposes local/cloud visual encoding and multimodal APIs',()=>{const facade=new CreativeDecisionModel();const visual=facade.encodeVisualLocal({width:2400,height:1600,observations});assert.equal(facade.encodeVisualCloud({localRepresentation:visual}).source,'CLOUD');assert.equal(facade.predictMultimodal({...input(),visual}).representationV3.version,'decision-representation-v3.0');assert.equal(facade.rankMultimodal({context:context(),visual},[candidate()]).length,1);});
test('all multimodal outputs are deeply immutable',()=>{const result=new MultimodalDecisionModel().predict(input());assert.throws(()=>(result.visualQuality.technicalQuality=0));assert.throws(()=>(result.representationV3.values[0]=0));});

for(let scenario=0;scenario<5;scenario++)for(let variant=0;variant<20;variant++)test(`multimodal conformance ${scenario+1}.${variant+1}`,()=>{const privacy=variant%5===0?'LOCAL_ONLY':'STANDARD';const target=variant%4===0?'CLOUD':'LOCAL';const visual=new LocalVisualEncoder().encode({width:400+variant*100,height:300+variant*50,observations:{...observations,composition:variant/19,backgroundComplexity:scenario/4,estimatedQuality:(variant+1)/20}});const request={context:{...context(privacy),operation:`OP_${scenario}`},candidate:candidate(`${scenario}-${variant}`,target),visual};const model=new MultimodalDecisionModel();const first=model.predict(request);assert.deepEqual(first,model.predict(request));assert.ok(first.predictionConfidence>=0&&first.predictionConfidence<=1);assert.ok(Object.values(first.visualQuality).every(Number.isFinite));if(privacy==='LOCAL_ONLY'&&target==='CLOUD'){assert.equal(first.expectedUtility,-1);assert.notEqual(first.action,'EXECUTE');}});
