import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import { HybridDataMinimizer, HybridEscalationPolicy, HybridExecutionEngine, HybridExecutionGraph, HybridLearningSignals, HybridMemory, HybridOptimizer, HybridReplay, HybridScheduler, HybridTargetSelector, HybridVerification, deepFreeze, type ExecutionCandidate, type HybridArtifact, type HybridExecutionNode, type HybridPolicy, type HybridPorts, type InputWorkflow } from '../src/platform/creative/hybrid/index.ts';
const scope = { tenantId: 'tenant', projectId: 'project', userId: 'user' };
const policy = (values: Partial<HybridPolicy> = {}): HybridPolicy => ({ mode: 'AUTO', cloudAllowed: true, outboundImageAllowed: true, cloudDownloadAllowed: true, qualityRequirement: .8, creditBudget: 20, privacyWeight: 2, latencyWeight: 1, energyWeight: 1, reliabilityWeight: 1, speculativeLocal: true, ...values });
const metrics = (values = {}) => ({ quality: .9, monetaryCost: 0, deviceCost: .1, energyCost: .1, latencyMs: 100, privacyExposure: 0, reliability: .95, deviceLoad: .1, providerHealth: 1, ...values });
const local = (values: Partial<ExecutionCandidate> = {}): ExecutionCandidate => ({ target: 'LOCAL', localModel: 'trusted-model', trustedModel: true, metrics: metrics(), ...values });
const cloud = (values: Partial<ExecutionCandidate> = {}): ExecutionCandidate => ({ target: 'CLOUD', cloudProvider: 'fal', providerAvailable: true, metrics: metrics({ quality: .96, monetaryCost: 4, deviceCost: 0, energyCost: 0, latencyMs: 250, privacyExposure: 1 }), ...values });
const workflow = (values: Partial<InputWorkflow> = {}): InputWorkflow => ({ id: 'wf', scope, policy: policy(), nodes: [{ id: 'segment', operation: 'segmentation', candidates: [local(), cloud()], reversible: true }, { id: 'generate', operation: 'generation', dependencies: ['segment'], candidates: [cloud()], requiredPayload: 'MASK_ONLY' }, { id: 'upscale', operation: 'upscale', dependencies: ['generate'], candidates: [local(), cloud()], reversible: true }], ...values });
const artifact = (producerNodeId: string, values: Partial<HybridArtifact> = {}): HybridArtifact => ({ id: `a-${producerNodeId}`, kind: 'image', value: { pixels: producerNodeId }, hash: `hash:${producerNodeId}`, mimeType: 'image/png', width: 10, height: 10, alpha: true, metadata: { producerNodeId }, scope, ...values });
const ports = (options: { localQuality?: number; localFail?: boolean } = {}): HybridPorts => ({ now: () => 1, resources: async () => ({ cpuLoad: .1, gpuLoad: .1, ramAvailableMb: 4096, vramAvailableMb: 2048, batteryPercent: 80, thermal: 'NORMAL', networkLatencyMs: 30 }), local: { execute: async (node) => { if (options.localFail) throw new Error('local failed'); const value = artifact(node.id); return { artifact: value, quality: options.localQuality ?? .9, latencyMs: 10, energy: 1, cost: 0 }; } }, cloud: { execute: async (node) => { const value = artifact(node.id); return { artifact: value, quality: .98, latencyMs: 20, energy: 0, cost: 4 }; } }, hash: async (value) => `hash:${(value as { pixels: string }).pixels}` });
const node = (values: Partial<HybridExecutionNode> = {}): HybridExecutionNode => ({ id: 'n', operation: 'x', executionTarget: 'LOCAL', localModel: 'm', dependencies: [], fallback: [cloud()], verification: { minQuality: .8, requireHash: true, allowedMimeTypes: ['image/png'] }, cost: 0, latency: 1, privacy: 0, candidate: local(), speculative: true, status: 'PENDING', ...values });

const categories = ['select-local', 'select-cloud', 'local-only', 'cloud-only', 'untrusted', 'graph', 'boundaries', 'minimization', 'scheduler', 'thermal', 'escalation', 'verification', 'memory', 'signals', 'optimization', 'simulation', 'execution', 'fallback', 'snapshot', 'immutability'] as const;
for (const category of categories) for (let variant = 1; variant <= 9; variant += 1) test(`${category} deterministic case ${variant}`, async () => {
  if (category === 'select-local') assert.equal(new HybridTargetSelector().select([local(), cloud()], policy()).target, 'LOCAL');
  if (category === 'select-cloud') assert.equal(new HybridTargetSelector().select([local({ metrics: metrics({ quality: .2 }) }), cloud()], policy()).target, 'CLOUD');
  if (category === 'local-only') assert.equal(new HybridTargetSelector().select([local(), cloud()], policy({ mode: 'LOCAL_ONLY' })).target, 'LOCAL');
  if (category === 'cloud-only') assert.equal(new HybridTargetSelector().select([local(), cloud()], policy({ mode: 'CLOUD_ONLY' })).target, 'CLOUD');
  if (category === 'untrusted') assert.equal(new HybridTargetSelector().select([local({ trustedModel: false })], policy()).target, 'BLOCKED');
  if (category === 'graph') assert.deepEqual(new HybridExecutionGraph().create(workflow()).stages.map((stage) => stage.nodeIds), [['segment'], ['generate'], ['upscale']]);
  if (category === 'boundaries') { const graph = new HybridExecutionGraph().create(workflow()); assert.equal(graph.edges[0].imageLeavesDevice, true); assert.equal(graph.edges[0].payload, 'MASK_ONLY'); }
  if (category === 'minimization') assert.equal(new HybridDataMinimizer().select('FULL_IMAGE', true), 'CROPPED_IMAGE');
  if (category === 'scheduler') { const graph = new HybridExecutionGraph().create(workflow()); assert.equal(new HybridScheduler().schedule(graph, await ports().resources()).stages.length, 3); }
  if (category === 'thermal') { const graph = new HybridExecutionGraph().create(workflow()); const resources = { ...(await ports().resources()), thermal: 'CRITICAL' as const }; assert.equal(new HybridScheduler().schedule(graph, resources).stages[1].strategy, 'CLOUD_FIRST'); }
  if (category === 'escalation') assert.equal(new HybridEscalationPolicy().reason(node(), 'quality insufficient', policy()), 'quality insufficient');
  if (category === 'verification') assert.equal((await new HybridVerification().verify(artifact('n'), scope, ports().hash)).valid, true);
  if (category === 'memory') { const memory = new HybridMemory(); memory.record({ operation: 'x', latency: variant, quality: .9, cost: 0, energy: 1, fallbackRate: 0 }); assert.equal(memory.aggregate('x').count, 1); }
  if (category === 'signals') assert.ok(new HybridLearningSignals().derive('LOCAL', { quality: 1, cost: 0, latency: 1 }, { quality: 1, cost: 4, latency: 4 }).includes('CLOUD_AVOIDED'));
  if (category === 'optimization') assert.equal(new HybridOptimizer().optimize(new HybridExecutionGraph().create(workflow()), policy()).nodes.length, 3);
  if (category === 'simulation') assert.equal(new HybridOptimizer().simulate(new HybridExecutionGraph().create(workflow())).length, 4);
  if (category === 'execution') { const result = await new HybridExecutionEngine(ports()).execute(workflow()); assert.equal(result.results.length, 3); assert.equal(result.results.every((item) => !item.error), true); }
  if (category === 'fallback') { const result = await new HybridExecutionEngine(ports({ localQuality: .1 })).execute(workflow()); assert.ok(result.metrics.fallbackCount >= 1); assert.ok(result.signals.includes('CLOUD_ESCALATED')); }
  if (category === 'snapshot') { const engine = new HybridExecutionEngine(ports()); const result = await engine.execute(workflow()); assert.deepEqual(engine.snapshot(), result); assert.deepEqual(new HybridReplay().replay(result), result); }
  if (category === 'immutability') { const frozen = deepFreeze({ nested: { value: variant } }); assert.ok(Object.isFrozen(frozen.nested)); }
});

test('security invariants and scope isolation fail closed', async () => { const localOnly = workflow({ policy: policy({ mode: 'LOCAL_ONLY', cloudAllowed: false, outboundImageAllowed: false }) }); const graph = new HybridExecutionGraph().create(localOnly); assert.equal(graph.nodes.some((item) => item.executionTarget === 'CLOUD'), false); const blocked = new HybridTargetSelector().select([cloud()], policy({ cloudAllowed: false })); assert.equal(blocked.target, 'BLOCKED'); await assert.rejects(() => new HybridVerification().verify(artifact('x', { scope: { ...scope, projectId: 'foreign' } }), scope, ports().hash).then((value) => { if (!value.valid) throw new Error('scope rejected'); }), /scope rejected/); });
test('invalid graph dependencies and cycles are rejected', () => { assert.throws(() => new HybridExecutionGraph().create(workflow({ nodes: [{ id: 'x', operation: 'x', dependencies: ['missing'], candidates: [local()] }] })), /Unknown dependency/); assert.throws(() => new HybridExecutionGraph().create(workflow({ nodes: [{ id: 'a', operation: 'x', dependencies: ['b'], candidates: [local()] }, { id: 'b', operation: 'x', dependencies: ['a'], candidates: [local()] }] })), /cycle/); });
test('hybrid scope contains no forbidden dependencies, secrets, network, or filesystem access', async () => { for (const file of await collect('src/platform/creative/hybrid')) { const source = (await readFile(file, 'utf8')).toLowerCase(); for (const marker of ["from '../decision", "from '../planning", "from '../execution", "from '../providers", "from '../local-ai", 'api_key', 'node:fs', 'node:http', 'fetch(', 'axios']) assert.equal(source.includes(marker), false, `${file} contains ${marker}`); } });
async function collect(directory: string): Promise<string[]> { const entries = await readdir(directory, { withFileTypes: true }); return (await Promise.all(entries.map((entry) => entry.isDirectory() ? collect(join(directory, entry.name)) : Promise.resolve(entry.name.endsWith('.ts') ? [join(directory, entry.name)] : [])))).flat(); }
