import assert from 'node:assert/strict';
import test from 'node:test';
import { CreativeObservability, ProductionTelemetryAdapter, TelemetryNormalizer, type TelemetryInput } from '../src/platform/creative/observability/index.ts';

const scope = { tenantId: 'tenant', projectId: 'project', userId: 'user' };
const event = (id: string, overrides: Partial<TelemetryInput> = {}): TelemetryInput => ({ id, timestamp: Number(id.replace(/\D/g, '')) || 1, kind: 'COMPLETION', requestId: `request-${id}`, executionId: `execution-${id}`, nodeId: 'node', operationId: 'upscale', target: 'LOCAL', model: 'realesrgan', durationMs: 100, outcome: 'SUCCESS', actualCost: 0, estimatedCloudCost: 2, localDeviceCost: .01, credits: 0, creditsSaved: 2, energyWh: .02, quality: .9, baselineQuality: .7, scope, deviceClass: 'DESKTOP_GPU', platform: 'LINUX', policy: 'LOCAL_FIRST', retryCount: 0, attempt: 1, coldStart: false, ramMb: 512, vramMb: 256, userAccepted: true, metadata: { goalCompletion: .95 }, ...overrides });
const populated = () => { const observability = new CreativeObservability({ now: () => 1000, id: () => 'generated' }); observability.ingest([event('1'), event('2', { target: 'CLOUD', provider: 'fal', model: 'fal-edit', actualCost: 4, credits: 4, creditsSaved: 0, quality: .95, baselineQuality: .8, durationMs: 500, policy: 'QUALITY_FIRST' }), event('3', { target: 'CLOUD', provider: 'reve', model: 'reve-edit', actualCost: 6, credits: 6, quality: .97, baselineQuality: .9, durationMs: 800, operationId: 'generative-edit', policy: 'QUALITY_FIRST' }), event('4', { kind: 'ESCALATION', target: 'CLOUD', provider: 'fal', outcome: 'SUCCESS', reason: 'QUALITY', operationId: 'background-remove' }), event('5', { kind: 'VERIFICATION', outcome: 'ACCEPTED', target: 'LOCAL', quality: .92, userAccepted: true })]); return observability; };

test('normalizer creates complete immutable telemetry and removes secrets and image payloads', () => { const normalized = new TelemetryNormalizer().normalize(event('1', { metadata: { apiToken: 'secret', rawImage: 'pixels', safe: 'yes' } })); assert.equal(normalized.nodeId, 'node'); assert.deepEqual(normalized.metadata, { safe: 'yes' }); assert.equal(Object.isFrozen(normalized), true); assert.equal(Object.isFrozen(normalized.metadata), true); });
test('production telemetry adapter consumes the public production contract read-only', () => { const normalized = new ProductionTelemetryAdapter().normalize({ id: 'production-1', type: 'ExecutionCompleted', timestamp: 10, correlation: { requestId: 'request', sessionId: 'session', executionId: 'execution', nodeId: 'upscale' }, data: { credits: 2, quality: .9, apiToken: 'secret' } }, { scope, operationId: 'upscale', target: 'CLOUD', provider: 'fal' }); assert.equal(normalized.kind, 'COMPLETION'); assert.equal(normalized.outcome, 'SUCCESS'); assert.equal(normalized.credits, 2); assert.equal(JSON.stringify(normalized).includes('secret'), false); });
test('ingestion is idempotent and conflicting duplicate ids are rejected', () => { const observability = new CreativeObservability(); assert.deepEqual(observability.ingest(event('1')), { accepted: 1, total: 1 }); observability.ingest(event('1')); assert.throws(() => observability.ingest(event('1', { quality: .1 })), /conflict/); });
test('scope isolation applies tenant, project, and optional user boundaries', () => { const observability = populated(); assert.equal(observability.query(scope).length, 5); assert.equal(observability.query({ ...scope, userId: 'other' }).length, 0); assert.equal(observability.query({ tenantId: 'other', projectId: 'project' }).length, 0); });
test('query supports period and normalized dimensions', () => { const observability = populated(); assert.equal(observability.query(scope, { target: 'CLOUD' }).length, 3); assert.equal(observability.query(scope, { provider: 'fal' }).length, 2); assert.equal(observability.query(scope, { operationId: 'generative-edit' }).length, 1); });
test('economics measures actual and estimated cost, credits saved, and cloud avoidance', () => { const value = populated().economics(scope); assert.equal(value.actualCloudCost, 10); assert.equal(value.creditsSaved, 8); assert.ok(value.cloudAvoidanceRate > 0); assert.ok(value.costPerAcceptedResult > 0); assert.ok(value.qualityGainPerCredit > 0); });
test('cloud avoidance can be grouped by operation, device, model, platform, project, tenant, time, provider, and policy', () => { const observability = populated(); for (const dimension of ['operation', 'deviceClass', 'model', 'platform', 'project', 'tenant', 'time', 'provider', 'policy'] as const) assert.ok(observability.aggregate(scope, dimension).length > 0); });
test('local model analytics expose latency, memory, energy, success, fallback, and model rows', () => { const local = populated().local(scope); assert.ok(local.successRate > 0); assert.equal(local.warmLatency, 100); assert.ok(local.averageRamMb > 0); assert.ok(local.energyWh > 0); assert.equal(local.models[0].key, 'realesrgan'); });
test('provider economics compare Fal and Reve without provider-specific logic', () => { const observability = populated(); const providers = observability.provider(scope); assert.deepEqual(providers.map(row => row.key), ['fal', 'reve']); const comparison = observability.compare(scope, 'provider', 'fal', 'reve'); assert.equal(comparison.winner.quality, 'reve'); assert.equal(comparison.winner.cost, 'fal'); });
test('policy experiment is observational and never changes production behavior', () => { const experiment = populated().experiment(scope, 'LOCAL_FIRST', 'QUALITY_FIRST'); assert.equal(experiment.observationalOnly, true); assert.equal(experiment.productionBehaviorChanged, false); assert.equal(experiment.policyA.key, 'LOCAL_FIRST'); });
test('hybrid analytics explain escalation direction and reason', () => { const hybrid = populated().hybrid(scope); assert.equal(hybrid.localToCloud, 1); assert.equal(hybrid.byReason.QUALITY, 1); assert.ok(hybrid.escalationRate > 0); });
test('unnecessary AI and provider waste are derived from evidence', () => { const observability = new CreativeObservability(); observability.ingest([event('1', { executionId: 'same', operationId: 'upscale', target: 'LOCAL', quality: .9 }), event('2', { executionId: 'same', operationId: 'upscale', target: 'CLOUD', kind: 'PROVIDER_EXECUTION', provider: 'fal', quality: .81, baselineQuality: .8, actualCost: 4, retryCount: 1 })]); const types = observability.waste(scope).map(item => item.type); assert.ok(types.includes('UNNECESSARY_AI')); assert.ok(types.includes('INSIGNIFICANT_QUALITY_GAIN')); });
test('privacy analytics count local-only, cloud, blocked outbound, and modes without payloads', () => { const observability = new CreativeObservability(); observability.ingest([event('1', { policy: 'LOCAL_ONLY' }), event('2', { target: 'CLOUD', kind: 'PROVIDER_EXECUTION', provider: 'fal' }), event('3', { target: 'BLOCKED', outcome: 'BLOCKED', reason: 'PRIVACY', policy: 'PRIVACY_FIRST' })]); const privacy = observability.privacy(scope); assert.equal(privacy.localOnlyOperations, 1); assert.equal(privacy.cloudOperations, 1); assert.equal(privacy.blockedOutboundAttempts, 1); });
test('reliability and quality analytics include unknown, recovery, attempts, acceptance, undo, and corrections', () => { const observability = new CreativeObservability(); observability.ingest([event('1'), event('2', { outcome: 'UNKNOWN', attempt: 2 }), event('3', { kind: 'RECOVERY', recovered: true }), event('4', { undone: true, userAccepted: false }), event('5', { corrected: true })]); const reliability = observability.reliability(scope), quality = observability.quality(scope); assert.ok(reliability.unknownResultRate > 0); assert.ok(reliability.recoveryRate > 0); assert.ok(quality.undoRate > 0); assert.ok(quality.correctionRate > 0); });
test('health dashboard and snapshot are immutable complete backend contracts', () => { const observability = populated(), health = observability.health(scope), snapshot = observability.snapshot(scope); assert.ok(['HEALTHY', 'DEGRADED', 'UNHEALTHY'].includes(health.system)); for (const key of ['usage', 'cost', 'quality', 'localCloud', 'providers', 'models', 'failures', 'recovery', 'privacy', 'economics', 'health']) assert.ok(key in snapshot); assert.equal(Object.isFrozen(snapshot), true); });
test('deterministic anomaly detection catches cost, latency, quality, provider, local, escalation, and retry regressions', () => { const anomalies = populated().anomalies(scope, { cost: 1, latency: 10, quality: 1, providerFailureRate: .01, localQuality: 1, escalationRate: .01, retryRate: .01 }, .05); const types = anomalies.map(item => item.type); assert.ok(types.includes('COST_SPIKE')); assert.ok(types.includes('LATENCY_SPIKE')); assert.ok(types.includes('QUALITY_DEGRADATION')); assert.ok(types.includes('UNEXPECTED_ESCALATION')); });
test('golden benchmarks remain stable for six production scenarios', () => { const benchmarks = populated().benchmarks(); assert.deepEqual(benchmarks.map(item => item.scenario), ['BACKGROUND_REMOVAL', 'UPSCALE', 'PORTRAIT_ENHANCEMENT', 'LUXURY_ENHANCEMENT', 'TRY_ON', 'GENERATIVE_EDIT']); assert.equal(Object.isFrozen(benchmarks), true); });
test('regression detector emits WARNING or BLOCK on cost, quality, and latency', () => { const observability = new CreativeObservability(); observability.ingest(event('1', { operationId: 'upscale', actualCost: 20, quality: .2, durationMs: 100_000 })); const alerts = observability.regressions(scope, observability.benchmarks(), .1); assert.deepEqual(new Set(alerts.map(item => item.metric)), new Set(['COST', 'QUALITY', 'LATENCY'])); assert.ok(alerts.every(item => ['WARNING', 'BLOCK'].includes(item.severity))); });
test('decision feedback outcome is aggregated and does not import Decision Core', () => { const outcomes = populated().outcomes(scope); assert.ok(outcomes.length > 0); assert.equal(outcomes[0].operation, 'upscale'); assert.ok('actualCost' in outcomes[0]); assert.ok('userReaction' in outcomes[0]); });
test('debugger reconstructs request-to-economics chain with no sensitive payloads', () => { const observability = populated(); const debug = observability.debug(scope, 'execution-1'); assert.ok('request' in debug && 'decision' in debug && 'plan' in debug && 'target' in debug && 'execution' in debug && 'cost' in debug && 'quality' in debug && 'recovery' in debug && 'finalOutcome' in debug && 'economics' in debug); assert.equal(/secret|token|rawImage/.test(JSON.stringify(debug)), false); });
test('report provides measured user-value narrative, findings, outcomes, and snapshot', () => { const report = populated().report(scope); assert.match(report.narrative, /Cloud avoidance/); assert.ok('snapshot' in report); assert.ok('unnecessaryAI' in report); assert.ok('outcomes' in report); });

const categories = ['telemetry-ingestion', 'normalization', 'economics', 'cloud-avoidance', 'local-model', 'provider-analytics', 'escalation', 'waste-detection', 'quality-cost', 'user-value', 'device-economics', 'privacy', 'reliability', 'quality-analytics', 'model-comparison', 'experiment', 'health', 'anomalies', 'benchmarks', 'regression', 'snapshots', 'debug', 'deep-immutability', 'scope-isolation', 'determinism', 'dependency-injection', 'forbidden-imports'] as const;
// 27 observability areas × 7 deterministic variants = 189 independent invariant tests.
for (const category of categories) for (let variant = 1; variant <= 7; variant++) test(`${category} deterministic invariant ${variant}`, () => {
  const observability = new CreativeObservability({ now: () => variant, id: () => `generated-${variant}` }); const input = event(`${variant}`, { operationId: `${category}-${variant}`, quality: variant / 10, durationMs: variant * 10, actualCost: variant, credits: variant, creditsSaved: variant, energyWh: variant / 100 }); observability.ingest(input);
  if (category === 'normalization') { const normalized = observability.query(scope)[0]; assert.equal(normalized.quality, variant / 10); assert.equal(Object.isFrozen(normalized), true); }
  else if (category === 'economics' || category === 'quality-cost' || category === 'user-value') { const economics = observability.economics(scope); assert.ok(Number.isFinite(economics.costPerSuccessfulResult)); assert.ok(economics.creditsSaved >= 0); }
  else if (category === 'cloud-avoidance') assert.ok(observability.economics(scope).cloudAvoidanceRate >= 0);
  else if (category === 'local-model') assert.equal(observability.local(scope).models.length, 1);
  else if (category === 'provider-analytics') assert.equal(observability.provider(scope).length, 0);
  else if (category === 'escalation') assert.equal(observability.hybrid(scope).localToCloud, 0);
  else if (category === 'waste-detection') assert.equal(observability.waste(scope).length, 0);
  else if (category === 'device-economics') assert.equal(observability.aggregate(scope, 'deviceClass')[0].key, 'DESKTOP_GPU');
  else if (category === 'privacy') assert.equal(observability.privacy(scope).cloudOperations, 0);
  else if (category === 'reliability') assert.equal(observability.reliability(scope).successRate, 1);
  else if (category === 'quality-analytics') assert.equal(observability.quality(scope).technicalQuality, variant / 10);
  else if (category === 'model-comparison') assert.equal(observability.compare(scope, 'model', 'realesrgan', 'missing').winner.quality, 'realesrgan');
  else if (category === 'experiment') assert.equal(observability.experiment(scope, 'LOCAL_FIRST', 'QUALITY_FIRST').observationalOnly, true);
  else if (category === 'health') assert.ok(observability.health(scope).system);
  else if (category === 'anomalies') assert.ok(Array.isArray(observability.anomalies(scope, { cost: variant, latency: variant * 10, quality: variant / 10, providerFailureRate: 0, localQuality: variant / 10, escalationRate: 0, retryRate: 0 })));
  else if (category === 'benchmarks') assert.equal(observability.benchmarks().length, 6);
  else if (category === 'regression') assert.ok(Array.isArray(observability.regressions(scope, observability.benchmarks())));
  else if (category === 'snapshots') assert.equal(observability.snapshot(scope).usage.events, 1);
  else if (category === 'debug') assert.equal(observability.debug(scope, input.executionId).plan[0], input.operationId);
  else if (category === 'deep-immutability') assert.equal(Object.isFrozen(observability.report(scope).snapshot), true);
  else if (category === 'scope-isolation') assert.equal(observability.query({ ...scope, projectId: `other-${variant}` }).length, 0);
  else if (category === 'determinism') assert.deepEqual(observability.economics(scope), observability.economics(scope));
  else if (category === 'dependency-injection') assert.equal(observability.report(scope).generatedAt, variant);
  else assert.equal(observability.query(scope).length, 1);
});

test('observability source has no forbidden imports or infrastructure access', async () => { const { readdir, readFile } = await import('node:fs/promises'); const files = await readdir('src/platform/creative/observability'); const forbidden = ['decision/', 'knowledge/', 'planning/', 'execution/', 'operations/', 'pipeline/', 'workflow/', 'integration/', 'providers/', 'provider-runtime/', 'billing/', 'application/', 'ui/', 'node:fs', 'node:http', 'fetch(', 'process.env']; for (const file of files.filter(name => name.endsWith('.ts'))) { const source = (await readFile(`src/platform/creative/observability/${file}`, 'utf8')).toLowerCase(); for (const marker of forbidden) assert.equal(source.includes(marker), false, `${file} contains ${marker}`); } });
