import assert from "node:assert/strict";
import test from "node:test";
import { CreativeDNAEngine, CreativeDiscoveryEngine, CreativeReasoningTree, CreativeSatisfactionModel, CreativeStrategyLibrary,
  CreativeWorldModel, DecisionArchetypeEngine, DecisionEconomics, DecisionFatigueModel, DecisionGraphMemory,
  DecisionPatternDiscovery, DecisionProvenance, DecisionSelfCritic, DecisionSimulator, HeuristicDecisionModel,
  LongTermLearning, MetaLearningEngine, ReversePlanningEngine, StyleSpace, UnifiedIntelligenceDebuggerV4,
  INTELLIGENCE_V4_STAGES, type LearningEvent } from "../src/platform/creative/decision/intelligence/core/index";

const scope = { tenantId: "tenant", projectId: "project", userId: "user" };
const events: readonly LearningEvent[] = Object.freeze(Array.from({ length: 8 }, (_, index) => Object.freeze({ id: `e${index}`, ...scope,
  intent: index < 6 ? "Luxury" : "Catalog", operations: Object.freeze(["lighting", "contrast"]), strategy: "Premium",
  outcome: index === 6 ? "UNDO" as const : "ACCEPTED" as const, quality: .8 + index / 100, cost: 2 + index, latency: 100 + index,
  satisfaction: .75, createdAt: index * 100 })));

test("decision graph traverses, ranks, clusters and exports immutable scoped knowledge", () => { const graph = new DecisionGraphMemory();
  ["decision", "intent", "goal"].forEach((id, index) => graph.add({ id, ...scope, kind: (["DECISION", "INTENT", "GOAL"] as const)[index], label: id }));
  const edge = (from: string, to: string) => graph.connect({ from, to, weight: 1, frequency: 2, success: .8, cost: 2, satisfaction: .9, confidence: .8, quality: .9 }); edge("decision", "intent"); edge("intent", "goal");
  assert.deepEqual(graph.shortestPath("decision", "goal", scope).map(({ id }) => id), ["decision", "intent", "goal"]); assert.equal(graph.findRelated("decision", scope, 2).length, 2); assert.equal(graph.centralNodes(scope)[0].id, "intent"); assert.equal(graph.communityDetection(scope).length, 1); assert.equal(Object.isFrozen(graph.exportSubgraph(["decision", "intent"], scope).nodes), true); });
test("graph rejects cross-tenant connections", () => { const graph = new DecisionGraphMemory(); graph.add({ id: "a", ...scope, kind: "DECISION", label: "a" }); graph.add({ id: "b", ...scope, tenantId: "other", kind: "GOAL", label: "b" }); assert.throws(() => graph.connect({ from: "a", to: "b", weight: 1, frequency: 1, success: 1, cost: 0, satisfaction: 1, confidence: 1, quality: 1 })); });
test("pattern discovery derives strength, lifetime, stability and confidence", () => { const pattern = new DecisionPatternDiscovery().discover(events, 1000).find(({ sequence }) => sequence[0] === "Luxury")!; assert.equal(pattern.frequency, 6); assert.ok(pattern.strength > 0 && pattern.confidence > 0); assert.equal(pattern.lifetime, 1000); assert.equal(Object.isFrozen(pattern.sequence), true); });
test("archetypes are generated dynamically and merge", () => { const engine = new DecisionArchetypeEngine(), values = engine.create(events), merged = engine.merge(values[0], values[1]); assert.equal(values.length, 2); assert.equal(merged.members, 8); assert.ok(merged.typicalOperations.includes("lighting")); });
test("DNA evolves gradually through versioned generations", () => { const next = new CreativeDNAEngine().evolve({ version: 1, style: { warmth: .5 }, risk: .5, creativity: .5, aiTrust: .5, automation: .5, samples: 0 }, { style: { warmth: 1 }, risk: 1 }, .1); assert.equal(next.version, 2); assert.equal(next.parentVersion, 1); assert.equal(next.style.warmth, .55); assert.equal(next.risk, .55); });
test("simulator creates at least ten pre-execution futures", () => { const result = new DecisionSimulator().simulate({ operations: ["lighting", "contrast", "upscale"], baselineQuality: .5 }); assert.equal(result.length, 10); assert.ok(result.every(({ probability, quality }) => probability <= 1 && quality <= 1)); assert.equal(Object.isFrozen(result), true); });
test("economics distinguishes justified and wasteful AI", () => { const economics = new DecisionEconomics(); assert.equal(economics.analyze({ baselineQuality: .5, expectedQuality: .9, cost: 5, mode: "AI" }).recommendation, "AI_JUSTIFIED"); assert.equal(economics.analyze({ baselineQuality: .5, expectedQuality: .51, cost: 50, mode: "AI" }).recommendation, "AI_WASTE"); });
test("meta learning compares prediction with reality and adapts statistics", () => { const result = new MetaLearningEngine().learn({ quality: .5, satisfaction: .5, utility: .5, confidence: .5 }, { quality: .8, satisfaction: .7, utility: .6, confidence: .8 }, { weights: {}, thresholds: {}, samples: 0 }); assert.equal(result.state.samples, 1); assert.ok(result.errors.predictionError > 0); assert.ok(result.state.weights.quality > .5); });
test("long-term learning forgets older events", () => { const result = new LongTermLearning().analyze(events, 10_000, 100); assert.ok(result.effectiveEvents[7].weight > result.effectiveEvents[0].weight); assert.ok(result.experience < events.length); });
test("fatigue separates four overloads and recommends intervention", () => { const result = new DecisionFatigueModel().assess({ choices: 30, confirmations: 20, creativeBranches: 30, decisions: 50 }); assert.equal(result.recommendation, "AUTOMATIC_MODE"); assert.equal(result.score, 1); });
test("satisfaction remains separate from technical quality", () => { const result = new CreativeSatisfactionModel().assess({ technicalQuality: 1, creativeQuality: .2, goalCompletion: .7, userSatisfaction: .3, confidenceSatisfaction: .8, expectedSatisfaction: .9 }); assert.notEqual(result.satisfaction, result.technicalQuality); assert.ok(result.expectationGap < 0); });
test("reverse planning derives operations from desired style", () => { const result = new ReversePlanningEngine().plan({ desiredResult: "premium portrait", targetStyle: { warmth: .9, premium: 1 }, requiredQuality: .9, availableOperations: ["white_balance", "lighting", "skin_cleanup"] }); assert.ok(result.requiredOperations.includes("lighting")); assert.equal(result.executionPlan[0].order, 1); });
test("reasoning tree expands, prunes, compares and selects", () => { const result = new CreativeReasoningTree().build("portrait", ["premium"], [{ id: "a", alternative: "local", confidence: .2, utility: .9, explanation: "cheap" }, { id: "b", alternative: "hybrid", confidence: .9, utility: .8, explanation: "balanced" }]); assert.equal(result.pruning[0].pruningReason, "LOW_CONFIDENCE"); assert.equal(result.selection?.id, "b"); });
test("self critic never mutates selected decision", () => { const selected = Object.freeze({ id: "a", quality: .8, risk: .4, cost: 4, operations: Object.freeze(["light"]) }); const result = new DecisionSelfCritic().critique(selected, [selected, { id: "b", quality: .9, risk: .2, cost: 3, operations: [] }]); assert.equal(selected.quality, .8); assert.deepEqual(result.missedOpportunities, ["b"]); });
test("strategy library supplies all requested base strategies", () => { const library = new CreativeStrategyLibrary(); assert.equal(library.list().length, 11); assert.equal(library.get("luxury")?.name, "Luxury"); assert.equal(Object.isFrozen(library.list()), true); });
test("heuristic DecisionModel supports its complete replaceable contract", () => { const model = new HeuristicDecisionModel(); const candidate = { id: "a", features: { quality: .9, creativity: .7 }, cost: 2 }; model.train([]); assert.equal(model.rank([candidate])[0].id, "a"); assert.ok(model.predict(candidate).quality > 0); assert.equal(model.simulate([candidate]).length, 1); model.adapt({ id: "s", features: {}, quality: .8, satisfaction: .8, accepted: true, cost: 1 }); const exported = model.exportDataset(); model.importDataset(exported); model.calibrate([.5], [.6]); assert.ok(model.explain(candidate)); assert.equal(model.version(), "heuristic-1.0"); });
test("world model stores updatable knowledge rather than episodes", () => { const world = new CreativeWorldModel(); world.update({ from: "Luxury", to: "warm lighting", relation: "requires", weight: .8, evidence: 2 }); world.update({ from: "Luxury", to: "warm lighting", relation: "requires", weight: 1, evidence: 2 }); assert.equal(world.query("Luxury")[0].weight, .9); assert.equal(Object.isFrozen(world.export()), true); });
test("style space represents styles as multidimensional points", () => { const space = new StyleSpace(), a = space.point({ warmth: 1 }), b = space.point({ warmth: 0 }); assert.equal(Object.keys(a).length, 11); assert.ok(space.distance(a, b) > 0); assert.equal(space.interpolate(a, b, .5).warmth, .5); });
test("provenance normalizes causal contributions", () => { const result = new DecisionProvenance().calculate({ Preference: 18, Knowledge: 23, History: 16, Pattern: 27, Rules: 9, Simulation: 7 }); assert.equal(Object.values(result).reduce((sum, value) => sum + value, 0), 1); assert.equal(result.Pattern, .27); });
test("discovery ranks novel, diverse, unexpected creative options", () => { const result = new CreativeDiscoveryEngine().discover([{ id: "ordinary", features: { a: .5, b: .5 } }, { id: "novel", features: { a: 1, b: 0 } }]); assert.equal(result[0].candidate.id, "novel"); assert.ok(result[0].creative > 0); });
test("debugger v4 emits the complete immutable intelligence chain", () => { const debuggerV4 = new UnifiedIntelligenceDebuggerV4(), trace = debuggerV4.trace({ Prompt: "Luxury" }); assert.equal(trace.length, 23); assert.deepEqual(trace.map(({ stage }) => stage), INTELLIGENCE_V4_STAGES); assert.equal(debuggerV4.explain(trace).complete, true); assert.equal(Object.isFrozen(trace), true); });

// A deterministic matrix guards repeatability and immutable style normalization across 100 independent cases.
for (let index = 0; index < 100; index++) test(`determinism and immutability matrix ${String(index + 1).padStart(3, "0")}`, () => { const style = new StyleSpace(), input = { warmth: (index % 11) / 10, luxury: ((index * 7) % 11) / 10 }, first = style.point(input), second = style.point(input); assert.deepEqual(first, second); assert.equal(Object.isFrozen(first), true); assert.ok(Object.values(first).every((value) => value >= 0 && value <= 1)); });
