import assert from 'node:assert/strict';
import test from 'node:test';
import { CreativeDecisionModel, DecisionConstraintLayer, DecisionDatasetBuilder, DecisionFeatureEncoderV1, DecisionModelEvaluator, DecisionModelRegistry, DecisionTrainerV1, HeuristicBaselineModel, TabularDecisionModelV1, calculateReward, decisionRegret } from '../src/platform/creative/model';
import type { DecisionCandidateV1, DecisionContextV1, DecisionDatasetRecord, DecisionFeaturesV1 } from '../src/platform/creative/model';

const context = (projectId = 'p1', privacyMode: DecisionContextV1['privacyMode'] = 'NORMAL'): DecisionContextV1 => ({ operation: 'upscale', intent: 'repair', goal: 'quality', deviceClass: 'desktop', platform: 'web', projectType: 'portrait', privacyMode, budget: 10, latencyTarget: 5000, qualityTarget: .8, projectId, deviceId: `device-${projectId}`, timestamp: 1 });
const candidate = (id = 'local', target: DecisionCandidateV1['executionTarget'] = 'LOCAL'): DecisionCandidateV1 => ({ id, executionTarget: target, model: `model-${id}`, provider: target === 'LOCAL' ? 'local' : 'cloud', runtime: 'WEBGPU', estimatedQuality: id === 'good' ? .95 : .7, estimatedLatency: 1000, estimatedCost: target === 'LOCAL' ? 0 : 2, energy: .2, memory: 1024, reliability: .9 });
const features = (id = 'local'): DecisionFeaturesV1 => ({ context: context(), candidate: candidate(id), history: { modelSuccessRate: .8, providerSuccessRate: .8, deviceSpecificSuccessRate: .7, cloudAvoidance: .7, acceptanceRate: .8, undoRate: .1 } });
const records = (): readonly DecisionDatasetRecord[] => Array.from({ length: 15 }, (_, index) => { const input = features(index % 2 ? 'good' : `candidate-${index}`); const projectId = `project-${Math.floor(index / 3)}`; return { id: `r${index}`, features: { ...input, context: context(projectId) }, context: context(projectId), candidate: input.candidate, decision: input.candidate.id, actualOutcome: { quality: index % 2 ? .95 : .6, success: index % 3 !== 0, accepted: index % 2 === 1, latency: 800 + index * 10, cost: index % 2, escalated: false }, reward: index % 2 ? 5 : 2, timestamp: index, modelVersion: 'v0', projectId, deviceId: `device-${projectId}` }; });

test('dataset builder creates immutable ML records', () => { const data = new DecisionDatasetBuilder({}, () => 10).fromOutcomes([{ operation: 'upscale', selectedTarget: 'LOCAL', actualOutcome: 'SUCCESS', actualCost: 0, actualQuality: .9, actualLatency: 12, userReaction: 'ACCEPTED' }]); assert.equal(data.length, 1); assert.equal(data[0].features.context.operation, 'upscale'); assert.ok(Object.isFrozen(data)); assert.ok(Number.isFinite(data[0].reward)); });
test('encoder is deterministic, normalized and versioned', () => { const encoder = new DecisionFeatureEncoderV1(), a = encoder.encode(features()), b = encoder.encode(features()); assert.deepEqual(a, b); assert.equal(a.length, encoder.featureNames.length); assert.ok(a.every(value => value >= 0 && value <= 1)); assert.equal(encoder.schemaVersion, 'decision-features-v1'); });
test('constraint gate preserves hard security boundaries', () => { const gate = new DecisionConstraintLayer(); assert.deepEqual(gate.evaluate(context('p', 'LOCAL_ONLY'), candidate('cloud', 'CLOUD')).exclusions, ['PRIVACY_LOCAL_ONLY']); assert.ok(!gate.evaluate(context(), { ...candidate(), quarantined: true }).allowed); assert.ok(!gate.evaluate(context(), { ...candidate(), runtimeSupported: false }).allowed); assert.ok(!gate.evaluate(context(), { ...candidate('expensive'), estimatedCost: 11 }).allowed); });
test('tabular model trains six heads and ranks deterministically', () => { const model = TabularDecisionModelV1.train(records(), { modelVersion: 'v1' }); const prediction = model.predict(features()); assert.ok(prediction.quality >= 0 && prediction.quality <= 1); assert.ok(prediction.acceptanceProbability >= 0); assert.equal(model.version(), 'v1'); assert.equal(model.rank(context(), [candidate('b'), candidate('a')]).length, 2); assert.deepEqual(model.rank(context(), [candidate('b'), candidate('a')]), model.rank(context(), [candidate('b'), candidate('a')])); });
test('trainer split prevents project leakage', () => { const split = new DecisionTrainerV1().split(records()); const train = new Set(split.train.map(item => item.projectId)), validation = new Set(split.validation.map(item => item.projectId)), heldOut = new Set(split.test.map(item => item.projectId)); assert.ok([...train].every(id => !validation.has(id) && !heldOut.has(id))); assert.ok([...validation].every(id => !heldOut.has(id))); });
test('registry enforces canary lifecycle and rollback', () => { const registry = new DecisionModelRegistry(), model = new HeuristicBaselineModel(), metrics = new DecisionModelEvaluator().evaluate(model, records()); registry.register(model, { featureSchemaVersion: 'v1', datasetVersion: 'v1', trainingConfigVersion: 'v1', metrics, parentModel: null, createdAt: 1 }); registry.transition(model.version(), 'CANARY'); assert.equal(registry.promote(model.version()).status, 'ACTIVE'); });
test('facade shadow never controls execution', () => { const facade = new CreativeDecisionModel(); const result = facade.shadow(features()); assert.equal(result.mode, 'MODEL_SHADOW'); assert.equal(result.executedBy, 'heuristic-baseline-v0'); assert.equal(facade.benchmark().length, 30); });
test('reward and regret are policy aware', () => { const reward = calculateReward({ quality: .9, success: true, accepted: true, latency: 100, cost: 0, escalated: false }, context()); assert.ok(reward > 0); assert.equal(decisionRegret(2, 5), 3); assert.equal(decisionRegret(5, 2), 0); });

// 250 named deterministic cases protect schema stability, bounded outputs and input immutability.
for (let index = 0; index < 250; index++) test(`decision model invariant ${String(index + 1).padStart(3, '0')}`, () => { const input = features(`case-${index}`), before = JSON.stringify(input), encoded = new DecisionFeatureEncoderV1().encode(input), prediction = new HeuristicBaselineModel().predict(input); assert.equal(encoded.length, 26); assert.ok(encoded.every(value => Number.isFinite(value))); assert.ok(prediction.quality >= 0 && prediction.quality <= 1); assert.equal(JSON.stringify(input), before); });
