import assert from 'node:assert/strict';
import test from 'node:test';
import { readdirSync, readFileSync } from 'node:fs';
import { FalErrorMapper, FalProvider, FalProviderError, FalRequestMapper, FalResponseMapper, type FalCapability, type ProviderRuntimeDependencies } from '../src/platform/creative/providers/fal';

const scope = Object.freeze({ tenantId: 'tenant', projectId: 'project', userId: 'user' });
const capabilities: readonly FalCapability[] = ['image-edit', 'background-remove', 'segmentation', 'upscale', 'inpaint', 'outpaint', 'try-on'];
let now = 1_000; let sequence = 0;
const response = (body: unknown, status = 200, headers: Record<string, string> = {}) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json', ...headers } });
const dependencies = (fetchImpl: typeof fetch, overrides: Partial<ProviderRuntimeDependencies> = {}): ProviderRuntimeDependencies => ({ fetch: fetchImpl, clock: () => now++, random: () => 0, id: () => `id-${++sequence}`, sleep: async () => { now += 10; }, api: { apiKey: 'super-secret', pollIntervalMs: 1, timeoutMs: 1_000 }, artifactLoader: { load: async (url) => Object.freeze({ url, mimeType: 'image/png', size: 3, hash: 'abc' }) }, ...overrides });

// 140 deterministic capability-contract cases (7 capabilities x 20 invariants).
for (const capability of capabilities) for (let invariant = 1; invariant <= 20; invariant += 1) test(`${capability} mapping invariant ${invariant}`, () => {
  const mapper = new FalRequestMapper(); const input = Object.freeze({ strength: invariant }); const mapped = mapper.map({ scope, capability, prompt: 'safe prompt', imageUrl: 'https://input/image.png', maskUrl: 'https://input/mask.png', inputs: input });
  assert.equal(mapper.capability(capability), capability); assert.ok(mapper.model(capability, { apiKey: 'x' }).startsWith('fal-ai/')); assert.equal(mapped.prompt, 'safe prompt'); assert.equal(mapped.image_url, 'https://input/image.png'); assert.equal(mapped.mask_url, 'https://input/mask.png'); assert.equal(mapped.strength, invariant); assert.ok(Object.isFrozen(mapped)); assert.deepEqual(input, { strength: invariant });
});

test('request mapper supports documented aliases', () => { const mapper = new FalRequestMapper(); assert.equal(mapper.capability('virtual_try_on'), 'try-on'); assert.equal(mapper.capability('remove-background'), 'background-remove'); });
test('request mapper rejects unsupported capabilities', () => assert.throws(() => new FalRequestMapper().map({ scope, capability: 'magic' })));
test('custom model mapping wins', () => assert.equal(new FalRequestMapper().model('upscale', { apiKey: 'x', models: { upscale: 'custom/model' } }), 'custom/model'));
test('response mapper extracts nested unique artifacts', () => assert.deepEqual(new FalResponseMapper().urls({ images: [{ url: 'https://x/a.png' }, { url: 'https://x/a.png' }], output: { file_url: 'https://x/b.png' } }), ['https://x/a.png', 'https://x/b.png']));
test('response mapper reads provider cost', () => assert.equal(new FalResponseMapper().cost({ metrics: { cost_usd: 0.12 } }), 0.12));
test('response mapper recognizes async job', () => assert.equal(new FalResponseMapper().job({ request_id: 'job-1' })?.requestId, 'job-1'));

for (const [status, category] of [[401, 'authentication'], [422, 'validation'], [408, 'timeout'], [429, 'rate limit'], [503, 'provider unavailable'], [500, 'internal provider error'], [418, 'unknown']] as const) test(`maps HTTP ${status} to ${category}`, () => assert.equal(new FalErrorMapper().map(status).category, category));

test('provider authenticates and produces unified immutable result', async () => { let authorization = ''; const provider = new FalProvider(dependencies(async (_url, init) => { authorization = new Headers(init?.headers).get('authorization') ?? ''; return response({ images: [{ url: 'https://artifact/result.png' }], metrics: { cost: 0.2 } }); })); const result = await provider.execute({ scope, capability: 'image-edit', prompt: 'edit' }); assert.equal(authorization, 'Key super-secret'); assert.equal(result.provider, 'fal'); assert.equal(result.metrics.cost, 0.2); assert.equal(result.metrics.costSource, 'provider'); assert.equal(result.artifacts.length, 1); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.scope)); });
test('provider uses deterministic cost estimate', async () => { const result = await new FalProvider(dependencies(async () => response({ output: 'done' }))).execute({ scope, capability: 'upscale' }); assert.equal(result.metrics.cost, 0.03); assert.equal(result.metrics.costSource, 'estimate'); });
test('provider polls queued job and obtains result', async () => { let calls = 0; const provider = new FalProvider(dependencies(async (_url, init) => { calls += 1; if (init?.method === 'POST') return response({ request_id: 'job' }); if (String(_url).endsWith('/status')) return response({ status: 'COMPLETED' }); return response({ image: { url: 'https://artifact/result.png' } }); })); const result = await provider.execute({ scope, capability: 'segmentation' }); assert.equal(calls, 3); assert.equal(result.metrics.pollCount, 1); });
test('provider retries rate limiting', async () => { let calls = 0; const provider = new FalProvider(dependencies(async () => { calls += 1; return calls === 1 ? response({ message: 'slow' }, 429) : response({ ok: true }); })); const result = await provider.execute({ scope, capability: 'inpaint' }); assert.equal(calls, 2); assert.equal(result.metrics.retries, 1); });
test('provider reports authentication errors', async () => { const provider = new FalProvider(dependencies(async () => response({}, 401))); await assert.rejects(provider.execute({ scope, capability: 'outpaint' }), (error: unknown) => error instanceof FalProviderError && error.category === 'authentication'); });
test('provider requires complete dependency injection', () => assert.throws(() => new FalProvider({} as ProviderRuntimeDependencies)));
test('provider requires complete scope', async () => await assert.rejects(new FalProvider(dependencies(async () => response({}))).execute({ scope: { ...scope, userId: '' }, capability: 'upscale' })));
test('health records success and failure', async () => { let ok = true; const provider = new FalProvider(dependencies(async () => ok ? response({ ok: true }) : response({}, 401))); await provider.execute({ scope, capability: 'upscale' }); ok = false; await assert.rejects(provider.execute({ scope, capability: 'upscale' })); assert.equal(provider.health().successes, 1); assert.equal(provider.health().failures, 1); });
test('snapshot replay performs no HTTP', async () => { let calls = 0; const provider = new FalProvider(dependencies(async () => { calls += 1; return response({ ok: true }); })); const result = await provider.execute({ scope, capability: 'upscale' }); const snapshot = provider.history(scope)[0]; assert.deepEqual(provider.replay(snapshot, scope), result); assert.equal(calls, 1); });
test('history and replay enforce full scope isolation', async () => { const provider = new FalProvider(dependencies(async () => response({ ok: true }))); await provider.execute({ scope, capability: 'upscale' }); const foreign = { ...scope, userId: 'other' }; assert.equal(provider.history(foreign).length, 0); assert.throws(() => provider.replay(provider.history(scope)[0], foreign)); assert.throws(() => provider.debug(provider.history(scope)[0], foreign)); });
test('debugger exposes ordered explainability stages', async () => { const provider = new FalProvider(dependencies(async () => response({ ok: true }))); await provider.execute({ scope, capability: 'upscale' }); assert.deepEqual(provider.debug(provider.history(scope)[0], scope).map((event) => event.stage), ['Request', 'Fal Request', 'HTTP', 'Fal Response', 'Artifacts', 'Provider Result']); });
test('API key never enters snapshot debugger or replay', async () => { const provider = new FalProvider(dependencies(async () => response({ ok: true }))); await provider.execute({ scope, capability: 'upscale', metadata: { token: 'also-secret' } }); const serialized = JSON.stringify({ history: provider.history(scope), debug: provider.debug(provider.history(scope)[0], scope), replay: provider.replay(provider.history(scope)[0], scope) }); assert.equal(serialized.includes('super-secret'), false); assert.equal(serialized.includes('also-secret'), false); assert.equal(/authorization|apiKey/i.test(serialized), false); });
test('Fal implementation has no forbidden architectural imports', () => { const roots = ['src/platform/creative/providers/fal', 'src/platform/creative/provider-runtime/adapters']; const forbidden = ['decision/', 'knowledge/', 'planning/', 'execution/', 'workflow/', 'pipeline/', 'provider-platform/', 'provider-runtime/core/', 'billing/', 'ui/', 'application/']; for (const root of roots) for (const file of readdirSync(root)) { if (!file.endsWith('.ts')) continue; const imports = readFileSync(`${root}/${file}`, 'utf8').split('\n').filter((line) => /^import|^export .* from/.test(line)).join('\n').toLowerCase(); for (const term of forbidden) assert.equal(imports.includes(term), false, `${file} imports ${term}`); } });
