export const modules = {
  common: { appName: 'Edytor Zdjęć AI', save: 'Zapisz', cancel: 'Anuluj', delete: 'Usuń', edit: 'Edytuj', close: 'Zamknij', create: 'Utwórz', apply: 'Zastosuj', retry: 'Ponów', confirm: 'Potwierdź', back: 'Wstecz', next: 'Dalej', done: 'Gotowe', loading: 'Ładowanie…', search: 'Szukaj', add: 'Dodaj', remove: 'Usuń', rename: 'Zmień nazwę', duplicate: 'Duplikuj', download: 'Pobierz', favorite: 'Ulubione', archive: 'Archiwizuj', restore: 'Przywróć', signOut: 'Wyloguj', empty: 'Jeszcze nic tu nie ma', minutes: '{count} min', seconds: '{seconds}s' },
  editor: { title: 'Edytor', undo: 'Cofnij', redo: 'Ponów', restoreOriginal: 'Przywróć oryginał', detectObjects: 'Wykryj obiekty', detecting: 'Wykrywanie obiektów…', prompt: 'Polecenie', creativeStudio: 'Studio Kreatywne', recipes: 'Przepisy', aiAgent: 'Agent AI', fashion: 'Moda', outfits: 'Stylizacje', before: 'Przed', after: 'Po', accept: 'Akceptuj', discard: 'Odrzuć', objects: 'Obiekty', versions: 'Wersje', newVersion: 'Nowa wersja', sceneMemory: 'Pamięć sceny', workspace: 'Obszar roboczy', jobCenter: 'Centrum zadań', instructionPlaceholder: 'Opisz swoją edycję…', projectNotFound: 'Nie znaleziono projektu' },
  projects: { title: 'Projekty', newProject: 'Nowy projekt', upload: 'Prześlij obraz', empty: 'Brak projektów — prześlij obraz, aby zacząć.', open: 'Otwórz', processing: 'Przetwarzanie', draft: 'Szkic', completed: 'Ukończono' },
  recipes: { title: 'Przepisy', favorite: 'Ulubione', popular: 'Popularne', recent: 'Ostatnie', recommended: 'Polecane', run: 'Uruchom przepis', use: 'Użyj', searchPlaceholder: 'Szukaj przepisów…' },
  workspace: { title: 'Obszar roboczy', auto: 'Wykryto automatycznie', manual: 'Ręcznie', switch: 'Zmień obszar', recommendations: 'Rekomendacje', mostUsed: 'Najczęściej używane' },
  automation: { title: 'Studio Automatyzacji', subtitle: 'Twórz wielokrotne przepływy edycji bez kodowania.', library: 'Biblioteka automatyzacji', templateGallery: 'Galeria szablonów', builder: 'Kreator', history: 'Historia wykonań', run: 'Uruchom', queuing: 'W kolejce…', save: 'Zapisz', trigger: 'Wyzwalacz', conditions: 'Warunki', condition: 'Warunek', actions: 'Akcje', action: 'Akcja', schedule: 'Harmonogram', variables: 'Zmienne', estimatedCredits: 'Szacowane kredyty', estimatedTime: 'Szacowany czas', emptyBuilder: 'Wybierz szablon lub utwórz automatyzację.', emptyLibrary: 'Zapisz szablon, aby zbudować bibliotekę.', noRuns: 'Brak wykonań.', mostExecuted: 'Najczęściej', successRate: 'Sukces {rate}%', failureRate: 'Błędy {rate}%', describePlaceholder: 'Opisz ten przepływ', actionsCount: '{count} akcji', untitled: 'Automatyzacja bez nazwy', scheduleImmediate: 'Natychmiast', scheduleScheduled: 'Zaplanowane', scheduleDaily: 'Codziennie', scheduleWeekly: 'Co tydzień', scheduleManual: 'Tylko ręcznie', containsPerson: 'Zawiera osobę', containsVehicle: 'Zawiera pojazd', containsProduct: 'Zawiera produkt', containsAnimal: 'Zawiera zwierzę', containsText: 'Zawiera tekst' },
  fashion: { title: 'Moda', wardrobe: 'Garderoba', garments: 'Ubrania', outfits: 'Stylizacje', addGarment: 'Dodaj ubranie', collections: 'Kolekcje', tryOn: 'Przymierzalnia', searchPlaceholder: 'Szukaj w garderobie…', empty: 'Twoja garderoba jest pusta.' },
  billing: { title: 'Płatności', subscription: 'Subskrypcja', plan: 'Plan', credits: 'Kredyty', upgrade: 'Ulepsz', currentPlan: 'Bieżący plan', usage: 'Użycie', renew: 'Odnawia się {date}' },
  settings: { title: 'Ustawienia', account: 'Konto', appearance: 'Wygląd', appearanceHint: 'Przełączaj między trybem jasnym a ciemnym', language: 'Język', languageHint: 'Wybierz język interfejsu', performance: 'Wydajność', loadingPerformance: 'Ładowanie ustawień wydajności…' },
  errors: { generic: 'Coś poszło nie tak.', network: 'Błąd sieci — sprawdź połączenie.', offline: 'Jesteś offline. Zmiany zsynchronizują się po połączeniu.', timeout: 'Przekroczono limit czasu. Spróbuj ponownie.', provider: 'Dostawca AI nie mógł zrealizować żądania.', validation: 'Popraw zaznaczone pola.', credits: 'Nie masz wystarczających kredytów na tę operację.', subscription: 'Twój plan nie pozwala na tę akcję.' },
  notifications: { title: 'Powiadomienia', markAllRead: 'Oznacz wszystkie jako przeczytane', empty: 'Brak powiadomień.', completed: 'Generowanie zakończone', failed: 'Błąd generowania', saved: 'Edycja zapisana' },
  jobs: { title: 'Centrum zadań', queued: 'W kolejce', running: 'W trakcie', waiting: 'Oczekiwanie', completed: 'Ukończono', failed: 'Niepowodzenie', cancelled: 'Anulowano', retrying: 'Ponawianie', cancel: 'Anuluj', pause: 'Wstrzymaj', resume: 'Wznów', empty: 'Brak aktywnych zadań.' },
  creative: { title: 'Studio Kreatywne', goal: 'Cel', ideas: 'Pomysły', moodBoards: 'Moodboardy', strategy: 'Strategia', generate: 'Generuj pomysły', apply: 'Zastosuj strategię' },
  brand: { title: 'Studio Marki', profile: 'Profil marki', colors: 'Kolory', fonts: 'Czcionki', voice: 'Ton', guidelines: 'Wytyczne' },
  assets: { title: 'Biblioteka zasobów', collections: 'Kolekcje', pinned: 'Przypięte', smart: 'Inteligentne', searchPlaceholder: 'Szukaj zasobów…', empty: 'Brak zasobów.', details: 'Szczegóły' },
};
export default modules;