export const modules = {
  common: { appName: 'محرر الصور بالذكاء الاصطناعي', save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', close: 'إغلاق', create: 'إنشاء', apply: 'تطبيق', retry: 'إعادة المحاولة', confirm: 'تأكيد', back: 'رجوع', next: 'التالي', done: 'تم', loading: 'جارٍ التحميل…', search: 'بحث', add: 'إضافة', remove: 'إزالة', rename: 'إعادة تسمية', duplicate: 'نسخ', download: 'تنزيل', favorite: 'المفضلة', archive: 'أرشفة', restore: 'استعادة', signOut: 'تسجيل الخروج', empty: 'لا يوجد شيء هنا بعد', minutes: '{count} دقيقة', seconds: '{seconds} ث' },
  editor: { title: 'المحرر', undo: 'تراجع', redo: 'إعادة', restoreOriginal: 'استعادة الأصل', detectObjects: 'اكتشاف العناصر', detecting: 'جارٍ اكتشاف العناصر…', prompt: 'الأمر', creativeStudio: 'استوديو الإبداع', recipes: 'الوصفات', aiAgent: 'وكيل الذكاء الاصطناعي', fashion: 'الأزياء', outfits: 'الإطلالات', before: 'قبل', after: 'بعد', accept: 'قبول', discard: 'تجاهل', objects: 'العناصر', versions: 'الإصدارات', newVersion: 'إصدار جديد', sceneMemory: 'ذاكرة المشهد', workspace: 'مساحة العمل', jobCenter: 'مركز المهام', instructionPlaceholder: 'صف التعديل…', projectNotFound: 'المشروع غير موجود' },
  projects: { title: 'المشاريع', newProject: 'مشروع جديد', upload: 'رفع صورة', empty: 'لا توجد مشاريع بعد — ارفع صورة للبدء.', open: 'فتح', processing: 'قيد المعالجة', draft: 'مسودة', completed: 'مكتمل' },
  recipes: { title: 'الوصفات', favorite: 'المفضلة', popular: 'الشائعة', recent: 'الأخيرة', recommended: 'موصى بها', run: 'تشغيل الوصفة', use: 'استخدام', searchPlaceholder: 'ابحث في الوصفات…' },
  workspace: { title: 'مساحة العمل', auto: 'اكتشاف تلقائي', manual: 'يدوي', switch: 'تبديل مساحة العمل', recommendations: 'التوصيات', mostUsed: 'الأكثر استخدامًا' },
  automation: { title: 'استوديو الأتمتة', subtitle: 'أنشئ سير عمل قابلاً لإعادة الاستخدام دون كتابة كود.', library: 'مكتبة الأتمتة', templateGallery: 'معرض القوالب', builder: 'المنشئ', history: 'سجل التنفيذ', run: 'تشغيل', queuing: 'في قائمة الانتظار…', save: 'حفظ', trigger: 'المُشغّل', conditions: 'الشروط', condition: 'شرط', actions: 'الإجراءات', action: 'إجراء', schedule: 'الجدولة', variables: 'المتغيرات', estimatedCredits: 'الرصيد التقديري', estimatedTime: 'الوقت التقديري', emptyBuilder: 'اختر قالبًا أو أنشئ أتمتة.', emptyLibrary: 'احفظ قالبًا لبناء مكتبتك.', noRuns: 'لا توجد عمليات تنفيذ بعد.', mostExecuted: 'الأكثر تنفيذًا', successRate: 'النجاح {rate}%', failureRate: 'الإخفاقات {rate}%', describePlaceholder: 'صف سير العمل هذا', actionsCount: '{count} إجراءات', untitled: 'أتمتة بدون عنوان', scheduleImmediate: 'فوري', scheduleScheduled: 'مجدول', scheduleDaily: 'يومي', scheduleWeekly: 'أسبوعي', scheduleManual: 'يدوي فقط', containsPerson: 'يحتوي على شخص', containsVehicle: 'يحتوي على مركبة', containsProduct: 'يحتوي على منتج', containsAnimal: 'يحتوي على حيوان', containsText: 'يحتوي على نص' },
  fashion: { title: 'الأزياء', wardrobe: 'خزانة الملابس', garments: 'الملابس', outfits: 'الإطلالات', addGarment: 'إضافة قطعة', collections: 'المجموعات', tryOn: 'التجربة الافتراضية', searchPlaceholder: 'ابحث في الخزانة…', empty: 'خزانتك فارغة.' },
  billing: { title: 'الفوترة', subscription: 'الاشتراك', plan: 'الخطة', credits: 'الرصيد', upgrade: 'ترقية', currentPlan: 'الخطة الحالية', usage: 'الاستخدام', renew: 'يتجدد في {date}' },
  settings: { title: 'الإعدادات', account: 'الحساب', appearance: 'المظهر', appearanceHint: 'التبديل بين الوضع الفاتح والداكن', language: 'اللغة', languageHint: 'اختر لغة الواجهة', performance: 'الأداء', loadingPerformance: 'جارٍ تحميل إعدادات الأداء…' },
  errors: { generic: 'حدث خطأ ما.', network: 'خطأ في الشبكة — تحقق من اتصالك.', offline: 'أنت غير متصل. ستتم المزامنة عند إعادة الاتصال.', timeout: 'انتهت مهلة الطلب. حاول مجددًا.', provider: 'تعذّر على مزود الذكاء الاصطناعي إكمال الطلب.', validation: 'يرجى تصحيح الحقول المميزة.', credits: 'ليس لديك رصيد كافٍ لهذه العملية.', subscription: 'خطتك لا تسمح بهذا الإجراء.' },
  notifications: { title: 'الإشعارات', markAllRead: 'تحديد الكل كمقروء', empty: 'لا توجد إشعارات.', completed: 'اكتمل التوليد', failed: 'فشل التوليد', saved: 'تم حفظ التعديل' },
  jobs: { title: 'مركز المهام', queued: 'في الانتظار', running: 'قيد التشغيل', waiting: 'انتظار', completed: 'مكتمل', failed: 'فشل', cancelled: 'أُلغي', retrying: 'إعادة المحاولة', cancel: 'إلغاء', pause: 'إيقاف مؤقت', resume: 'استئناف', empty: 'لا توجد مهام نشطة.' },
  creative: { title: 'استوديو الإبداع', goal: 'الهدف', ideas: 'الأفكار', moodBoards: 'لوحات المزاج', strategy: 'الاستراتيجية', generate: 'توليد الأفكار', apply: 'تطبيق الاستراتيجية' },
  brand: { title: 'استوديو العلامة', profile: 'ملف العلامة', colors: 'الألوان', fonts: 'الخطوط', voice: 'النبرة', guidelines: 'الإرشادات' },
  assets: { title: 'مكتبة الأصول', collections: 'المجموعات', pinned: 'المثبتة', smart: 'ذكية', searchPlaceholder: 'ابحث في الأصول…', empty: 'لا توجد أصول بعد.', details: 'التفاصيل' },
};
export default modules;