/**
 * Browser/Node-safe immutable identity for the F5a.1 refinement-support law.
 *
 * This contract grants no model/runtime/provider/Billing/FINAL/Try-On authority.
 * It only defines the deterministic region in which a later separately admitted
 * refinement runtime may propose pixel changes.
 */
/** @type {'1'} */
export const GARMENT_APPEARANCE_REFINEMENT_CONTRACT_VERSION = '1';
/** @type {'GARMENT_APPEARANCE_REFINEMENT'} */
export const GARMENT_APPEARANCE_REFINEMENT_OPERATION = 'GARMENT_APPEARANCE_REFINEMENT';
/** @type {'BERS_GARMENT_APPEARANCE_REFINEMENT_SUPPORT_V1'} */
export const GARMENT_APPEARANCE_REFINEMENT_SUPPORT_SCHEMA = 'BERS_GARMENT_APPEARANCE_REFINEMENT_SUPPORT_V1';
/** @type {'REFINE_REALISM_V1'} */
export const GARMENT_APPEARANCE_REFINEMENT_PROFILE = 'REFINE_REALISM_V1';
/** @type {'GARMENT_WARP_ALPHA_NONZERO'} */
export const GARMENT_APPEARANCE_REFINEMENT_SUPPORT_SOURCE = 'GARMENT_WARP_ALPHA_NONZERO';
/** @type {2} */
export const GARMENT_APPEARANCE_REFINEMENT_DILATION_RADIUS_PX = 2;
/** @type {'CHEBYSHEV_SQUARE_CLIPPED'} */
export const GARMENT_APPEARANCE_REFINEMENT_DILATION_POLICY = 'CHEBYSHEV_SQUARE_CLIPPED';
/** @type {'BINARY_R8_0_OR_255'} */
export const GARMENT_APPEARANCE_REFINEMENT_MASK_POLICY = 'BINARY_R8_0_OR_255';
/** @type {'BYTE_EXACT_PARENT_RGBA8_OUTSIDE_SUPPORT'} */
export const GARMENT_APPEARANCE_REFINEMENT_OUTSIDE_SUPPORT_POLICY = 'BYTE_EXACT_PARENT_RGBA8_OUTSIDE_SUPPORT';
/** @type {'NOT_ADMITTED'} */
export const GARMENT_APPEARANCE_REFINEMENT_PRODUCTION_ADMISSION = 'NOT_ADMITTED';
