import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { Pool } from 'pg';

async function migration(name:string){try{return await readFile(new URL(`./migrations/${name}`,import.meta.url),'utf8');}catch{return readFile(resolve(process.cwd(),'server/core/projects/migrations',name),'utf8');}}
async function hardened(pool:Pool){const result=await pool.query("SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='canonical_project_history' AND column_name='execution_id') AS hardened");return Boolean(result.rows[0]?.hardened);}
async function sourceLineage(pool:Pool){const result=await pool.query("SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='canonical_project_history' AND column_name='source_image_storage_id') AS lineage");return Boolean(result.rows[0]?.lineage);}

export async function checkProjectSchema(pool: Pool) { const result = await pool.query("SELECT to_regclass('canonical_projects')::text AS projects, to_regclass('canonical_project_history')::text AS history, to_regclass('canonical_project_versions')::text AS versions"); if (!result.rows[0]?.projects || !result.rows[0]?.history || !result.rows[0]?.versions) throw new Error('canonical Project schema is incomplete; apply migrations 004 and 005'); if(!await hardened(pool))throw new Error('canonical Project history schema is incomplete; apply migration 006'); if(!await sourceLineage(pool))throw new Error('canonical Project history source lineage is incomplete; apply migration 007'); }
export async function migrateProjectSchema(pool: Pool) { let result = await pool.query("SELECT to_regclass('canonical_projects')::text AS projects"); if (!result.rows[0]?.projects) await pool.query(await migration('004_canonical_projects_and_originals.sql')); result=await pool.query("SELECT to_regclass('canonical_project_history')::text AS history"); if(!result.rows[0]?.history) await pool.query(await migration('005_canonical_project_history_versions.sql')); if(!await hardened(pool))await pool.query(await migration('006_project_history_acceptance_hardening.sql')); if(!await sourceLineage(pool))await pool.query(await migration('007_project_history_source_lineage.sql')); }
