import { CostOptimizer } from './CostOptimizer';
import { ProviderCapabilityGraph } from './ProviderCapabilityGraph';
import { ProviderHealthIntelligence } from './ProviderHealthIntelligence';
import { ProviderIntelligenceDebugger } from './ProviderIntelligenceDebugger';
import { ProviderPolicyEngine } from './ProviderPolicyEngine';
import { ProviderRankingEngine } from './ProviderRankingEngine';
import { ProviderSelector } from './ProviderSelector';
import { intelligenceDeepFreeze, sameIntelligenceScope } from './immutable';
import type { ProviderDescriptor, ProviderHealthSample, ProviderIntelligenceDebugEvent, ProviderIntelligenceDependencies, ProviderIntelligenceScope, ProviderIntelligenceSnapshot, ProviderScore, ProviderSelection, ProviderSelectionRequest } from './types';
export class CreativeProviderIntelligence {
  readonly graph = new ProviderCapabilityGraph(); readonly health = new ProviderHealthIntelligence(); private readonly policies = new ProviderPolicyEngine(); private readonly ranking: ProviderRankingEngine; private readonly selector = new ProviderSelector(new CostOptimizer()); private readonly debugger = new ProviderIntelligenceDebugger(); private snapshots: readonly ProviderIntelligenceSnapshot[] = [];
  constructor(private readonly dependencies: ProviderIntelligenceDependencies, providers: readonly ProviderDescriptor[] = []) { if (!dependencies?.clock || !dependencies.id || !dependencies.random || !dependencies.scoringModel || !dependencies.weightingPolicy) throw new Error('Provider Intelligence requires complete dependency injection'); this.ranking = new ProviderRankingEngine(dependencies.scoringModel); providers.forEach((provider) => this.graph.register(provider)); }
  select(request: ProviderSelectionRequest): ProviderSelection { return this.evaluate(request); }
  route(request: ProviderSelectionRequest): ProviderScore | undefined { return this.evaluate(request).winner; }
  evaluate(request: ProviderSelectionRequest): ProviderSelection { this.validate(request); const policy = request.policy ?? 'Reliability First'; const strategy = request.strategy ?? 'Balanced'; const candidates = this.graph.candidates(request); const weights = this.dependencies.weightingPolicy(strategy, policy, request.customWeights); const ranking = this.ranking.rank(candidates, request, (id) => this.health.metrics(request.scope, id), weights); return this.selector.select(ranking, request.budget, request.budgetMode); }
  fallback(request: ProviderSelectionRequest, failedProviderId?: string): readonly string[] { const selection = this.evaluate(request); return intelligenceDeepFreeze(selection.ranking.map((x) => x.providerId).filter((id) => id !== (failedProviderId ?? selection.winner?.providerId))); }
  rebalance(request: ProviderSelectionRequest, samples: readonly ProviderHealthSample[] = []): ProviderSelection { samples.forEach((sample) => this.health.record(request.scope, { ...sample, at: sample.at ?? this.dependencies.clock() })); return this.evaluate(request); }
  snapshot(request: ProviderSelectionRequest): ProviderIntelligenceSnapshot { const selection = this.evaluate(request); const candidates = this.graph.candidates(request); const timeline: ProviderIntelligenceDebugEvent[] = [{ stage: 'Candidates', at: this.dependencies.clock(), data: { ids: candidates.map((x) => x.id) } }, { stage: 'Scores', at: this.dependencies.clock(), data: { scores: selection.ranking.map((x) => ({ providerId: x.providerId, score: x.score })) } }, { stage: 'Ranking', at: this.dependencies.clock(), data: { ids: selection.ranking.map((x) => x.providerId) } }, { stage: 'Winner', at: this.dependencies.clock(), data: { providerId: selection.winner?.providerId } }, { stage: 'Fallback Plan', at: this.dependencies.clock(), data: { chain: selection.fallbackChain } }]; const snapshot = intelligenceDeepFreeze({ id: this.dependencies.id(), scope: { ...request.scope }, request: { ...request, scope: { ...request.scope }, metadata: { ...(request.metadata ?? {}) } }, candidates, ranking: selection.ranking, winner: selection.winner, fallbackChain: selection.fallbackChain, policies: [request.strategy ?? 'Balanced', request.policy ?? 'Reliability First', request.budgetMode ?? 'unlimited'], metrics: { candidateCount: candidates.length, winningScore: selection.winner?.score ?? 0, randomAudit: this.dependencies.random() }, reasoning: selection.reasoning, timeline, createdAt: this.dependencies.clock() }) as ProviderIntelligenceSnapshot; this.snapshots = intelligenceDeepFreeze([...this.snapshots, snapshot]); return snapshot; }
  debug(snapshot: ProviderIntelligenceSnapshot, scope: ProviderIntelligenceScope): readonly ProviderIntelligenceDebugEvent[] { return this.debugger.debug(snapshot, scope); }
  replay(snapshot: ProviderIntelligenceSnapshot, scope: ProviderIntelligenceScope): ProviderSelection { if (!sameIntelligenceScope(snapshot.scope, scope)) throw new Error('Scope isolation violation'); return intelligenceDeepFreeze({ winner: snapshot.winner, ranking: snapshot.ranking, fallbackChain: snapshot.fallbackChain, simulations: snapshot.ranking.map((x) => ({ providerId: x.providerId, expectedQuality: x.quality, expectedLatencyMs: x.predictedLatencyMs, expectedCost: x.price, successProbability: x.successRate * x.availability, utility: x.score })), reasoning: snapshot.reasoning }); }
  history(scope: ProviderIntelligenceScope): readonly ProviderIntelligenceSnapshot[] { return intelligenceDeepFreeze(this.snapshots.filter((x) => sameIntelligenceScope(x.scope, scope))); }
  private validate(request: ProviderSelectionRequest): void { if (!request?.scope?.tenantId || !request.scope.projectId || !request.scope.userId || !request.capability) throw new Error('Complete scope and capability are required'); }
}
export const createDefaultWeightingPolicy = (): ProviderIntelligenceDependencies['weightingPolicy'] => { const engine = new ProviderPolicyEngine(); return (strategy, policy, custom) => engine.weights(strategy, policy, custom); };
