export interface ProviderIntelligenceScope { readonly tenantId: string; readonly projectId: string; readonly userId: string }
export type ProviderStrategy = 'Cheapest' | 'Fastest' | 'HighestQuality' | 'Balanced' | 'LowestLatency' | 'HighestAvailability' | 'CustomPolicy';
export type ProviderPolicy = 'Cost First' | 'Quality First' | 'Brand First' | 'Creative First' | 'Speed First' | 'Reliability First';
export type BudgetMode = 'hard' | 'soft' | 'unlimited';
export interface ProviderConstraint { readonly name: string; readonly value: string | number | boolean }
export interface ProviderCapability { readonly name: string; readonly formats: readonly string[]; readonly maxWidth: number; readonly maxHeight: number; readonly cost: number; readonly latencyMs: number; readonly quality: number; readonly stability: number; readonly constraints?: readonly ProviderConstraint[] }
export interface ProviderDescriptor { readonly id: string; readonly brand?: string; readonly capabilities: readonly ProviderCapability[] }
export interface ProviderHealthSample { readonly providerId: string; readonly success: boolean; readonly latencyMs: number; readonly retries: number; readonly timeout: boolean; readonly available: boolean; readonly at?: number }
export interface ProviderHealthMetrics { readonly providerId: string; readonly sampleCount: number; readonly successRate: number; readonly averageLatencyMs: number; readonly retryFrequency: number; readonly timeoutRate: number; readonly availability: number; readonly degradationTrend: number; readonly score: number }
export interface ProviderSelectionRequest { readonly scope: ProviderIntelligenceScope; readonly capability: string; readonly format?: string; readonly width?: number; readonly height?: number; readonly strategy?: ProviderStrategy; readonly policy?: ProviderPolicy; readonly budget?: number; readonly budgetMode?: BudgetMode; readonly preferredBrand?: string; readonly customWeights?: Partial<ProviderWeights>; readonly metadata?: Readonly<Record<string, unknown>> }
export interface ProviderWeights { readonly quality: number; readonly latency: number; readonly price: number; readonly availability: number; readonly health: number; readonly retry: number; readonly success: number; readonly compatibility: number; readonly brand: number; readonly creativity: number }
export interface ProviderScore { readonly providerId: string; readonly compatible: boolean; readonly score: number; readonly quality: number; readonly predictedLatencyMs: number; readonly price: number; readonly availability: number; readonly health: number; readonly retryHistory: number; readonly successRate: number; readonly reasoning: readonly string[] }
export interface ProviderSimulation { readonly providerId: string; readonly expectedQuality: number; readonly expectedLatencyMs: number; readonly expectedCost: number; readonly successProbability: number; readonly utility: number }
export interface ProviderSelection { readonly winner?: ProviderScore; readonly ranking: readonly ProviderScore[]; readonly fallbackChain: readonly string[]; readonly simulations: readonly ProviderSimulation[]; readonly reasoning: readonly string[] }
export interface ProviderIntelligenceSnapshot { readonly id: string; readonly scope: ProviderIntelligenceScope; readonly request: ProviderSelectionRequest; readonly candidates: readonly ProviderDescriptor[]; readonly ranking: readonly ProviderScore[]; readonly winner?: ProviderScore; readonly fallbackChain: readonly string[]; readonly policies: readonly string[]; readonly metrics: Readonly<Record<string, number>>; readonly reasoning: readonly string[]; readonly timeline: readonly ProviderIntelligenceDebugEvent[]; readonly createdAt: number }
export interface ProviderIntelligenceDebugEvent { readonly stage: 'Candidates' | 'Scores' | 'Ranking' | 'Winner' | 'Fallback Plan'; readonly at: number; readonly data: Readonly<Record<string, unknown>> }
export interface ProviderScoringModel { score(input: Omit<ProviderScore, 'score' | 'reasoning'>, weights: ProviderWeights): number }
export interface ProviderIntelligenceDependencies { readonly clock: () => number; readonly id: () => string; readonly random: () => number; readonly scoringModel: ProviderScoringModel; readonly weightingPolicy: (strategy: ProviderStrategy, policy: ProviderPolicy, custom?: Partial<ProviderWeights>) => ProviderWeights }
