import { average, clamp, hash, immutable } from './immutable';
import { VISUAL_LAWS } from './principles';
import type { ConsensusModel, DirectorModel, ExpertOpinion, ExpertRole, ReasoningModel, StudioPrompt, TasteDimension, TasteModel, TradeoffModel, TradeoffQuestion, WorldModel } from './types';

export const EXPERT_ROLES: readonly ExpertRole[] = immutable(['CREATIVE_DIRECTOR', 'ART_DIRECTOR', 'BRAND_DIRECTOR', 'LIGHTING_DIRECTOR', 'COMPOSITION_DIRECTOR', 'FASHION_DIRECTOR', 'MARKETING_DIRECTOR', 'COST_DIRECTOR', 'AI_DIRECTOR', 'QUALITY_DIRECTOR']);
const roleFocus: Readonly<Record<ExpertRole, string>> = { CREATIVE_DIRECTOR: 'creative coherence', ART_DIRECTOR: 'visual language', BRAND_DIRECTOR: 'brand integrity', LIGHTING_DIRECTOR: 'light and depth', COMPOSITION_DIRECTOR: 'composition and hierarchy', FASHION_DIRECTOR: 'styling and silhouette', MARKETING_DIRECTOR: 'commercial clarity', COST_DIRECTOR: 'resource efficiency', AI_DIRECTOR: 'AI leverage', QUALITY_DIRECTOR: 'finish quality' };
export class HeuristicReasoningModel implements ReasoningModel {
  constructor(private readonly nextId: () => string = () => `opinion-${Math.random().toString(36).slice(2)}`) {}
  reason(prompt: StudioPrompt, role: ExpertRole): ExpertOpinion { const seed = hash(`${prompt.projectId}:${prompt.text}:${role}`), variance = (seed % 19) / 100, ai = role === 'AI_DIRECTOR' || /generat|replace|invent|ai/i.test(prompt.text), economy = role === 'COST_DIRECTOR', composition = role === 'COMPOSITION_DIRECTOR'; const operations = economy ? ['LOCAL', 'FINAL'] as const : ai ? ['LOCAL', 'AI', 'FINAL'] as const : composition ? ['LOCAL', 'LIGHT', 'FINAL'] as const : ['LOCAL', 'LIGHT', 'COLOR', 'FINAL'] as const; const expectedCost = economy ? 8 : ai ? 42 : 18 + seed % 8; return immutable({ id: this.nextId(), role, recommendation: `${roleFocus[role]}: ${operations.join(' → ')}`, confidence: clamp(.67 + variance), reason: `Prioritize ${roleFocus[role]} while preserving the stated intent.`, operations, risks: ai ? ['AI artifacts', 'identity drift'] : economy ? ['quality ceiling'] : [`${roleFocus[role]} may be under-resolved`], expectedQuality: clamp((ai ? .83 : .72) + variance / 2), expectedCost }); }
}
export class HeuristicDirectorModel implements DirectorModel {
  constructor(private readonly nextId: () => string = () => `statement-${Math.random().toString(36).slice(2)}`) {}
  direct(_prompt: StudioPrompt, opinions: readonly ExpertOpinion[]) { const aiOpinion = opinions.find(({ role }) => role === 'AI_DIRECTOR')!, cost = opinions.find(({ role }) => role === 'COST_DIRECTOR')!, quality = opinions.find(({ role }) => role === 'QUALITY_DIRECTOR')!; return immutable(opinions.map((opinion) => ({ id: this.nextId(), expert: opinion.role, kind: opinion.role === 'COST_DIRECTOR' && aiOpinion.operations.includes('AI') ? 'OBJECTION' as const : opinion.expectedQuality >= average(opinions.map((item) => item.expectedQuality)) ? 'SUPPORT' as const : 'ALTERNATIVE' as const, targetOpinionId: opinion.role === 'COST_DIRECTOR' ? aiOpinion.id : opinion.id, statement: opinion.role === 'COST_DIRECTOR' ? `AI must justify its ${aiOpinion.expectedCost - cost.expectedCost} cost premium.` : opinion.role === 'QUALITY_DIRECTOR' ? `A local-first pass can protect quality before escalation (${quality.expectedQuality.toFixed(2)} expected).` : opinion.reason, weight: opinion.confidence }))); }
}
export class HeuristicConsensusModel implements ConsensusModel {
  resolve(_prompt: StudioPrompt, debate: { opinions: readonly ExpertOpinion[] }) { const support = new Map<string, number>(); for (const opinion of debate.opinions) for (const operation of opinion.operations) support.set(operation, (support.get(operation) ?? 0) + opinion.confidence); const threshold = debate.opinions.length * .4, operations = [...support.entries()].filter(([, value]) => value >= threshold).sort((a, b) => ['LOCAL','LIGHT','COLOR','AI','FINAL'].indexOf(a[0]) - ['LOCAL','LIGHT','COLOR','AI','FINAL'].indexOf(b[0])).map(([operation]) => operation) as ('LOCAL'|'LIGHT'|'COLOR'|'AI'|'FINAL')[]; const accepted = debate.opinions.filter((opinion) => opinion.operations.every((operation) => operations.includes(operation))).map(({ recommendation }) => recommendation); const rejected = debate.opinions.filter((opinion) => !opinion.operations.some((operation) => operations.includes(operation))).map(({ recommendation }) => recommendation); const minority = debate.opinions.filter((opinion) => opinion.operations.some((operation) => !operations.includes(operation))).map(({ recommendation }) => recommendation); return immutable({ summary: `Use ${operations.join(' → ')} after independent review.`, acceptedIdeas: accepted, rejectedIdeas: rejected, minorityOpinion: minority, operations, confidence: clamp(average(debate.opinions.map(({ confidence }) => confidence)) * (1 - minority.length / debate.opinions.length * .2)) }); }
}
const tastes: readonly TasteDimension[] = ['LUXURY','MINIMAL','DARK','BRIGHT','FASHION','EDITORIAL','COMMERCIAL','INSTAGRAM','PINTEREST','CINEMA','ART','PREMIUM'];
export class HeuristicTasteModel implements TasteModel { encode(prompt: StudioPrompt, dimensions: 128 | 256 = 128) { const text = `${prompt.text} ${prompt.domain ?? ''}`.toLowerCase(), coordinates = Object.fromEntries(tastes.map((taste) => [taste, clamp((text.includes(taste.toLowerCase()) ? .72 : .28) + (hash(`${prompt.projectId}:${taste}`) % 23) / 100)])) as Record<TasteDimension, number>; const values = Array.from({ length: dimensions }, (_, index) => { const taste = tastes[index % tastes.length]; return clamp(coordinates[taste] * .75 + (hash(`${text}:${index}`) % 25) / 100); }); return immutable({ dimensions, values, coordinates, version: 'heuristic-taste-1' }); } }
export class HeuristicWorldModel implements WorldModel { assess(prompt: StudioPrompt) { return immutable(VISUAL_LAWS.map((law) => { const score = clamp(.42 + (hash(`${prompt.text}:${law}`) % 45) / 100); return { law, score, confidence: .72, recommendation: score < .65 ? `Strengthen ${law.toLowerCase().replaceAll('_', ' ')}.` : `Preserve ${law.toLowerCase().replaceAll('_', ' ')}.` }; })); } }
export class HeuristicTradeoffModel implements TradeoffModel { solve(prompt: StudioPrompt, question: TradeoffQuestion): import('./types').TradeoffResult { const left = question.leftWeight ?? (question.left === 'QUALITY' ? .8 : question.left === 'BRAND' ? .75 : .55), right = question.rightWeight ?? (question.right === 'FACE_PRESERVATION' ? prompt.preserveIdentity ?? .8 : question.right === 'COST' ? 1 - Math.min(1, (prompt.budget ?? 50) / 100) : prompt.speedPriority ?? .5), delta = left - right; const winner: 'LEFT' | 'RIGHT' | 'BALANCED' = Math.abs(delta) < .1 ? 'BALANCED' : delta > 0 ? 'LEFT' : 'RIGHT'; return immutable({ ...question, winner, rationale: `Weighted ${question.left.toLowerCase()} ${left.toFixed(2)} against ${question.right.toLowerCase()} ${right.toFixed(2)}.`, confidence: clamp(.65 + Math.abs(delta) / 2) }); } }
