import { immutable } from './immutable';
import { CreativePrinciplesEngine } from './principles';
import { EXPERT_ROLES, HeuristicConsensusModel, HeuristicDirectorModel, HeuristicReasoningModel, HeuristicTasteModel, HeuristicTradeoffModel, HeuristicWorldModel } from './models';
import { CreativeIdentityEngine, CreativeIQEngine, CreativeMetricsEngine, DebateEngine, DirectorTimeline, HeuristicLearningModel, StrategyEvolution, StudioDebugger, StudioKnowledgeBase, StudioReplay } from './engines';
import type { ConsensusModel, DirectorModel, LearningModel, ReasoningModel, StudioDependencies, StudioPrompt, StudioTrace, TasteModel, TradeoffModel, TradeoffQuestion, WorldModel } from './types';

export interface StudioBrainModels { readonly reasoning?: ReasoningModel; readonly director?: DirectorModel; readonly consensus?: ConsensusModel; readonly taste?: TasteModel; readonly world?: WorldModel; readonly tradeoff?: TradeoffModel; readonly learning?: LearningModel }
export class CreativeStudioBrain {
  readonly knowledge = new StudioKnowledgeBase(); readonly replay = new StudioReplay(); readonly timeline: DirectorTimeline; readonly debugger = new StudioDebugger(); readonly strategies: StrategyEvolution; readonly principles = new CreativePrinciplesEngine();
  private readonly reasoning: ReasoningModel; private readonly director: DirectorModel; private readonly consensus: ConsensusModel; private readonly taste: TasteModel; private readonly world: WorldModel; private readonly tradeoff: TradeoffModel; private readonly learning: LearningModel;
  constructor(private readonly dependencies: StudioDependencies, models: StudioBrainModels = {}) { this.reasoning = models.reasoning ?? new HeuristicReasoningModel(dependencies.nextId); this.director = models.director ?? new HeuristicDirectorModel(dependencies.nextId); this.consensus = models.consensus ?? new HeuristicConsensusModel(); this.taste = models.taste ?? new HeuristicTasteModel(); this.world = models.world ?? new HeuristicWorldModel(); this.tradeoff = models.tradeoff ?? new HeuristicTradeoffModel(); this.learning = models.learning ?? new HeuristicLearningModel(dependencies.nextId, dependencies.now); this.timeline = new DirectorTimeline(dependencies.nextId, dependencies.now); this.strategies = new StrategyEvolution(dependencies.nextId, dependencies.now); }
  think(prompt: StudioPrompt, questions: readonly TradeoffQuestion[] = defaultTradeoffs): StudioTrace {
    const input = immutable(prompt), intent = prompt.intent ?? prompt.text, goals = immutable(prompt.goals ?? ['maximize creative quality', 'respect constraints']);
    const experts = immutable(EXPERT_ROLES.map((role) => this.reasoning.reason(input, role))), statements = this.director.direct(input, experts); const ai = experts.filter((opinion) => opinion.operations.includes('AI')).map(({ role }) => role), local = experts.filter((opinion) => !opinion.operations.includes('AI')).map(({ role }) => role); const debate = immutable({ opinions: experts, statements, conflicts: ai.length && local.length ? [{ topic: 'AI escalation', experts: [...ai, ...local] }] : [] }); const consensus = this.consensus.resolve(input, debate); const tradeoffs = immutable(questions.map((question) => this.tradeoff.solve(input, question))); const vector = this.taste.encode(input); const identity = new CreativeIdentityEngine().build(vector, consensus.operations); const visualLaws = this.world.assess(input); const expectedResult = new CreativeMetricsEngine().calculate(experts, visualLaws, vector); const strategy = this.strategies.evolve(prompt.domain ?? 'GENERAL', consensus.operations, expectedResult.beauty, consensus.confidence); const draft = { id: this.dependencies.nextId(), at: this.dependencies.now(), prompt: input, intent, goals, experts, debate, consensus, tradeoffs, knowledge: this.knowledge.query(prompt.domain), identity, reasoning: immutable(experts.map(({ reason }) => reason)), decision: consensus.summary, expectedResult, creativeIQ: new CreativeIQEngine().profile(expectedResult, this.knowledge.query().length / 10), visualLaws, strategy } as StudioTrace; const learned = this.knowledge.add(this.learning.learn(immutable(draft))); const trace = immutable({ ...draft, knowledge: this.knowledge.query(prompt.domain), creativeIQ: new CreativeIQEngine().profile(expectedResult, learned.confidence) }); this.replay.record(trace); this.timeline.append('DECISION', `${strategy.name} v${strategy.version}: ${trace.decision}`); return trace;
  }
}
const defaultTradeoffs: readonly TradeoffQuestion[] = immutable([{ left: 'QUALITY', right: 'SPEED' }, { left: 'QUALITY', right: 'COST' }, { left: 'REALISM', right: 'CREATIVITY' }, { left: 'BRAND', right: 'EMOTION' }, { left: 'QUALITY', right: 'FACE_PRESERVATION' }]);
export { CreativeStudioBrain as StudioBrain };
