import { CreativeOntology } from './CreativeOntology';
import { KnowledgeGraph } from './KnowledgeGraph';
import { clamp, deepFreeze, normalize, sameScope } from './immutable';
import type { CreativeRule, ImportanceScore, ImportanceSignals, KnowledgeDebugSnapshot, KnowledgeDependencies, KnowledgeNode, KnowledgeScope, ReasoningResult, SearchResult, ValidationIssue } from './types';

export class KnowledgeReasoner {
 constructor(private readonly graph:KnowledgeGraph){}
 reason(start:string,scope?:KnowledgeScope,maxDepth=5):ReasoningResult{const node=this.graph.findConcept(start,scope);if(!node)return deepFreeze({start,chain:[],recommended:[],confidence:0});const chain:ReasoningResult['chain'][number][]=[],recommended:string[]=[];let current=node;const seen=new Set([node.id]);for(let depth=0;depth<maxDepth;depth++){const candidates=this.graph.edges(scope).filter(e=>e.source===current.id&&!seen.has(e.target)).sort((a,b)=>b.weight*b.confidence-a.weight*a.confidence||a.target.localeCompare(b.target));if(!candidates.length)break;const edge=candidates[0],target=this.graph.nodes(scope).find(n=>n.id===edge.target)!;chain.push({from:current.concept,to:target.concept,relation:edge.relation,because:`${current.concept} ${edge.relation} ${target.concept}`,therefore:`consider ${target.concept}`,recommended:edge.relation==='recommends'||edge.relation==='leads-to'||edge.weight>=.7,confidence:edge.confidence});if(chain.at(-1)!.recommended)recommended.push(target.concept);seen.add(target.id);current=target;}return deepFreeze({start:node.concept,chain,recommended:[...new Set(recommended)],confidence:chain.length?chain.reduce((p,x)=>p*x.confidence,1):node.confidence});}
}
export class KnowledgeSearch {
 constructor(private readonly graph:KnowledgeGraph){}
 nearestConcepts(concept:string,scope?:KnowledgeScope,limit=10):readonly SearchResult[]{const start=this.graph.findConcept(concept,scope);if(!start)return deepFreeze([]);return deepFreeze(this.graph.nodes(scope).filter(n=>n.id!==start.id).map(n=>{const p=this.graph.shortestPath(start.id,n.id,scope);return{node:n,score:p.length?1/(p.length-1):0,path:p.map(x=>x.concept)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||b.node.importance-a.node.importance||a.node.id.localeCompare(b.node.id)).slice(0,limit));}
 semanticNeighborhood(concept:string,scope?:KnowledgeScope,depth=2):readonly KnowledgeNode[]{return deepFreeze(this.nearestConcepts(concept,scope).filter(x=>x.path.length-1<=depth).map(x=>x.node));}
 relatedKnowledge(concept:string,scope?:KnowledgeScope){return this.semanticNeighborhood(concept,scope,3);}
 reasoningPath(from:string,to:string,scope?:KnowledgeScope):readonly string[]{const a=this.graph.findConcept(from,scope),b=this.graph.findConcept(to,scope);return deepFreeze(a&&b?this.graph.shortestPath(a.id,b.id,scope).map(n=>n.concept):[]);}
 bestEvidence(scope?:KnowledgeScope,limit=10){return deepFreeze(this.graph.nodes(scope).slice().sort((a,b)=>b.evidenceCount*b.confidence-a.evidenceCount*a.confidence||a.id.localeCompare(b.id)).slice(0,limit));}
 topConcepts(scope?:KnowledgeScope,limit=10){return this.graph.centralConcepts(limit,scope);}
 search(query:{concept?:string;scope?:KnowledgeScope;limit?:number}){return query.concept?this.nearestConcepts(query.concept,query.scope,query.limit):deepFreeze(this.topConcepts(query.scope,query.limit));}
}
export class KnowledgeImportanceEngine {
 calculate(signals:ImportanceSignals):ImportanceScore{const clean={support:clamp(signals.support),usage:clamp(signals.usage),novelty:clamp(signals.novelty),frequency:clamp(signals.frequency),impact:clamp(signals.impact),confidence:clamp(signals.confidence)};return deepFreeze({...clean,importance:clamp(clean.support*.2+clean.usage*.15+clean.novelty*.1+clean.frequency*.1+clean.impact*.25+clean.confidence*.2)});}
 rank(nodes:readonly KnowledgeNode[],usage:Readonly<Record<string,number>>={}):readonly KnowledgeNode[]{return deepFreeze(nodes.slice().sort((a,b)=>{const sa=this.calculate({support:a.support/(a.support+1),usage:usage[a.id]??0,novelty:1/(a.generation??1),frequency:a.evidenceCount/(a.evidenceCount+1),impact:a.importance,confidence:a.confidence}).importance,sb=this.calculate({support:b.support/(b.support+1),usage:usage[b.id]??0,novelty:1/(b.generation??1),frequency:b.evidenceCount/(b.evidenceCount+1),impact:b.importance,confidence:b.confidence}).importance;return sb-sa||a.id.localeCompare(b.id);}));}
}
export class KnowledgeValidator {
 validate(graph:KnowledgeGraph,ontology?:CreativeOntology,rules:readonly CreativeRule[]=[] ,scope?:KnowledgeScope):readonly ValidationIssue[]{const issues:ValidationIssue[]=[];const nodes=graph.nodes(scope),groups=new Map<string,string[]>();for(const n of nodes){const key=normalize(n.concept);groups.set(key,[...(groups.get(key)??[]),n.id]);}for(const [concept,ids] of groups)if(ids.length>1)issues.push({type:'duplicate-concept',message:`Duplicate concept: ${concept}`,ids});for(const e of graph.edges(scope))if(!nodes.some(n=>n.id===e.source)||!nodes.some(n=>n.id===e.target))issues.push({type:'broken-reference',message:'Broken edge reference',ids:[e.source,e.target]});if(ontology?.hasCycle())issues.push({type:'cycle',message:'Ontology contains a cycle',ids:[]});if(ontology)for(const c of ontology.concepts())if(!c.trim())issues.push({type:'invalid-ontology',message:'Empty ontology concept',ids:[c]});const byId=new Map(rules.map(r=>[r.id,r]));for(const r of rules)for(const c of r.conflicts)if(byId.has(c)&&r.id<c)issues.push({type:'conflicting-rule',message:`Rules conflict: ${r.id} / ${c}`,ids:[r.id,c]});const connected=new Set(graph.connectedComponents(scope).slice().sort((a,b)=>b.length-a.length)[0]?.map(n=>n.id)??[]);for(const n of nodes)if(nodes.length>1&&!connected.has(n.id))issues.push({type:'unreachable-node',message:`Unreachable node: ${n.id}`,ids:[n.id]});return deepFreeze(issues.sort((a,b)=>`${a.type}:${a.ids.join()}`.localeCompare(`${b.type}:${b.ids.join()}`)));}
}
export class KnowledgeConsistencyEngine {
 check(graph:KnowledgeGraph,ontology:CreativeOntology,rules:readonly CreativeRule[],scope?:KnowledgeScope){const contradictions=graph.edges(scope).filter(e=>e.relation==='contradicts').map(e=>[e.source,e.target] as const);const duplicateRules:readonly string[][]=[...new Map(rules.map(r=>[JSON.stringify(r.conditions)+JSON.stringify(r.recommendations),[] as string[]])).entries()].map(([key])=>rules.filter(r=>JSON.stringify(r.conditions)+JSON.stringify(r.recommendations)===key).map(r=>r.id)).filter(x=>x.length>1);const ruleConflicts=rules.flatMap(r=>r.conflicts.filter(c=>rules.some(x=>x.id===c)).map(c=>[r.id,c] as const)).filter(([a,b])=>a<b);const ruleDominance=ruleConflicts.map(([a,b])=>{const x=rules.find(r=>r.id===a)!,y=rules.find(r=>r.id===b)!;return x.priority===y.priority?undefined:(x.priority>y.priority?[a,b]:[b,a]);}).filter(Boolean);return deepFreeze({contradictions,ontologyViolations:ontology.hasCycle()?['cycle']:[],duplicateRules,ruleDominance,ruleConflicts});}
}
export class KnowledgeEvolution {
 constructor(private readonly dependencies:KnowledgeDependencies){}
 branch(node:KnowledgeNode,changes:Partial<KnowledgeNode>):KnowledgeNode{const now=this.dependencies.now();return deepFreeze({...node,...changes,id:changes.id??this.dependencies.id(),scope:{...node.scope},tags:[...(changes.tags??node.tags)],generation:(node.generation??1)+1,parent:node.id,children:[],history:[...(node.history??[]),{generation:node.generation??1,concept:node.concept,timestamp:node.updatedAt,parent:node.parent}],updatedAt:now,createdAt:now,mergedFrom:[]});}
 merge(nodes:readonly KnowledgeNode[],changes:Partial<KnowledgeNode>={}):KnowledgeNode{if(nodes.length<2)throw new Error('Merge requires at least two nodes');if(nodes.some(n=>!sameScope(n,nodes[0].scope)))throw new Error('Scope isolation violation');const now=this.dependencies.now();return deepFreeze({...nodes[0],...changes,id:changes.id??this.dependencies.id(),scope:{...nodes[0].scope},tags:[...new Set(nodes.flatMap(n=>n.tags))].sort(),confidence:Math.max(...nodes.map(n=>n.confidence)),support:nodes.reduce((s,n)=>s+n.support,0),evidenceCount:nodes.reduce((s,n)=>s+n.evidenceCount,0),generation:Math.max(...nodes.map(n=>n.generation??1))+1,parent:undefined,children:[],history:nodes.flatMap(n=>n.history??[]),mergedFrom:nodes.map(n=>n.id).sort(),createdAt:now,updatedAt:now});}
 rollback(node:KnowledgeNode,generation:number):KnowledgeNode{const version=node.history?.find(v=>v.generation===generation);if(!version)throw new Error(`Generation ${generation} not found`);return deepFreeze({...node,concept:version.concept,generation,updatedAt:this.dependencies.now(),deprecated:false,active:true});}
 compare(a:KnowledgeNode,b:KnowledgeNode){const keys=(Object.keys({...a,...b}) as (keyof KnowledgeNode)[]).sort();return deepFreeze(keys.filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k])).map(field=>({field,before:a[field],after:b[field]})));}
}
export class KnowledgeDebugger {
 snapshot(input:KnowledgeDebugSnapshot):KnowledgeDebugSnapshot{return deepFreeze({...input,retrievedConcepts:[...input.retrievedConcepts],appliedRules:[...input.appliedRules],reasoningChain:input.reasoningChain.map(x=>({...x})),recommendedConcepts:[...input.recommendedConcepts],finalKnowledgeGraph:{nodes:[...input.finalKnowledgeGraph.nodes],edges:[...input.finalKnowledgeGraph.edges]}}) as KnowledgeDebugSnapshot;}
}
