import type { HealthReport, PrivacyAudit, ProductionDependencies, ProductionError, ProductionEventType, ProductionExecutionState, ProductionRequest, ProductionTelemetryEvent, RecoveryAction, SecurityEvent, SecurityEventType, TraceCorrelation } from './types';
import { ArtifactLifecycleManager, ConcurrencyGate, CostProtection, DependencyCircuitBreaker, MemoryProductionStateStore, MetricsAggregator, ProductionReadinessScore, RecoveryPolicyEngine, SlidingWindowRateLimiter, immutable, productionError, sanitize, scopeKey, withTimeout } from './ProductionInfrastructure';

const DEFAULT_TIMEOUT = { localInferenceMs: 30_000, networkMs: 15_000, providerJobMs: 120_000, artifactDownloadMs: 30_000, verificationMs: 10_000, recoveryMs: 30_000 };
const DEFAULT_RATES = { requestsPerMinute: 60, concurrentExecutions: 5, aiCallsPerMinute: 30, localInferencePerMinute: 60, downloadBytesPerMinute: 100_000_000 };
const DEFAULT_CONCURRENCY = { localInference: 2, cloudCalls: 4, highMemoryOperations: 1, downloads: 3, largeArtifacts: 1 };

export class CreativeProductionCoordinator {
  readonly #store; readonly #now; readonly #id; readonly #rate; readonly #gate = new ConcurrencyGate(); readonly #telemetry: ProductionTelemetryEvent[] = []; readonly #security: SecurityEvent[] = []; readonly #circuits = new Map<string, DependencyCircuitBreaker>(); readonly #states = new Map<string, ProductionExecutionState>(); readonly #inflight = new Map<string, Promise<ProductionExecutionState>>();
  readonly #timeout; readonly #concurrency; readonly #hash;
  constructor(private readonly deps: ProductionDependencies) { this.#store = deps.store ?? new MemoryProductionStateStore(); this.#now = deps.now ?? (() => Date.now()); this.#id = deps.id ?? (() => crypto.randomUUID()); this.#hash = deps.hash ?? sha256; this.#timeout = { ...DEFAULT_TIMEOUT, ...deps.timeout }; this.#concurrency = { ...DEFAULT_CONCURRENCY, ...deps.concurrency }; this.#rate = new SlidingWindowRateLimiter({ ...DEFAULT_RATES, ...deps.rateLimits }, this.#now); }

  async start(request: ProductionRequest): Promise<ProductionExecutionState> {
    const key = `${scopeKey(request.scope)}\0${request.idempotencyKey}`; const running = this.#inflight.get(key); if (running) return running;
    const execution = this.startOnce(request); this.#inflight.set(key, execution); try { return await execution; } finally { this.#inflight.delete(key); }
  }
  private async startOnce(request: ProductionRequest): Promise<ProductionExecutionState> {
    this.validate(request); const existing = await this.#store.getByIdempotency(request.scope, request.idempotencyKey); if (existing) return existing;
    const rateKey = `${scopeKey(request.scope)}:${request.operation}`; if (!this.#rate.acquire(rateKey, 'request', true)) throw productionError('RESOURCE_ERROR', 'RATE_LIMITED', true, 'Production rate limit exceeded');
    const executionId = this.#id(), attemptId = this.#id(), now = this.#now(); const correlation = this.correlation(request, executionId);
    const preflight = new CostProtection().preflight(request.estimatedCredits, request.maxRetries ?? 0, request.maxFallbackCost ?? 0, this.deps.budget);
    if (preflight.decision !== 'ALLOW') { this.eventSecurity('POLICY_BYPASS_ATTEMPT', correlation, { decision: preflight.decision, reasons: preflight.reasons }); throw productionError('BUDGET_ERROR', preflight.decision === 'BLOCK' ? 'BUDGET_BLOCKED' : 'USER_CONFIRMATION_REQUIRED', false, 'Cost preflight did not authorize execution', { preflight }); }
    if (request.billable && request.retrySemantics === 'UNSAFE_TO_RETRY') throw productionError('POLICY_ERROR', 'UNSAFE_BILLABLE_RETRY', false, 'Billable operation requires deduplication semantics');
    const lifecycle = new ArtifactLifecycleManager(); let record = lifecycle.create(request.artifact, request.scope, request.scope.userId, now, 86_400_000); record = lifecycle.transition(record, 'VALIDATING'); const checksumValid = request.artifact.bytes.byteLength > 0 && await this.#hash(request.artifact.bytes) === request.artifact.hash; record = lifecycle.transition(record, checksumValid ? 'READY' : 'QUARANTINED');
    if (record.state !== 'READY') { this.eventSecurity('CROSS_SCOPE_ARTIFACT', correlation, { artifactId: request.artifact.id }); throw productionError('ARTIFACT_ERROR', 'INVALID_ARTIFACT', false, 'Input artifact failed validation'); } lifecycle.assertUsable(record, request.scope, now);
    let state: ProductionExecutionState = immutable({ executionId, requestId: request.requestId, sessionId: request.sessionId, idempotencyKey: request.idempotencyKey, scope: request.scope, status: 'RUNNING', currentNode: request.operation, completedNodes: [], failedNodes: [], attempts: [{ attemptId, nodeId: request.operation, startedAt: now, outcome: 'RUNNING' }], artifacts: [lifecycle.transition(record, 'IN_USE')], cost: 0, credits: 0, latencyMs: 0, recovery: [], checkpoint: 0, createdAt: now, updatedAt: now }) as ProductionExecutionState;
    await this.persist(state); this.event('ExecutionStarted', correlation, { operation: request.operation }); this.event('NodeStarted', { ...correlation, nodeId: request.operation, artifactId: request.artifact.id }, {});
    try {
      if (['LOCAL_ONLY', 'OFFLINE_ONLY'].includes(request.privacyMode) && request.provider && request.provider !== 'local') { this.eventSecurity('OUTBOUND_DATA_BLOCKED', correlation, { provider: request.provider }); throw productionError('POLICY_ERROR', 'CLOUD_FORBIDDEN', false, 'Privacy policy forbids cloud execution'); }
      const resource = request.provider && request.provider !== 'local' ? 'cloudCalls' : 'localInference', limit = this.#concurrency[resource];
      if (resource === 'cloudCalls' && !this.#rate.acquire(rateKey, 'ai')) throw productionError('RESOURCE_ERROR', 'AI_RATE_LIMITED', true, 'AI call rate exceeded');
      if (resource === 'localInference' && !this.#rate.acquire(rateKey, 'local')) throw productionError('RESOURCE_ERROR', 'LOCAL_RATE_LIMITED', true, 'Local inference rate exceeded');
      const provider = request.provider ?? 'local', circuit = this.circuit(provider); if (!circuit.allow()) throw productionError('PROVIDER_ERROR', 'CIRCUIT_OPEN', true, 'Dependency circuit is open', { provider });
      this.event('ProviderSelected', correlation, { provider }); if (provider !== 'local') this.event('ProviderCalled', correlation, { provider, estimatedCredits: preflight.estimatedCredits });
      const outcome = await this.#gate.run(resource, limit, () => withTimeout(provider === 'local' ? this.#timeout.localInferenceMs : this.#timeout.providerJobMs, signal => this.deps.executor.execute(request, { executionId, attemptId, signal })));
      circuit.success(); const finished = this.#now(); const completedArtifact = outcome.result.finalArtifact ? lifecycle.create(outcome.result.finalArtifact, request.scope, request.scope.userId, finished, 86_400_000) : undefined;
      state = immutable({ ...state, status: 'COMPLETED', currentNode: undefined, completedNodes: [request.operation], attempts: [{ ...state.attempts[0], completedAt: finished, outcome: 'SUCCEEDED', ...(outcome.providerExecutionId ? { providerExecutionId: outcome.providerExecutionId } : {}) }], artifacts: completedArtifact ? [...state.artifacts, lifecycle.transition(lifecycle.transition(completedArtifact, 'VALIDATING'), 'READY')] : state.artifacts, cost: outcome.result.costSummary.cloudCost, credits: outcome.result.costSummary.cloudCredits, latencyMs: finished - now, checkpoint: 1, updatedAt: finished }) as ProductionExecutionState;
      this.event(outcome.qualityAccepted ? 'VerificationPassed' : 'VerificationFailed', correlation, {}); this.event('NodeCompleted', correlation, { local: outcome.local }); this.event('ExecutionCompleted', correlation, { credits: state.credits }); await this.persist(state); return state;
    } catch (cause) {
      const error = normalizeError(cause), unknown = request.billable && ['TIMEOUT', 'NETWORK_ERROR'].includes(error.category); const action = new RecoveryPolicyEngine().decide({ category: error.category, semantics: request.retrySemantics ?? (request.billable ? 'REQUIRES_DEDUPLICATION' : 'SAFE_TO_RETRY'), fallbackAvailable: false, checkpoint: false, providerResultUnknown: unknown }); if (request.provider) this.circuit(request.provider).failure();
      const failedAt = this.#now(); state = immutable({ ...state, status: action === 'MARK_UNKNOWN' ? 'UNKNOWN' : 'FAILED', failedNodes: [request.operation], attempts: [{ ...state.attempts[0], completedAt: failedAt, outcome: action === 'MARK_UNKNOWN' ? 'UNKNOWN' : 'FAILED' }], latencyMs: failedAt - now, recovery: [{ action, nodeId: request.operation, reason: error.category, timestamp: failedAt, outcome: 'PLANNED' }], updatedAt: failedAt, error }) as ProductionExecutionState;
      this.event('NodeFailed', correlation, { category: error.category, action }); await this.persist(state); return state;
    } finally { this.#rate.release(rateKey); }
  }

  async recover(executionId: string, action?: RecoveryAction) { const state = await this.required(executionId); const selected = action ?? state.recovery.at(-1)?.action ?? (state.status === 'RUNNING' ? 'MARK_UNKNOWN' : 'ABORT'); if (!['FAILED', 'UNKNOWN', 'RECOVERING', 'RUNNING'].includes(state.status)) return state; if (state.status === 'RUNNING' && !['MARK_UNKNOWN', 'RESUME', 'ABORT'].includes(selected)) throw productionError('RECOVERY_ERROR', 'CRASH_RECOVERY_ACTION_REQUIRED', false, 'Interrupted execution requires MARK_UNKNOWN, RESUME, or ABORT'); if (state.status === 'UNKNOWN' && ['RETRY', 'RESUME'].includes(selected)) throw productionError('RECOVERY_ERROR', 'UNKNOWN_RETRY_BLOCKED', false, 'Unknown billable result cannot be replayed automatically'); const now = this.#now(); const nextStatus = selected === 'ABORT' ? 'ABORTED' : selected === 'MARK_UNKNOWN' ? 'UNKNOWN' : 'RECOVERING'; const next = immutable({ ...state, status: nextStatus, attempts: selected === 'MARK_UNKNOWN' ? state.attempts.map(attempt => attempt.outcome === 'RUNNING' ? { ...attempt, completedAt: now, outcome: 'UNKNOWN' as const } : attempt) : state.attempts, recovery: [...state.recovery, { action: selected, reason: state.error?.category ?? 'RECOVERY_ERROR', timestamp: now, outcome: selected === 'ABORT' || selected === 'MARK_UNKNOWN' ? 'COMPLETED' : 'PLANNED' }], updatedAt: now }) as ProductionExecutionState; this.event(selected === 'ABORT' ? 'ExecutionAborted' : 'ExecutionRecovered', this.stateCorrelation(next), { action: selected }); await this.persist(next); return next; }
  async pause(id: string) { return this.transition(id, ['RUNNING', 'QUEUED'], 'PAUSED'); }
  async resume(id: string) { return this.transition(id, ['PAUSED', 'RECOVERING'], 'QUEUED'); }
  async cancel(id: string) { const state = await this.transition(id, ['CREATED', 'QUEUED', 'RUNNING', 'PAUSED', 'RECOVERING'], 'ABORTED'); this.event('ExecutionAborted', this.stateCorrelation(state), { reason: 'USER_CANCELLED' }); return state; }
  status(id: string) { return this.required(id); }
  snapshot(id: string) { return this.required(id); }
  async logicalReplay(id: string) { return immutable(await this.required(id)) as ProductionExecutionState; }
  async providerReplay(id: string, explicitlyAllowed: boolean) { const state = await this.required(id); if (!explicitlyAllowed) throw productionError('POLICY_ERROR', 'PROVIDER_REPLAY_FORBIDDEN', false, 'Provider replay requires explicit authorization'); if (state.credits > 0 || state.status === 'UNKNOWN') throw productionError('POLICY_ERROR', 'BILLABLE_REPLAY_FORBIDDEN', false, 'Billable or unknown provider result cannot be replayed'); return state; }
  telemetry(id?: string) { return immutable(this.#telemetry.filter(event => !id || event.correlation.executionId === id)); }
  securityEvents(id?: string) { return immutable(this.#security.filter(event => !id || event.correlation.executionId === id)); }
  allStates() { return immutable([...this.#states.values()]); }
  health(): HealthReport { const unknown = [...this.#states.values()].some(x => x.status === 'UNKNOWN'), failed = [...this.#states.values()].filter(x => x.status === 'FAILED').length; const component = unknown ? 'DEGRADED' : failed > 5 ? 'UNHEALTHY' : 'HEALTHY'; return immutable({ status: component, components: { provider: component, localRuntime: 'HEALTHY', model: 'HEALTHY', workflow: 'HEALTHY', execution: component, queue: 'HEALTHY', artifact: 'HEALTHY' }, checkedAt: this.#now() }) as HealthReport; }
  metrics() { return new MetricsAggregator().calculate([...this.#states.values()]); }
  readiness() { const health = this.health().status === 'HEALTHY' ? .95 : .75; return new ProductionReadinessScore().calculate({ reliability: health, security: 1, observability: 1, recovery: .9, costSafety: 1, privacy: 1, determinism: .95, artifactIntegrity: 1, providerStability: health, localRuntimeStability: health }); }
  privacyAudit(request: ProductionRequest, state: ProductionExecutionState): PrivacyAudit { const cloud = request.provider !== undefined && request.provider !== 'local' && this.#telemetry.some(event => event.correlation.executionId === state.executionId && event.type === 'ProviderCalled'); return immutable({ didImageLeaveDevice: cloud, ...(cloud ? { cloudProvider: request.provider, cloudOperation: request.operation } : {}), privacyPolicy: request.privacyMode, userConsent: request.userConsent, dataMinimizationMode: true }) as PrivacyAudit; }
  private validate(request: ProductionRequest) { scopeKey(request.scope); if (!request.idempotencyKey?.trim() || !request.requestId || !request.sessionId || !request.operation || !request.prompt) throw productionError('VALIDATION_ERROR', 'INVALID_REQUEST', false, 'Required production request fields are missing'); if (request.billable && !request.idempotencyKey) throw productionError('POLICY_ERROR', 'IDEMPOTENCY_REQUIRED', false, 'Billable execution requires idempotency'); }
  private circuit(provider: string) { let value = this.#circuits.get(provider); if (!value) { value = new DependencyCircuitBreaker(3, 30_000, this.#now); this.#circuits.set(provider, value); } return value; }
  private correlation(request: ProductionRequest, executionId: string): TraceCorrelation { return { requestId: request.requestId, sessionId: request.sessionId, executionId, nodeId: request.operation, artifactId: request.artifact.id }; }
  private stateCorrelation(state: ProductionExecutionState): TraceCorrelation { return { requestId: state.requestId, sessionId: state.sessionId, executionId: state.executionId, nodeId: state.currentNode }; }
  private event(type: ProductionEventType, correlation: TraceCorrelation, data: Record<string, unknown>) { this.#telemetry.push(immutable({ id: this.#id(), type, timestamp: this.#now(), correlation, data: sanitize(data) }) as ProductionTelemetryEvent); }
  private eventSecurity(type: SecurityEventType, correlation: TraceCorrelation, data: Record<string, unknown>) { this.#security.push(immutable({ id: this.#id(), type, timestamp: this.#now(), correlation, data: sanitize(data) }) as SecurityEvent); }
  private async persist(state: ProductionExecutionState) { this.#states.set(state.executionId, state); await this.#store.save(state); }
  private async required(id: string) { const state = this.#states.get(id) ?? await this.#store.get(id); if (!state) throw productionError('UNKNOWN_EXECUTION', 'EXECUTION_NOT_FOUND', false, 'Execution does not exist'); return state; }
  private async transition(id: string, allowed: readonly ProductionExecutionState['status'][], status: ProductionExecutionState['status']) { const state = await this.required(id); if (!allowed.includes(state.status)) throw productionError('POLICY_ERROR', 'INVALID_STATE_TRANSITION', false, `Cannot transition ${state.status} to ${status}`); const next = immutable({ ...state, status, updatedAt: this.#now() }) as ProductionExecutionState; await this.persist(next); return next; }
}

export class CreativeProductionDebugger { inspect(state: ProductionExecutionState, telemetry: readonly ProductionTelemetryEvent[]) { return immutable(sanitize({ request: { requestId: state.requestId, sessionId: state.sessionId, idempotencyKey: '[REDACTED]', scope: state.scope }, executionGraph: { currentNode: state.currentNode, completedNodes: state.completedNodes, failedNodes: state.failedNodes }, nodeStates: state.attempts, routing: telemetry.filter(x => x.type === 'ProviderSelected'), provider: state.attempts.map(x => x.providerExecutionId).filter(Boolean), cost: state.cost, latency: state.latencyMs, recovery: state.recovery, verification: telemetry.filter(x => x.type.startsWith('Verification')) })); } }

export class CreativeProductionRuntime {
  readonly coordinator: CreativeProductionCoordinator; readonly debugger = new CreativeProductionDebugger();
  constructor(dependencies: ProductionDependencies) { this.coordinator = new CreativeProductionCoordinator(dependencies); }
  start(request: ProductionRequest) { return this.coordinator.start(request); } resume(id: string) { return this.coordinator.resume(id); } pause(id: string) { return this.coordinator.pause(id); } cancel(id: string) { return this.coordinator.cancel(id); } status(id: string) { return this.coordinator.status(id); } recover(id: string, action?: RecoveryAction) { return this.coordinator.recover(id, action); } async inspect(id: string) { return this.debugger.inspect(await this.coordinator.status(id), this.coordinator.telemetry(id)); } health() { return this.coordinator.health(); } metrics() { return this.coordinator.metrics(); } trace(id?: string) { return this.coordinator.telemetry(id); } snapshot(id: string) { return this.coordinator.snapshot(id); } replay(id: string, mode: 'LOGICAL' | 'PROVIDER' = 'LOGICAL', explicitlyAllowed = false) { return mode === 'LOGICAL' ? this.coordinator.logicalReplay(id) : this.coordinator.providerReplay(id, explicitlyAllowed); }
}

function normalizeError(cause: unknown): ProductionError { if (cause && typeof cause === 'object' && 'category' in cause && 'code' in cause) return cause as ProductionError; const error = cause as Error; return productionError('PROVIDER_ERROR', 'EXECUTOR_FAILURE', true, error?.message ?? 'Executor failed'); }
async function sha256(bytes: Uint8Array) { const digest = await crypto.subtle.digest('SHA-256', bytes as BufferSource); return [...new Uint8Array(digest)].map(value => value.toString(16).padStart(2, '0')).join(''); }
