import { immutableClone } from './immutable';
import { HybridTargetSelector } from './HybridTargetSelector';
import type { HybridExecutionEdge, HybridExecutionGraphData, HybridExecutionNode, HybridExecutionStage, InputWorkflow, PayloadKind } from './types';
export class HybridExecutionGraph {
  create(workflow: InputWorkflow, selector = new HybridTargetSelector()): HybridExecutionGraphData {
    validate(workflow); const selected = new Map<string, HybridExecutionNode>();
    for (const input of workflow.nodes) { const choice = selector.select(input.candidates, workflow.policy); selected.set(input.id, { id: input.id, operation: input.operation, executionTarget: choice.target, localModel: choice.candidate?.localModel, cloudProvider: choice.candidate?.cloudProvider, dependencies: [...(input.dependencies ?? [])], fallback: choice.fallback, verification: { minQuality: workflow.policy.qualityRequirement, requireHash: true, allowedMimeTypes: ['image/png', 'image/jpeg', 'application/json', 'text/plain'] }, cost: choice.candidate?.metrics.monetaryCost ?? 0, latency: choice.candidate?.metrics.latencyMs ?? 0, privacy: choice.candidate?.metrics.privacyExposure ?? 0, candidate: choice.candidate, speculative: workflow.policy.speculativeLocal && input.reversible === true && choice.target === 'LOCAL' && choice.fallback.some((item) => item.target === 'CLOUD'), status: choice.target === 'BLOCKED' ? 'BLOCKED' : 'PENDING' }); }
    const nodes = workflow.nodes.map((node) => selected.get(node.id)!); const edges = nodes.flatMap((node) => node.dependencies.map((from) => boundary(selected.get(from)!, node, workflow.nodes.find((item) => item.id === node.id)?.requiredPayload ?? 'FULL_IMAGE', workflow.policy)));
    const levels = levelize(nodes); const stages: HybridExecutionStage[] = levels.map((nodeIds, index) => ({ id: `stage-${index + 1}`, nodeIds, strategy: strategy(nodeIds.map((id) => selected.get(id)!)) })); const barriers = stages.slice(0, -1).map((stage, index) => ({ id: `barrier-${index + 1}`, afterStage: stage.id, requiredNodeIds: stage.nodeIds }));
    return immutableClone({ id: `hybrid:${workflow.id}`, scope: workflow.scope, nodes, edges, stages, barriers });
  }
}
function boundary(from: HybridExecutionNode, to: HybridExecutionNode, requested: PayloadKind, policy: InputWorkflow['policy']): HybridExecutionEdge { const outbound = from.executionTarget === 'LOCAL' && (to.executionTarget === 'CLOUD' || to.executionTarget === 'HYBRID'); const download = (from.executionTarget === 'CLOUD' || from.executionTarget === 'HYBRID') && to.executionTarget === 'LOCAL'; const payload = outbound ? minimize(requested) : 'NONE'; return { from: from.id, to: to.id, imageLeavesDevice: outbound, cloudDownload: download, payload, permitted: (!outbound || policy.cloudAllowed && policy.outboundImageAllowed) && (!download || policy.cloudDownloadAllowed) }; }
function minimize(value: PayloadKind): PayloadKind { return value === 'FULL_IMAGE' ? 'CROPPED_IMAGE' : value; }
function strategy(nodes: readonly HybridExecutionNode[]): HybridExecutionStage['strategy'] { const targets = new Set(nodes.map((node) => node.executionTarget)); return targets.size > 1 ? 'PARALLEL' : targets.has('LOCAL') ? 'LOCAL_FIRST' : 'CLOUD_FIRST'; }
function validate(workflow: InputWorkflow): void { if (!workflow.id || !workflow.scope.tenantId || !workflow.scope.projectId || !workflow.scope.userId) throw new Error('Workflow and complete scope are required'); const ids = new Set<string>(); for (const node of workflow.nodes) { if (ids.has(node.id)) throw new Error(`Duplicate node: ${node.id}`); ids.add(node.id); } for (const node of workflow.nodes) for (const dependency of node.dependencies ?? []) if (!ids.has(dependency)) throw new Error(`Unknown dependency: ${dependency}`); levelize(workflow.nodes.map((node) => ({ id: node.id, dependencies: node.dependencies ?? [] } as HybridExecutionNode))); }
function levelize(nodes: readonly HybridExecutionNode[]): string[][] { const remaining = new Map(nodes.map((node) => [node.id, new Set(node.dependencies)])); const done = new Set<string>(); const levels: string[][] = []; while (remaining.size) { const ready = [...remaining.entries()].filter(([, dependencies]) => [...dependencies].every((id) => done.has(id))).map(([id]) => id).sort(); if (!ready.length) throw new Error('Hybrid graph contains a cycle'); levels.push(ready); for (const id of ready) { remaining.delete(id); done.add(id); } } return levels; }
