import { immutableClone } from './immutable';
import { HybridTargetSelector } from './HybridTargetSelector';
import type { ExecutionCandidate, HybridArtifact, HybridCheckpoint, HybridExecutionGraphData, HybridExecutionNode, HybridPolicy, HybridSimulation, LearningSignal, PayloadKind, RuntimeResources } from './types';
export class HybridScheduler {
  schedule(graph: HybridExecutionGraphData, resources: RuntimeResources) { const pressure = resources.thermal === 'HIGH' || resources.thermal === 'CRITICAL' || resources.batteryPercent < 15 || resources.ramAvailableMb < 256; const stages = graph.stages.map((stage) => ({ ...stage, strategy: pressure && stage.nodeIds.some((id) => graph.nodes.find((node) => node.id === id)?.executionTarget === 'CLOUD') ? 'CLOUD_FIRST' as const : resources.networkLatencyMs > 1_000 ? 'LOCAL_FIRST' as const : stage.strategy })); return immutableClone({ ...graph, stages }); }
}
export class HybridOptimizer {
  optimize(graph: HybridExecutionGraphData, policy: HybridPolicy): HybridExecutionGraphData { const selector = new HybridTargetSelector(); const nodes = graph.nodes.map((node) => { if (!node.candidate) return node; const selected = selector.select([node.candidate, ...node.fallback], policy); return { ...node, executionTarget: selected.target, candidate: selected.candidate, fallback: selected.fallback, localModel: selected.candidate?.localModel, cloudProvider: selected.candidate?.cloudProvider, cost: selected.candidate?.metrics.monetaryCost ?? 0, latency: selected.candidate?.metrics.latencyMs ?? 0, privacy: selected.candidate?.metrics.privacyExposure ?? 0 }; }); return immutableClone({ ...graph, nodes }); }
  simulate(graph: HybridExecutionGraphData): readonly HybridSimulation[] { const scenarios: HybridSimulation['name'][] = ['LOCAL_ONLY', 'CLOUD_ONLY', 'HYBRID_A', 'HYBRID_B']; return immutableClone(scenarios.map((name, index) => { const candidates = graph.nodes.flatMap((node) => [node.candidate, ...node.fallback]).filter((candidate): candidate is ExecutionCandidate => Boolean(candidate)).filter((candidate) => name === 'LOCAL_ONLY' ? candidate.target === 'LOCAL' : name === 'CLOUD_ONLY' ? candidate.target === 'CLOUD' : true); const metrics = candidates.map((item) => item.metrics); return { name, expectedQuality: average(metrics.map((item) => item.quality)), expectedCost: metrics.reduce((sum, item) => sum + item.monetaryCost, 0), expectedLatency: metrics.reduce((sum, item) => sum + item.latencyMs, 0), energy: metrics.reduce((sum, item) => sum + item.energyCost, 0), privacyExposure: metrics.reduce((sum, item) => sum + item.privacyExposure, 0), failureProbability: 1 - average(metrics.map((item) => item.reliability)) + index * 0 }; })); }
}
export class HybridOperationComposer { compose(local: ExecutionCandidate, cloud: ExecutionCandidate, verification: ExecutionCandidate): readonly ExecutionCandidate[] { if (local.target !== 'LOCAL' || cloud.target !== 'CLOUD' || verification.target !== 'LOCAL') throw new Error('Hybrid composition requires LOCAL + CLOUD + LOCAL'); return immutableClone([local, { ...cloud, target: 'HYBRID' as const }, verification]); } }
export class HybridEscalationPolicy { reason(node: HybridExecutionNode, problem: string, policy: HybridPolicy): string | null { if (!policy.cloudAllowed || policy.mode === 'LOCAL_ONLY') return null; const supported = ['quality insufficient', 'local latency too high', 'model unavailable', 'resource pressure', 'thermal restriction', 'unsupported operation']; return supported.includes(problem.toLowerCase()) && node.fallback.some((candidate) => candidate.target === 'CLOUD') ? problem : null; } }
export class HybridDataMinimizer { select(required: PayloadKind, outboundAllowed: boolean): PayloadKind { if (!outboundAllowed) return 'NONE'; return required === 'FULL_IMAGE' ? 'CROPPED_IMAGE' : required; } }
type MemoryRecord = Readonly<{ operation: string; localOutcome?: string; cloudOutcome?: string; latency: number; quality: number; cost: number; energy: number; fallbackRate: number }>;
export class HybridMemory { #records: MemoryRecord[] = []; record(value: MemoryRecord) { this.#records = [...this.#records, immutableClone(value)]; } aggregate(operation?: string) { const values = operation ? this.#records.filter((item) => item.operation === operation) : this.#records; return immutableClone({ count: values.length, latency: average(values.map((item) => item.latency)), quality: average(values.map((item) => item.quality)), cost: average(values.map((item) => item.cost)), energy: average(values.map((item) => item.energy)), fallbackRate: average(values.map((item) => item.fallbackRate)) }); } }
export class HybridLearningSignals { derive(target: string, local?: { quality: number; cost: number; latency: number }, cloud?: { quality: number; cost: number; latency: number }, blocked = false): readonly LearningSignal[] { const signals: LearningSignal[] = []; if (blocked) signals.push('PRIVACY_BLOCKED'); if (local) signals.push(local.quality > 0 ? 'LOCAL_SUCCESS' : 'LOCAL_FAILED'); if (target === 'CLOUD' && local) signals.push('CLOUD_ESCALATED'); if (target === 'LOCAL') signals.push('CLOUD_AVOIDED'); if (local && cloud && local.cost < cloud.cost) signals.push('LOCAL_CHEAPER'); if (local && cloud && local.latency < cloud.latency) signals.push('LOCAL_FASTER'); if (local && cloud && cloud.quality > local.quality) signals.push('CLOUD_HIGHER_QUALITY'); return Object.freeze(signals); } }
export const checkpoint = (node: HybridExecutionNode, artifacts: readonly HybridArtifact[], resources: RuntimeResources, remainingBudget: number, verified: boolean, imageLeavesDevice: boolean): HybridCheckpoint => immutableClone({ nodeId: node.id, target: node.executionTarget, localModel: node.localModel, cloudProvider: node.cloudProvider, artifacts, resources, remainingBudget, verified, imageLeavesDevice });
const average = (values: readonly number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;
