import { HybridExecutionGraph } from './HybridExecutionGraph';
import { HybridDebugger, HybridSnapshot } from './HybridReplay';
import { HybridDataMinimizer, HybridEscalationPolicy, HybridLearningSignals, HybridMemory, HybridOptimizer, HybridScheduler, checkpoint } from './HybridServices';
import { HybridTargetSelector } from './HybridTargetSelector';
import { HybridVerification } from './HybridVerification';
import { immutableClone } from './immutable';
import type { ExecutionCandidate, HybridArtifact, HybridExecutionGraphData, HybridExecutionNode, HybridExecutionSnapshot, HybridMetrics, HybridPorts, InputWorkflow, NodeResult, PayloadKind } from './types';
export class HybridExecutionEngine {
  readonly memory = new HybridMemory(); readonly #selector = new HybridTargetSelector(); readonly #verification = new HybridVerification(); readonly #optimizer = new HybridOptimizer(); #last?: HybridExecutionSnapshot;
  constructor(private readonly ports: HybridPorts) {}
  analyze(workflow: InputWorkflow) { const graph = new HybridExecutionGraph().create(workflow, this.#selector); return immutableClone({ workflowId: workflow.id, operations: workflow.nodes.length, localCandidates: workflow.nodes.filter((node) => node.candidates.some((item) => item.target === 'LOCAL' && item.trustedModel !== false)).length, cloudCandidates: workflow.nodes.filter((node) => node.candidates.some((item) => item.target === 'CLOUD' && item.providerAvailable !== false)).length, blocked: graph.nodes.filter((node) => node.executionTarget === 'BLOCKED').map((node) => node.id) }); }
  plan(workflow: InputWorkflow): HybridExecutionGraphData { return this.#optimizer.optimize(new HybridExecutionGraph().create(workflow, this.#selector), workflow.policy); }
  async route(workflow: InputWorkflow): Promise<HybridExecutionGraphData> { return new HybridScheduler().schedule(this.plan(workflow), await this.ports.resources()); }
  async execute(workflow: InputWorkflow): Promise<HybridExecutionSnapshot> {
    const graph = await this.route(workflow); const resources = await this.ports.resources(); const artifacts: HybridArtifact[] = []; const results: NodeResult[] = []; const checkpoints = []; const signals = []; const timeline: { sequence: number; event: string }[] = []; let spent = 0; let energy = 0; let latency = 0; let fallbackCount = 0;
    for (const stage of graph.stages) for (const nodeId of stage.nodeIds) { const node = graph.nodes.find((item) => item.id === nodeId)!; timeline.push({ sequence: timeline.length + 1, event: `${node.id}:${node.executionTarget}:START` });
      if (!validTarget(node.executionTarget) || node.executionTarget === 'BLOCKED') { results.push({ nodeId, target: 'BLOCKED', error: 'Execution blocked by policy' }); signals.push('PRIVACY_BLOCKED' as const); timeline.push({ sequence: timeline.length + 1, event: `${node.id}:BLOCKED` }); continue; }
      const inputs = node.dependencies.flatMap((dependency) => artifacts.filter((artifact) => artifact.metadata.producerNodeId === dependency)); assertScope(inputs, workflow.scope); const incoming = graph.edges.filter((edge) => edge.to === node.id); if (incoming.some((edge) => !edge.permitted)) { results.push({ nodeId, target: 'BLOCKED', error: 'Privacy boundary denied artifact handoff' }); signals.push('PRIVACY_BLOCKED' as const); continue; }
      const attempted = await this.#attempt(node, inputs, incoming[0]?.payload ?? 'NONE', workflow); let selected = attempted; let fallbackUsed: string | undefined;
      if (!attempted.ok) { const replacement = this.#fallback(node, workflow); if (replacement) { fallbackCount += 1; fallbackUsed = replacement.cloudProvider ?? replacement.localModel; signals.push('CLOUD_ESCALATED'); selected = await this.#attempt(replace(node, replacement), inputs, incoming[0]?.payload ?? 'NONE', workflow); } }
      if (selected.ok === false) { results.push({ nodeId, target: node.executionTarget, error: selected.error, fallbackUsed }); timeline.push({ sequence: timeline.length + 1, event: `${node.id}:FAILED` }); checkpoints.push(checkpoint(node, artifacts, resources, workflow.policy.creditBudget - spent, false, incoming.some((edge) => edge.imageLeavesDevice))); continue; }
      artifacts.push(selected.value.artifact); spent += selected.value.cost; energy += selected.value.energy; latency += selected.value.latencyMs; results.push({ nodeId, target: selected.target, result: selected.value, fallbackUsed }); signals.push(...new HybridLearningSignals().derive(selected.target, selected.target === 'LOCAL' ? { quality: selected.value.quality, cost: selected.value.cost, latency: selected.value.latencyMs } : undefined)); checkpoints.push(checkpoint(node, artifacts, resources, workflow.policy.creditBudget - spent, true, incoming.some((edge) => edge.imageLeavesDevice))); this.memory.record({ operation: node.operation, localOutcome: selected.target === 'LOCAL' ? 'SUCCESS' : undefined, cloudOutcome: selected.target !== 'LOCAL' ? 'SUCCESS' : undefined, latency: selected.value.latencyMs, quality: selected.value.quality, cost: selected.value.cost, energy: selected.value.energy, fallbackRate: fallbackUsed ? 1 : 0 }); timeline.push({ sequence: timeline.length + 1, event: `${node.id}:${selected.target}:SUCCESS` });
    }
    const metrics: HybridMetrics = { monetaryCost: spent, energy, latencyMs: latency, privacyExposure: graph.edges.filter((edge) => edge.imageLeavesDevice && edge.permitted).length, fallbackCount }; this.#last = new HybridSnapshot().create({ workflow, graph, results, artifacts, checkpoints, privacyDecisions: graph.edges, metrics, signals, timeline }); return this.#last;
  }
  async verify(snapshot: HybridExecutionSnapshot) { const values = await Promise.all(snapshot.artifacts.map((artifact) => this.#verification.verify(artifact, snapshot.workflow.scope, this.ports.hash))); return immutableClone({ valid: values.every((item) => item.valid), artifacts: values }); }
  recover(snapshot: HybridExecutionSnapshot, nodeId: string): HybridExecutionGraphData { const failed = snapshot.results.find((item) => item.nodeId === nodeId && item.error); const node = snapshot.graph.nodes.find((item) => item.id === nodeId); if (!failed || !node) throw new Error('Only a failed existing node can be replanned'); const replacement = this.#fallback(node, snapshot.workflow); if (!replacement) throw new Error('No recovery candidate'); return immutableClone({ ...snapshot.graph, nodes: snapshot.graph.nodes.map((item) => item.id === nodeId ? replace(item, replacement) : item) }); }
  estimate(workflow: InputWorkflow) { const graph = this.plan(workflow); return immutableClone({ selected: aggregate(graph.nodes.map((node) => node.candidate).filter((item): item is ExecutionCandidate => Boolean(item))), simulations: this.#optimizer.simulate(graph) }); }
  snapshot(): HybridExecutionSnapshot | undefined { return this.#last; }
  replay(snapshot: HybridExecutionSnapshot): HybridExecutionSnapshot { return immutableClone(snapshot) as HybridExecutionSnapshot; }
  debug(snapshot = this.#last) { return snapshot ? new HybridDebugger().inspect(snapshot) : undefined; }
  explain(snapshot = this.#last): readonly string[] { return snapshot ? new HybridDebugger().explain(snapshot) : Object.freeze([]); }
  async #attempt(node: HybridExecutionNode, artifacts: readonly HybridArtifact[], requiredPayload: PayloadKind, workflow: InputWorkflow): Promise<{ ok: true; value: Awaited<ReturnType<HybridPorts['local']['execute']>>; target: HybridExecutionNode['executionTarget'] } | { ok: false; error: string; target: HybridExecutionNode['executionTarget'] }> { try { const payload = new HybridDataMinimizer().select(requiredPayload, workflow.policy.cloudAllowed && workflow.policy.outboundImageAllowed); if ((node.executionTarget === 'CLOUD' || node.executionTarget === 'HYBRID') && requiredPayload !== 'NONE' && payload === 'NONE') return { ok: false, error: 'Outbound artifact blocked', target: node.executionTarget }; const value = node.executionTarget === 'LOCAL' ? await this.ports.local.execute(node, artifacts) : await this.ports.cloud.execute(node, artifacts, payload); const verified = await this.#verification.verify(value.artifact, workflow.scope, this.ports.hash); if (!verified.valid || value.quality < node.verification.minQuality) return { ok: false, error: 'Quality or artifact verification insufficient', target: node.executionTarget }; return { ok: true, value, target: node.executionTarget }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'Execution failed', target: node.executionTarget }; } }
  #fallback(node: HybridExecutionNode, workflow: InputWorkflow): ExecutionCandidate | undefined { const reason = new HybridEscalationPolicy().reason(node, 'quality insufficient', workflow.policy); return node.fallback.find((candidate) => (reason || node.executionTarget !== 'LOCAL') && (candidate.target !== 'CLOUD' || workflow.policy.cloudAllowed) && (candidate.target !== 'LOCAL' || candidate.trustedModel !== false)); }
}
function validTarget(target: string): target is HybridExecutionNode['executionTarget'] { return ['LOCAL', 'CLOUD', 'HYBRID', 'BLOCKED'].includes(target); }
function assertScope(artifacts: readonly HybridArtifact[], scope: InputWorkflow['scope']): void { if (artifacts.some((artifact) => artifact.scope.tenantId !== scope.tenantId || artifact.scope.projectId !== scope.projectId || artifact.scope.userId !== scope.userId)) throw new Error('Cross-project artifact rejected'); }
function replace(node: HybridExecutionNode, candidate: ExecutionCandidate): HybridExecutionNode { return immutableClone({ ...node, executionTarget: candidate.target, candidate, localModel: candidate.localModel, cloudProvider: candidate.cloudProvider, cost: candidate.metrics.monetaryCost, latency: candidate.metrics.latencyMs, privacy: candidate.metrics.privacyExposure, status: 'PENDING' }); }
function aggregate(candidates: readonly ExecutionCandidate[]) { return { expectedQuality: average(candidates.map((item) => item.metrics.quality)), monetaryCost: candidates.reduce((sum, item) => sum + item.metrics.monetaryCost, 0), deviceCost: candidates.reduce((sum, item) => sum + item.metrics.deviceCost, 0), energyCost: candidates.reduce((sum, item) => sum + item.metrics.energyCost, 0), latencyMs: candidates.reduce((sum, item) => sum + item.metrics.latencyMs, 0), privacyExposure: candidates.reduce((sum, item) => sum + item.metrics.privacyExposure, 0) }; }
const average = (values: readonly number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;
