export const modules = {
  common: { appName: 'Éditeur Photo IA', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', close: 'Fermer', create: 'Créer', apply: 'Appliquer', retry: 'Réessayer', confirm: 'Confirmer', back: 'Retour', next: 'Suivant', done: 'Terminé', loading: 'Chargement…', search: 'Rechercher', add: 'Ajouter', remove: 'Retirer', rename: 'Renommer', duplicate: 'Dupliquer', download: 'Télécharger', favorite: 'Favori', archive: 'Archiver', restore: 'Restaurer', signOut: 'Se déconnecter', empty: 'Rien ici pour le moment', minutes: '{count} min', seconds: '{seconds}s' },
  editor: { title: 'Éditeur', undo: 'Annuler', redo: 'Rétablir', restoreOriginal: "Restaurer l'original", detectObjects: 'Détecter les objets', detecting: 'Détection des objets…', prompt: 'Instruction', creativeStudio: 'Studio Créatif', recipes: 'Recettes', aiAgent: 'Agent IA', fashion: 'Mode', outfits: 'Tenues', before: 'Avant', after: 'Après', accept: 'Accepter', discard: 'Ignorer', objects: 'Objets', versions: 'Versions', newVersion: 'Nouvelle version', sceneMemory: 'Mémoire de scène', workspace: 'Espace de travail', jobCenter: 'Centre des tâches', instructionPlaceholder: 'Décrivez votre modification…', projectNotFound: 'Projet introuvable' },
  projects: { title: 'Projets', newProject: 'Nouveau projet', upload: 'Importer une image', empty: 'Aucun projet — importez une image pour commencer.', open: 'Ouvrir', processing: 'Traitement', draft: 'Brouillon', completed: 'Terminé' },
  recipes: { title: 'Recettes', favorite: 'Favori', popular: 'Populaires', recent: 'Récentes', recommended: 'Recommandées', run: 'Lancer la recette', use: 'Utiliser', searchPlaceholder: 'Rechercher des recettes…' },
  workspace: { title: 'Espace de travail', auto: 'Détecté automatiquement', manual: 'Manuel', switch: "Changer d'espace", recommendations: 'Recommandations', mostUsed: 'Le plus utilisé' },
  automation: { title: 'Studio d\'Automatisation', subtitle: 'Créez des workflows réutilisables sans écrire de code.', library: 'Bibliothèque d\'automatisations', templateGallery: 'Galerie de modèles', builder: 'Constructeur', history: 'Historique d\'exécution', run: 'Exécuter', queuing: 'En file d\'attente…', save: 'Enregistrer', trigger: 'Déclencheur', conditions: 'Conditions', condition: 'Condition', actions: 'Actions', action: 'Action', schedule: 'Planification', variables: 'Variables', estimatedCredits: 'Crédits estimés', estimatedTime: 'Temps estimé', emptyBuilder: 'Choisissez un modèle ou créez une automatisation.', emptyLibrary: 'Enregistrez un modèle pour votre bibliothèque.', noRuns: 'Aucune exécution pour le moment.', mostExecuted: 'Le plus exécuté', successRate: 'Succès {rate}%', failureRate: 'Échecs {rate}%', describePlaceholder: 'Décrivez ce workflow', actionsCount: '{count} actions', untitled: 'Automatisation sans titre', scheduleImmediate: 'Immédiat', scheduleScheduled: 'Planifié', scheduleDaily: 'Quotidien', scheduleWeekly: 'Hebdomadaire', scheduleManual: 'Manuel uniquement', containsPerson: 'Contient une personne', containsVehicle: 'Contient un véhicule', containsProduct: 'Contient un produit', containsAnimal: 'Contient un animal', containsText: 'Contient du texte' },
  fashion: { title: 'Mode', wardrobe: 'Garde-robe', garments: 'Vêtements', outfits: 'Tenues', addGarment: 'Ajouter un vêtement', collections: 'Collections', tryOn: 'Essayage', searchPlaceholder: 'Rechercher dans la garde-robe…', empty: 'Votre garde-robe est vide.' },
  billing: { title: 'Facturation', subscription: 'Abonnement', plan: 'Forfait', credits: 'Crédits', upgrade: 'Améliorer', currentPlan: 'Forfait actuel', usage: 'Utilisation', renew: 'Renouvellement le {date}' },
  settings: { title: 'Paramètres', account: 'Compte', appearance: 'Apparence', appearanceHint: 'Basculer entre le mode clair et sombre', language: 'Langue', languageHint: 'Choisissez la langue de l\'interface', performance: 'Performances', loadingPerformance: 'Chargement des paramètres de performance…' },
  errors: { generic: 'Une erreur est survenue.', network: 'Erreur réseau — vérifiez votre connexion.', offline: 'Vous êtes hors ligne. Les modifications seront synchronisées plus tard.', timeout: 'Délai dépassé. Veuillez réessayer.', provider: 'Le fournisseur IA n\'a pas pu traiter la demande.', validation: 'Veuillez corriger les champs en surbrillance.', credits: 'Vous n\'avez pas assez de crédits pour cette opération.', subscription: 'Votre forfait ne permet pas cette action.' },
  notifications: { title: 'Notifications', markAllRead: 'Tout marquer comme lu', empty: 'Aucune notification.', completed: 'Génération terminée', failed: 'Échec de la génération', saved: 'Modification enregistrée' },
  jobs: { title: 'Centre des tâches', queued: 'En file', running: 'En cours', waiting: 'En attente', completed: 'Terminé', failed: 'Échoué', cancelled: 'Annulé', retrying: 'Nouvelle tentative', cancel: 'Annuler', pause: 'Pause', resume: 'Reprendre', empty: 'Aucune tâche active.' },
  creative: { title: 'Studio Créatif', goal: 'Objectif', ideas: 'Idées', moodBoards: 'Planches d\'ambiance', strategy: 'Stratégie', generate: 'Générer des idées', apply: 'Appliquer la stratégie' },
  brand: { title: 'Studio de Marque', profile: 'Profil de marque', colors: 'Couleurs', fonts: 'Polices', voice: 'Ton', guidelines: 'Directives' },
  assets: { title: 'Bibliothèque de ressources', collections: 'Collections', pinned: 'Épinglés', smart: 'Intelligents', searchPlaceholder: 'Rechercher des ressources…', empty: 'Aucune ressource.', details: 'Détails' },
};
export default modules;