import React, { useEffect, useMemo, useState } from 'react';
import { coreClient } from '@/api/coreClient';
import AutomationTemplateGallery from '@/components/automation/AutomationTemplateGallery';
import AutomationLibraryPanel from '@/components/automation/AutomationLibraryPanel';
import AutomationBuilderPanel from '@/components/automation/AutomationBuilderPanel';
import AutomationHistoryPanel from '@/components/automation/AutomationHistoryPanel';
import { automationManager } from '@/lib/automation/AutomationManager';
import { automationBuilder } from '@/lib/automation/AutomationBuilder';
import { automationRunner } from '@/lib/automation/AutomationRunner';
import { automationHistory } from '@/lib/automation/AutomationHistory';
import { automationAnalytics } from '@/lib/automation/AutomationAnalytics';
import { useTranslation } from '@/lib/i18n/TranslationProvider';

export default function AutomationStudio() {
  const { t } = useTranslation(); const [automations, setAutomations] = useState([]); const [runs, setRuns] = useState([]); const [projects, setProjects] = useState([]); const [draft, setDraft] = useState(null); const [running, setRunning] = useState(false); const load = async () => { const [saved, history, allProjects] = await Promise.all([automationManager.list(), automationHistory.list(), coreClient.entities.Project.list('-updated_date', 100)]); setAutomations(saved); setRuns(history); setProjects(allProjects); }; useEffect(() => { load(); }, []); const analytics = useMemo(() => automationAnalytics.summary(runs), [runs]); const chooseTemplate = (id) => setDraft(automationBuilder.fromTemplate(id)); const create = () => setDraft(automationBuilder.blank()); const save = async () => { const estimate = automationBuilder.estimate(draft); const existing = automations.find((item) => item.id === draft.id); const saved = existing ? await automationManager.update(existing, { ...draft, ...estimate }) : await automationManager.create({ ...draft, ...estimate }); setAutomations((items) => existing ? items.map((item) => item.id === saved.id ? saved : item) : [saved, ...items]); setDraft(saved); automationAnalytics.track('saved', { actions: saved.actions.length }); }; const run = async () => { setRunning(true); try { const automation = automations.find((item) => item.id === draft.id) || draft; const result = await automationRunner.run({ automation, context: { project: projects[0] } }); setRuns((items) => [{ automation_name: automation.name, status: 'completed', action_count: automation.actions.length, result, id: `local-${Date.now()}` }, ...items]); } finally { setRunning(false); } }; return <div className="mx-auto max-w-7xl space-y-5 px-4 py-6"><div><h1 className="text-2xl font-semibold">{t('automation.title')}</h1><p className="text-sm text-muted-foreground">{t('automation.subtitle')}</p></div><AutomationTemplateGallery onChoose={chooseTemplate} /><div className="grid gap-4 lg:grid-cols-[220px_minmax(0,1fr)]"><AutomationLibraryPanel automations={automations} selectedId={draft?.id} onSelect={setDraft} onCreate={create} onFavorite={async (automation) => { const updated = await automationManager.favorite(automation); setAutomations((items) => items.map((item) => item.id === updated.id ? updated : item)); }} /><AutomationBuilderPanel automation={draft} projects={projects} onChange={setDraft} onSave={save} onRun={run} running={running} /></div><AutomationHistoryPanel runs={runs} analytics={analytics} /></div>; }