export const modules = {
  common: { appName: 'AI Фоторедактор', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Изменить', close: 'Закрыть', create: 'Создать', apply: 'Применить', retry: 'Повторить', confirm: 'Подтвердить', back: 'Назад', next: 'Далее', done: 'Готово', loading: 'Загрузка…', search: 'Поиск', add: 'Добавить', remove: 'Убрать', rename: 'Переименовать', duplicate: 'Дублировать', download: 'Скачать', favorite: 'В избранное', archive: 'В архив', restore: 'Восстановить', signOut: 'Выйти', empty: 'Здесь пока пусто', minutes: '{count} мин', seconds: '{seconds}с' },
  editor: { title: 'Редактор', undo: 'Отменить', redo: 'Повторить', restoreOriginal: 'Вернуть оригинал', detectObjects: 'Найти объекты', detecting: 'Поиск объектов…', prompt: 'Запрос', creativeStudio: 'Креатив-студия', recipes: 'Рецепты', aiAgent: 'ИИ-агент', fashion: 'Мода', outfits: 'Образы', before: 'До', after: 'После', accept: 'Принять', discard: 'Отклонить', objects: 'Объекты', versions: 'Версии', newVersion: 'Новая версия', sceneMemory: 'Память сцены', workspace: 'Рабочая область', jobCenter: 'Центр задач', instructionPlaceholder: 'Опишите изменение…', projectNotFound: 'Проект не найден' },
  projects: { title: 'Проекты', newProject: 'Новый проект', upload: 'Загрузить изображение', empty: 'Проектов пока нет — загрузите изображение, чтобы начать.', open: 'Открыть', processing: 'Обработка', draft: 'Черновик', completed: 'Готово' },
  recipes: { title: 'Рецепты', favorite: 'Избранное', popular: 'Популярные', recent: 'Недавние', recommended: 'Рекомендуемые', run: 'Запустить рецепт', use: 'Использовать', searchPlaceholder: 'Поиск рецептов…' },
  workspace: { title: 'Рабочая область', auto: 'Автоопределение', manual: 'Вручную', switch: 'Сменить область', recommendations: 'Рекомендации', mostUsed: 'Чаще всего' },
  automation: { title: 'Студия автоматизации', subtitle: 'Создавайте многоразовые рабочие процессы редактирования без кода.', library: 'Библиотека автоматизаций', templateGallery: 'Галерея шаблонов', builder: 'Конструктор', history: 'История выполнения', run: 'Запустить', queuing: 'В очереди…', save: 'Сохранить', trigger: 'Триггер', conditions: 'Условия', condition: 'Условие', actions: 'Действия', action: 'Действие', schedule: 'Расписание', variables: 'Переменные', estimatedCredits: 'Оценка кредитов', estimatedTime: 'Оценка времени', emptyBuilder: 'Выберите шаблон или создайте автоматизацию.', emptyLibrary: 'Сохраните шаблон, чтобы наполнить библиотеку.', noRuns: 'Запусков пока нет.', mostExecuted: 'Чаще всего', successRate: 'Успех {rate}%', failureRate: 'Ошибки {rate}%', describePlaceholder: 'Опишите этот процесс', actionsCount: '{count} действий', untitled: 'Автоматизация без названия', scheduleImmediate: 'Немедленно', scheduleScheduled: 'По расписанию', scheduleDaily: 'Ежедневно', scheduleWeekly: 'Еженедельно', scheduleManual: 'Только вручную', containsPerson: 'Содержит человека', containsVehicle: 'Содержит транспорт', containsProduct: 'Содержит товар', containsAnimal: 'Содержит животное', containsText: 'Содержит текст' },
  fashion: { title: 'Мода', wardrobe: 'Гардероб', garments: 'Одежда', outfits: 'Образы', addGarment: 'Добавить вещь', collections: 'Коллекции', tryOn: 'Примерка', searchPlaceholder: 'Поиск в гардеробе…', empty: 'Ваш гардероб пуст.' },
  billing: { title: 'Оплата', subscription: 'Подписка', plan: 'Тариф', credits: 'Кредиты', upgrade: 'Улучшить', currentPlan: 'Текущий тариф', usage: 'Использование', renew: 'Продление {date}' },
  settings: { title: 'Настройки', account: 'Аккаунт', appearance: 'Оформление', appearanceHint: 'Переключение светлой и тёмной темы', language: 'Язык', languageHint: 'Выберите язык интерфейса', performance: 'Производительность', loadingPerformance: 'Загрузка настроек производительности…' },
  errors: { generic: 'Что-то пошло не так.', network: 'Ошибка сети — проверьте подключение.', offline: 'Вы офлайн. Изменения синхронизируются при подключении.', timeout: 'Время ожидания истекло. Повторите попытку.', provider: 'ИИ-провайдер не смог выполнить запрос.', validation: 'Исправьте выделенные поля.', credits: 'Недостаточно кредитов для этой операции.', subscription: 'Ваш тариф не позволяет это действие.' },
  notifications: { title: 'Уведомления', markAllRead: 'Отметить все как прочитанные', empty: 'Нет уведомлений.', completed: 'Генерация завершена', failed: 'Ошибка генерации', saved: 'Изменение сохранено' },
  jobs: { title: 'Центр задач', queued: 'В очереди', running: 'Выполняется', waiting: 'Ожидание', completed: 'Завершено', failed: 'Ошибка', cancelled: 'Отменено', retrying: 'Повтор', cancel: 'Отменить', pause: 'Пауза', resume: 'Продолжить', empty: 'Нет активных задач.' },
  creative: { title: 'Креатив-студия', goal: 'Цель', ideas: 'Идеи', moodBoards: 'Мудборды', strategy: 'Стратегия', generate: 'Сгенерировать идеи', apply: 'Применить стратегию' },
  brand: { title: 'Бренд-студия', profile: 'Профиль бренда', colors: 'Цвета', fonts: 'Шрифты', voice: 'Тон', guidelines: 'Гайдлайны' },
  assets: { title: 'Библиотека ресурсов', collections: 'Коллекции', pinned: 'Закреплённые', smart: 'Умные', searchPlaceholder: 'Поиск ресурсов…', empty: 'Ресурсов пока нет.', details: 'Подробности' },
};
export default modules;