import { clamp, immutable } from "./immutable";

export interface WorldKnowledge { readonly from: string; readonly to: string; readonly relation: string; readonly weight: number; readonly evidence: number }
export class CreativeWorldModel { private knowledge: readonly WorldKnowledge[] = immutable([]); update(item: WorldKnowledge) { const current = this.knowledge.find((value) => value.from === item.from && value.to === item.to && value.relation === item.relation); const next = current ? { ...item, weight: (current.weight * current.evidence + item.weight * item.evidence) / (current.evidence + item.evidence), evidence: current.evidence + item.evidence } : structuredClone(item); this.knowledge = immutable([...this.knowledge.filter((value) => value !== current), next].sort((a, b) => `${a.from}:${a.to}`.localeCompare(`${b.from}:${b.to}`))); return immutable(next); } query(concept: string, depth = 1) { const result: WorldKnowledge[] = [], frontier = [concept], seen = new Set(frontier); for (let level = 0; level < depth; level++) { const next: string[] = []; this.knowledge.filter(({ from }) => frontier.includes(from)).forEach((item) => { result.push(item); if (!seen.has(item.to)) { seen.add(item.to); next.push(item.to); } }); frontier.splice(0, frontier.length, ...next); } return immutable(structuredClone(result)); } export() { return immutable(structuredClone(this.knowledge)); } }

export type StyleVector = Readonly<Record<string, number>>;
export class StyleSpace { static readonly dimensions = immutable(["minimalism", "warmth", "contrast", "brightness", "premium", "cleanliness", "cinematic", "fashion", "luxury", "social", "studio"]); point(values: StyleVector): StyleVector { return immutable(Object.fromEntries(StyleSpace.dimensions.map((key) => [key, clamp(values[key] ?? 0)]))); } distance(a: StyleVector, b: StyleVector) { const left = this.point(a), right = this.point(b); return Math.sqrt(StyleSpace.dimensions.reduce((sum, key) => sum + (left[key] - right[key]) ** 2, 0) / StyleSpace.dimensions.length); } interpolate(a: StyleVector, b: StyleVector, amount: number) { const t = clamp(amount); return this.point(Object.fromEntries(StyleSpace.dimensions.map((key) => [key, (a[key] ?? 0) * (1 - t) + (b[key] ?? 0) * t]))); } nearest(target: StyleVector, styles: Readonly<Record<string, StyleVector>>) { return immutable(Object.entries(styles).map(([name, vector]) => ({ name, distance: this.distance(target, vector) })).sort((a, b) => a.distance - b.distance || a.name.localeCompare(b.name))); } }

export interface CreativeStrategy { readonly name: string; readonly operations: readonly string[]; readonly goals: readonly string[]; readonly quality: number; readonly cost: number; readonly risk: number; readonly recommendedPersonas: readonly string[] }
const names = ["Luxury", "Minimal", "Professional", "Budget", "Catalog", "Portrait", "Fashion", "Studio", "Marketing", "Creative", "Experimental"] as const;
export class CreativeStrategyLibrary { private strategies: readonly CreativeStrategy[]; constructor(extra: readonly CreativeStrategy[] = []) { this.strategies = immutable([...names.map((name, index) => ({ name, operations: index % 2 ? ["exposure", "color"] : ["lighting", "contrast"], goals: [name.toLowerCase()], quality: clamp(.68 + index * .025), cost: index % 4, risk: clamp(.08 + index * .04), recommendedPersonas: [name.toUpperCase()] })), ...structuredClone(extra)]); } list() { return immutable(structuredClone(this.strategies)); } get(name: string) { const result = this.strategies.find((strategy) => strategy.name.toLowerCase() === name.toLowerCase()); return result && immutable(structuredClone(result)); } recommend(goal: string, persona?: string) { return immutable([...this.strategies].sort((a, b) => Number(b.goals.includes(goal.toLowerCase())) - Number(a.goals.includes(goal.toLowerCase())) || Number(b.recommendedPersonas.includes(persona ?? "")) - Number(a.recommendedPersonas.includes(persona ?? "")) || b.quality - a.quality)); } }

export class ReversePlanningEngine { plan(input: { readonly desiredResult: string; readonly targetStyle: StyleVector; readonly requiredQuality: number; readonly availableOperations: readonly string[] }) { const style = new StyleSpace().point(input.targetStyle), ranked = Object.entries(style).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])), operationHints: Record<string, string[]> = { warmth: ["white_balance", "lighting"], contrast: ["contrast"], brightness: ["exposure"], cleanliness: ["cleanup"], premium: ["lighting", "skin_cleanup"], cinematic: ["color_grade"], studio: ["background", "lighting"], fashion: ["retouch"] }; const operations = [...new Set(ranked.filter(([, value]) => value >= .5).flatMap(([key]) => operationHints[key] ?? []).filter((op) => input.availableOperations.includes(op)))]; return immutable({ desiredResult: input.desiredResult, targetStyle: style, requiredQuality: clamp(input.requiredQuality), requiredOperations: operations, executionPlan: operations.map((operation, index) => immutable({ order: index + 1, operation, reason: `Required for ${ranked.find(([key]) => operationHints[key]?.includes(operation))?.[0] ?? "target style"}` })) }); } }

export interface ReasoningBranch { readonly id: string; readonly alternative: string; readonly confidence: number; readonly utility: number; readonly explanation: string; readonly pruned: boolean; readonly pruningReason?: string }
export class CreativeReasoningTree { build(prompt: string, goals: readonly string[], alternatives: readonly Omit<ReasoningBranch, "pruned" | "pruningReason">[], threshold = .3) { const branches = alternatives.map((item) => immutable({ ...structuredClone(item), pruned: item.confidence < threshold || item.utility < threshold, pruningReason: item.confidence < threshold ? "LOW_CONFIDENCE" : item.utility < threshold ? "LOW_UTILITY" : undefined })); const selected = [...branches].filter(({ pruned }) => !pruned).sort((a, b) => b.utility - a.utility || b.confidence - a.confidence || a.id.localeCompare(b.id))[0]; return immutable({ prompt, goals: [...goals], expansion: branches, pruning: branches.filter(({ pruned }) => pruned), comparison: branches.filter(({ pruned }) => !pruned), selection: selected }); } }
export class DecisionSelfCritic { critique(selected: { readonly id: string; readonly quality: number; readonly risk: number; readonly cost: number; readonly operations: readonly string[] }, alternatives: readonly { readonly id: string; readonly quality: number; readonly risk: number; readonly cost: number; readonly operations: readonly string[] }[]) { return immutable({ decisionId: selected.id, strengths: [selected.quality >= .8 ? "HIGH_QUALITY" : "CLEAR_EXECUTION_PATH"], weaknesses: [selected.cost > 0 ? "HAS_COST" : "LIMITED_QUALITY_CEILING"], risks: selected.risk > .3 ? ["ELEVATED_RISK"] : [], alternatives: alternatives.filter(({ id }) => id !== selected.id).map(({ id }) => id), missedOpportunities: alternatives.filter((item) => item.quality > selected.quality || item.cost < selected.cost).map(({ id }) => id), improvementSuggestions: selected.risk > .3 ? ["ADD_PREVIEW"] : ["VALIDATE_AGAINST_GOAL"] }); } }

export class DecisionFatigueModel { assess(input: { readonly choices: number; readonly confirmations: number; readonly creativeBranches: number; readonly decisions: number }) { const choiceOverload = clamp((input.choices - 3) / 12), confirmationOverload = clamp(input.confirmations / 8), creativeOverload = clamp(input.creativeBranches / 12), decisionOverload = clamp(input.decisions / 20), score = (choiceOverload + confirmationOverload + creativeOverload + decisionOverload) / 4; const recommendation = score >= .75 ? "AUTOMATIC_MODE" : choiceOverload >= .6 ? "ONE_RECOMMENDATION" : creativeOverload >= .6 ? "BREAK_COMPLEX_WORKFLOW" : score >= .35 ? "PRESET" : "NONE"; return immutable({ choiceOverload, confirmationOverload, creativeOverload, decisionOverload, score, recommendation }); } }
export class CreativeSatisfactionModel { assess(input: { readonly technicalQuality: number; readonly creativeQuality: number; readonly goalCompletion: number; readonly userSatisfaction: number; readonly confidenceSatisfaction: number; readonly expectedSatisfaction?: number }) { const satisfaction = clamp(input.technicalQuality * .2 + input.creativeQuality * .25 + input.goalCompletion * .25 + input.userSatisfaction * .2 + input.confidenceSatisfaction * .1); return immutable({ ...input, satisfaction, expectationGap: satisfaction - (input.expectedSatisfaction ?? satisfaction) }); } }
