import { clamp, immutable } from "./immutable";

export interface FutureScenario { readonly id: string; readonly operations: readonly string[]; readonly quality: number; readonly cost: number; readonly latency: number; readonly risk: number; readonly probability: number; readonly satisfaction: number; readonly creativity: number }
export interface SimulationInput { readonly operations: readonly string[]; readonly baselineQuality?: number; readonly budget?: number; readonly count?: number }
export interface ScenarioEstimator { estimate(operations: readonly string[], index: number, input: SimulationInput): Omit<FutureScenario, "id" | "operations"> }
export class DecisionSimulator { constructor(private readonly estimator?: ScenarioEstimator) {} simulate(input: SimulationInput): readonly FutureScenario[] { const count = Math.max(10, input.count ?? 10), operations = [...new Set(input.operations)].sort(), scenarios = Array.from({ length: count }, (_, index) => { const selected = operations.filter((_, operationIndex) => (operationIndex + index) % Math.max(1, Math.min(3, operations.length)) !== 1); const defaults = { quality: clamp((input.baselineQuality ?? .5) + .025 * selected.length - index * .002), cost: selected.length * (index % 3), latency: selected.length * 120 + index * 15, risk: clamp(.08 + index * .025), probability: clamp(.92 - index * .035), satisfaction: clamp((input.baselineQuality ?? .5) + selected.length * .02), creativity: clamp(.3 + (index % 5) * .12) }; return immutable({ id: `future-${String(index + 1).padStart(2, "0")}`, operations: immutable(selected), ...(this.estimator?.estimate(selected, index, input) ?? defaults) }); }); return immutable(scenarios.sort((a, b) => (b.quality * b.probability + b.satisfaction - b.cost / Math.max(1, input.budget ?? 100)) - (a.quality * a.probability + a.satisfaction - a.cost / Math.max(1, input.budget ?? 100)) || a.id.localeCompare(b.id))); } }

export type EconomicRecommendation = "STOP" | "CONTINUE" | "LOCAL_ONLY" | "AI_JUSTIFIED" | "AI_WASTE";
export class DecisionEconomics { analyze(input: { readonly baselineQuality: number; readonly expectedQuality: number; readonly cost: number; readonly credits?: number; readonly previousCost?: number; readonly previousQuality?: number; readonly expectedRevenue?: number; readonly bestAlternativeValue?: number; readonly mode?: "LOCAL" | "HYBRID" | "AI" }) { const qualityGain = input.expectedQuality - input.baselineQuality, marginalQuality = input.expectedQuality - (input.previousQuality ?? input.baselineQuality), marginalCost = input.cost - (input.previousCost ?? 0), expectedValue = (input.expectedRevenue ?? input.expectedQuality * 100) * input.expectedQuality - input.cost, roi = input.cost ? (expectedValue - input.cost) / input.cost : expectedValue; let recommendation: EconomicRecommendation = qualityGain <= 0 ? "STOP" : "CONTINUE"; if (input.mode === "LOCAL") recommendation = "LOCAL_ONLY"; else if (input.mode === "AI") recommendation = qualityGain / Math.max(input.cost, .001) >= .02 ? "AI_JUSTIFIED" : "AI_WASTE"; return immutable({ roi, qualityGain, costEfficiency: qualityGain / Math.max(input.cost, .001), creditEfficiency: qualityGain / Math.max(input.credits ?? input.cost, .001), marginalQuality, marginalCost, expectedValue, opportunityCost: Math.max(0, (input.bestAlternativeValue ?? 0) - expectedValue), recommendation }); } }

export interface DecisionModelSample { readonly id: string; readonly features: Readonly<Record<string, number>>; readonly quality: number; readonly satisfaction: number; readonly accepted: boolean; readonly cost: number }
export interface DecisionModelCandidate { readonly id: string; readonly features: Readonly<Record<string, number>>; readonly cost?: number }
export interface DecisionModel { train(samples: readonly DecisionModelSample[]): unknown; evaluate(candidate: DecisionModelCandidate): number; rank(candidates: readonly DecisionModelCandidate[]): readonly DecisionModelCandidate[]; predict(candidate: DecisionModelCandidate): Readonly<Record<string, number>>; simulate(candidates: readonly DecisionModelCandidate[]): readonly Readonly<Record<string, unknown>>[]; adapt(sample: DecisionModelSample): unknown; exportDataset(): string; importDataset(dataset: string): unknown; calibrate(predictions: readonly number[], realities: readonly number[]): unknown; explain(candidate: DecisionModelCandidate): unknown; version(): string }
export class HeuristicDecisionModel implements DecisionModel {
  private samples: readonly DecisionModelSample[] = immutable([]); private bias = 0; constructor(private readonly modelVersion = "heuristic-1.0") {}
  train(samples: readonly DecisionModelSample[]) { this.samples = immutable(structuredClone(samples)); return immutable({ samples: samples.length, version: this.modelVersion }); }
  evaluate(candidate: DecisionModelCandidate): number { const values = Object.values(candidate.features); return clamp((values.length ? average(values) : .5) + this.bias - (candidate.cost ?? 0) / 1000); }
  rank(candidates: readonly DecisionModelCandidate[]): readonly DecisionModelCandidate[] { return immutable([...candidates].sort((a, b) => this.evaluate(b) - this.evaluate(a) || a.id.localeCompare(b.id)).map((candidate) => structuredClone(candidate))); }
  predict(candidate: DecisionModelCandidate) { const score = this.evaluate(candidate); return immutable({ quality: score, satisfaction: clamp(score * .9 + .05), probability: clamp(.5 + score / 2), cost: candidate.cost ?? 0 }); }
  simulate(candidates: readonly DecisionModelCandidate[]) { return immutable(this.rank(candidates).map((candidate) => ({ candidate, prediction: this.predict(candidate) }))); }
  adapt(sample: DecisionModelSample) { this.samples = immutable([...this.samples, structuredClone(sample)]); this.bias = clamp(this.bias + ((sample.accepted ? sample.quality : 1 - sample.quality) - .5) * .01) - .5; return immutable({ samples: this.samples.length, bias: this.bias }); }
  exportDataset() { return JSON.stringify(this.samples); } importDataset(dataset: string) { const parsed = JSON.parse(dataset) as DecisionModelSample[]; return this.train(parsed); }
  calibrate(predictions: readonly number[], realities: readonly number[]) { if (predictions.length !== realities.length) throw new Error("Calibration vectors must have equal length"); const error = predictions.length ? average(predictions.map((value, index) => realities[index] - value)) : 0; this.bias = Math.max(-.5, Math.min(.5, this.bias + error)); return immutable({ error, bias: this.bias }); }
  explain(candidate: DecisionModelCandidate) { return immutable({ model: this.modelVersion, score: this.evaluate(candidate), contributions: Object.entries(candidate.features).sort(([a], [b]) => a.localeCompare(b)).map(([feature, value]) => immutable({ feature, value, contribution: value / Math.max(1, Object.keys(candidate.features).length) })), evidence: this.samples.length }); }
  version() { return this.modelVersion; }
}
const average = (values: readonly number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;

export class DecisionProvenance { calculate(sources: Readonly<Record<string, number>>) { const entries = Object.entries(sources).filter(([, value]) => value > 0).sort(([a], [b]) => a.localeCompare(b)), total = entries.reduce((sum, [, value]) => sum + value, 0); return immutable(Object.fromEntries(entries.map(([key, value]) => [key, total ? value / total : 0]))); } }
export class CreativeDiscoveryEngine { discover(candidates: readonly DecisionModelCandidate[], limit = 5) { const keys = [...new Set(candidates.flatMap(({ features }) => Object.keys(features)))].sort(); const distance = (a: DecisionModelCandidate, b: DecisionModelCandidate) => Math.sqrt(keys.reduce((sum, key) => sum + ((a.features[key] ?? 0) - (b.features[key] ?? 0)) ** 2, 0) / Math.max(1, keys.length)); return immutable(candidates.map((candidate) => { const distances = candidates.filter(({ id }) => id !== candidate.id).map((other) => distance(candidate, other)); const novelty = distances.length ? Math.min(...distances) : 1, diversity = distances.length ? average(distances) : 1, unexpectedness = clamp(Math.abs(average(Object.values(candidate.features)) - .5) * 2); return { candidate: structuredClone(candidate), novel: novelty, diverse: diversity, unexpected: unexpectedness, creative: clamp((novelty + diversity + unexpectedness) / 3) }; }).sort((a, b) => b.creative - a.creative || a.candidate.id.localeCompare(b.candidate.id)).slice(0, limit)); } }
