import { clamp, immutable } from "./immutable";

export interface LearningEvent { readonly id: string; readonly tenantId: string; readonly projectId: string; readonly userId: string; readonly intent: string; readonly operations: readonly string[]; readonly strategy: string; readonly outcome: "ACCEPTED" | "REJECTED" | "UNDO" | "REDO" | "RETRY" | "MANUAL_CORRECTION" | "CANCEL" | "REPEATED_EDIT"; readonly quality: number; readonly cost: number; readonly latency: number; readonly satisfaction: number; readonly createdAt: number }
export interface DecisionPattern { readonly id: string; readonly sequence: readonly string[]; readonly frequency: number; readonly success: number; readonly failure: number; readonly acceptance: number; readonly undo: number; readonly averageQuality: number; readonly averageCost: number; readonly averageLatency: number; readonly strength: number; readonly lifetime: number; readonly stability: number; readonly confidence: number }
const average = (xs: readonly number[]) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0;
export class DecisionPatternDiscovery { discover(events: readonly LearningEvent[], now = 0): readonly DecisionPattern[] { const groups = new Map<string, LearningEvent[]>(); events.forEach((event) => { const sequence = [event.intent, ...event.operations, event.strategy], key = sequence.join("→"); groups.set(key, [...(groups.get(key) ?? []), event]); }); return immutable([...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([id, entries]) => { const accepted = entries.filter(({ outcome }) => outcome === "ACCEPTED").length, undo = entries.filter(({ outcome }) => outcome === "UNDO").length, ages = entries.map(({ createdAt }) => createdAt); const frequency = entries.length, success = accepted / frequency, failure = 1 - success; return { id, sequence: id.split("→"), frequency, success, failure, acceptance: success, undo: undo / frequency, averageQuality: average(entries.map(({ quality }) => quality)), averageCost: average(entries.map(({ cost }) => cost)), averageLatency: average(entries.map(({ latency }) => latency)), strength: clamp(Math.log2(frequency + 1) / 5 * success), lifetime: Math.max(0, now - Math.min(...ages)), stability: clamp(1 - Math.sqrt(average(entries.map(({ quality }) => (entries[0].quality - quality) ** 2)))), confidence: clamp(frequency / (frequency + 5) * (1 - undo / frequency)) }; })); } }

export interface DecisionArchetype { readonly id: string; readonly preferences: readonly string[]; readonly goals: readonly string[]; readonly quality: number; readonly risk: number; readonly budget: number; readonly typicalOperations: readonly string[]; readonly confidence: number; readonly members: number }
export class DecisionArchetypeEngine { create(events: readonly LearningEvent[]): readonly DecisionArchetype[] { const groups = new Map<string, LearningEvent[]>(); events.forEach((event) => groups.set(event.intent, [...(groups.get(event.intent) ?? []), event])); return immutable([...groups.entries()].sort().map(([id, values]) => ({ id, preferences: [...new Set(values.map(({ strategy }) => strategy))].sort(), goals: [id], quality: average(values.map(({ quality }) => quality)), risk: clamp(values.filter(({ outcome }) => ["REJECTED", "UNDO", "CANCEL"].includes(outcome)).length / values.length), budget: average(values.map(({ cost }) => cost)), typicalOperations: [...new Set(values.flatMap(({ operations }) => operations))].sort(), confidence: clamp(values.length / (values.length + 5)), members: values.length }))); } merge(left: DecisionArchetype, right: DecisionArchetype): DecisionArchetype { const total = left.members + right.members, weighted = (a: number, b: number) => (a * left.members + b * right.members) / total; return immutable({ id: `${left.id}+${right.id}`, preferences: [...new Set([...left.preferences, ...right.preferences])].sort(), goals: [...new Set([...left.goals, ...right.goals])].sort(), quality: weighted(left.quality, right.quality), risk: weighted(left.risk, right.risk), budget: weighted(left.budget, right.budget), typicalOperations: [...new Set([...left.typicalOperations, ...right.typicalOperations])].sort(), confidence: weighted(left.confidence, right.confidence), members: total }); } }

export interface CreativeDNA { readonly version: number; readonly parentVersion?: number; readonly style: Readonly<Record<string, number>>; readonly risk: number; readonly creativity: number; readonly aiTrust: number; readonly automation: number; readonly samples: number }
export class CreativeDNAEngine { evolve(dna: CreativeDNA, signal: { readonly style?: Readonly<Record<string, number>>; readonly risk?: number; readonly creativity?: number; readonly aiTrust?: number; readonly automation?: number }, learningRate = .05): CreativeDNA { const learn = (old: number, value?: number) => clamp(old + ((value ?? old) - old) * clamp(learningRate)); const keys = new Set([...Object.keys(dna.style), ...Object.keys(signal.style ?? {})]); return immutable({ version: dna.version + 1, parentVersion: dna.version, style: Object.fromEntries([...keys].sort().map((key) => [key, learn(dna.style[key] ?? .5, signal.style?.[key])])), risk: learn(dna.risk, signal.risk), creativity: learn(dna.creativity, signal.creativity), aiTrust: learn(dna.aiTrust, signal.aiTrust), automation: learn(dna.automation, signal.automation), samples: dna.samples + 1 }); } }

export class LongTermLearning { analyze(events: readonly LearningEvent[], now: number, halfLife = 365 * 86_400_000) { const weighted = events.map((event) => ({ event, weight: 2 ** (-(Math.max(0, now - event.createdAt) / halfLife)) })); const experience = weighted.reduce((sum, item) => sum + item.weight, 0), positive = weighted.filter(({ event }) => ["ACCEPTED", "REDO"].includes(event.outcome)).reduce((sum, item) => sum + item.weight, 0); const reliability = experience ? positive / experience : 0; return immutable({ experience, knowledge: clamp(Math.log2(experience + 1) / 10), maturity: clamp(experience / 100), reliability, expertise: clamp(Math.sqrt(experience * reliability) / 10), effectiveEvents: weighted }); } }

export interface MetaPrediction { readonly quality: number; readonly satisfaction: number; readonly utility: number; readonly confidence: number }
export class MetaLearningEngine { learn(prediction: MetaPrediction, reality: MetaPrediction, state: { readonly weights: Readonly<Record<string, number>>; readonly thresholds: Readonly<Record<string, number>>; readonly samples: number }, rate = .05) { const errors = { predictionError: average(Object.keys(prediction).map((key) => Math.abs(prediction[key as keyof MetaPrediction] - reality[key as keyof MetaPrediction]))), confidenceError: reality.confidence - prediction.confidence, utilityError: reality.utility - prediction.utility, qualityError: reality.quality - prediction.quality, satisfactionError: reality.satisfaction - prediction.satisfaction }; const adjust = (value: number, error: number) => clamp(value + rate * error); return immutable({ errors, state: { weights: { ...state.weights, quality: adjust(state.weights.quality ?? .5, errors.qualityError), utility: adjust(state.weights.utility ?? .5, errors.utilityError), satisfaction: adjust(state.weights.satisfaction ?? .5, errors.satisfactionError) }, thresholds: { ...state.thresholds, confidence: adjust(state.thresholds.confidence ?? .5, errors.confidenceError) }, samples: state.samples + 1 } }); } }
