import { AIExecutionGraph } from './AIExecutionGraph';
import { ExecutionCoordinator } from './ExecutionCoordinator';
import { AIExecutionMemory, AIOperationExecutor, ArtifactManager, ParameterResolver, PromptAssembler, ProviderRouter, ResultNormalizer } from './components';
import { assertScope, clone, deepFreeze } from './immutable';
import type { AICheckpoint, AIExecuteRequest, AIExecutionServices, AIExecutionSnapshot, AIMemoryEntry, AIOperation, AIOperationRecord, AIProgress, AIScope, AIStreamListener, AITimelineEvent } from './types';

interface State { id: string; scope: AIScope; graph: AIExecutionGraph; records: Map<string, AIOperationRecord>; timeline: AITimelineEvent[]; checkpoints: AICheckpoint[]; status: AIOperationRecord['status']; createdAt: number; updatedAt: number; controller: AbortController; listeners: Set<AIStreamListener>; budget: number; cost: number }

export class AIExecutionManager {
  private readonly states = new Map<string, State>(); private readonly artifacts: ArtifactManager; private readonly memory: AIExecutionMemory; private readonly executor: AIOperationExecutor; private readonly coordinator = new ExecutionCoordinator();
  constructor(private readonly services: AIExecutionServices) { this.artifacts = new ArtifactManager(services.dependencies); this.memory = new AIExecutionMemory(); const router = new ProviderRouter(services.runtime, services.intelligence); this.executor = new AIOperationExecutor(services.runtime, router, new PromptAssembler(), new ParameterResolver(), new ResultNormalizer(), this.artifacts); }
  async execute(request: AIExecuteRequest): Promise<AIExecutionSnapshot> { assertScope(request.scope); const id = request.id ?? this.services.dependencies.id(); if (this.states.has(id)) throw new Error(`Execution "${id}" already exists.`); const graph = new AIExecutionGraph(request.operations); const now = this.services.dependencies.now(); const state: State = { id, scope: deepFreeze({ ...request.scope }), graph, records: new Map(request.operations.map((operation) => [operation.id, deepFreeze({ operation, status: 'queued' as const, attempts: 0, explanation: [] })])), timeline: [], checkpoints: [], status: 'queued', createdAt: now, updatedAt: now, controller: new AbortController(), listeners: new Set(), budget: request.budget ?? Infinity, cost: 0 }; this.states.set(id, state); this.emit(state, 'execution.queued', undefined, 'queued'); await this.run(state, request.concurrency ?? 1, request.timeout); return this.snapshot(id, request.scope); }
  async executeOperation(scope: AIScope, operation: AIOperation, options: Omit<AIExecuteRequest, 'scope' | 'operations'> = {}): Promise<AIExecutionSnapshot> { return this.execute({ ...options, scope, operations: [operation] }); }
  async executeGraph(request: AIExecuteRequest | (Omit<AIExecuteRequest, 'operations'> & { graph: AIExecutionGraph })): Promise<AIExecutionSnapshot> { return this.execute('graph' in request ? { ...request, operations: request.graph.snapshot.operations } : request); }
  async executeBatch(requests: readonly AIExecuteRequest[], concurrency = 1): Promise<readonly AIExecutionSnapshot[]> { return this.coordinator.run(requests.map((request) => () => this.execute(request)), { concurrency }); }
  async resume(id: string, scope: AIScope): Promise<AIExecutionSnapshot> { const state = this.require(id, scope); if (!['failed', 'cancelled'].includes(state.status)) return this.snapshot(id, scope); state.controller = new AbortController(); state.records.forEach((record, key) => { if (['failed', 'cancelled'].includes(record.status)) state.records.set(key, deepFreeze({ ...record, status: 'queued', error: undefined })); }); await this.run(state, 1); return this.snapshot(id, scope); }
  cancel(id: string, scope: AIScope): AIExecutionSnapshot { const state = this.require(id, scope); state.controller.abort(); state.status = 'cancelled'; state.records.forEach((record, key) => { if (record.status === 'queued' || record.status === 'running') state.records.set(key, deepFreeze({ ...record, status: 'cancelled' })); }); this.emit(state, 'execution.cancelled', undefined, 'cancelled'); return this.snapshot(id, scope); }
  status(id: string, scope: AIScope): Readonly<{ status: State['status']; progress: AIProgress }> { const state = this.require(id, scope); return deepFreeze({ status: state.status, progress: this.progress(state) }); }
  snapshot(id: string, scope: AIScope): AIExecutionSnapshot { const state = this.require(id, scope); const records = [...state.records.values()]; const artifacts = this.artifacts.list(scope).filter((item) => records.some((record) => record.operation.id === item.operationId)); return deepFreeze({ id, scope: { ...scope }, status: state.status, graph: state.graph.snapshot, operations: records, providers: records.flatMap((item) => item.provider ? [item.provider] : []), artifacts, metrics: { cost: state.cost, latency: records.reduce((sum, item) => sum + (item.result?.latency ?? 0), 0), operations: records.length, completed: records.filter((item) => item.status === 'completed').length }, progress: this.progress(state), retries: state.timeline.filter((event) => event.type.startsWith('retry')), timeline: [...state.timeline], checkpoints: [...state.checkpoints], memory: this.memory.list(scope, id), createdAt: state.createdAt, updatedAt: state.updatedAt }); }
  replay(snapshot: AIExecutionSnapshot, listener?: AIStreamListener): AIExecutionSnapshot { const copy = deepFreeze(clone(snapshot)); copy.timeline.forEach((event) => listener?.(event)); return copy; }
  debug(id: string, scope: AIScope): Readonly<Record<string, unknown>> { const snapshot = this.snapshot(id, scope); return deepFreeze({ executionId: id, graphOrder: snapshot.graph.order, ready: snapshot.operations.filter((item) => item.status === 'queued' && (item.operation.dependencies ?? []).every((dep) => snapshot.operations.find((candidate) => candidate.operation.id === dep)?.status === 'completed')).map((item) => item.operation.id), explanations: Object.fromEntries(snapshot.operations.map((item) => [item.operation.id, item.explanation])), snapshot }); }
  subscribe(id: string, scope: AIScope, listener: AIStreamListener): () => void { const state = this.require(id, scope); state.listeners.add(listener); return () => state.listeners.delete(listener); }
  rollback(id: string, scope: AIScope, checkpointId: string): AIExecutionSnapshot { const state = this.require(id, scope); const checkpoint = state.checkpoints.find((item) => item.id === checkpointId); if (!checkpoint) throw new Error(`Checkpoint "${checkpointId}" not found.`); const keep = new Set(checkpoint.artifactIds); this.artifacts.remove(this.artifacts.list(scope).filter((item) => !keep.has(item.id) && state.records.has(item.operationId)).map((item) => item.id), scope); state.records.forEach((record, operationId) => state.records.set(operationId, deepFreeze({ ...record, status: checkpoint.statuses[operationId] ?? 'rolled-back' }))); state.status = 'rolled-back'; this.emit(state, 'execution.rollback', checkpoint.operationId, 'rolled-back', { checkpointId }); return this.snapshot(id, scope); }
  private async run(state: State, concurrency: number, timeout?: number): Promise<void> { state.status = 'running'; this.emit(state, 'execution.running', undefined, 'running'); const completed = new Set([...state.records.values()].filter((record) => record.status === 'completed').map((record) => record.operation.id)); try { for (const group of state.graph.snapshot.groups) { const ids = group.filter((id) => !completed.has(id)); await this.coordinator.run(ids.map((id) => () => this.runOperation(state, id)), { concurrency, timeout }); ids.forEach((id) => { if (state.records.get(id)?.status === 'completed') completed.add(id); }); if (state.controller.signal.aborted) break; } if (!state.controller.signal.aborted) { state.status = completed.size === state.records.size ? 'completed' : 'failed'; this.emit(state, `execution.${state.status}`, undefined, state.status); } } catch (error) { state.status = state.controller.signal.aborted ? 'cancelled' : 'failed'; this.emit(state, `execution.${state.status}`, undefined, state.status, { error: message(error) }); } }
  private async runOperation(state: State, id: string): Promise<void> { const original = state.records.get(id)!; let excluded: string[] = []; const max = original.operation.retries ?? 0; for (let attempt = 0; attempt <= max; attempt++) { if (state.controller.signal.aborted) return; state.records.set(id, deepFreeze({ ...state.records.get(id)!, status: 'running', attempts: attempt + 1, startedAt: this.services.dependencies.now() })); this.emit(state, 'operation.running', id, 'running', { attempt: attempt + 1 }); try { const executed = await this.executor.execute(original.operation, state.scope, state.controller.signal, excluded); if (state.cost + executed.result.cost > state.budget || (original.operation.budget !== undefined && executed.result.cost > original.operation.budget)) throw new Error('AI execution budget exceeded.'); state.cost += executed.result.cost; const checkpointId = original.operation.checkpoint === false ? undefined : this.services.dependencies.uuid(); const explanation = [`Provider: ${executed.decision.reason}`, executed.prompt.explanation, `Parameters resolved for ${executed.decision.providerId}.`, `Cost reported by provider runtime: ${executed.result.cost}.`]; const completedAt = this.services.dependencies.now(); state.records.set(id, deepFreeze({ operation: original.operation, status: 'completed', attempts: attempt + 1, provider: executed.decision, prompt: executed.prompt, parameters: executed.parameters, result: executed.result, checkpointId, startedAt: state.records.get(id)?.startedAt, completedAt, explanation })); if (checkpointId) state.checkpoints.push(deepFreeze({ id: checkpointId, operationId: id, artifactIds: this.artifacts.list(state.scope).filter((item) => state.records.has(item.operationId)).map((item) => item.id), statuses: Object.fromEntries([...state.records].map(([key, record]) => [key, record.status])), createdAt: completedAt })); this.recordMemory(state, id, true); this.emit(state, 'operation.completed', id, 'completed', { providerId: executed.decision.providerId, artifactIds: executed.result.artifacts.map((item) => item.id) }); return; } catch (error) { const provider = state.records.get(id)?.provider?.providerId; if (provider) excluded.push(provider); if (attempt < max) { this.emit(state, 'retry.fallback', id, 'queued', { attempt: attempt + 1, reason: message(error) }); await this.services.dependencies.sleep(0); continue; } state.records.set(id, deepFreeze({ ...state.records.get(id)!, status: state.controller.signal.aborted ? 'cancelled' : 'failed', error: message(error), completedAt: this.services.dependencies.now(), explanation: [...state.records.get(id)!.explanation, `Retry aborted: ${message(error)}`] })); this.recordMemory(state, id, false); this.emit(state, 'operation.failed', id, 'failed', { error: message(error) }); throw error; } } }
  private recordMemory(state: State, id: string, success: boolean): void { const record = state.records.get(id)!; const entry: AIMemoryEntry = { scope: state.scope, executionId: state.id, operationId: id, success, error: record.error, retries: Math.max(0, record.attempts - 1), latency: record.result?.latency ?? 0, cost: record.result?.cost ?? 0, quality: record.result?.quality, provider: record.provider?.providerId, artifactIds: record.result?.artifacts.map((item) => item.id) ?? [], at: this.services.dependencies.now() }; this.memory.record(entry); }
  private progress(state: State): AIProgress { const records = [...state.records.values()]; const values = Object.fromEntries(records.map((record) => [record.operation.id, record.status === 'completed' ? 1 : record.status === 'running' || record.status === 'partial' ? .5 : 0])); const overall = records.length ? Object.values(values).reduce((a, b) => a + b, 0) / records.length : 1; return deepFreeze({ overall, provider: Object.fromEntries(records.filter((item) => item.provider).map((item) => [item.provider!.providerId, values[item.operation.id]])), operation: values, graph: overall, pipeline: overall, artifacts: records.length ? this.artifacts.list(state.scope).filter((item) => state.records.has(item.operationId)).length / records.length : 1 }); }
  private emit(state: State, type: string, operationId?: string, status?: AITimelineEvent['status'], data: Record<string, unknown> = {}): void { const event = deepFreeze({ id: this.services.dependencies.uuid(), at: this.services.dependencies.now(), executionId: state.id, operationId, type, status, data }); state.timeline.push(event); state.updatedAt = event.at; state.listeners.forEach((listener) => listener(event)); }
  private require(id: string, scope: AIScope): State { assertScope(scope); const state = this.states.get(id); if (!state || state.scope.tenantId !== scope.tenantId || state.scope.projectId !== scope.projectId || state.scope.userId !== scope.userId) throw new Error(`Execution "${id}" not found in scope.`); return state; }
}
function message(error: unknown): string { return error instanceof Error ? error.message : String(error); }
