import { deepFreeze } from './immutable';
import type { AIArtifact, AIDependencies, AIMemoryEntry, AIOperation, AIScope, AssembledPrompt, CreativeProviderResult, PromptSources, ProviderDecision, ProviderIntelligence } from './types';
import type { ProviderRuntimeRegistry } from '../../providers/runtime/ProviderRuntimeRegistry';

export class PromptAssembler {
  assemble(sources: PromptSources = {}): AssembledPrompt { const positive = ['director', 'knowledge', 'planning', 'execution', 'pipeline', 'provider'].flatMap((key) => values(sources[key as keyof PromptSources])); const negative = values(sources.negative); return deepFreeze({ prompt: unique(positive).join(', '), negativePrompt: unique(negative).join(', '), parts: unique(positive), explanation: `Prompt assembled from ${positive.length} ordered creative constraints.` }); }
}
function values(value: unknown): string[] { if (value == null) return []; if (Array.isArray(value)) return value.flatMap(values); if (typeof value === 'object') return Object.keys(value as object).sort().flatMap((key) => values((value as Record<string, unknown>)[key])); return String(value).trim() ? [String(value).trim()] : []; }
function unique(items: readonly string[]): string[] { return [...new Set(items)]; }

export class ParameterResolver {
  resolve(providerId: string, operation: AIOperation, prompt: AssembledPrompt): Readonly<Record<string, unknown>> { const base: Record<string, unknown> = { prompt: prompt.prompt, ...operation.parameters }; if (prompt.negativePrompt) base.negative_prompt = prompt.negativePrompt; if (base.seed === undefined) delete base.seed; return deepFreeze({ ...base, provider: providerId }); }
}
export class ProviderRouter {
  constructor(private readonly runtime: ProviderRuntimeRegistry, private readonly intelligence?: ProviderIntelligence) {}
  route(operation: AIOperation, scope: AIScope, excluded: readonly string[] = []): ProviderDecision { const available = (operation.providers?.length ? operation.providers.map((id) => this.runtime.get(id)).filter(Boolean) : this.runtime.getByCapability(operation.capability)).filter((item) => item!.capabilities.includes(operation.capability) && !excluded.includes(item!.id)).map((item) => item!.id); if (!available.length) throw new Error(`No provider supports capability "${operation.capability}".`); const selected = this.intelligence?.select?.({ capability: operation.capability, scope, candidates: available, operation }); if (typeof selected === 'object') return deepFreeze(selected); let ranked = this.intelligence?.rank?.({ capability: operation.capability, scope, candidates: available, operation }) ?? available; const normalized = ranked.map((item) => typeof item === 'string' ? { id: item, score: available.length - ranked.indexOf(item) } : item).filter((item) => available.includes(item.id)); const providerId = typeof selected === 'string' && available.includes(selected) ? selected : normalized[0]?.id ?? available[0]; return deepFreeze({ providerId, alternatives: normalized.map((item) => item.id).filter((id) => id !== providerId), reason: normalized.find((item) => item.id === providerId)?.reason ?? `Selected for capability ${operation.capability}.`, scores: Object.fromEntries(normalized.map((item) => [item.id, item.score ?? 0])) }); }
}
export class ResultNormalizer {
  normalize(providerId: string, operationId: string, response: { output: unknown; cost?: number; duration?: number; usage?: Readonly<{ tokens?: number; images?: number }>; metadata?: Readonly<Record<string, unknown>>; retryCount?: number }): Omit<CreativeProviderResult, 'artifacts'> { const output = response.output as Record<string, unknown> | undefined; const quality = typeof output?.quality === 'number' ? output.quality : typeof response.metadata?.quality === 'number' ? response.metadata.quality : undefined; return deepFreeze({ providerId, operationId, cost: response.cost ?? 0, latency: response.duration ?? 0, quality, usage: response.usage ?? {}, metadata: { ...(response.metadata ?? {}), retryCount: response.retryCount ?? 0 }, raw: response.output }); }
}
export class ArtifactManager {
  private readonly artifacts = new Map<string, AIArtifact>();
  constructor(private readonly deps: AIDependencies) {}
  create(scope: AIScope, operationId: string, value: unknown, options: Partial<Pick<AIArtifact, 'kind' | 'mime' | 'size' | 'parentIds' | 'metadata'>> = {}): AIArtifact { const serialized = stable(value); const artifact = deepFreeze({ id: this.deps.uuid(), scope: { ...scope }, operationId, kind: options.kind ?? 'output', value, mime: options.mime ?? inferMime(value), size: options.size ?? serialized.length, hash: this.deps.hash(serialized), parentIds: [...(options.parentIds ?? [])], metadata: { ...(options.metadata ?? {}) }, createdAt: this.deps.now() }); this.artifacts.set(artifact.id, artifact); return artifact; }
  get(id: string, scope: AIScope): AIArtifact | undefined { const item = this.artifacts.get(id); return item && sameScope(item.scope, scope) ? item : undefined; }
  list(scope: AIScope): readonly AIArtifact[] { return deepFreeze([...this.artifacts.values()].filter((item) => sameScope(item.scope, scope))); }
  remove(ids: readonly string[], scope: AIScope): void { ids.forEach((id) => { if (this.get(id, scope)) this.artifacts.delete(id); }); }
}
export class AIExecutionMemory { private entries: AIMemoryEntry[] = []; record(entry: AIMemoryEntry): AIMemoryEntry { const immutable = deepFreeze({ ...entry }); this.entries.push(immutable); return immutable; } list(scope: AIScope, executionId?: string): readonly AIMemoryEntry[] { return deepFreeze(this.entries.filter((item) => sameScope(item.scope, scope) && (!executionId || item.executionId === executionId))); } }
export class AIOperationExecutor {
  constructor(private readonly runtime: ProviderRuntimeRegistry, private readonly router: ProviderRouter, private readonly prompts: PromptAssembler, private readonly parameters: ParameterResolver, private readonly normalizer: ResultNormalizer, private readonly artifacts: ArtifactManager) {}
  async execute(operation: AIOperation, scope: AIScope, signal?: AbortSignal, excluded: readonly string[] = []): Promise<{ decision: ProviderDecision; prompt: AssembledPrompt; parameters: Readonly<Record<string, unknown>>; result: CreativeProviderResult }> { const decision = this.router.route(operation, scope, excluded); const prompt = this.prompts.assemble(operation.prompt); const parameters = this.parameters.resolve(decision.providerId, operation, prompt); const response = await this.runtime.require(decision.providerId).executor.execute({ capability: operation.capability, input: { source: operation.input, ...parameters }, context: { ...scope, operationId: operation.id }, timeout: operation.timeout ?? 60_000, retryPolicy: { maxRetries: 0, backoffMs: 0, retryTimeouts: false }, signal }); const normalized = this.normalizer.normalize(decision.providerId, operation.id, response); const outputs = Array.isArray(response.output) ? response.output : [response.output]; const result = deepFreeze({ ...normalized, artifacts: outputs.map((output) => this.artifacts.create(scope, operation.id, output, { kind: 'output' })) }); return { decision, prompt, parameters, result }; }
}
function stable(value: unknown): string { if (value === undefined) return 'undefined'; if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(stable).join(',')}]`; return `{${Object.keys(value as object).sort().map((key) => `${JSON.stringify(key)}:${stable((value as Record<string, unknown>)[key])}`).join(',')}}`; }
function inferMime(value: unknown): string { return typeof value === 'string' && value.startsWith('data:image/') ? value.slice(5, value.indexOf(';')) : 'application/octet-stream'; }
function sameScope(a: AIScope, b: AIScope): boolean { return a.tenantId === b.tenantId && a.projectId === b.projectId && a.userId === b.userId; }
