import type { ProviderRuntimeRegistry } from '../../providers/runtime/ProviderRuntimeRegistry';

export interface AIScope { readonly tenantId: string; readonly projectId: string; readonly userId: string }
export type AIOperationStatus = 'queued' | 'running' | 'partial' | 'completed' | 'failed' | 'cancelled' | 'rolled-back';
export interface AIDependencies { readonly id: () => string; readonly now: () => number; readonly random: () => number; readonly sleep: (ms: number) => Promise<void>; readonly hash: (value: string) => string; readonly uuid: () => string }
export interface AIOperation { readonly id: string; readonly capability: string; readonly input?: unknown; readonly dependencies?: readonly string[]; readonly parallelGroup?: string; readonly barrier?: boolean; readonly checkpoint?: boolean; readonly prompt?: PromptSources; readonly parameters?: Readonly<Record<string, unknown>>; readonly providers?: readonly string[]; readonly timeout?: number; readonly retries?: number; readonly budget?: number; readonly metadata?: Readonly<Record<string, unknown>> }
export interface PromptSources { readonly director?: unknown; readonly knowledge?: unknown; readonly planning?: unknown; readonly execution?: unknown; readonly pipeline?: unknown; readonly provider?: unknown; readonly negative?: unknown }
export interface AssembledPrompt { readonly prompt: string; readonly negativePrompt: string; readonly parts: readonly string[]; readonly explanation: string }
export interface ProviderDecision { readonly providerId: string; readonly alternatives: readonly string[]; readonly reason: string; readonly scores: Readonly<Record<string, number>> }
export interface CreativeProviderResult { readonly providerId: string; readonly operationId: string; readonly artifacts: readonly AIArtifact[]; readonly cost: number; readonly latency: number; readonly quality?: number; readonly usage: Readonly<Record<string, number>>; readonly metadata: Readonly<Record<string, unknown>>; readonly raw?: unknown }
export interface AIArtifact { readonly id: string; readonly scope: AIScope; readonly operationId: string; readonly kind: 'input' | 'intermediate' | 'output'; readonly value: unknown; readonly mime: string; readonly size: number; readonly hash: string; readonly parentIds: readonly string[]; readonly metadata: Readonly<Record<string, unknown>>; readonly createdAt: number }
export interface AIProgress { readonly overall: number; readonly provider: Readonly<Record<string, number>>; readonly operation: Readonly<Record<string, number>>; readonly graph: number; readonly pipeline: number; readonly artifacts: number }
export interface AITimelineEvent { readonly id: string; readonly at: number; readonly executionId: string; readonly operationId?: string; readonly type: string; readonly status?: AIOperationStatus; readonly data: Readonly<Record<string, unknown>> }
export interface AIOperationRecord { readonly operation: AIOperation; readonly status: AIOperationStatus; readonly attempts: number; readonly provider?: ProviderDecision; readonly prompt?: AssembledPrompt; readonly parameters?: Readonly<Record<string, unknown>>; readonly result?: CreativeProviderResult; readonly error?: string; readonly checkpointId?: string; readonly startedAt?: number; readonly completedAt?: number; readonly explanation: readonly string[] }
export interface AICheckpoint { readonly id: string; readonly operationId: string; readonly artifactIds: readonly string[]; readonly statuses: Readonly<Record<string, AIOperationStatus>>; readonly createdAt: number }
export interface AIExecutionSnapshot { readonly id: string; readonly scope: AIScope; readonly status: AIOperationStatus; readonly graph: AIGraphSnapshot; readonly operations: readonly AIOperationRecord[]; readonly providers: readonly ProviderDecision[]; readonly artifacts: readonly AIArtifact[]; readonly metrics: Readonly<Record<string, number>>; readonly progress: AIProgress; readonly retries: readonly AITimelineEvent[]; readonly timeline: readonly AITimelineEvent[]; readonly checkpoints: readonly AICheckpoint[]; readonly memory: readonly AIMemoryEntry[]; readonly createdAt: number; readonly updatedAt: number }
export interface AIGraphSnapshot { readonly operations: readonly AIOperation[]; readonly order: readonly string[]; readonly groups: readonly (readonly string[])[] }
export interface AIMemoryEntry { readonly scope: AIScope; readonly executionId: string; readonly operationId: string; readonly success: boolean; readonly error?: string; readonly retries: number; readonly latency: number; readonly cost: number; readonly quality?: number; readonly provider?: string; readonly artifactIds: readonly string[]; readonly at: number }
export interface AIExecuteRequest { readonly scope: AIScope; readonly operations: readonly AIOperation[]; readonly id?: string; readonly budget?: number; readonly timeout?: number; readonly concurrency?: number }
export interface ProviderIntelligence { rank?(request: Readonly<{ capability: string; scope: AIScope; candidates: readonly string[]; operation: AIOperation }>): readonly (string | Readonly<{ id: string; score?: number; reason?: string }>)[]; select?(request: Readonly<{ capability: string; scope: AIScope; candidates: readonly string[]; operation: AIOperation }>): string | ProviderDecision }
export interface AIExecutionServices { readonly dependencies: AIDependencies; readonly runtime: ProviderRuntimeRegistry; readonly intelligence?: ProviderIntelligence }
export type AIStreamListener = (event: AITimelineEvent) => void;
