import type { ProductionTelemetryEvent } from '../production';
import type { Anomaly, EconomicsSummary, GoldenBenchmark, ObservabilityDependencies, ObservabilityEventKind, ObservabilityOutcome, ObservabilityScope, ObservabilitySnapshot, PerformanceRow, TelemetryInput, UnifiedTelemetryEvent, WasteFinding } from './types';

const freeze = <T>(value: T): Readonly<T> => { if (value && typeof value === 'object' && !Object.isFrozen(value) && !ArrayBuffer.isView(value)) { Object.freeze(value); for (const child of Object.values(value as object)) freeze(child); } return value as Readonly<T>; };
const immutable = <T>(value: T): Readonly<T> => freeze(structuredClone(value));
const safeNumber = (value: number | undefined) => Number.isFinite(value) ? Math.max(0, value!) : 0;
const clamp = (value: number | undefined) => Math.max(0, Math.min(1, Number.isFinite(value) ? value! : 0));
const scopeKey = (scope: ObservabilityScope) => { if (!scope?.tenantId || !scope.projectId) throw new Error('tenantId and projectId are required'); return `${scope.tenantId}\0${scope.projectId}${scope.userId ? `\0${scope.userId}` : ''}`; };
const inScope = (event: UnifiedTelemetryEvent, scope: ObservabilityScope) => event.scope.tenantId === scope.tenantId && event.scope.projectId === scope.projectId && (!scope.userId || event.scope.userId === scope.userId);
const sanitize = (value: unknown): unknown => { if (Array.isArray(value)) return value.map(sanitize); if (value && typeof value === 'object' && !ArrayBuffer.isView(value)) return Object.fromEntries(Object.entries(value).filter(([key]) => !/(secret|token|key|authorization|cookie|credential|bytes|image|prompt|payload|raw)/i.test(key)).map(([key, child]) => [key, sanitize(child)])); return value; };

export class TelemetryNormalizer {
  normalize(input: TelemetryInput): UnifiedTelemetryEvent {
    scopeKey(input.scope); if (!input.id || !input.requestId || !input.executionId || !input.operationId) throw new Error('Complete telemetry correlation is required');
    return immutable({ id: input.id, timestamp: input.timestamp, kind: input.kind, requestId: input.requestId, executionId: input.executionId, nodeId: input.nodeId ?? input.operationId, operationId: input.operationId, target: input.target, ...(input.model ? { model: input.model } : {}), ...(input.provider ? { provider: input.provider } : {}), durationMs: safeNumber(input.durationMs), outcome: input.outcome, actualCost: safeNumber(input.actualCost), estimatedCloudCost: safeNumber(input.estimatedCloudCost), localDeviceCost: safeNumber(input.localDeviceCost), credits: safeNumber(input.credits), creditsSaved: safeNumber(input.creditsSaved), energyWh: safeNumber(input.energyWh), quality: clamp(input.quality), baselineQuality: clamp(input.baselineQuality), scope: input.scope, deviceClass: input.deviceClass ?? 'UNKNOWN', platform: input.platform ?? 'UNKNOWN', policy: input.policy ?? 'UNKNOWN', ...(input.reason ? { reason: input.reason } : {}), retryCount: Math.floor(safeNumber(input.retryCount)), attempt: Math.max(1, Math.floor(safeNumber(input.attempt) || 1)), coldStart: input.coldStart ?? false, ramMb: safeNumber(input.ramMb), vramMb: safeNumber(input.vramMb), ...(input.userAccepted === undefined ? {} : { userAccepted: input.userAccepted }), ...(input.undone === undefined ? {} : { undone: input.undone }), ...(input.corrected === undefined ? {} : { corrected: input.corrected }), ...(input.recovered === undefined ? {} : { recovered: input.recovered }), metadata: sanitize(input.metadata ?? {}) }) as UnifiedTelemetryEvent;
  }
}

export class ProductionTelemetryAdapter {
  normalize(event: ProductionTelemetryEvent, context: Readonly<{ scope: ObservabilityScope; operationId: string; target: TelemetryInput['target']; model?: string; provider?: string; deviceClass?: string; platform?: string; policy?: string }>): UnifiedTelemetryEvent {
    const kind = productionKind(event.type), outcome = productionOutcome(event.type); const data = event.data as Readonly<Record<string, unknown>>;
    return new TelemetryNormalizer().normalize({ id: event.id, timestamp: event.timestamp, kind, requestId: event.correlation.requestId, executionId: event.correlation.executionId, nodeId: event.correlation.nodeId, operationId: context.operationId, target: context.target, model: context.model, provider: context.provider, durationMs: numeric(data.latencyMs), outcome, actualCost: numeric(data.cost), credits: numeric(data.credits), quality: numeric(data.quality), scope: context.scope, deviceClass: context.deviceClass, platform: context.platform, policy: context.policy, retryCount: numeric(data.retryCount), recovered: event.type === 'ExecutionRecovered', metadata: data });
  }
}

export class CreativeObservability {
  #events = new Map<string, UnifiedTelemetryEvent>(); readonly #now: () => number; readonly #id: () => string;
  constructor(dependencies: ObservabilityDependencies = {}) { this.#now = dependencies.now ?? (() => Date.now()); this.#id = dependencies.id ?? (() => crypto.randomUUID()); }
  ingest(input: TelemetryInput | readonly TelemetryInput[]) { const values = Array.isArray(input) ? input : [input]; for (const raw of values) { const event = new TelemetryNormalizer().normalize(raw); const existing = this.#events.get(event.id); if (existing && JSON.stringify(existing) !== JSON.stringify(event)) throw new Error(`Telemetry event conflict: ${event.id}`); this.#events.set(event.id, event); } return immutable({ accepted: values.length, total: this.#events.size }); }
  query(scope: ObservabilityScope, filter: Readonly<{ from?: number; to?: number; kind?: ObservabilityEventKind; operationId?: string; target?: string; provider?: string; model?: string }> = {}) { scopeKey(scope); return immutable([...this.#events.values()].filter(event => inScope(event, scope) && (filter.from === undefined || event.timestamp >= filter.from) && (filter.to === undefined || event.timestamp <= filter.to) && (!filter.kind || event.kind === filter.kind) && (!filter.operationId || event.operationId === filter.operationId) && (!filter.target || event.target === filter.target) && (!filter.provider || event.provider === filter.provider) && (!filter.model || event.model === filter.model)).sort((a, b) => a.timestamp - b.timestamp || a.id.localeCompare(b.id))); }
  aggregate(scope: ObservabilityScope, by: 'operation' | 'deviceClass' | 'model' | 'platform' | 'project' | 'tenant' | 'time' | 'provider' | 'policy'): readonly PerformanceRow[] { const events = this.query(scope); const key = (event: UnifiedTelemetryEvent) => ({ operation: event.operationId, deviceClass: event.deviceClass, model: event.model ?? 'UNKNOWN', platform: event.platform, project: event.scope.projectId, tenant: event.scope.tenantId, time: new Date(event.timestamp).toISOString().slice(0, 10), provider: event.provider ?? 'LOCAL', policy: event.policy })[by]; return this.rows(events, key); }
  compare(scope: ObservabilityScope, dimension: 'model' | 'provider' | 'policy', left: string, right: string) { const rows = this.aggregate(scope, dimension); const a = rows.find(row => row.key === left) ?? emptyRow(left), b = rows.find(row => row.key === right) ?? emptyRow(right); return immutable({ left: a, right: b, winner: { quality: a.averageQuality === b.averageQuality ? 'TIE' : a.averageQuality > b.averageQuality ? left : right, cost: a.averageCost === b.averageCost ? 'TIE' : a.averageCost < b.averageCost ? left : right, latency: a.averageLatency === b.averageLatency ? 'TIE' : a.averageLatency < b.averageLatency ? left : right, energy: a.energyWh === b.energyWh ? 'TIE' : a.energyWh < b.energyWh ? left : right } }); }
  experiment(scope: ObservabilityScope, policyA: string, policyB: string) { const comparison = this.compare(scope, 'policy', policyA, policyB); return immutable({ policyA: comparison.left, policyB: comparison.right, winner: comparison.winner, observationalOnly: true, productionBehaviorChanged: false }); }
  economics(scope: ObservabilityScope): EconomicsSummary { const events = this.query(scope), terminal = terminalEvents(events), successful = terminal.filter(success), accepted = terminal.filter(event => event.outcome === 'ACCEPTED' || event.userAccepted === true), localCandidates = terminal.filter(event => event.target === 'LOCAL' || event.target === 'CLOUD'), local = localCandidates.filter(event => event.target === 'LOCAL' && success(event)), cost = sum(events, event => event.actualCost), cloud = sum(events.filter(event => event.target === 'CLOUD'), event => event.actualCost), estimated = sum(events.filter(event => event.target === 'CLOUD'), event => event.estimatedCloudCost), localCost = sum(events.filter(event => event.target === 'LOCAL'), event => event.localDeviceCost), saved = sum(events, event => event.creditsSaved), qualityGain = sum(terminal, event => Math.max(0, event.quality - event.baselineQuality)), seconds = sum(terminal, event => event.durationMs) / 1000, resource = sum(events.filter(event => event.target === 'LOCAL'), event => event.energyWh + event.ramMb / 1024 + event.vramMb / 1024); return immutable({ actualCloudCost: cloud, estimatedCloudCost: estimated, localDeviceCost: localCost, totalCost: cost + localCost, costPerSuccessfulResult: (cost + localCost) / Math.max(1, successful.length), costPerAcceptedResult: (cost + localCost) / Math.max(1, accepted.length), creditsSaved: saved, cloudAvoidanceRate: local.length / Math.max(1, localCandidates.length), qualityGainPerCredit: qualityGain / Math.max(.000001, sum(events, event => event.credits)), qualityGainPerSecond: qualityGain / Math.max(.001, seconds), qualityGainPerLocalResource: qualityGain / Math.max(.001, resource) }) as EconomicsSummary; }
  health(scope: ObservabilityScope) { const economics = this.economics(scope), reliability = this.reliability(scope), quality = this.quality(scope), privacy = this.privacy(scope), providers = this.provider(scope); const component = (value: number) => value >= .9 ? 'HEALTHY' : value >= .7 ? 'DEGRADED' : 'UNHEALTHY'; return immutable({ system: component((reliability.successRate + quality.acceptanceRate) / 2), provider: component(1 - average(providers, row => 1 - row.successRate)), localAI: component(this.local(scope).successRate), workflow: component(reliability.successRate), cost: economics.costPerAcceptedResult <= economics.estimatedCloudCost || economics.estimatedCloudCost === 0 ? 'HEALTHY' : 'DEGRADED', privacy: privacy.blockedOutboundAttempts >= 0 ? 'HEALTHY' : 'UNHEALTHY', quality: component(quality.acceptanceRate), checkedAt: this.#now() }); }
  quality(scope: ObservabilityScope) { const terminal = terminalEvents(this.query(scope)), accepted = terminal.filter(event => event.userAccepted || event.outcome === 'ACCEPTED'); return immutable({ technicalQuality: average(terminal, event => event.quality), creativeQuality: average(terminal.filter(event => event.kind === 'VERIFICATION'), event => event.quality), goalCompletion: average(terminal, event => Number(event.metadata.goalCompletion ?? event.quality)), acceptanceRate: accepted.length / Math.max(1, terminal.length), undoRate: terminal.filter(event => event.undone).length / Math.max(1, terminal.length), correctionRate: terminal.filter(event => event.corrected).length / Math.max(1, terminal.length) }); }
  privacy(scope: ObservabilityScope) { const events = this.query(scope); return immutable({ localOnlyOperations: events.filter(event => event.policy === 'LOCAL_ONLY' && event.target === 'LOCAL').length, cloudOperations: events.filter(event => event.target === 'CLOUD' && event.kind === 'PROVIDER_EXECUTION').length, blockedOutboundAttempts: events.filter(event => event.outcome === 'BLOCKED' && event.reason === 'PRIVACY').length, normalMode: events.filter(event => event.policy === 'NORMAL').length, privacyFirstMode: events.filter(event => event.policy === 'PRIVACY_FIRST').length, localOnlyMode: events.filter(event => event.policy === 'LOCAL_ONLY').length, offlineOnlyMode: events.filter(event => event.policy === 'OFFLINE_ONLY').length }); }
  provider(scope: ObservabilityScope) { return this.rows(this.query(scope).filter(event => event.target === 'CLOUD'), event => event.provider ?? 'UNKNOWN'); }
  local(scope: ObservabilityScope) { const events = this.query(scope).filter(event => event.target === 'LOCAL'), rows = this.rows(events, event => event.model ?? 'UNKNOWN'), terminal = terminalEvents(events); return immutable({ successRate: terminal.filter(success).length / Math.max(1, terminal.length), coldLatency: average(events.filter(event => event.coldStart), event => event.durationMs), warmLatency: average(events.filter(event => !event.coldStart), event => event.durationMs), averageRamMb: average(events, event => event.ramMb), averageVramMb: average(events, event => event.vramMb), energyWh: sum(events, event => event.energyWh), fallbackRate: events.filter(event => event.kind === 'FALLBACK').length / Math.max(1, terminal.length), models: rows }); }
  hybrid(scope: ObservabilityScope) { const events = this.query(scope), escalations = events.filter(event => event.kind === 'ESCALATION' || event.kind === 'FALLBACK'); return immutable({ localToCloud: escalations.filter(event => event.target === 'CLOUD').length, cloudToLocal: escalations.filter(event => event.target === 'LOCAL').length, byReason: Object.fromEntries(['QUALITY', 'LATENCY', 'FAILURE', 'RESOURCE', 'PRIVACY', 'AVAILABILITY', 'UNKNOWN'].map(reason => [reason, escalations.filter(event => event.reason === reason).length])), escalationRate: escalations.filter(event => event.kind === 'ESCALATION').length / Math.max(1, terminalEvents(events).length) }); }
  reliability(scope: ObservabilityScope) { const events = this.query(scope), terminal = terminalEvents(events), executions = new Set(events.map(event => event.executionId)); return immutable({ successRate: terminal.filter(success).length / Math.max(1, terminal.length), unknownResultRate: terminal.filter(event => event.outcome === 'UNKNOWN').length / Math.max(1, terminal.length), recoveryRate: events.filter(event => event.kind === 'RECOVERY' && event.recovered).length / Math.max(1, executions.size), meanAttempts: average(terminal, event => event.attempt), fallbackSuccess: events.filter(event => event.kind === 'FALLBACK' && success(event)).length / Math.max(1, events.filter(event => event.kind === 'FALLBACK').length), crashRecoverySuccess: events.filter(event => event.kind === 'RECOVERY' && event.recovered).length / Math.max(1, events.filter(event => event.kind === 'RECOVERY').length) }); }
  waste(scope: ObservabilityScope): readonly WasteFinding[] { const events = this.query(scope), findings: WasteFinding[] = []; for (const event of events.filter(item => item.target === 'CLOUD' && item.kind === 'PROVIDER_EXECUTION')) { const local = events.find(item => item.executionId === event.executionId && item.operationId === event.operationId && item.target === 'LOCAL' && item.quality >= .8); if (local) findings.push(finding('UNNECESSARY_AI', event, event.actualCost, { localQuality: local.quality })); if (event.retryCount > 0 && event.quality <= event.baselineQuality) findings.push(finding('RETRY_WITHOUT_GAIN', event, event.actualCost, { retryCount: event.retryCount })); if (event.quality - event.baselineQuality < .02) findings.push(finding('INSIGNIFICANT_QUALITY_GAIN', event, event.actualCost, { qualityGain: event.quality - event.baselineQuality })); const duplicates = events.filter(item => item.id !== event.id && item.executionId === event.executionId && item.operationId === event.operationId && item.provider === event.provider && item.kind === 'PROVIDER_EXECUTION'); if (duplicates.length) findings.push(finding('DUPLICATE_CALL', event, event.actualCost, { duplicates: duplicates.length })); } for (const event of events.filter(item => item.kind === 'FALLBACK' && item.quality <= item.baselineQuality)) findings.push(finding('FALLBACK_WITHOUT_IMPROVEMENT', event, event.actualCost, { qualityGain: event.quality - event.baselineQuality })); return immutable(unique(findings, item => `${item.type}:${item.executionId}:${item.operationId}`)); }
  anomalies(scope: ObservabilityScope, baseline: Readonly<{ cost: number; latency: number; quality: number; providerFailureRate: number; localQuality: number; escalationRate: number; retryRate: number }>, threshold = .2): readonly Anomaly[] { const events = this.query(scope), economics = this.economics(scope), current = { COST_SPIKE: economics.costPerAcceptedResult, LATENCY_SPIKE: average(terminalEvents(events), event => event.durationMs), QUALITY_DEGRADATION: this.quality(scope).technicalQuality, PROVIDER_DEGRADATION: 1 - average(this.provider(scope), row => row.successRate), LOCAL_MODEL_REGRESSION: average(events.filter(event => event.target === 'LOCAL'), event => event.quality), UNEXPECTED_ESCALATION: this.hybrid(scope).escalationRate, UNUSUAL_RETRY_RATE: average(events, event => event.retryCount) }, bases = { COST_SPIKE: baseline.cost, LATENCY_SPIKE: baseline.latency, QUALITY_DEGRADATION: baseline.quality, PROVIDER_DEGRADATION: baseline.providerFailureRate, LOCAL_MODEL_REGRESSION: baseline.localQuality, UNEXPECTED_ESCALATION: baseline.escalationRate, UNUSUAL_RETRY_RATE: baseline.retryRate }; const lowerBad = new Set(['QUALITY_DEGRADATION', 'LOCAL_MODEL_REGRESSION']); return immutable(Object.entries(current).flatMap(([type, value]) => { const base = bases[type as keyof typeof bases], change = base ? (value - base) / base : 0, bad = lowerBad.has(type) ? change < -threshold : change > threshold; return bad ? [{ type, severity: Math.abs(change) > threshold * 2 ? 'BLOCK' : 'WARNING', key: scopeKey(scope), current: value, baseline: base, change }] : []; })) as readonly Anomaly[]; }
  benchmarks(): readonly GoldenBenchmark[] { return immutable([{ scenario: 'BACKGROUND_REMOVAL', operationId: 'background-remove', minimumQuality: .85, maximumCost: 4, maximumLatencyMs: 30_000 }, { scenario: 'UPSCALE', operationId: 'upscale', minimumQuality: .9, maximumCost: 3, maximumLatencyMs: 20_000 }, { scenario: 'PORTRAIT_ENHANCEMENT', operationId: 'portrait-enhance', minimumQuality: .88, maximumCost: 5, maximumLatencyMs: 45_000 }, { scenario: 'LUXURY_ENHANCEMENT', operationId: 'luxury-enhance', minimumQuality: .9, maximumCost: 7, maximumLatencyMs: 60_000 }, { scenario: 'TRY_ON', operationId: 'try-on', minimumQuality: .86, maximumCost: 8, maximumLatencyMs: 90_000 }, { scenario: 'GENERATIVE_EDIT', operationId: 'generative-edit', minimumQuality: .9, maximumCost: 8, maximumLatencyMs: 90_000 }]); }
  regressions(scope: ObservabilityScope, baselines: readonly GoldenBenchmark[], threshold = .1) { const rows = this.aggregate(scope, 'operation'); return immutable(baselines.flatMap(baseline => { const row = rows.find(item => item.key === baseline.operationId); if (!row) return []; const alerts = []; if (row.averageCost > baseline.maximumCost * (1 + threshold)) alerts.push({ scenario: baseline.scenario, metric: 'COST', severity: row.averageCost > baseline.maximumCost * (1 + threshold * 2) ? 'BLOCK' : 'WARNING', actual: row.averageCost, baseline: baseline.maximumCost }); if (row.averageQuality < baseline.minimumQuality * (1 - threshold)) alerts.push({ scenario: baseline.scenario, metric: 'QUALITY', severity: row.averageQuality < baseline.minimumQuality * (1 - threshold * 2) ? 'BLOCK' : 'WARNING', actual: row.averageQuality, baseline: baseline.minimumQuality }); if (row.averageLatency > baseline.maximumLatencyMs * (1 + threshold)) alerts.push({ scenario: baseline.scenario, metric: 'LATENCY', severity: row.averageLatency > baseline.maximumLatencyMs * (1 + threshold * 2) ? 'BLOCK' : 'WARNING', actual: row.averageLatency, baseline: baseline.maximumLatencyMs }); return alerts; })); }
  outcomes(scope: ObservabilityScope): readonly ObservabilityOutcome[] { return immutable(terminalEvents(this.query(scope)).map(event => ({ operation: event.operationId, selectedTarget: event.target, actualOutcome: event.outcome, actualCost: event.actualCost + event.localDeviceCost, actualQuality: event.quality, actualLatency: event.durationMs, userReaction: event.undone ? 'UNDO' : event.corrected ? 'CORRECTED' : event.userAccepted ? 'ACCEPTED' : event.userAccepted === false ? 'REJECTED' : 'UNKNOWN' }))); }
  snapshot(scope: ObservabilityScope, period?: Readonly<{ from: number; to: number }>): ObservabilitySnapshot { const events = this.query(scope, period), economics = this.economicsFor(events), quality = this.qualityFrom(events), providers = this.rows(events.filter(event => event.target === 'CLOUD'), event => event.provider ?? 'UNKNOWN'), models = this.rows(events.filter(event => event.target === 'LOCAL'), event => event.model ?? 'UNKNOWN'); return immutable({ period: period ?? { from: events[0]?.timestamp ?? 0, to: events.at(-1)?.timestamp ?? 0 }, scope, usage: { events: events.length, executions: new Set(events.map(event => event.executionId)).size, operations: new Set(events.map(event => event.operationId)).size }, cost: economics, quality, localCloud: { local: events.filter(event => event.target === 'LOCAL').length, cloud: events.filter(event => event.target === 'CLOUD').length, cloudAvoidanceRate: economics.cloudAvoidanceRate }, providers, models, failures: events.filter(event => event.outcome === 'FAILED').length, recovery: { attempted: events.filter(event => event.kind === 'RECOVERY').length, succeeded: events.filter(event => event.kind === 'RECOVERY' && event.recovered).length }, privacy: this.privacyFrom(events), economics, health: this.healthFrom(events) }) as ObservabilitySnapshot; }
  report(scope: ObservabilityScope) { const snapshot = this.snapshot(scope); return immutable({ generatedAt: this.#now(), snapshot, unnecessaryAI: this.waste(scope), anomalies: [], outcomes: this.outcomes(scope), narrative: `Cloud avoidance ${percent(snapshot.economics.cloudAvoidanceRate)}; credits saved ${snapshot.economics.creditsSaved.toFixed(2)}; accepted-edit cost ${snapshot.economics.costPerAcceptedResult.toFixed(2)}.` }); }
  debug(scope: ObservabilityScope, executionId: string) { const chain = this.query(scope).filter(event => event.executionId === executionId); return immutable({ request: chain.filter(event => event.kind === 'REQUEST'), decision: chain.filter(event => event.kind === 'PROVIDER_SELECTION'), plan: unique(chain.map(event => event.operationId), value => value), target: chain.map(event => event.target), execution: chain.filter(event => ['LOCAL_INFERENCE', 'CLOUD_INFERENCE', 'PROVIDER_EXECUTION'].includes(event.kind)), cost: sum(chain, event => event.actualCost + event.localDeviceCost), quality: chain.filter(event => event.kind === 'VERIFICATION'), recovery: chain.filter(event => event.kind === 'RECOVERY'), finalOutcome: terminalEvents(chain).at(-1), economics: this.economicsFor(chain) }); }
  private rows(events: readonly UnifiedTelemetryEvent[], key: (event: UnifiedTelemetryEvent) => string): readonly PerformanceRow[] { const groups = new Map<string, UnifiedTelemetryEvent[]>(); for (const event of events) groups.set(key(event), [...(groups.get(key(event)) ?? []), event]); return immutable([...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([name, values]) => { const terminal = terminalEvents(values), successful = terminal.filter(success); return { key: name, executions: new Set(values.map(event => event.executionId)).size, successes: successful.length, successRate: successful.length / Math.max(1, terminal.length), acceptanceRate: terminal.filter(event => event.userAccepted || event.outcome === 'ACCEPTED').length / Math.max(1, terminal.length), averageQuality: average(terminal, event => event.quality), averageCost: average(terminal, event => event.actualCost + event.localDeviceCost), averageLatency: average(terminal, event => event.durationMs), energyWh: sum(values, event => event.energyWh), fallbackRate: values.filter(event => event.kind === 'FALLBACK').length / Math.max(1, terminal.length), retryRate: average(values, event => event.retryCount) }; })); }
  private economicsFor(events: readonly UnifiedTelemetryEvent[]) { const temporary = new CreativeObservability({ now: this.#now, id: this.#id }); temporary.ingest(events); const scope = events[0]?.scope ?? { tenantId: 'none', projectId: 'none' }; return temporary.economics(scope); }
  private qualityFrom(events: readonly UnifiedTelemetryEvent[]) { const terminal = terminalEvents(events); return immutable({ average: average(terminal, event => event.quality), acceptanceRate: terminal.filter(event => event.userAccepted || event.outcome === 'ACCEPTED').length / Math.max(1, terminal.length), undoRate: terminal.filter(event => event.undone).length / Math.max(1, terminal.length), correctionRate: terminal.filter(event => event.corrected).length / Math.max(1, terminal.length) }); }
  private privacyFrom(events: readonly UnifiedTelemetryEvent[]) { return immutable({ localOnly: events.filter(event => event.policy === 'LOCAL_ONLY').length, cloud: events.filter(event => event.target === 'CLOUD').length, blocked: events.filter(event => event.outcome === 'BLOCKED' && event.reason === 'PRIVACY').length }); }
  private healthFrom(events: readonly UnifiedTelemetryEvent[]) { const terminal = terminalEvents(events), successRate = terminal.filter(success).length / Math.max(1, terminal.length); return immutable({ status: successRate >= .9 ? 'HEALTHY' : successRate >= .7 ? 'DEGRADED' : 'UNHEALTHY', successRate }); }
}

const terminalEvents = (events: readonly UnifiedTelemetryEvent[]) => events.filter(event => ['COMPLETION', 'VERIFICATION', 'PROVIDER_EXECUTION', 'LOCAL_INFERENCE', 'RECOVERY', 'FALLBACK'].includes(event.kind) && event.outcome !== 'STARTED');
const success = (event: UnifiedTelemetryEvent) => ['SUCCESS', 'ACCEPTED'].includes(event.outcome);
const sum = <T>(values: readonly T[], selector: (value: T) => number) => values.reduce((total, value) => total + safeNumber(selector(value)), 0);
const average = <T>(values: readonly T[], selector: (value: T) => number) => sum(values, selector) / Math.max(1, values.length);
const emptyRow = (key: string): PerformanceRow => ({ key, executions: 0, successes: 0, successRate: 0, acceptanceRate: 0, averageQuality: 0, averageCost: 0, averageLatency: 0, energyWh: 0, fallbackRate: 0, retryRate: 0 });
const unique = <T>(values: readonly T[], key: (value: T) => string) => [...new Map(values.map(value => [key(value), value])).values()];
const finding = (type: WasteFinding['type'], event: UnifiedTelemetryEvent, estimatedWaste: number, evidence: Record<string, unknown>): WasteFinding => ({ type, executionId: event.executionId, operationId: event.operationId, estimatedWaste, evidence });
const percent = (value: number) => `${(value * 100).toFixed(1)}%`;
const numeric = (value: unknown) => typeof value === 'number' ? value : 0;
const productionKind = (type: ProductionTelemetryEvent['type']): ObservabilityEventKind => ({ ExecutionStarted: 'EXECUTION', NodeStarted: 'OPERATION', NodeCompleted: 'OPERATION', NodeFailed: 'OPERATION', ProviderSelected: 'PROVIDER_SELECTION', ProviderCalled: 'PROVIDER_EXECUTION', LocalModelLoaded: 'LOCAL_INFERENCE', LocalInferenceCompleted: 'LOCAL_INFERENCE', FallbackTriggered: 'FALLBACK', EscalationTriggered: 'ESCALATION', VerificationPassed: 'VERIFICATION', VerificationFailed: 'VERIFICATION', ExecutionRecovered: 'RECOVERY', ExecutionCompleted: 'COMPLETION', ExecutionAborted: 'COMPLETION' } as Record<ProductionTelemetryEvent['type'], ObservabilityEventKind>)[type];
const productionOutcome = (type: ProductionTelemetryEvent['type']): TelemetryInput['outcome'] => type === 'ExecutionAborted' ? 'BLOCKED' : type === 'NodeFailed' || type === 'VerificationFailed' ? 'FAILED' : type === 'ExecutionStarted' || type === 'NodeStarted' || type === 'ProviderCalled' || type === 'ProviderSelected' || type === 'LocalModelLoaded' ? 'STARTED' : type === 'VerificationPassed' ? 'ACCEPTED' : 'SUCCESS';
