export const modules = {
  common: { appName: 'KI-Fotoeditor', save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten', close: 'Schließen', create: 'Erstellen', apply: 'Anwenden', retry: 'Erneut versuchen', confirm: 'Bestätigen', back: 'Zurück', next: 'Weiter', done: 'Fertig', loading: 'Wird geladen…', search: 'Suchen', add: 'Hinzufügen', remove: 'Entfernen', rename: 'Umbenennen', duplicate: 'Duplizieren', download: 'Herunterladen', favorite: 'Favorit', archive: 'Archivieren', restore: 'Wiederherstellen', signOut: 'Abmelden', empty: 'Noch nichts hier', minutes: '{count} Min', seconds: '{seconds}s' },
  editor: { title: 'Editor', undo: 'Rückgängig', redo: 'Wiederholen', restoreOriginal: 'Original wiederherstellen', detectObjects: 'Objekte erkennen', detecting: 'Objekte werden erkannt…', prompt: 'Eingabe', creativeStudio: 'Kreativ-Studio', recipes: 'Rezepte', aiAgent: 'KI-Agent', fashion: 'Mode', outfits: 'Outfits', before: 'Vorher', after: 'Nachher', accept: 'Übernehmen', discard: 'Verwerfen', objects: 'Objekte', versions: 'Versionen', newVersion: 'Neue Version', sceneMemory: 'Szenenspeicher', workspace: 'Arbeitsbereich', jobCenter: 'Auftragszentrum', instructionPlaceholder: 'Beschreibe deine Bearbeitung…', projectNotFound: 'Projekt nicht gefunden' },
  projects: { title: 'Projekte', newProject: 'Neues Projekt', upload: 'Bild hochladen', empty: 'Noch keine Projekte — lade ein Bild hoch.', open: 'Öffnen', processing: 'Verarbeitung', draft: 'Entwurf', completed: 'Abgeschlossen' },
  recipes: { title: 'Rezepte', favorite: 'Favorit', popular: 'Beliebt', recent: 'Zuletzt', recommended: 'Empfohlen', run: 'Rezept ausführen', use: 'Verwenden', searchPlaceholder: 'Rezepte suchen…' },
  workspace: { title: 'Arbeitsbereich', auto: 'Automatisch erkannt', manual: 'Manuell', switch: 'Arbeitsbereich wechseln', recommendations: 'Empfehlungen', mostUsed: 'Meistgenutzt' },
  automation: { title: 'Automatisierungs-Studio', subtitle: 'Erstelle wiederverwendbare Bearbeitungs-Workflows ohne Code.', library: 'Automatisierungsbibliothek', templateGallery: 'Vorlagengalerie', builder: 'Builder', history: 'Ausführungsverlauf', run: 'Ausführen', queuing: 'In Warteschlange…', save: 'Speichern', trigger: 'Auslöser', conditions: 'Bedingungen', condition: 'Bedingung', actions: 'Aktionen', action: 'Aktion', schedule: 'Zeitplan', variables: 'Variablen', estimatedCredits: 'Geschätzte Credits', estimatedTime: 'Geschätzte Zeit', emptyBuilder: 'Wähle eine Vorlage oder erstelle eine Automatisierung.', emptyLibrary: 'Speichere eine Vorlage für deine Bibliothek.', noRuns: 'Noch keine Ausführungen.', mostExecuted: 'Am häufigsten', successRate: 'Erfolg {rate}%', failureRate: 'Fehler {rate}%', describePlaceholder: 'Beschreibe diesen Workflow', actionsCount: '{count} Aktionen', untitled: 'Unbenannte Automatisierung', scheduleImmediate: 'Sofort', scheduleScheduled: 'Geplant', scheduleDaily: 'Täglich', scheduleWeekly: 'Wöchentlich', scheduleManual: 'Nur manuell', containsPerson: 'Enthält Person', containsVehicle: 'Enthält Fahrzeug', containsProduct: 'Enthält Produkt', containsAnimal: 'Enthält Tier', containsText: 'Enthält Text' },
  fashion: { title: 'Mode', wardrobe: 'Kleiderschrank', garments: 'Kleidung', outfits: 'Outfits', addGarment: 'Kleidungsstück hinzufügen', collections: 'Kollektionen', tryOn: 'Anprobe', searchPlaceholder: 'Kleiderschrank durchsuchen…', empty: 'Dein Kleiderschrank ist leer.' },
  billing: { title: 'Abrechnung', subscription: 'Abo', plan: 'Tarif', credits: 'Credits', upgrade: 'Upgraden', currentPlan: 'Aktueller Tarif', usage: 'Nutzung', renew: 'Verlängert am {date}' },
  settings: { title: 'Einstellungen', account: 'Konto', appearance: 'Darstellung', appearanceHint: 'Zwischen hellem und dunklem Modus wechseln', language: 'Sprache', languageHint: 'Wähle deine Oberflächensprache', performance: 'Leistung', loadingPerformance: 'Leistungseinstellungen werden geladen…' },
  errors: { generic: 'Etwas ist schiefgelaufen.', network: 'Netzwerkfehler — prüfe deine Verbindung.', offline: 'Du bist offline. Änderungen werden später synchronisiert.', timeout: 'Zeitüberschreitung. Bitte erneut versuchen.', provider: 'Der KI-Anbieter konnte die Anfrage nicht abschließen.', validation: 'Bitte korrigiere die markierten Felder.', credits: 'Du hast nicht genügend Credits für diesen Vorgang.', subscription: 'Dein Tarif erlaubt diese Aktion nicht.' },
  notifications: { title: 'Benachrichtigungen', markAllRead: 'Alle als gelesen markieren', empty: 'Keine Benachrichtigungen.', completed: 'Generierung abgeschlossen', failed: 'Generierung fehlgeschlagen', saved: 'Bearbeitung gespeichert' },
  jobs: { title: 'Auftragszentrum', queued: 'In Warteschlange', running: 'Läuft', waiting: 'Wartet', completed: 'Abgeschlossen', failed: 'Fehlgeschlagen', cancelled: 'Abgebrochen', retrying: 'Wiederholung', cancel: 'Abbrechen', pause: 'Pausieren', resume: 'Fortsetzen', empty: 'Keine aktiven Aufträge.' },
  creative: { title: 'Kreativ-Studio', goal: 'Ziel', ideas: 'Ideen', moodBoards: 'Moodboards', strategy: 'Strategie', generate: 'Ideen generieren', apply: 'Strategie anwenden' },
  brand: { title: 'Marken-Studio', profile: 'Markenprofil', colors: 'Farben', fonts: 'Schriften', voice: 'Tonalität', guidelines: 'Richtlinien' },
  assets: { title: 'Asset-Bibliothek', collections: 'Kollektionen', pinned: 'Angeheftet', smart: 'Smart', searchPlaceholder: 'Assets suchen…', empty: 'Noch keine Assets.', details: 'Details' },
};
export default modules;