export const modules = {
  common: { appName: 'Editor Foto IA', save: 'Salva', cancel: 'Annulla', delete: 'Elimina', edit: 'Modifica', close: 'Chiudi', create: 'Crea', apply: 'Applica', retry: 'Riprova', confirm: 'Conferma', back: 'Indietro', next: 'Avanti', done: 'Fatto', loading: 'Caricamento…', search: 'Cerca', add: 'Aggiungi', remove: 'Rimuovi', rename: 'Rinomina', duplicate: 'Duplica', download: 'Scarica', favorite: 'Preferito', archive: 'Archivia', restore: 'Ripristina', signOut: 'Esci', empty: 'Ancora niente qui', minutes: '{count} min', seconds: '{seconds}s' },
  editor: { title: 'Editor', undo: 'Annulla', redo: 'Ripeti', restoreOriginal: 'Ripristina originale', detectObjects: 'Rileva oggetti', detecting: 'Rilevamento oggetti…', prompt: 'Istruzione', creativeStudio: 'Studio Creativo', recipes: 'Ricette', aiAgent: 'Agente IA', fashion: 'Moda', outfits: 'Outfit', before: 'Prima', after: 'Dopo', accept: 'Accetta', discard: 'Scarta', objects: 'Oggetti', versions: 'Versioni', newVersion: 'Nuova versione', sceneMemory: 'Memoria scena', workspace: 'Area di lavoro', jobCenter: 'Centro attività', instructionPlaceholder: 'Descrivi la modifica…', projectNotFound: 'Progetto non trovato' },
  projects: { title: 'Progetti', newProject: 'Nuovo progetto', upload: 'Carica immagine', empty: 'Ancora nessun progetto — carica un\'immagine per iniziare.', open: 'Apri', processing: 'Elaborazione', draft: 'Bozza', completed: 'Completato' },
  recipes: { title: 'Ricette', favorite: 'Preferito', popular: 'Popolari', recent: 'Recenti', recommended: 'Consigliate', run: 'Esegui ricetta', use: 'Usa', searchPlaceholder: 'Cerca ricette…' },
  workspace: { title: 'Area di lavoro', auto: 'Rilevata automaticamente', manual: 'Manuale', switch: 'Cambia area', recommendations: 'Consigli', mostUsed: 'Più usata' },
  automation: { title: 'Studio di Automazione', subtitle: 'Crea flussi di modifica riutilizzabili senza scrivere codice.', library: 'Libreria automazioni', templateGallery: 'Galleria modelli', builder: 'Costruttore', history: 'Cronologia esecuzioni', run: 'Esegui', queuing: 'In coda…', save: 'Salva', trigger: 'Trigger', conditions: 'Condizioni', condition: 'Condizione', actions: 'Azioni', action: 'Azione', schedule: 'Pianificazione', variables: 'Variabili', estimatedCredits: 'Crediti stimati', estimatedTime: 'Tempo stimato', emptyBuilder: 'Scegli un modello o crea un\'automazione.', emptyLibrary: 'Salva un modello per la tua libreria.', noRuns: 'Ancora nessuna esecuzione.', mostExecuted: 'Più eseguita', successRate: 'Successo {rate}%', failureRate: 'Errori {rate}%', describePlaceholder: 'Descrivi questo flusso', actionsCount: '{count} azioni', untitled: 'Automazione senza titolo', scheduleImmediate: 'Immediato', scheduleScheduled: 'Pianificato', scheduleDaily: 'Giornaliero', scheduleWeekly: 'Settimanale', scheduleManual: 'Solo manuale', containsPerson: 'Contiene persona', containsVehicle: 'Contiene veicolo', containsProduct: 'Contiene prodotto', containsAnimal: 'Contiene animale', containsText: 'Contiene testo' },
  fashion: { title: 'Moda', wardrobe: 'Guardaroba', garments: 'Capi', outfits: 'Outfit', addGarment: 'Aggiungi capo', collections: 'Collezioni', tryOn: 'Prova virtuale', searchPlaceholder: 'Cerca nel guardaroba…', empty: 'Il tuo guardaroba è vuoto.' },
  billing: { title: 'Fatturazione', subscription: 'Abbonamento', plan: 'Piano', credits: 'Crediti', upgrade: 'Aggiorna', currentPlan: 'Piano attuale', usage: 'Utilizzo', renew: 'Si rinnova il {date}' },
  settings: { title: 'Impostazioni', account: 'Account', appearance: 'Aspetto', appearanceHint: 'Passa tra modalità chiara e scura', language: 'Lingua', languageHint: 'Scegli la lingua dell\'interfaccia', performance: 'Prestazioni', loadingPerformance: 'Caricamento impostazioni prestazioni…' },
  errors: { generic: 'Qualcosa è andato storto.', network: 'Errore di rete — controlla la connessione.', offline: 'Sei offline. Le modifiche verranno sincronizzate al riconnetterti.', timeout: 'Richiesta scaduta. Riprova.', provider: 'Il provider IA non ha potuto completare la richiesta.', validation: 'Correggi i campi evidenziati.', credits: 'Non hai crediti sufficienti per questa operazione.', subscription: 'Il tuo piano non consente questa azione.' },
  notifications: { title: 'Notifiche', markAllRead: 'Segna tutto come letto', empty: 'Nessuna notifica.', completed: 'Generazione completata', failed: 'Generazione fallita', saved: 'Modifica salvata' },
  jobs: { title: 'Centro attività', queued: 'In coda', running: 'In esecuzione', waiting: 'In attesa', completed: 'Completato', failed: 'Fallito', cancelled: 'Annullato', retrying: 'Nuovo tentativo', cancel: 'Annulla', pause: 'Pausa', resume: 'Riprendi', empty: 'Nessuna attività attiva.' },
  creative: { title: 'Studio Creativo', goal: 'Obiettivo', ideas: 'Idee', moodBoards: 'Mood board', strategy: 'Strategia', generate: 'Genera idee', apply: 'Applica strategia' },
  brand: { title: 'Studio del Brand', profile: 'Profilo del brand', colors: 'Colori', fonts: 'Font', voice: 'Tono', guidelines: 'Linee guida' },
  assets: { title: 'Libreria risorse', collections: 'Collezioni', pinned: 'Fissati', smart: 'Intelligenti', searchPlaceholder: 'Cerca risorse…', empty: 'Ancora nessuna risorsa.', details: 'Dettagli' },
};
export default modules;