export const modules = {
  common: { appName: 'Editor de Fotos IA', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', close: 'Cerrar', create: 'Crear', apply: 'Aplicar', retry: 'Reintentar', confirm: 'Confirmar', back: 'Atrás', next: 'Siguiente', done: 'Listo', loading: 'Cargando…', search: 'Buscar', add: 'Añadir', remove: 'Quitar', rename: 'Renombrar', duplicate: 'Duplicar', download: 'Descargar', favorite: 'Favorito', archive: 'Archivar', restore: 'Restaurar', signOut: 'Cerrar sesión', empty: 'Aún no hay nada aquí', minutes: '{count} min', seconds: '{seconds}s' },
  editor: { title: 'Editor', undo: 'Deshacer', redo: 'Rehacer', restoreOriginal: 'Restaurar original', detectObjects: 'Detectar objetos', detecting: 'Detectando objetos…', prompt: 'Instrucción', creativeStudio: 'Estudio Creativo', recipes: 'Recetas', aiAgent: 'Agente IA', fashion: 'Moda', outfits: 'Conjuntos', before: 'Antes', after: 'Después', accept: 'Aceptar', discard: 'Descartar', objects: 'Objetos', versions: 'Versiones', newVersion: 'Nueva versión', sceneMemory: 'Memoria de escena', workspace: 'Espacio de trabajo', jobCenter: 'Centro de tareas', instructionPlaceholder: 'Describe tu edición…', projectNotFound: 'Proyecto no encontrado' },
  projects: { title: 'Proyectos', newProject: 'Nuevo proyecto', upload: 'Subir imagen', empty: 'Aún no hay proyectos — sube una imagen para empezar.', open: 'Abrir', processing: 'Procesando', draft: 'Borrador', completed: 'Completado' },
  recipes: { title: 'Recetas', favorite: 'Favorito', popular: 'Populares', recent: 'Recientes', recommended: 'Recomendadas', run: 'Ejecutar receta', use: 'Usar', searchPlaceholder: 'Buscar recetas…' },
  workspace: { title: 'Espacio de trabajo', auto: 'Detección automática', manual: 'Manual', switch: 'Cambiar espacio', recommendations: 'Recomendaciones', mostUsed: 'Más usado' },
  automation: { title: 'Estudio de Automatización', subtitle: 'Crea flujos de edición reutilizables sin escribir código.', library: 'Biblioteca de automatizaciones', templateGallery: 'Galería de plantillas', builder: 'Constructor', history: 'Historial de ejecución', run: 'Ejecutar', queuing: 'En cola…', save: 'Guardar', trigger: 'Disparador', conditions: 'Condiciones', condition: 'Condición', actions: 'Acciones', action: 'Acción', schedule: 'Programación', variables: 'Variables', estimatedCredits: 'Créditos estimados', estimatedTime: 'Tiempo estimado', emptyBuilder: 'Elige una plantilla o crea una automatización.', emptyLibrary: 'Guarda una plantilla para tu biblioteca.', noRuns: 'Aún no hay ejecuciones.', mostExecuted: 'Más ejecutado', successRate: 'Éxito {rate}%', failureRate: 'Fallos {rate}%', describePlaceholder: 'Describe este flujo', actionsCount: '{count} acciones', untitled: 'Automatización sin título', scheduleImmediate: 'Inmediato', scheduleScheduled: 'Programado', scheduleDaily: 'Diario', scheduleWeekly: 'Semanal', scheduleManual: 'Solo manual', containsPerson: 'Contiene persona', containsVehicle: 'Contiene vehículo', containsProduct: 'Contiene producto', containsAnimal: 'Contiene animal', containsText: 'Contiene texto' },
  fashion: { title: 'Moda', wardrobe: 'Armario', garments: 'Prendas', outfits: 'Conjuntos', addGarment: 'Añadir prenda', collections: 'Colecciones', tryOn: 'Prueba virtual', searchPlaceholder: 'Buscar en el armario…', empty: 'Tu armario está vacío.' },
  billing: { title: 'Facturación', subscription: 'Suscripción', plan: 'Plan', credits: 'Créditos', upgrade: 'Mejorar', currentPlan: 'Plan actual', usage: 'Uso', renew: 'Se renueva el {date}' },
  settings: { title: 'Configuración', account: 'Cuenta', appearance: 'Apariencia', appearanceHint: 'Cambiar entre modo claro y oscuro', language: 'Idioma', languageHint: 'Elige el idioma de la interfaz', performance: 'Rendimiento', loadingPerformance: 'Cargando ajustes de rendimiento…' },
  errors: { generic: 'Algo salió mal.', network: 'Error de red — verifica tu conexión.', offline: 'Estás sin conexión. Los cambios se sincronizarán al reconectar.', timeout: 'La solicitud expiró. Inténtalo de nuevo.', provider: 'El proveedor de IA no pudo completar la solicitud.', validation: 'Corrige los campos resaltados.', credits: 'No tienes créditos suficientes para esta operación.', subscription: 'Tu plan no permite esta acción.' },
  notifications: { title: 'Notificaciones', markAllRead: 'Marcar todo como leído', empty: 'Sin notificaciones.', completed: 'Generación completada', failed: 'Error de generación', saved: 'Edición guardada' },
  jobs: { title: 'Centro de tareas', queued: 'En cola', running: 'En ejecución', waiting: 'Esperando', completed: 'Completado', failed: 'Fallido', cancelled: 'Cancelado', retrying: 'Reintentando', cancel: 'Cancelar', pause: 'Pausar', resume: 'Reanudar', empty: 'No hay tareas activas.' },
  creative: { title: 'Estudio Creativo', goal: 'Objetivo', ideas: 'Ideas', moodBoards: 'Paneles de inspiración', strategy: 'Estrategia', generate: 'Generar ideas', apply: 'Aplicar estrategia' },
  brand: { title: 'Estudio de Marca', profile: 'Perfil de marca', colors: 'Colores', fonts: 'Fuentes', voice: 'Tono', guidelines: 'Directrices' },
  assets: { title: 'Biblioteca de recursos', collections: 'Colecciones', pinned: 'Fijados', smart: 'Inteligentes', searchPlaceholder: 'Buscar recursos…', empty: 'Aún no hay recursos.', details: 'Detalles' },
};
export default modules;