import type { IntelligencePlugin, KernelScope, PluginContext, PluginPublication } from '../kernel';
import { RuntimeExecutionGraphBuilder, RuntimeInvariantValidator } from './ExecutionGraph';
import { immutable } from './immutable';
import { TransactionalBlackboard } from './RuntimeBlackboard';
import { DependencyCache, RuntimeDeterminismValidator, RuntimeEventRecorder, RuntimeMetricsCollector, RuntimeOptimizer, RuntimeProfiler, RuntimeSandbox, RuntimeTrace } from './services';
import type { ExecutionNode, PluginProfile, RuntimeCheckpoint, RuntimeCreateRequest, RuntimeDependencies, RuntimePluginRegistration, RuntimeRunOptions, RuntimeSession, RuntimeSnapshot } from './types';

const sameScope = (a: KernelScope, b: KernelScope) => a.tenantId === b.tenantId && a.projectId === b.projectId && a.userId === b.userId;
export class CreativeIntelligenceRuntime {
  readonly blackboard: TransactionalBlackboard;
  readonly determinism = new RuntimeDeterminismValidator();
  private readonly sessions = new Map<string, RuntimeSession>(); private readonly plugins = new Map<string, RuntimePluginRegistration>(); private readonly checkpoints = new Map<string, RuntimeCheckpoint[]>(); private readonly executions: Array<{ pluginId: string; elapsed: number; outputCount: number; valueScore: number }> = [];
  private readonly graphs: RuntimeExecutionGraphBuilder; private readonly invariants = new RuntimeInvariantValidator(); private readonly cache = new DependencyCache(); private readonly recorder: RuntimeEventRecorder; private readonly sandbox: RuntimeSandbox; private readonly optimizer = new RuntimeOptimizer(); private readonly profiler = new RuntimeProfiler(); private readonly metrics = new RuntimeMetricsCollector(); private readonly traces = new RuntimeTrace();
  constructor(private readonly dependencies: RuntimeDependencies) { this.blackboard = new TransactionalBlackboard(dependencies); this.graphs = new RuntimeExecutionGraphBuilder(dependencies); this.recorder = new RuntimeEventRecorder(dependencies); this.sandbox = new RuntimeSandbox(dependencies); }

  register(plugin: IntelligencePlugin, valueScore = .5): RuntimePluginRegistration { if (this.plugins.has(plugin.id)) throw new Error(`Runtime plugin ${plugin.id} already registered`); const registration = immutable({ plugin, enabled: true, valueScore }); this.plugins.set(plugin.id, registration); return registration; }
  setPluginEnabled(pluginId: string, enabled: boolean): RuntimePluginRegistration { const current = this.requirePlugin(pluginId); const next = immutable({ ...current, enabled }); this.plugins.set(pluginId, next); return next; }
  createSession(input: RuntimeCreateRequest): RuntimeSession { this.validateRequest(input); const graph = this.graphs.build([...this.plugins.values()].map((item) => item.plugin)); this.invariants.validateGraph(graph); const at = this.dependencies.now(); const session = immutable({ tenantId: input.tenantId, projectId: input.projectId, userId: input.userId, id: this.dependencies.nextId(), objective: input.objective, prompt: input.prompt, seed: input.seed, budget: input.budget, capabilities: [...(input.capabilities ?? [])], status: 'CREATED' as const, graph, completedNodeIds: [], createdAt: at, updatedAt: at }); this.sessions.set(session.id, session); this.recorder.record(session, 'SESSION_CREATED', { seed: input.seed }); const transaction = this.blackboard.begin(session.id, input); for (const [key, value] of Object.entries(input.initialState ?? {})) this.blackboard.write(transaction.id, { ...input, sessionId: session.id, key, value, author: 'RUNTIME' }); this.blackboard.write(transaction.id, { ...input, sessionId: session.id, key: 'prompt', value: input.prompt, author: 'RUNTIME' }); this.blackboard.write(transaction.id, { ...input, sessionId: session.id, key: 'objective', value: input.objective, author: 'RUNTIME' }); this.blackboard.write(transaction.id, { ...input, sessionId: session.id, key: 'budget', value: input.budget, author: 'RUNTIME' }); this.blackboard.commit(transaction.id); return session; }
  run(sessionId: string, scope: KernelScope, options: RuntimeRunOptions = {}): RuntimeSnapshot { let session = this.requireSession(sessionId, scope); if (session.status === 'SHUTDOWN') throw new Error('Runtime session is shutdown'); session = this.update(session, { status: 'RUNNING', failedNodeId: undefined }); this.recorder.record(session, session.status === 'PAUSED' ? 'RESUMED' : 'RUN_STARTED'); const order = this.invariants.topological(session.graph); const changedKeys = options.changedKeys ?? []; for (const nodeId of order) { const node = session.graph.nodes.find((item) => item.id === nodeId)!; if (!changedKeys.length && session.completedNodeIds.includes(node.id)) continue; try { const outcome = this.executeNode(session, node, changedKeys); session = outcome.session; if (options.untilNodeId === node.id) { session = this.update(session, { status: 'PAUSED' }); this.recorder.record(session, 'PAUSED', {}, { nodeId: node.id }); break; } } catch (error) { session = this.update(session, { status: 'FAILED', failedNodeId: node.id }); this.recorder.record(session, 'FAILED', { error: error instanceof Error ? error.message : String(error) }, { nodeId: node.id, pluginId: node.pluginId }); return this.inspect(session.id, scope); } }
    if (session.status === 'RUNNING') { session = this.update(session, { status: 'COMPLETED' }); this.recorder.record(session, 'COMPLETED'); }
    return this.inspect(session.id, scope);
  }
  pause(sessionId: string, scope: KernelScope): RuntimeSession { const session = this.requireSession(sessionId, scope); if (session.status !== 'RUNNING' && session.status !== 'CREATED') throw new Error('Only active runtime sessions can pause'); const next = this.update(session, { status: 'PAUSED' }); this.recorder.record(next, 'PAUSED'); return next; }
  resume(sessionId: string, scope: KernelScope, options: RuntimeRunOptions = {}): RuntimeSnapshot { const session = this.requireSession(sessionId, scope); if (session.status !== 'PAUSED' && session.status !== 'FAILED' && session.status !== 'RECOVERING') throw new Error('Runtime session is not resumable'); this.recorder.record(session, 'RESUMED'); return this.run(sessionId, scope, options); }
  checkpoint(sessionId: string, scope: KernelScope, label: string): RuntimeCheckpoint { const snapshot = this.inspect(sessionId, scope); const history = this.checkpoints.get(sessionId) ?? []; const checkpoint = immutable({ ...scope, id: this.dependencies.nextId(), sessionId, label, sequence: history.length, session: snapshot.session, blackboard: snapshot.blackboard, events: snapshot.events, createdAt: this.dependencies.now() }); this.checkpoints.set(sessionId, [...history, checkpoint]); this.recorder.record(snapshot.session, 'CHECKPOINT', { checkpointId: checkpoint.id, label }); return checkpoint; }
  rollback(sessionId: string, scope: KernelScope, checkpointId: string): RuntimeSnapshot { const checkpoint = this.requireCheckpoint(sessionId, scope, checkpointId); this.sessions.set(sessionId, checkpoint.session); this.blackboard.restore(sessionId, scope, checkpoint.blackboard); this.recorder.replace(sessionId, scope, checkpoint.events); this.recorder.record(checkpoint.session, 'ROLLBACK', { checkpointId }); return this.inspect(sessionId, scope); }
  recover(sessionId: string, scope: KernelScope): RuntimeSnapshot { let session = this.requireSession(sessionId, scope); if (session.status !== 'FAILED' && session.status !== 'PAUSED') throw new Error('Runtime session does not require recovery'); session = this.update(session, { status: 'RECOVERING' }); this.recorder.record(session, 'RECOVERY', { failedNodeId: session.failedNodeId }); return this.resume(sessionId, scope); }
  replay(sessionId: string, scope: KernelScope) { const snapshot = this.inspect(sessionId, scope); return immutable(snapshot.events.map((event, sequence) => ({ sequence, event, blackboardRevision: snapshot.blackboard.filter((entry) => entry.at <= event.at).at(-1)?.revision ?? 0 }))); }
  inspect(sessionId: string, scope: KernelScope): RuntimeSnapshot { const session = this.requireSession(sessionId, scope); const events = this.recorder.history(sessionId, scope); const blackboard = this.blackboard.read(sessionId, scope); this.invariants.validateEvents(events); this.invariants.validateBlackboard(blackboard); const profiles = this.profiler.profile(this.executions); const metrics = this.metrics.calculate(events, profiles); const trace = this.traces.build(session, events, blackboard.length); return immutable({ session: structuredClone(session), blackboard, events, metrics, trace }); }
  shutdown(sessionId: string, scope: KernelScope): RuntimeSession { let session = this.requireSession(sessionId, scope); const context = this.context(session); for (const registration of this.plugins.values()) registration.plugin.shutdown(context); session = this.update(session, { status: 'SHUTDOWN' }); this.recorder.record(session, 'SHUTDOWN'); return session; }
  profile(): readonly PluginProfile[] { return this.profiler.profile(this.executions); }
  debug(sessionId: string, scope: KernelScope): string { const snapshot = this.inspect(sessionId, scope); return immutable(['Session', 'Plugin', 'Messages', 'Reasoning', 'State', 'Budget', 'Timeline', 'Replay'].map((section) => `${section}: ${section === 'Session' ? snapshot.session.id : section === 'State' ? snapshot.session.status : section === 'Budget' ? snapshot.session.budget : snapshot.events.length}`).join('\n')); }

  private executeNode(session: RuntimeSession, node: ExecutionNode, changedKeys: readonly string[]) { this.recorder.record(session, 'NODE_STARTED', { kind: node.kind }, { nodeId: node.id, pluginId: node.pluginId }); if (!node.pluginId) return this.executeCore(session, node); const registration = this.requirePlugin(node.pluginId); const entries = this.blackboard.read(session.id, session); const input = Object.fromEntries(entries.filter((entry) => node.inputKeys.includes(entry.key)).map((entry) => [entry.key, entry.value])); const cached = this.cache.get(node.pluginId, input, session); const decision = this.optimizer.shouldRun(node, { requestedCapabilities: session.capabilities, changedKeys, hasCache: Boolean(cached), plugin: registration }); if (!decision.run) { this.recorder.record(session, 'NODE_SKIPPED', { reason: decision.reason }, { nodeId: node.id, pluginId: node.pluginId }); return { session: this.completeNode(session, node.id) }; } let publications: readonly PluginPublication[]; let elapsed = 0; if (cached && (!changedKeys.length || !node.inputKeys.some((key) => changedKeys.includes(key)))) { publications = cached.output; this.recorder.record(session, 'CACHE_HIT', { key: cached.key }, { nodeId: node.id, pluginId: node.pluginId }); } else { const result = this.sandbox.execute(registration.plugin, this.context(session), [], Math.max(1, Math.floor(session.budget / Math.max(1, this.plugins.size)))); publications = result.publications; elapsed = result.elapsed; this.cache.put(node.pluginId, input, publications, session, this.dependencies.now()); this.executions.push({ pluginId: node.pluginId, elapsed, outputCount: publications.length, valueScore: registration.valueScore }); } const transaction = this.blackboard.begin(session.id, session); publications.forEach((publication, index) => { this.blackboard.write(transaction.id, { ...session, sessionId: session.id, key: publication.blackboard?.key ?? `${node.outputKey}.${index}`, value: publication.blackboard?.value ?? publication.payload, author: node.pluginId! }); this.recorder.record(session, 'MESSAGE', { topic: publication.topic }, { nodeId: node.id, pluginId: node.pluginId }); }); const writes = this.blackboard.commit(transaction.id); if (writes.length) this.recorder.record(session, 'BLACKBOARD_COMMITTED', { writes: writes.length }, { nodeId: node.id, pluginId: node.pluginId }); this.recorder.record(session, 'NODE_COMPLETED', { outputKey: node.outputKey, elapsed }, { nodeId: node.id, pluginId: node.pluginId }); return { session: this.completeNode(session, node.id) }; }
  private executeCore(session: RuntimeSession, node: ExecutionNode) { const transaction = this.blackboard.begin(session.id, session); this.blackboard.write(transaction.id, { ...session, sessionId: session.id, key: node.outputKey, value: { kind: node.kind, computed: true }, author: 'RUNTIME' }); this.blackboard.commit(transaction.id); this.recorder.record(session, 'BLACKBOARD_COMMITTED', { writes: 1, kind: node.kind }, { nodeId: node.id }); this.recorder.record(session, 'NODE_COMPLETED', { outputKey: node.outputKey, kind: node.kind }, { nodeId: node.id }); return { session: this.completeNode(session, node.id) }; }
  private completeNode(session: RuntimeSession, nodeId: string) { return this.update(session, { completedNodeIds: [...new Set([...session.completedNodeIds, nodeId])] }); }
  private context(session: RuntimeSession): PluginContext { return immutable({ tenantId: session.tenantId, projectId: session.projectId, userId: session.userId, sessionId: session.id, objective: session.objective }); }
  private update(session: RuntimeSession, patch: Partial<RuntimeSession>): RuntimeSession { const next = immutable({ ...session, ...patch, updatedAt: this.dependencies.now() }); this.sessions.set(session.id, next); return next; }
  private requireSession(id: string, scope: KernelScope) { const session = this.sessions.get(id); if (!session) throw new Error(`Unknown runtime session ${id}`); if (!sameScope(session, scope)) throw new Error('Runtime session scope violation'); return session; }
  private requirePlugin(id: string) { const plugin = this.plugins.get(id); if (!plugin) throw new Error(`Unknown runtime plugin ${id}`); return plugin; }
  private requireCheckpoint(sessionId: string, scope: KernelScope, checkpointId: string) { this.requireSession(sessionId, scope); const checkpoint = this.checkpoints.get(sessionId)?.find((item) => item.id === checkpointId); if (!checkpoint || !sameScope(checkpoint, scope)) throw new Error(`Unknown runtime checkpoint ${checkpointId}`); return checkpoint; }
  private validateRequest(input: RuntimeCreateRequest) { if (!input.tenantId || !input.projectId || !input.userId) throw new Error('Complete runtime scope is required'); if (!input.objective.trim() || !input.prompt.trim()) throw new Error('Objective and prompt are required'); if (!Number.isInteger(input.budget) || input.budget < 0) throw new Error('Runtime budget must be a non-negative integer'); }
}
