import { immutable } from './immutable';
import type { KernelScope } from '../kernel';
import type { BlackboardTransaction, RuntimeBlackboardEntry, RuntimeDependencies } from './types';
const sameScope = (a: KernelScope, b: KernelScope) => a.tenantId === b.tenantId && a.projectId === b.projectId && a.userId === b.userId;
export class TransactionalBlackboard {
  private readonly entries: RuntimeBlackboardEntry[] = []; private readonly transactions = new Map<string, BlackboardTransaction>();
  constructor(private readonly dependencies: RuntimeDependencies) {}
  begin(sessionId: string, scope: KernelScope): BlackboardTransaction { const transaction = immutable({ id: this.dependencies.nextId(), sessionId, scope: structuredClone(scope), baseRevision: this.read(sessionId, scope).length, writes: [], status: 'OPEN' as const }); this.transactions.set(transaction.id, transaction); return transaction; }
  write(transactionId: string, input: Omit<RuntimeBlackboardEntry, 'id' | 'revision' | 'at'>): BlackboardTransaction { const transaction = this.requireOpen(transactionId); if (input.sessionId !== transaction.sessionId || !sameScope(input, transaction.scope)) throw new Error('Blackboard transaction scope violation'); const next = immutable({ ...transaction, writes: [...transaction.writes, structuredClone(input)] }); this.transactions.set(transactionId, next); return next; }
  commit(transactionId: string): readonly RuntimeBlackboardEntry[] { const transaction = this.requireOpen(transactionId); if (this.read(transaction.sessionId, transaction.scope).length !== transaction.baseRevision) throw new Error('Blackboard transaction conflict'); const committed = transaction.writes.map((write, index) => immutable({ ...write, id: this.dependencies.nextId(), revision: transaction.baseRevision + index + 1, at: this.dependencies.now() })); this.entries.push(...committed); this.transactions.set(transactionId, immutable({ ...transaction, status: 'COMMITTED' })); return immutable(committed); }
  rollback(transactionId: string): BlackboardTransaction { const transaction = this.requireOpen(transactionId); const rolledBack = immutable({ ...transaction, writes: [], status: 'ROLLED_BACK' as const }); this.transactions.set(transactionId, rolledBack); return rolledBack; }
  read(sessionId: string, scope: KernelScope): readonly RuntimeBlackboardEntry[] { return immutable(this.entries.filter((entry) => entry.sessionId === sessionId && sameScope(entry, scope)).map((entry) => structuredClone(entry))); }
  restore(sessionId: string, scope: KernelScope, entries: readonly RuntimeBlackboardEntry[]): void { if (entries.some((entry) => entry.sessionId !== sessionId || !sameScope(entry, scope))) throw new Error('Blackboard restore scope violation'); const retained = this.entries.filter((entry) => entry.sessionId !== sessionId || !sameScope(entry, scope)); this.entries.length = 0; this.entries.push(...retained, ...structuredClone(entries)); }
  private requireOpen(id: string) { const transaction = this.transactions.get(id); if (!transaction) throw new Error(`Unknown blackboard transaction ${id}`); if (transaction.status !== 'OPEN') throw new Error(`Blackboard transaction is ${transaction.status.toLowerCase()}`); return transaction; }
}
