import type { Capability, IntelligencePlugin, KernelScope, PluginPublication } from '../kernel';

export interface RuntimeDependencies { readonly nextId: () => string; readonly now: () => number; readonly random: () => number }
export type RuntimeStatus = 'CREATED' | 'RUNNING' | 'PAUSED' | 'RECOVERING' | 'COMPLETED' | 'SHUTDOWN' | 'FAILED';
export type ExecutionNodeKind = 'GOAL' | 'INTENT' | 'HYPOTHESIS' | 'DEBATE' | 'SIMULATION' | 'REFLECTION' | 'DECISION' | 'COMMIT' | 'PLUGIN';
export interface ExecutionNode { readonly id: string; readonly kind: ExecutionNodeKind; readonly pluginId?: string; readonly dependencyIds: readonly string[]; readonly requiredCapabilities: readonly Capability[]; readonly inputKeys: readonly string[]; readonly outputKey: string; readonly status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'SKIPPED' | 'CACHED' | 'FAILED' }
export interface RuntimeExecutionGraph { readonly id: string; readonly nodes: readonly ExecutionNode[] }
export interface RuntimeSession extends KernelScope { readonly id: string; readonly objective: string; readonly prompt: string; readonly seed: string; readonly budget: number; readonly capabilities: readonly Capability[]; readonly status: RuntimeStatus; readonly graph: RuntimeExecutionGraph; readonly completedNodeIds: readonly string[]; readonly failedNodeId?: string; readonly createdAt: number; readonly updatedAt: number }
export interface RuntimeEvent extends KernelScope { readonly id: string; readonly sessionId: string; readonly sequence: number; readonly type: 'SESSION_CREATED' | 'RUN_STARTED' | 'NODE_STARTED' | 'NODE_COMPLETED' | 'NODE_SKIPPED' | 'CACHE_HIT' | 'BLACKBOARD_COMMITTED' | 'MESSAGE' | 'PAUSED' | 'RESUMED' | 'CHECKPOINT' | 'ROLLBACK' | 'RECOVERY' | 'COMPLETED' | 'FAILED' | 'SHUTDOWN'; readonly at: number; readonly pluginId?: string; readonly nodeId?: string; readonly data: Readonly<Record<string, unknown>> }
export interface RuntimeBlackboardEntry extends KernelScope { readonly id: string; readonly sessionId: string; readonly key: string; readonly value: unknown; readonly author: string; readonly revision: number; readonly at: number }
export interface BlackboardTransaction { readonly id: string; readonly sessionId: string; readonly scope: KernelScope; readonly baseRevision: number; readonly writes: readonly Omit<RuntimeBlackboardEntry, 'id' | 'revision' | 'at'>[]; readonly status: 'OPEN' | 'COMMITTED' | 'ROLLED_BACK' }
export interface CacheEntry extends KernelScope { readonly key: string; readonly pluginId: string; readonly inputHash: string; readonly output: readonly PluginPublication[]; readonly createdAt: number; readonly hits: number }
export interface RuntimeCheckpoint extends KernelScope { readonly id: string; readonly sessionId: string; readonly label: string; readonly sequence: number; readonly session: RuntimeSession; readonly blackboard: readonly RuntimeBlackboardEntry[]; readonly events: readonly RuntimeEvent[]; readonly createdAt: number }
export interface RuntimeMetrics { readonly reasoningTime: number; readonly simulationTime: number; readonly debateTime: number; readonly reflectionTime: number; readonly pluginExecutionTime: Readonly<Record<string, number>>; readonly blackboardWrites: number; readonly messages: number; readonly cacheHits: number; readonly skippedNodes: number }
export interface PluginProfile { readonly pluginId: string; readonly executions: number; readonly totalTime: number; readonly averageTime: number; readonly outputCount: number; readonly valueScore: number; readonly classification: 'BOTTLENECK' | 'EFFICIENT' | 'LOW_VALUE' }
export interface RuntimeTraceEntry { readonly sequence: number; readonly plugin?: string; readonly state: RuntimeStatus; readonly blackboardRevision: number; readonly messageCount: number; readonly reasoning: string; readonly outputKey?: string; readonly at: number }
export interface RuntimeSnapshot { readonly session: RuntimeSession; readonly blackboard: readonly RuntimeBlackboardEntry[]; readonly events: readonly RuntimeEvent[]; readonly metrics: RuntimeMetrics; readonly trace: readonly RuntimeTraceEntry[] }
export interface RuntimeCreateRequest extends KernelScope { readonly objective: string; readonly prompt: string; readonly seed: string; readonly budget: number; readonly capabilities?: readonly Capability[]; readonly initialState?: Readonly<Record<string, unknown>> }
export interface RuntimeRunOptions { readonly changedKeys?: readonly string[]; readonly untilNodeId?: string }
export interface SandboxResult { readonly publications: readonly PluginPublication[]; readonly elapsed: number }
export interface RuntimePluginRegistration { readonly plugin: IntelligencePlugin; readonly enabled: boolean; readonly valueScore: number }
