import { CreativeWorkflowEngine, WorkflowCompiler, type Artifact, type WorkflowSnapshot } from '../workflow-engine';
import { ProductionOperationAuthority } from '../authority';
import { CreativeCostAuthority } from '../cost/contracts';
import type { CreativeOperationInstance } from '../operations/contracts';
import type { CreativeArtifact, CreativeDecision, CreativeExecutionPlan, CreativeExecutionPlatformDependencies, CreativePipeline, CreativePlan, CreativeRequest, ExecutionCapabilityPort, ProductionOutcome, VerificationResult } from './contracts';
import { validateCreativePlan, validateExecutionTargets } from './planning/planValidation';

type RecordState = { request: CreativeRequest; decision?: CreativeDecision; plan?: CreativePlan; execution?: CreativeExecutionPlan; pipeline?: CreativePipeline; workflow?: ReturnType<WorkflowCompiler['compile']>; operation?: CreativeOperationInstance; snapshot?: WorkflowSnapshot; outcome?: ProductionOutcome; paused: boolean; cancelled: boolean };

/**
 * The sole recommended production entry point for Creative execution.
 * Planning and compilation are pure boundaries; CreativeWorkflowEngine is the
 * only graph execution authority. Runtimes remain operation adapters.
 */
export class CreativeExecutionPlatform {
  readonly #records = new Map<string, RecordState>();
  readonly #workflow: CreativeWorkflowEngine;
  readonly #authority: ProductionOperationAuthority;
  constructor(private readonly dependencies: CreativeExecutionPlatformDependencies) { this.#workflow = new CreativeWorkflowEngine(dependencies); this.#authority = dependencies.authority ?? new ProductionOperationAuthority({ billing: dependencies.billing ?? rejectingBilling, execute: async instance => { const record = this.require(instance.identity.requestId); const seed = (record.request.inputArtifacts ?? []).map(toWorkflowArtifact); record.snapshot = await this.#workflow.execute(record.workflow!, seed); return { workflowStatus: record.snapshot.status }; }, now: () => new Date((dependencies.now ?? Date.now)()).toISOString(), id: dependencies.id }); }

  createExecution(request: CreativeRequest): string { if (this.#records.has(request.id)) throw new Error(`Execution "${request.id}" already exists`); this.#records.set(request.id, { request, paused: false, cancelled: false }); return request.id; }
  async plan(id: string): Promise<CreativePlan> { const record = this.require(id); record.decision ??= await this.dependencies.decision.decide(record.request); record.plan = await this.dependencies.planning.plan(record.request, record.decision); return record.plan; }
  async compile(id: string): Promise<CreativeExecutionPlan> { const record = this.require(id); const plan = record.plan ?? await this.plan(id); validateCreativePlan(plan, (record.request.inputArtifacts ?? []).map(artifact => artifact.id)); const targets = Object.fromEntries(plan.operations.map(operation => [operation.id, this.dependencies.targetSelector.select(operation, record.request)])); validateExecutionTargets(plan, targets); const capabilityAdmission = this.dependencies.capabilityAdmission ?? compatibilityCapabilityAdmission; for (const operation of plan.operations) { const target = targets[operation.id]; const capability = capabilityAdmission.admit({ request: record.request, operation, target }); if (!capability.allowed) throw new Error(`Execution capability blocked operation ${operation.id}: ${capability.reasonCode}`); if (!this.dependencies.securityGate.authorize(record.request, operation, target)) throw new Error(`Security or target policy blocked operation ${operation.id}`); }
    record.execution = { requestId: record.request.id, operations: plan.operations, targets }; record.pipeline = { operationIds: plan.operations.map(operation => operation.id) }; record.workflow = new WorkflowCompiler().compile({ id, prompt: record.request.intent, scope: record.request.scope, sources: { executionGraph: { operations: plan.operations }, pipelineGraph: { operations: record.pipeline.operationIds.map(operationId => { const operation = plan.operations.find(item => item.id === operationId)!; return { ...operation, providerId: targets[operation.id] === 'LOCAL' ? undefined : operation.providerId }; }) } }, budget: record.request.budget, compiledAt: (this.dependencies.now ?? Date.now)() });
    const selected = Object.values(targets); const target = selected.some(x => x === 'CLOUD') && selected.some(x => x === 'LOCAL') ? 'HYBRID' : selected.some(x => x === 'CLOUD' || x === 'HYBRID') ? selected.find(x => x === 'HYBRID') ?? 'CLOUD' : 'LOCAL'; const credits = target === 'LOCAL' ? 0 : Number(record.request.metadata?.estimatedCredits ?? record.request.budget?.credits ?? 0); const operationId = `creative.execution.${id}`;
    record.operation = this.#authority.instantiateOperation({ identity: { operationId, operationVersion: '1', operationFamily: 'creative-workflow', ...record.request.scope, requestId: id }, definition: { operationId, version: '1', family: 'creative-workflow', capabilities: [], inputArtifacts: [], outputArtifacts: [], parametersSchema: {}, executionPolicy: {}, verificationPolicy: {}, resourceProfile: {}, costModel: {}, riskProfile: {}, billable: credits > 0 }, parameters: { intent: record.request.intent }, intent: { target, requiredCapabilities: [], executionMode: 'PRODUCTION', fallbackPolicy: {}, verificationPolicy: {} }, idempotencyKey: String(record.request.metadata?.idempotencyKey ?? id) });
    this.#authority.preflight(record.operation, { target, billable: credits > 0, credits, retries: record.request.budget?.retries ?? 0, policy: { maxCredits: record.request.budget?.credits ?? 0, maxProviderCost: Number(record.request.metadata?.maxProviderCost ?? Number.MAX_SAFE_INTEGER), allowFallback: true, allowRetry: true, allowEscalation: false, budgetMode: 'HARD' } });
    const authorization = this.#authority.authorize(record.operation, { checks: { operationValid: true, capabilityAvailable: true, runtimeAllowed: true, modelTrusted: true, privacyAllowed: true, budgetAllowed: true, scopeValid: true }, policyVersion: 'production-6.32', expiresAt: new Date((this.dependencies.now ?? Date.now)() + 300_000).toISOString(), costPolicy: { maxCredits: record.request.budget?.credits ?? 0, maxProviderCost: Number.MAX_SAFE_INTEGER, allowFallback: true, allowRetry: true, allowEscalation: false, budgetMode: 'HARD' } }); if (!authorization.allowed) throw new Error(authorization.reason); await this.#authority.reserve(record.operation); return record.execution; }
  async execute(id: string): Promise<ProductionOutcome> { const record = this.require(id); if (record.cancelled) throw new Error('Execution is cancelled'); if (record.paused) throw new Error('Execution is paused'); if (!record.workflow || !record.operation) await this.compile(id); try { await this.#authority.execute(record.operation!); const verification = this.verification(record.snapshot!); const outcome: ProductionOutcome = { executionId: id, status: record.snapshot!.status === 'SUCCESS' && verification.valid ? 'SUCCESS' : 'FAILED', workflow: record.snapshot!, verification, artifacts: record.snapshot!.artifacts.map(fromWorkflowArtifact) }; record.outcome = outcome; this.#authority.recordOutcome(record.operation!, { status: outcome.status }); if (outcome.status === 'FAILED') { await this.#authority.release(record.operation!, 'workflow or verification failed'); await this.dependencies.telemetry?.record(outcome); return outcome; } const target = record.operation!.executionIntent.target; const actual = target === 'LOCAL' ? new CreativeCostAuthority().local({ latency: record.snapshot!.metrics.executionTimeMs }) : { actualProviderCost: { amount: Number(record.request.metadata?.actualProviderCost ?? 0), currency: 'USD' }, actualCreditsBasis: Number(record.request.metadata?.billableCredits ?? record.request.budget?.credits ?? 0), actualLatency: record.snapshot!.metrics.executionTimeMs, actualRetries: 0, actualFallbacks: 0, actualDeviceCost: 0, actualEnergyEstimate: 0 }; this.#authority.recordActualCost(record.operation!, actual); this.#authority.buildBillingEvent(record.operation!, actual.actualCreditsBasis); await this.#authority.commit(record.operation!); await this.dependencies.telemetry?.record(outcome); return outcome; } catch (error) { if (isUnknown(error)) { await this.#authority.markUnknown(record.operation!, 'provider result unknown'); const outcome: ProductionOutcome = { executionId: id, status: 'UNKNOWN', verification: { valid: false, checks: [], errors: ['Provider outcome pending reconciliation'] }, artifacts: [] }; record.outcome = outcome; await this.dependencies.telemetry?.record(outcome); return outcome; } await this.#authority.release(record.operation!, 'execution failed'); throw error; } }
  status(id: string) { const record = this.require(id); return record.cancelled ? 'SKIPPED' as const : record.paused ? 'WAITING' as const : record.outcome?.status ?? (record.snapshot ? 'RUNNING' as const : 'READY' as const); }
  pause(id: string): void { this.require(id).paused = true; }
  resume(id: string): void { const record = this.require(id); if (record.cancelled) throw new Error('Cancelled execution cannot resume'); record.paused = false; }
  cancel(id: string): void { this.require(id).cancelled = true; }
  recover(id: string) { const record = this.require(id); if (record.outcome?.status !== 'FAILED') throw new Error('Only failed executions can recover'); return this.dependencies.recovery.decide({ executionId: id, error: record.workflow?.id ?? 'workflow-failed' }); }
  verify(id: string): VerificationResult { const snapshot = this.require(id).snapshot; if (!snapshot) throw new Error('Execution has not run'); return this.verification(snapshot); }
  result(id: string): ProductionOutcome | undefined { return this.require(id).outcome; }
  snapshot(id: string): WorkflowSnapshot | undefined { return this.require(id).snapshot; }
  replay(id: string): WorkflowSnapshot { const snapshot = this.require(id).snapshot; if (!snapshot) throw new Error('Execution has not run'); return this.#workflow.replay(snapshot); }
  private verification(snapshot: WorkflowSnapshot): VerificationResult { return { valid: snapshot.status === 'SUCCESS' && snapshot.verification.every(item => item.valid), checks: snapshot.verification.flatMap(item => item.checks), errors: snapshot.verification.flatMap(item => item.errors) }; }
  private require(id: string): RecordState { const record = this.#records.get(id); if (!record) throw new Error(`Execution "${id}" not found`); return record; }
}
function toWorkflowArtifact(value: CreativeArtifact): Artifact { return { id: value.id, kind: value.kind, value: value.value, producerStepId: value.producerOperationId, scope: value.scope, metadata: { ...value.metadata, lifecycle: value.state, artifactRole: value.role, image: value.image } }; }
function fromWorkflowArtifact(value: Artifact): CreativeArtifact { const metadata = value.metadata as Readonly<Record<string, unknown>> | undefined; return { id: value.id, kind: value.kind, value: value.value, producerOperationId: value.producerStepId, scope: value.scope, state: (metadata?.lifecycle as CreativeArtifact['state']) ?? 'FINAL', role: metadata?.artifactRole as CreativeArtifact['role'], image: metadata?.image as CreativeArtifact['image'], metadata: value.metadata }; }
const compatibilityCapabilityAdmission: ExecutionCapabilityPort = Object.freeze({ admit: ({ operation, target }) => { if (target === 'BLOCKED') return Object.freeze({ allowed: false, reasonCode: 'TARGET_BLOCKED' as const }); if (target === 'LOCAL' && !operation.providerId) return Object.freeze({ allowed: true, reasonCode: 'CAPABILITY_SUPPORTED' as const, capabilityId: 'local-adapter-compatibility' }); if (!['image-edit', 'CONTROLLED_LOCAL_EDIT'].includes(operation.type)) return Object.freeze({ allowed: false, reasonCode: 'UNSUPPORTED_OPERATION' as const }); if (!operation.providerId) return Object.freeze({ allowed: false, reasonCode: 'PROVIDER_REQUIRED' as const }); if (operation.providerId !== 'fal') return Object.freeze({ allowed: false, reasonCode: 'UNSUPPORTED_PROVIDER' as const }); return Object.freeze({ allowed: true, reasonCode: 'CAPABILITY_SUPPORTED' as const, capabilityId: 'fal-image-edit-compatibility' }); } });
const rejectingBilling = Object.freeze({ reserve: async () => { throw new Error('Billable production execution requires BillingTransactionAuthority'); }, commit: async () => { throw new Error('Billing authority is unavailable'); }, release: async () => { throw new Error('Billing authority is unavailable'); } });
function isUnknown(error: unknown): boolean { return Boolean(error && typeof error === 'object' && ('unknownOutcome' in error || (error as { code?: string }).code === 'PROVIDER_RESULT_UNKNOWN')); }
