#!/usr/bin/env python3
"""Build the byte-pinned BERS MODNet portrait-matting ONNX candidate.

The builder verifies the authoritative checkpoint before weights-only torch.load, exports the pinned
upstream architecture in two independent Python child processes with a fixed hash seed and constant
folding disabled, requires cross-process byte reproducibility, validates ONNX structure, proves
PyTorch/ORT parity, and—once the manifest export identity is PINNED—requires the generated bytes to
match that exact size/SHA. It does not sign, publish or promote.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import platform
import subprocess
import sys
from pathlib import Path
from typing import Any

import numpy as np
import onnx
import onnxruntime as ort
import torch

UPSTREAM_REVISION = "28165a451e4610c9d77cfdf925a94610bb2810fb"
MODEL_ID = "modnet-photographic-portrait-matting"
MODEL_VERSION = "1.0.0-candidate.2"
OPSET = 17
PARITY_SHAPES = ((128, 160), (256, 320), (512, 512))
PARITY_ATOL = 1e-4
EXPORT_PYTHON_HASH_SEED = "0"
CONSTANT_FOLDING = False


def git(source: Path, *args: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(source), *args], text=True, stderr=subprocess.STDOUT
        ).strip()
    except (OSError, subprocess.CalledProcessError) as error:
        raise RuntimeError(f"Git verification failed: {' '.join(args)}") from error


def sha256(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            value.update(chunk)
    return value.hexdigest()


def load_manifest(path: Path) -> dict[str, Any]:
    manifest = json.loads(path.read_text(encoding="utf-8"))
    if manifest.get("modelId") != MODEL_ID or manifest.get("version") != MODEL_VERSION:
        raise RuntimeError("MODNet manifest identity mismatch")
    checkpoint = manifest.get("upstream", {}).get("checkpoint", {})
    if checkpoint.get("identityState") != "PINNED":
        raise RuntimeError("MODNet checkpoint identity is not PINNED")
    size = checkpoint.get("size")
    digest = checkpoint.get("sha256")
    if not isinstance(size, int) or size <= 0:
        raise RuntimeError("MODNet checkpoint size is not pinned")
    if not isinstance(digest, str) or len(digest) != 64 or any(c not in "0123456789abcdef" for c in digest):
        raise RuntimeError("MODNet checkpoint SHA-256 is not pinned")
    export = manifest.get("bersExport", {})
    if export.get("opset") != OPSET:
        raise RuntimeError("MODNet BERS export opset mismatch")
    if export.get("constantFolding") is not CONSTANT_FOLDING:
        raise RuntimeError("MODNet manifest constant-folding strategy mismatch")
    if export.get("state") == "PINNED":
        if not isinstance(export.get("onnxSize"), int) or export["onnxSize"] <= 0:
            raise RuntimeError("Pinned MODNet ONNX size is invalid")
        export_sha = export.get("onnxSha256")
        if not isinstance(export_sha, str) or len(export_sha) != 64 or any(c not in "0123456789abcdef" for c in export_sha):
            raise RuntimeError("Pinned MODNet ONNX SHA-256 is invalid")
    return manifest


def verify_checkpoint_bytes(checkpoint: Path, manifest: dict[str, Any]) -> None:
    expected = manifest["upstream"]["checkpoint"]
    if checkpoint.name != expected["name"]:
        raise RuntimeError("MODNet checkpoint filename mismatch")
    if checkpoint.stat().st_size != expected["size"]:
        raise RuntimeError("MODNet checkpoint size mismatch before deserialization")
    if sha256(checkpoint) != expected["sha256"]:
        raise RuntimeError("MODNet checkpoint SHA-256 mismatch before deserialization")


def load_model(source: Path, checkpoint: Path, manifest: dict[str, Any]) -> torch.nn.Module:
    verify_checkpoint_bytes(checkpoint, manifest)

    sys.path.insert(0, str(source))
    spec = importlib.util.spec_from_file_location(
        "bers_modnet_onnx_source", source / "onnx" / "modnet_onnx.py"
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("Cannot import pinned MODNet ONNX architecture")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    wrapped = torch.nn.DataParallel(module.MODNet(backbone_pretrained=False))
    state = torch.load(
        checkpoint,
        map_location=torch.device("cpu"),
        weights_only=True,
    )
    if not isinstance(state, dict) or not state:
        raise RuntimeError("MODNet checkpoint state_dict is invalid")
    wrapped.load_state_dict(state, strict=True)
    wrapped.eval()
    return wrapped.module


def export_once(model: torch.nn.Module, path: Path) -> None:
    torch.manual_seed(6425)
    dummy = torch.linspace(-1.0, 1.0, steps=1 * 3 * 128 * 160, dtype=torch.float32).reshape(1, 3, 128, 160)
    with torch.inference_mode():
        torch.onnx.export(
            model,
            dummy,
            path,
            export_params=True,
            opset_version=OPSET,
            do_constant_folding=CONSTANT_FOLDING,
            input_names=["input"],
            output_names=["output"],
            dynamic_axes={
                "input": {0: "batch_size", 2: "height", 3: "width"},
                "output": {0: "batch_size", 2: "height", 3: "width"},
            },
        )


def run_export_child(source: Path, checkpoint: Path, manifest: Path, output: Path) -> None:
    env = os.environ.copy()
    env["PYTHONHASHSEED"] = EXPORT_PYTHON_HASH_SEED
    subprocess.run(
        [
            sys.executable,
            str(Path(__file__).resolve()),
            "--single-export",
            "--source", str(source),
            "--checkpoint", str(checkpoint),
            "--manifest", str(manifest),
            "--output", str(output),
        ],
        check=True,
        env=env,
    )


def validate_graph(path: Path) -> dict[str, Any]:
    model = onnx.load(path, load_external_data=False)
    onnx.checker.check_model(model, full_check=True)
    default_opsets = [item.version for item in model.opset_import if item.domain in ("", "ai.onnx")]
    if default_opsets != [OPSET]:
        raise RuntimeError(f"Unexpected ONNX opset: {default_opsets!r}")
    inputs = list(model.graph.input)
    outputs = list(model.graph.output)
    if [value.name for value in inputs] != ["input"] or [value.name for value in outputs] != ["output"]:
        raise RuntimeError("Unexpected MODNet ONNX graph I/O names")
    if inputs[0].type.tensor_type.elem_type != onnx.TensorProto.FLOAT:
        raise RuntimeError("MODNet ONNX input must be float32")
    if outputs[0].type.tensor_type.elem_type != onnx.TensorProto.FLOAT:
        raise RuntimeError("MODNet ONNX output must be float32")
    return {
        "irVersion": int(model.ir_version),
        "opset": OPSET,
        "nodeCount": len(model.graph.node),
        "initializerCount": len(model.graph.initializer),
        "input": inputs[0].name,
        "output": outputs[0].name,
    }


def parity(model: torch.nn.Module, onnx_path: Path) -> list[dict[str, Any]]:
    session = ort.InferenceSession(str(onnx_path), providers=["CPUExecutionProvider"])
    evidence: list[dict[str, Any]] = []
    rng = np.random.default_rng(6425)
    for height, width in PARITY_SHAPES:
        values = rng.uniform(-1.0, 1.0, size=(1, 3, height, width)).astype(np.float32)
        with torch.inference_mode():
            expected = model(torch.from_numpy(values)).cpu().numpy()
        actual = session.run(["output"], {"input": values})[0]
        if expected.shape != (1, 1, height, width) or actual.shape != expected.shape:
            raise RuntimeError(f"MODNet output shape mismatch for {height}x{width}")
        max_abs = float(np.max(np.abs(expected - actual)))
        if max_abs > PARITY_ATOL:
            raise RuntimeError(f"MODNet PyTorch/ORT parity failed: {max_abs} > {PARITY_ATOL}")
        if float(actual.min()) < -1e-6 or float(actual.max()) > 1.0 + 1e-6:
            raise RuntimeError("MODNet sigmoid output escaped [0,1]")
        evidence.append({
            "height": height,
            "width": width,
            "maxAbsError": max_abs,
            "minOutput": float(actual.min()),
            "maxOutput": float(actual.max()),
        })
    return evidence


def require_pinned_export_identity(manifest: dict[str, Any], path: Path) -> tuple[int, str]:
    actual_size = path.stat().st_size
    actual_sha = sha256(path)
    export = manifest["bersExport"]
    if export.get("state") != "PINNED":
        raise RuntimeError("MODNet BERS export identity must be PINNED before acceptance")
    if actual_size != export.get("onnxSize"):
        raise RuntimeError(f"MODNet ONNX size mismatch: {actual_size} != {export.get('onnxSize')}")
    if actual_sha != export.get("onnxSha256"):
        raise RuntimeError(
            f"MODNet ONNX SHA-256 mismatch against pinned export identity: {actual_sha} != {export.get('onnxSha256')}"
        )
    return actual_size, actual_sha


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--single-export", action="store_true")
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    return parser.parse_args()


def single_export(args: argparse.Namespace) -> None:
    if os.environ.get("PYTHONHASHSEED") != EXPORT_PYTHON_HASH_SEED:
        raise RuntimeError("MODNet child exporter requires fixed PYTHONHASHSEED=0")
    if git(args.source, "rev-parse", "HEAD") != UPSTREAM_REVISION:
        raise RuntimeError("MODNet source revision mismatch")
    manifest = load_manifest(args.manifest)
    model = load_model(args.source, args.checkpoint, manifest)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    export_once(model, args.output)
    print(
        f"MODNET CHILD EXPORT: seed={EXPORT_PYTHON_HASH_SEED} "
        "constantFolding=OFF "
        f"size={args.output.stat().st_size} sha256={sha256(args.output)}"
    )


def main() -> None:
    args = parse_args()
    if args.single_export:
        single_export(args)
        return
    if args.report is None:
        raise RuntimeError("--report is required for the parent MODNet build")
    if git(args.source, "rev-parse", "HEAD") != UPSTREAM_REVISION:
        raise RuntimeError("MODNet source revision mismatch")
    manifest = load_manifest(args.manifest)
    verify_checkpoint_bytes(args.checkpoint, manifest)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    first = args.output.with_suffix(".first.onnx")
    second = args.output.with_suffix(".second.onnx")
    run_export_child(args.source, args.checkpoint, args.manifest, first)
    run_export_child(args.source, args.checkpoint, args.manifest, second)
    first_hash = sha256(first)
    second_hash = sha256(second)
    if first_hash != second_hash or first.stat().st_size != second.stat().st_size:
        raise RuntimeError(
            "MODNet ONNX export is not byte-reproducible across independent fixed-hash-seed processes: "
            f"first={first.stat().st_size}/{first_hash} second={second.stat().st_size}/{second_hash}"
        )
    first.replace(args.output)
    second.unlink()

    artifact_size, artifact_sha = require_pinned_export_identity(manifest, args.output)
    graph = validate_graph(args.output)
    model = load_model(args.source, args.checkpoint, manifest)
    parity_evidence = parity(model, args.output)
    report = {
        "schemaVersion": 1,
        "modelId": MODEL_ID,
        "version": MODEL_VERSION,
        "status": "CANDIDATE",
        "productionDeviceApproval": False,
        "sourceRevision": UPSTREAM_REVISION,
        "checkpoint": {
            "size": args.checkpoint.stat().st_size,
            "sha256": manifest["upstream"]["checkpoint"]["sha256"],
            "verifiedBeforeDeserialization": True,
            "weightsOnlyDeserialization": True,
        },
        "artifact": {
            "size": artifact_size,
            "sha256": artifact_sha,
            "format": "ONNX",
            "quantization": "NONE",
            "simplification": "NONE",
            "constantFolding": CONSTANT_FOLDING,
            "matchesPinnedIdentity": True,
            "crossProcessReproducible": True,
        },
        "graph": graph,
        "parity": parity_evidence,
        "environment": {
            "python": sys.version.split()[0],
            "platform": platform.platform(),
            "torch": torch.__version__,
            "onnx": onnx.__version__,
            "onnxruntime": ort.__version__,
            "numpy": np.__version__,
            "exportPythonHashSeed": EXPORT_PYTHON_HASH_SEED,
            "independentExportProcesses": 2,
            "constantFolding": "DISABLED",
        },
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"MODNET ONNX EXPORT: PASS size={artifact_size} sha256={artifact_sha}")


if __name__ == "__main__":
    main()
