#!/usr/bin/env python3
"""GPU-only local FASHN parserless Fashion Pack smoke benchmark (R&D, never Core authority).

Pre-verified local weights + locally installed generated fork are required.
No cloud provider/API, no runtime downloads, no Project or Artifact mutation.
"""
import argparse
import hashlib
import json
import os
import statistics
import time
from pathlib import Path

from fashion_vton_weight_preflight import verify_weights

MAX_IMAGE_BYTES = 25 * 1024 * 1024
MAX_PIXELS = 16_777_216
CATEGORIES = ('tops', 'bottoms', 'one-pieces')


def _image_path(value: str) -> Path:
    p = Path(value)
    if p.is_symlink() or not p.is_file():
        raise ValueError('Input must be an existing regular local image file')
    size = p.stat().st_size
    if not 0 < size <= MAX_IMAGE_BYTES:
        raise ValueError('Input image byte size is outside research limit')
    return p


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(chunk)
    return digest.hexdigest()


def _validate(args):
    if args.category not in CATEGORIES:
        raise ValueError('Unsupported garment category')
    if type(args.runs) is not int or not 1 <= args.runs <= 10:
        raise ValueError('GPU benchmark runs must be 1..10')
    if type(args.seed) is not int or not 0 <= args.seed <= 2**32 - 1:
        raise ValueError('Invalid reproducible seed')
    person, garment = _image_path(args.person), _image_path(args.garment)
    output = Path(args.output)
    if output.exists():
        raise FileExistsError('Never overwrite an existing output directory')
    if output.resolve() == person.resolve() or output.resolve() == garment.resolve():
        raise ValueError('Invalid result directory')
    return person, garment, output


def assert_parserless_package():
    """Refuse an accidental import of the original parser-dependent FASHN wheel."""
    from importlib.util import find_spec
    from build_fashion_vton_parserless import UPSTREAM_COMMIT
    spec = find_spec('fashn_vton')
    if not spec or not spec.origin:
        raise RuntimeError('Generated BERS parserless research package is not installed')
    root = Path(spec.origin).parent
    identity = root / 'research_identity.py'
    expected = ('# GENERATED BERS parserless research identity; no production admission.\n'
                'KIND = "BERS_FASHION_PARSERLESS_RESEARCH_V1"\n'
                f'UPSTREAM_SHA = "{UPSTREAM_COMMIT}"\n')
    if identity.is_symlink() or not identity.is_file() or identity.read_text(encoding='utf-8') != expected:
        raise RuntimeError('Installed fashn_vton is not the exact generated parserless research package')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--person', required=True, help='Local person photo; no uploads')
    parser.add_argument('--garment', required=True, help='Local flat-lay garment photo')
    parser.add_argument('--weights-dir', required=True, type=Path)
    parser.add_argument('--weights-manifest', required=True, type=Path, help='Reviewed size/SHA-256 manifest')
    parser.add_argument('--output', required=True, help='New local result directory')
    parser.add_argument('--category', required=True, choices=CATEGORIES)
    parser.add_argument('--runs', type=int, default=3)
    parser.add_argument('--seed', type=int, default=42)
    args = parser.parse_args(argv)

    person_path, garment_path, output = _validate(args)
    # Verification comes first; a file manifest generated by the user is not license authority.
    weight_evidence = verify_weights(args.weights_dir, args.weights_manifest)

    # Block commonly used implicit Hugging Face networking at the process environment level.
    # A proper offline acceptance still needs network isolation of the process/container.
    os.environ['HF_HUB_OFFLINE'] = '1'
    os.environ['TRANSFORMERS_OFFLINE'] = '1'
    os.environ['HF_DATASETS_OFFLINE'] = '1'
    assert_parserless_package()
    import torch
    from PIL import Image
    from fashn_vton import TryOnPipeline

    if not torch.cuda.is_available():
        raise RuntimeError('CUDA GPU is required for this benchmark: no silent CPU fallback')
    if args.weights_dir.is_symlink() or not args.weights_dir.is_dir():
        raise ValueError('Weights directory must be an existing regular directory')

    def load_image(image_path):
        with Image.open(image_path) as input_image:
            if input_image.width < 1 or input_image.height < 1 or input_image.width * input_image.height > MAX_PIXELS:
                raise ValueError('Input image pixel count is outside research limit')
            return input_image.convert('RGB')

    person, garment = load_image(person_path), load_image(garment_path)
    pipeline = TryOnPipeline(weights_dir=str(args.weights_dir), device='cuda')
    samples = []
    latencies = []

    # Record measurements of actual end-to-end FASHN pipeline calls incl. pose estimation.
    for i in range(args.runs):
        torch.cuda.reset_peak_memory_stats()
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        result = pipeline(
            person_image=person,
            garment_image=garment,
            category=args.category,
            garment_photo_type='flat-lay',
            segmentation_free=True,
            num_samples=1,
            num_timesteps=30,
            seed=args.seed,
        )
        torch.cuda.synchronize()
        elapsed_ms = (time.perf_counter() - t0) * 1000
        if len(result.images) != 1:
            raise RuntimeError('Expected exactly one generated image')
        latencies.append(elapsed_ms)
        samples.append((result.images[0], torch.cuda.max_memory_allocated()))

    # Fail-closed output: save only after all GPU runs are successful.
    os.umask(0o077)
    output.mkdir(parents=True, exist_ok=False)
    reports = []
    for index, (image, peak_bytes) in enumerate(samples):
        file = output / f'result-{index+1:02d}.png'
        image.save(file, format='PNG')
        reports.append({'name': file.name, 'sha256': _sha256(file),
                        'latencyMs': round(latencies[index], 3), 'peakCudaAllocatedBytes': peak_bytes})
    sorted_latencies = sorted(latencies)
    def p95(values):
        return sorted(values)[max(0, (95 * len(values) + 99) // 100 - 1)]
    report = {
        'kind': 'BERS_FASHION_VTON_GPU_RESEARCH_V1',
        'admittedToProduction': False,
        'weights': weight_evidence,
        'source': {'personSha256': _sha256(person_path), 'garmentSha256': _sha256(garment_path)},
        'category': args.category, 'seed': args.seed, 'numTimesteps': 30,
        'garmentPhotoType': 'flat-lay', 'segmentationFree': True,
        'device': torch.cuda.get_device_name(0),
        'runs': reports, 'p50LatencyMs': round(statistics.median(latencies), 3),
        'p95LatencyMs': round(p95(latencies), 3),
        'peakCudaAllocatedBytes': max(item['peakCudaAllocatedBytes'] for item in reports),
    }
    (output / 'run-report.json').write_text(json.dumps(report, sort_keys=True, indent=2) + '\n')
    print('R&D GPU smoke complete; output and hashes recorded locally; no production authority')
    print(json.dumps({'runs': len(samples), 'p50LatencyMs': report['p50LatencyMs'],
                      'p95LatencyMs': report['p95LatencyMs']}))


if __name__ == '__main__':
    main()
