#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path
from typing import Any

from transformers import CLIPTokenizer, CLIPTokenizerFast


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def first_difference(expected: list[int], actual: list[int]) -> int | None:
    limit = min(len(expected), len(actual))
    for index in range(limit):
        if expected[index] != actual[index]:
            return index
    return limit if len(expected) != len(actual) else None


def prove_derived_fast_parity(output_dir: Path, reference_path: Path) -> dict[str, Any]:
    reference = json.loads(reference_path.read_text(encoding="utf-8"))
    if reference.get("stage") != "D5_CONTROL_SEMANTICS_REFERENCE":
        raise RuntimeError("unexpected D5 tokenizer reference stage")
    cases = ((reference.get("tokenizer") or {}).get("cases") or {})
    if set(cases) != {"empty", "ascii", "punctuation_whitespace", "unicode", "over_length"}:
        raise RuntimeError("D5 tokenizer reference corpus drift")

    derived = CLIPTokenizerFast.from_pretrained(output_dir, local_files_only=True)
    if derived.model_max_length != 77:
        raise RuntimeError(f"derived fast tokenizer max length drift: {derived.model_max_length}")
    if (derived.bos_token_id, derived.eos_token_id, derived.pad_token_id) != (49406, 49407, 49407):
        raise RuntimeError("derived fast CLIP special-token identity drift")

    per_case: dict[str, Any] = {}
    for name, expected in cases.items():
        encoded = derived(
            expected["prompt"],
            padding="max_length",
            truncation=True,
            max_length=77,
            return_attention_mask=True,
            add_special_tokens=True,
        )
        actual_ids = [int(value) for value in encoded["input_ids"]]
        actual_mask = [int(value) for value in encoded["attention_mask"]]
        expected_ids = [int(value) for value in expected["inputIds"]]
        expected_mask = [int(value) for value in expected["attentionMask"]]
        id_difference = first_difference(expected_ids, actual_ids)
        mask_difference = first_difference(expected_mask, actual_mask)
        exact_ids = id_difference is None
        exact_mask = mask_difference is None
        per_case[name] = {
            "exactInputIds": exact_ids,
            "exactAttentionMask": exact_mask,
            "inputIdFirstDifference": id_difference,
            "attentionMaskFirstDifference": mask_difference,
        }
        if not exact_ids or not exact_mask:
            raise RuntimeError(
                "derived Python CLIPTokenizerFast parity failed: "
                f"case={name} input_id_diff={id_difference} mask_diff={mask_difference} "
                f"expected_tail={expected_ids[-8:]} actual_tail={actual_ids[-8:]}"
            )
    return {
        "exact": True,
        "reference": "HISTORICAL_CLIPTOKENIZER_TRANSFORMERS_4_30_2",
        "derivedImplementation": derived.__class__.__name__,
        "cases": per_case,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--snapshot", type=Path, required=True)
    parser.add_argument("--reference", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()

    snapshot = args.snapshot.resolve()
    reference_path = args.reference.resolve(strict=True)
    source_dir = snapshot / "tokenizer"
    output_dir = args.output_dir.resolve()
    shutil.rmtree(output_dir, ignore_errors=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    slow = CLIPTokenizer.from_pretrained(source_dir, local_files_only=True)
    fast = CLIPTokenizerFast.from_pretrained(source_dir, local_files_only=True)
    if slow.model_max_length != 77 or fast.model_max_length != 77:
        raise RuntimeError("Tiny-SD tokenizer max length drift")
    if (slow.bos_token_id, slow.eos_token_id, slow.pad_token_id) != (49406, 49407, 49407):
        raise RuntimeError("Tiny-SD slow CLIP special-token identity drift")
    if (fast.bos_token_id, fast.eos_token_id, fast.pad_token_id) != (49406, 49407, 49407):
        raise RuntimeError("Tiny-SD fast CLIP special-token identity drift")

    # Generate only the fast-tokenizer compatibility artifact. save_pretrained() is allowed to
    # normalize legacy vocab/merges JSON/text serialization, so those regenerated bytes are not
    # accepted as source identity. The exact pinned upstream control files are restored below.
    fast.save_pretrained(output_dir)
    tokenizer_json = output_dir / "tokenizer.json"
    if not tokenizer_json.is_file():
        raise RuntimeError("CLIPTokenizerFast did not emit tokenizer.json")

    source_assets = {
        "vocab.json": source_dir / "vocab.json",
        "merges.txt": source_dir / "merges.txt",
        "tokenizer_config.json": source_dir / "tokenizer_config.json",
        "special_tokens_map.json": source_dir / "special_tokens_map.json",
    }
    for name, source in source_assets.items():
        if not source.is_file():
            raise RuntimeError(f"missing pinned Tiny-SD tokenizer asset: {name}")

    generated_legacy_hashes = {}
    for name in ("vocab.json", "merges.txt"):
        generated = output_dir / name
        if generated.is_file():
            generated_legacy_hashes[name] = sha256(generated)

    # Preserve the actual pinned tokenizer authority byte-for-byte. tokenizer.json remains a
    # derived runner-local compatibility artifact whose semantics are proven independently below
    # and then again in real Chrome.
    for name, source in source_assets.items():
        shutil.copyfile(source, output_dir / name)
        if sha256(output_dir / name) != sha256(source):
            raise RuntimeError(f"failed to preserve pinned Tiny-SD tokenizer bytes: {name}")

    # AutoTokenizer in Transformers.js may consult config.json to resolve the architecture.
    # Use the pinned Tiny-SD text-encoder config rather than synthesizing untrusted metadata.
    text_config = snapshot / "text_encoder" / "config.json"
    if not text_config.is_file():
        raise RuntimeError("pinned Tiny-SD text_encoder/config.json is required for browser tokenizer loading")
    shutil.copyfile(text_config, output_dir / "config.json")

    source_vocab = source_assets["vocab.json"]
    source_merges = source_assets["merges.txt"]
    pinned_assets_preserved = all(
        sha256(output_dir / name) == sha256(source)
        for name, source in source_assets.items()
    )
    if not pinned_assets_preserved:
        raise RuntimeError("browser tokenizer preparation did not preserve pinned control assets")

    # Critical diagnostic boundary: prove the derived tokenizer.json with Python's fast-tokenizer
    # runtime before blaming or adapting Transformers.js. This consumes the generated output_dir,
    # not the original source tokenizer object.
    derived_fast_parity = prove_derived_fast_parity(output_dir, reference_path)

    files = {}
    for path in sorted(output_dir.iterdir()):
        if path.is_file():
            files[path.name] = {"bytes": path.stat().st_size, "sha256": sha256(path)}
    report = {
        "schemaVersion": 1,
        "status": "CANDIDATE",
        "stage": "D5_BROWSER_TOKENIZER_PREPARATION",
        "authority": "COMPOSITION_ONLY_NOT_QUALITY_ADMISSION",
        "referenceLibrary": "transformers==4.30.2",
        "sourceTokenizerClass": slow.__class__.__name__,
        "browserTokenizerClass": fast.__class__.__name__,
        "modelMaxLength": int(fast.model_max_length),
        "specialTokenIds": {"bos": int(fast.bos_token_id), "eos": int(fast.eos_token_id), "pad": int(fast.pad_token_id)},
        "sourceVocabSha256": sha256(source_vocab),
        "sourceMergesSha256": sha256(source_merges),
        "pinnedSourceAssetsPreservedByteExactly": pinned_assets_preserved,
        "derivedFastVsHistoricalReference": derived_fast_parity,
        "fastVsHistoricalReferenceExact": derived_fast_parity["exact"],
        "derivedTokenizerJson": {
            "sha256": sha256(tokenizer_json),
            "bytes": tokenizer_json.stat().st_size,
            "authority": "RUNNER_LOCAL_COMPATIBILITY_ARTIFACT_REQUIRES_BROWSER_SEMANTIC_PARITY",
        },
        "generatedLegacySerializationBeforePinnedRestore": generated_legacy_hashes,
        "files": files,
        "generatedAssetsRunnerLocalOnly": True,
        "runtimeAuthorityGranted": False,
        "productionApproval": False,
        "editorAuthorityGranted": False,
        "cloudFallbackAllowed": False,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(
        "TINY-SD D5 BROWSER TOKENIZER PREPARATION: PASS "
        f"files={len(files)} pinned_assets_preserved={pinned_assets_preserved} "
        f"fast_vs_historical={derived_fast_parity['exact']}"
    )


if __name__ == "__main__":
    main()
