import { average, clamp, clone, immutable } from "./immutable";
import { sameScope, scopeKey, type CreativeCandidate, type CreativeVision, type DirectorDependencies, type DirectorScope, type StyleGenomeRepresentation, type WeightedSignal } from "./types";

const words = (value: string) => value.toLocaleLowerCase().split(/[^\p{L}\p{N}]+/u).filter(Boolean);
const lexicon: Readonly<Record<string, readonly string[]>> = immutable({
  Luxury: ["luxury", "premium", "дорого", "премиум", "элегантно"], Minimal: ["minimal", "clean", "минимал", "чисто"],
  Fashion: ["fashion", "editorial", "мода"], Warm: ["warm", "уют", "тепл"], Modern: ["modern", "соврем"],
  Portrait: ["portrait", "портрет"], Catalog: ["catalog", "каталог"], Product: ["product", "товар", "продукт"],
});
const detected = (prompt: string): string[] => { const normalized = words(prompt).join(" "); return Object.entries(lexicon).filter(([, markers]) => markers.some((marker) => normalized.includes(marker))).map(([name]) => name); };

export class CreativeVisionEngine {
  constructor(private readonly dependencies: DirectorDependencies) {}
  create(scope: DirectorScope, prompt: string): CreativeVision {
    const signals = detected(prompt); const styles = signals.filter((item) => ["Luxury", "Minimal", "Fashion", "Modern"].includes(item));
    const mood = [...new Set([...signals.filter((item) => ["Luxury", "Warm"].includes(item)), styles.includes("Luxury") ? "Elegant" : "Calm"])];
    const visionGoals = [...new Set(styles.length ? styles : ["Clean", "Balanced"] )];
    return immutable({ ...scope, id: this.dependencies.createId(), prompt, visionGoals, mood, style: styles.length ? styles : ["Minimal"],
      commercialIntent: signals.includes("Catalog") ? "CATALOG" : signals.includes("Product") ? "PRODUCT" : "BRAND",
      visualDirection: [...new Set([styles.includes("Luxury") ? "Soft lighting" : "Balanced lighting", styles.includes("Luxury") ? "Premium texture" : "Clean background", "Controlled contrast"])],
      confidence: clamp(.45 + signals.length * .08), createdAt: this.dependencies.now() });
  }
  analyze(scope: DirectorScope, prompt: string): CreativeVision { return this.create(scope, prompt); }
}

export interface VisualLanguage { readonly style: string; readonly signals: readonly WeightedSignal[]; readonly confidence: number }
const LANGUAGE: readonly VisualLanguage[] = immutable([
  { style: "Luxury", confidence: .92, signals: [{ name: "Soft lighting", weight: .95, confidence: .9 }, { name: "Warm palette", weight: .85, confidence: .9 }, { name: "Premium texture", weight: .9, confidence: .88 }, { name: "Low noise", weight: .8, confidence: .95 }, { name: "Balanced contrast", weight: .75, confidence: .85 }] },
  { style: "Fashion", confidence: .9, signals: [{ name: "High contrast", weight: .85, confidence: .9 }, { name: "Dynamic light", weight: .9, confidence: .86 }, { name: "Rich texture", weight: .8, confidence: .84 }, { name: "Editorial composition", weight: .95, confidence: .92 }] },
  { style: "Minimal", confidence: .9, signals: [{ name: "Negative space", weight: .95, confidence: .9 }, { name: "Clean palette", weight: .9, confidence: .9 }, { name: "Simple hierarchy", weight: .85, confidence: .88 }] },
]);
export class VisualLanguageEngine { language(style: string): VisualLanguage { const found = LANGUAGE.find((item) => item.style.toLowerCase() === style.toLowerCase()); return immutable(clone(found ?? { style, confidence: .3, signals: [] })); } all(): readonly VisualLanguage[] { return immutable(clone(LANGUAGE)); } }

export interface EmotionProfile { readonly emotions: readonly WeightedSignal[]; readonly recommendations: readonly string[]; readonly confidence: number }
const EMOTIONS: Readonly<Record<string, readonly string[]>> = immutable({ Luxury: ["soft light", "black or gold accents", "refined texture"], Trust: ["blue palette", "balanced composition", "natural light"], Warm: ["warm palette", "soft shadows", "human detail"], Calm: ["negative space", "low contrast", "stable composition"], Energetic: ["red accents", "dynamic perspective", "high contrast"], Elegant: ["refined lines", "controlled contrast", "premium detail"], "Luxury Fashion": ["editorial composition", "premium texture", "dynamic elegance"], "Premium Product": ["material detail", "controlled reflection", "clean focus"], Dramatic: ["hard light", "deep shadows", "strong focus"], Minimal: ["negative space", "simple hierarchy", "clean palette"], Friendly: ["warm color", "open composition", "soft light"], Modern: ["clean geometry", "bold restraint", "neutral palette"], Classic: ["symmetry", "timeless palette", "formal balance"] });
export class CreativeEmotionEngine {
  analyze(input: string | CreativeVision): EmotionProfile { const source = typeof input === "string" ? `${input} ${detected(input).join(" ")}` : `${input.prompt} ${input.mood.join(" ")} ${input.style.join(" ")}`; const normalized = source.toLowerCase(); let names = Object.keys(EMOTIONS).filter((name) => normalized.includes(name.toLowerCase())); if (!names.length) names = ["Calm"]; const emotions = names.sort().map((name) => ({ name, weight: 1 / names.length, confidence: .8 })); return immutable({ emotions, recommendations: [...new Set(names.flatMap((name) => EMOTIONS[name]))], confidence: average(emotions.map(({ confidence }) => confidence)) }); }
  recognize(input: string | CreativeVision): EmotionProfile { return this.analyze(input); }
}

export interface CreativeNarrative { readonly subject: string; readonly arc: readonly string[]; readonly story: string; readonly confidence: number }
export class CreativeNarrativeEngine { analyze(prompt: string): CreativeNarrative { const found = detected(prompt); const subject = found.includes("Portrait") ? "Portrait" : found.includes("Product") ? "Product" : /car|авто/i.test(prompt) ? "Luxury Car" : "Brand"; const arc = subject === "Luxury Car" ? ["Status", "Confidence", "Success"] : subject === "Portrait" ? ["Warmth", "Connection", "Emotion"] : subject === "Product" ? ["Craft", "Trust", "Desire"] : ["Identity", "Recognition", "Affinity"]; return immutable({ subject, arc, story: [subject, ...arc].join(" → "), confidence: .82 }); } }

export interface CompositionAssessment { readonly dimensions: Readonly<Record<"hierarchy" | "balance" | "focus" | "negativeSpace" | "rhythm" | "perspective" | "symmetry" | "ruleOfThirds", number>>; readonly score: number; readonly recommendations: readonly string[] }
export class CompositionExpert { evaluate(candidate: CreativeCandidate | Readonly<Record<string, number>>): CompositionAssessment { const attributes = "attributes" in candidate ? candidate.attributes : candidate; const names = ["hierarchy", "balance", "focus", "negativeSpace", "rhythm", "perspective", "symmetry", "ruleOfThirds"] as const; const dimensions = Object.fromEntries(names.map((name) => [name, clamp(attributes[name] ?? .5)])) as CompositionAssessment["dimensions"]; return immutable({ dimensions, score: average(Object.values(dimensions)), recommendations: names.filter((name) => dimensions[name] < .6).map((name) => `Improve ${name}`) }); } }

export interface PsychologyRecommendation { readonly signal: string; readonly perception: string; readonly confidence: number; readonly recommendation: string }
const COLOR = immutable({ Gold: "Luxury", Blue: "Trust", Red: "Energy", White: "Purity", Black: "Premium" } as const);
const LIGHT = immutable({ Soft: "Luxury", Hard: "Drama", Warm: "Comfort", Cold: "Technology" } as const);
class PsychologyEngine { constructor(private readonly knowledge: Readonly<Record<string, string>>) {} analyze(signals: readonly string[]): readonly PsychologyRecommendation[] { return immutable(signals.map((signal) => { const match = Object.keys(this.knowledge).find((key) => key.toLowerCase() === signal.toLowerCase()); return { signal, perception: match ? this.knowledge[match] : "Neutral", confidence: match ? .95 : .3, recommendation: match ? `Use ${match} to communicate ${this.knowledge[match]}` : `Validate ${signal} in context` }; })); } all(): Readonly<Record<string, string>> { return immutable(clone(this.knowledge)); } }
export class ColorPsychologyEngine extends PsychologyEngine { constructor() { super(COLOR); } }
export class LightingPsychologyEngine extends PsychologyEngine { constructor() { super(LIGHT); } }

export interface BrandDNA extends DirectorScope { readonly id: string; readonly name: string; readonly preferredPalette: readonly string[]; readonly preferredMood: readonly string[]; readonly preferredLighting: readonly string[]; readonly preferredStyle: readonly string[]; readonly consistencyRules: readonly string[]; readonly createdAt: number }
export class BrandIdentityEngine {
  private brands: ReadonlyMap<string, BrandDNA> = new Map();
  constructor(private readonly dependencies: DirectorDependencies) {}
  define(scope: DirectorScope, input: Omit<BrandDNA, keyof DirectorScope | "id" | "createdAt">): BrandDNA { const brand = immutable({ ...scope, ...clone(input), id: this.dependencies.createId(), createdAt: this.dependencies.now() }); this.brands = new Map([...this.brands, [scopeKey(scope), brand]]); return brand; }
  get(scope: DirectorScope): BrandDNA | undefined { const value = this.brands.get(scopeKey(scope)); return value ? immutable(clone(value)) : undefined; }
  evaluate(scope: DirectorScope, candidate: CreativeCandidate): number { const brand = this.get(scope); if (!brand) return .5; const desired = [...brand.preferredPalette, ...brand.preferredMood, ...brand.preferredLighting, ...brand.preferredStyle].map((value) => value.toLowerCase()); const actual = [...(candidate.styles ?? []), ...(candidate.colors ?? []), ...(candidate.lighting ?? [])].map((value) => value.toLowerCase()); return desired.length ? desired.filter((value) => actual.includes(value)).length / desired.length : 1; }
}

export interface StyleEvolutionEvent extends DirectorScope { readonly id: string; readonly style: string; readonly confidence: number; readonly createdAt: number }
export class StyleEvolutionEngine { private events: readonly StyleEvolutionEvent[] = immutable([]); constructor(private readonly dependencies: DirectorDependencies) {} record(scope: DirectorScope, style: string, confidence: number): StyleEvolutionEvent { const event = immutable({ ...scope, id: this.dependencies.createId(), style, confidence: clamp(confidence), createdAt: this.dependencies.now() }); this.events = immutable([...this.events, event]); return event; } history(scope: DirectorScope): readonly StyleEvolutionEvent[] { return immutable(this.events.filter((item) => sameScope(item, scope)).map(clone).sort((a, b) => a.createdAt - b.createdAt || a.id.localeCompare(b.id))); } }

export interface ConsistencyAssessment { readonly score: number; readonly perAttribute: Readonly<Record<string, number>>; readonly outliers: readonly string[] }
export class CreativeConsistencyEngine { evaluate(candidates: readonly CreativeCandidate[]): ConsistencyAssessment { if (!candidates.length) return immutable({ score: 1, perAttribute: {}, outliers: [] }); const keys = [...new Set(candidates.flatMap(({ attributes }) => Object.keys(attributes)))].sort(); const perAttribute = Object.fromEntries(keys.map((key) => { const values = candidates.map(({ attributes }) => attributes[key] ?? .5); return [key, clamp(1 - (Math.max(...values) - Math.min(...values)))]; })); const itemScores = candidates.map((candidate) => average(keys.map((key) => Math.abs((candidate.attributes[key] ?? .5) - average(candidates.map(({ attributes }) => attributes[key] ?? .5)))))); return immutable({ score: average(Object.values(perAttribute)), perAttribute, outliers: candidates.filter((_, index) => itemScores[index] > .35).map(({ id }) => id) }); } }
export class CreativeDiversityEngine { evaluate(candidates: readonly CreativeCandidate[]): Readonly<{ score: number; pairwise: readonly Readonly<{ leftId: string; rightId: string; distance: number }>[] }> { const keys = [...new Set(candidates.flatMap(({ attributes }) => Object.keys(attributes)))].sort(); const pairwise = candidates.flatMap((left, index) => candidates.slice(index + 1).map((right) => ({ leftId: left.id, rightId: right.id, distance: Math.sqrt(average(keys.map((key) => ((left.attributes[key] ?? 0) - (right.attributes[key] ?? 0)) ** 2))) }))); return immutable({ score: average(pairwise.map(({ distance }) => distance)), pairwise }); } }

export class CreativeInspirationEngine { combine(styles: readonly string[]): Readonly<{ name: string; sources: readonly string[]; direction: readonly string[]; novelty: number }> { const sources = [...new Set(styles)].sort(); if (sources.length < 2) throw new Error("Inspiration requires at least two styles"); const language = new VisualLanguageEngine(); return immutable({ name: sources.join(" "), sources, direction: [...new Set(sources.flatMap((style) => language.language(style).signals.slice(0, 2).map(({ name }) => name)))], novelty: clamp(.5 + sources.length * .1) }); } }

export interface CreativeConstraints { readonly maxCredits?: number; readonly allowAI: boolean; readonly preserveFace: boolean; readonly preserveClothing: boolean; readonly preserveBrand: boolean; readonly statements: readonly string[] }
export class CreativeConstraintEngine { parse(prompt: string): CreativeConstraints { const credit = prompt.match(/(?:до|max(?:imum)?|under)\s*(\d+)\s*(?:credits?|кредит)/i); return immutable({ maxCredits: credit ? Number(credit[1]) : undefined, allowAI: !/(?:без|no)\s*ai/i.test(prompt), preserveFace: /(?:не менять|keep|preserve)\s*(?:the\s*)?(?:face|лицо)/i.test(prompt), preserveClothing: /(?:не менять|keep|preserve)\s*(?:the\s*)?(?:clothing|clothes|одежд)/i.test(prompt), preserveBrand: /(?:оставить|keep|preserve)\s*(?:the\s*)?(?:brand|бренд)/i.test(prompt), statements: prompt.split(/[,;]/).map((item) => item.trim()).filter(Boolean) }); } validate(candidate: CreativeCandidate, constraints: CreativeConstraints): readonly string[] { return immutable([constraints.maxCredits !== undefined && (candidate.credits ?? 0) > constraints.maxCredits ? "CREDIT_LIMIT" : "", !constraints.allowAI && candidate.usesAI ? "AI_DISALLOWED" : ""].filter(Boolean)); } }

export interface ProjectVisualIdentity extends DirectorScope { readonly id: string; readonly preferredMood: readonly string[]; readonly preferredPalette: readonly string[]; readonly preferredLighting: readonly string[]; readonly preferredComposition: readonly string[]; readonly preferredStyle: readonly string[]; readonly version: number; readonly createdAt: number }
export class ProjectVisualMemory { private identities: ReadonlyMap<string, ProjectVisualIdentity> = new Map(); constructor(private readonly dependencies: DirectorDependencies) {} save(scope: DirectorScope, input: Omit<ProjectVisualIdentity, keyof DirectorScope | "id" | "version" | "createdAt">): ProjectVisualIdentity { const previous = this.identities.get(scopeKey(scope)); const identity = immutable({ ...scope, ...clone(input), id: this.dependencies.createId(), version: (previous?.version ?? 0) + 1, createdAt: this.dependencies.now() }); this.identities = new Map([...this.identities, [scopeKey(scope), identity]]); return identity; } get(scope: DirectorScope): ProjectVisualIdentity | undefined { const identity = this.identities.get(scopeKey(scope)); return identity ? immutable(clone(identity)) : undefined; } }

export interface DirectorReviewAnswer { readonly question: string; readonly answer: boolean; readonly reason: string; readonly confidence: number; readonly recommendation: string }
export class CreativeDirectorReview { review(input: { readonly candidate: CreativeCandidate; readonly alternatives?: readonly CreativeCandidate[]; readonly brandAlignment?: number; readonly composition?: number }): readonly DirectorReviewAnswer[] { const candidate = input.candidate; const alternatives = input.alternatives ?? []; const cheaper = alternatives.some((item) => (item.credits ?? 0) < (candidate.credits ?? 0)); const prettier = alternatives.some((item) => (item.attributes.quality ?? 0) > (candidate.attributes.quality ?? 0)); const simpler = (candidate.operations?.length ?? 0) > 4; const withoutAI = Boolean(candidate.usesAI && alternatives.some((item) => !item.usesAI)); const overloaded = (candidate.operations?.length ?? 0) > 6; const lostIdea = (candidate.attributes.focus ?? .5) < .6; const lostBrand = (input.brandAlignment ?? .5) < .7; const weakComposition = (input.composition ?? .5) < .7; const checks: readonly [string, boolean, boolean, string, string][] = [
    ["Can it be cheaper?", cheaper, cheaper, "Compared candidate costs", "Prefer a cheaper option when quality holds"],
    ["Can it be more beautiful?", prettier, prettier, "Compared creative quality", "Review the strongest visual alternative"],
    ["Can it be simpler?", simpler, simpler, "Measured operation count", "Remove non-contributing operations"],
    ["Can it work without AI?", withoutAI, withoutAI, "Compared local alternatives", "Use local execution if expressive value remains"],
    ["Is it not overloaded?", !overloaded, overloaded, "Checked visual intervention count", "Restore hierarchy and negative space"],
    ["Is the main idea preserved?", !lostIdea, lostIdea, "Focus is the proxy for idea clarity", "Strengthen the primary focus"],
    ["Was brand style preserved?", !lostBrand, lostBrand, "Measured Brand DNA alignment", "Align palette, mood and lighting with the brand"],
    ["Is composition expressive enough?", !weakComposition, weakComposition, "Measured composition score", "Improve hierarchy, rhythm or perspective"],
  ]; return immutable(checks.map(([question, answer, issue, reason, recommendation]) => ({ question, answer, reason, confidence: .85, recommendation: issue ? recommendation : "Keep current direction" }))); } }

export type CouncilDomain = "COMPOSITION" | "LIGHTING" | "COLOR" | "EMOTION" | "BRAND" | "COST" | "QUALITY" | "NARRATIVE";
export interface DirectorExpertOpinion { readonly expert: string; readonly domain: CouncilDomain; readonly score: number; readonly confidence: number; readonly reason: string }
export interface CreativeDirectorExpert { readonly name: string; readonly domain: CouncilDomain; evaluate(candidate: CreativeCandidate): DirectorExpertOpinion }
export class HeuristicCreativeExpert implements CreativeDirectorExpert { constructor(readonly name: string, readonly domain: CouncilDomain, private readonly attribute: string, private readonly inverse = false) {} evaluate(candidate: CreativeCandidate): DirectorExpertOpinion { const value = clamp(candidate.attributes[this.attribute] ?? .5); return immutable({ expert: this.name, domain: this.domain, score: this.inverse ? 1 - value : value, confidence: candidate.attributes[this.attribute] === undefined ? .35 : .9, reason: `${this.attribute}=${value}` }); } }
export class CreativeExpertCouncil { constructor(private readonly experts: readonly CreativeDirectorExpert[]) {} evaluate(candidate: CreativeCandidate): Readonly<{ score: number; opinions: readonly DirectorExpertOpinion[]; recommendation: string }> { const opinions = this.experts.map((expert) => expert.evaluate(candidate)).sort((a, b) => a.domain.localeCompare(b.domain)); const weights = opinions.reduce((sum, opinion) => sum + opinion.confidence, 0); const score = weights ? opinions.reduce((sum, opinion) => sum + opinion.score * opinion.confidence, 0) / weights : 0; const weakest = [...opinions].sort((a, b) => a.score - b.score || a.domain.localeCompare(b.domain))[0]; return immutable({ score, opinions, recommendation: weakest ? `Improve ${weakest.domain}: ${weakest.reason}` : "Add expert evidence" }); } }
export class CreativeMetaCouncil extends CreativeExpertCouncil {}

export interface CreativeScorecardValues { readonly luxury: number; readonly emotion: number; readonly composition: number; readonly narrative: number; readonly brand: number; readonly consistency: number; readonly creativity: number; readonly commercialValue: number; readonly technicalQuality: number; readonly tasteAlignment: number; readonly costEfficiency: number }
export class CreativeScorecard { calculate(values: CreativeScorecardValues): Readonly<{ dimensions: CreativeScorecardValues; score: number; weakest: keyof CreativeScorecardValues }> { const dimensions = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, clamp(value)])) as unknown as CreativeScorecardValues; const entries = Object.entries(dimensions) as [keyof CreativeScorecardValues, number][]; return immutable({ dimensions, score: average(entries.map(([, value]) => value)), weakest: [...entries].sort((a, b) => a[1] - b[1] || a[0].localeCompare(b[0]))[0][0] }); } }
export class CreativeIQ { evaluate(scorecard: CreativeScorecardValues | Readonly<{ dimensions: CreativeScorecardValues }>, review?: readonly DirectorReviewAnswer[]): Readonly<{ score: number; level: "DEVELOPING" | "PROFICIENT" | "DIRECTOR" | "MASTER"; explanation: readonly string[] }> { const values = "dimensions" in scorecard ? scorecard.dimensions : scorecard; const base = average(Object.values(values)); const reviewScore = review?.length ? review.filter(({ answer }) => answer).length / review.length : base; const score = clamp(base * .8 + reviewScore * .2); return immutable({ score, level: score >= .9 ? "MASTER" : score >= .75 ? "DIRECTOR" : score >= .55 ? "PROFICIENT" : "DEVELOPING", explanation: [`scorecard=${base}`, `review=${reviewScore}`] }); } }

const GENOMES: Readonly<Record<string, readonly number[]>> = immutable({ Luxury: [.9, .8, .85, 1, .7, .9, .6, .9], Minimal: [.7, .8, .65, .3, .4, .75, .5, .6], Fashion: [.8, .9, .9, .85, 1, .8, .9, .85], Editorial: [.75, 1, .8, .8, .9, .75, .95, .8] });
export class StyleGenome { encode(style: string): StyleGenomeRepresentation { const values = GENOMES[style] ?? Array(8).fill(.5); const total = values.reduce((sum, value) => sum + value, 0) || 1; const normalized = values.map((value) => value / total); return immutable({ style, lighting: normalized[0], composition: normalized[1], color: normalized[2], texture: normalized[3], contrast: normalized[4], palette: normalized[5], perspective: normalized[6], emotion: normalized[7] }); } combine(styles: readonly string[]): StyleGenomeRepresentation { if (!styles.length) throw new Error("At least one style is required"); const genomes = styles.map((style) => this.encode(style)); const dimensions = ["lighting", "composition", "color", "texture", "contrast", "palette", "perspective", "emotion"] as const; const raw = dimensions.map((key) => average(genomes.map((genome) => genome[key]))); const total = raw.reduce((sum, value) => sum + value, 0); return immutable({ style: [...styles].sort().join(" "), ...Object.fromEntries(dimensions.map((key, index) => [key, raw[index] / total])) } as unknown as StyleGenomeRepresentation); } }
export class StyleGenomeEngine extends StyleGenome {}

export interface CreativeReasoningContext { readonly scope: DirectorScope; readonly vision: CreativeVision; readonly candidates: readonly CreativeCandidate[] }
export interface CreativeReasoner { reason(context: CreativeReasoningContext): readonly string[] }
export interface CreativePlanner { plan(context: CreativeReasoningContext): readonly string[] }
export interface CreativeCritic { critique(candidate: CreativeCandidate): readonly string[] }
export interface CreativeDirector { direct(context: CreativeReasoningContext): CreativeCandidate }
export interface CreativeVisionModel { create(scope: DirectorScope, prompt: string): CreativeVision }
export interface CreativeStyleEncoder { encode(style: string): StyleGenomeRepresentation }
export interface CreativeNarrativeEncoder { encode(narrative: CreativeNarrative): readonly number[] }
export interface CreativeEmotionEncoder { encode(emotion: EmotionProfile): readonly number[] }
export interface CreativeWorldModel { observe(scope: DirectorScope, attributes: Readonly<Record<string, number>>): Readonly<{ scope: DirectorScope; attributes: Readonly<Record<string, number>> }> }
export interface CreativeImaginationEngine { imagine(styles: readonly string[]): readonly string[] }
export class HeuristicCreativeReasoner implements CreativeReasoner { reason(context: CreativeReasoningContext): readonly string[] { return immutable([`Vision: ${context.vision.visionGoals.join(", ")}`, `Candidates: ${context.candidates.length}`, `Prioritize ${context.vision.visualDirection[0]}`]); } }
export class HeuristicCreativePlanner implements CreativePlanner { plan(context: CreativeReasoningContext): readonly string[] { return immutable([...context.vision.visualDirection, "Validate composition", "Validate brand consistency"]); } }
export class HeuristicCreativeCritic implements CreativeCritic { critique(candidate: CreativeCandidate): readonly string[] { return immutable(Object.entries(candidate.attributes).filter(([, value]) => value < .5).sort(([a], [b]) => a.localeCompare(b)).map(([key]) => `Weak ${key}`)); } }
export class HeuristicCreativeDirector implements CreativeDirector { direct(context: CreativeReasoningContext): CreativeCandidate { const selected = [...context.candidates].sort((a, b) => average(Object.values(b.attributes)) - average(Object.values(a.attributes)) || a.id.localeCompare(b.id))[0]; if (!selected) throw new Error("Creative direction requires candidates"); return immutable(clone(selected)); } }
export class HeuristicCreativeNarrativeEncoder implements CreativeNarrativeEncoder { encode(narrative: CreativeNarrative): readonly number[] { return immutable([clamp(narrative.confidence), clamp(narrative.arc.length / 5)]); } }
export class HeuristicCreativeEmotionEncoder implements CreativeEmotionEncoder { encode(emotion: EmotionProfile): readonly number[] { return immutable([...emotion.emotions].sort((a, b) => a.name.localeCompare(b.name)).map(({ weight }) => clamp(weight))); } }
export class HeuristicCreativeWorldModel implements CreativeWorldModel { observe(scope: DirectorScope, attributes: Readonly<Record<string, number>>) { return immutable({ scope: clone(scope), attributes: clone(attributes) }); } }
export class HeuristicCreativeImaginationEngine implements CreativeImaginationEngine { imagine(styles: readonly string[]): readonly string[] { const sorted = [...new Set(styles)].sort(); return immutable(sorted.flatMap((style, index) => sorted.slice(index + 1).map((other) => `${style} ${other}`))); } }

export const CREATIVE_DIRECTOR_DEBUG_STAGES = immutable(["Prompt", "Vision", "Emotion", "Narrative", "Visual Language", "Composition", "Brand Identity", "Constraints", "Experts", "Director Review", "Creative Scorecard", "Creative IQ", "Reasoning", "Recommendation"] as const);
export interface CreativeDirectorDebugNode { readonly stage: typeof CREATIVE_DIRECTOR_DEBUG_STAGES[number]; readonly value: string; readonly next?: CreativeDirectorDebugNode }
export class CreativeDirectorDebugger { build(values: Partial<Record<CreativeDirectorDebugNode["stage"], string>>): CreativeDirectorDebugNode { let next: CreativeDirectorDebugNode | undefined; [...CREATIVE_DIRECTOR_DEBUG_STAGES].reverse().forEach((stage) => { next = immutable({ stage, value: values[stage] ?? "not available", ...(next ? { next } : {}) }); }); return next!; } flatten(root: CreativeDirectorDebugNode): readonly CreativeDirectorDebugNode[] { const output: CreativeDirectorDebugNode[] = []; let current: CreativeDirectorDebugNode | undefined = root; while (current) { output.push(current); current = current.next; } return immutable(output); } }
