export const modules = {
  common: { appName: 'AI 사진 편집기', save: '저장', cancel: '취소', delete: '삭제', edit: '편집', close: '닫기', create: '만들기', apply: '적용', retry: '다시 시도', confirm: '확인', back: '뒤로', next: '다음', done: '완료', loading: '불러오는 중…', search: '검색', add: '추가', remove: '제거', rename: '이름 변경', duplicate: '복제', download: '다운로드', favorite: '즐겨찾기', archive: '보관', restore: '복원', signOut: '로그아웃', empty: '아직 아무것도 없습니다', minutes: '{count}분', seconds: '{seconds}초' },
  editor: { title: '편집기', undo: '실행 취소', redo: '다시 실행', restoreOriginal: '원본 복원', detectObjects: '객체 감지', detecting: '객체 감지 중…', prompt: '프롬프트', creativeStudio: '크리에이티브 스튜디오', recipes: '레시피', aiAgent: 'AI 에이전트', fashion: '패션', outfits: '코디', before: '이전', after: '이후', accept: '적용', discard: '취소', objects: '객체', versions: '버전', newVersion: '새 버전', sceneMemory: '장면 메모리', workspace: '작업 공간', jobCenter: '작업 센터', instructionPlaceholder: '편집 내용을 설명하세요…', projectNotFound: '프로젝트를 찾을 수 없습니다' },
  projects: { title: '프로젝트', newProject: '새 프로젝트', upload: '이미지 업로드', empty: '아직 프로젝트가 없습니다 — 이미지를 업로드하여 시작하세요.', open: '열기', processing: '처리 중', draft: '초안', completed: '완료' },
  recipes: { title: '레시피', favorite: '즐겨찾기', popular: '인기', recent: '최근', recommended: '추천', run: '레시피 실행', use: '사용', searchPlaceholder: '레시피 검색…' },
  workspace: { title: '작업 공간', auto: '자동 감지', manual: '수동', switch: '작업 공간 전환', recommendations: '추천', mostUsed: '가장 많이 사용' },
  automation: { title: '오토메이션 스튜디오', subtitle: '코드 작성 없이 재사용 가능한 편집 워크플로를 만드세요.', library: '오토메이션 라이브러리', templateGallery: '템플릿 갤러리', builder: '빌더', history: '실행 기록', run: '실행', queuing: '대기열 추가 중…', save: '저장', trigger: '트리거', conditions: '조건', condition: '조건', actions: '작업', action: '작업', schedule: '일정', variables: '변수', estimatedCredits: '예상 크레딧', estimatedTime: '예상 시간', emptyBuilder: '템플릿을 선택하거나 오토메이션을 만드세요.', emptyLibrary: '템플릿을 저장하여 라이브러리를 구성하세요.', noRuns: '아직 실행 기록이 없습니다.', mostExecuted: '가장 많이 실행', successRate: '성공 {rate}%', failureRate: '실패 {rate}%', describePlaceholder: '이 워크플로를 설명하세요', actionsCount: '작업 {count}개', untitled: '제목 없는 오토메이션', scheduleImmediate: '즉시', scheduleScheduled: '예약', scheduleDaily: '매일', scheduleWeekly: '매주', scheduleManual: '수동 전용', containsPerson: '사람 포함', containsVehicle: '차량 포함', containsProduct: '제품 포함', containsAnimal: '동물 포함', containsText: '텍스트 포함' },
  fashion: { title: '패션', wardrobe: '옷장', garments: '의류', outfits: '코디', addGarment: '의류 추가', collections: '컬렉션', tryOn: '가상 피팅', searchPlaceholder: '옷장 검색…', empty: '옷장이 비어 있습니다.' },
  billing: { title: '결제', subscription: '구독', plan: '요금제', credits: '크레딧', upgrade: '업그레이드', currentPlan: '현재 요금제', usage: '사용량', renew: '{date}에 갱신' },
  settings: { title: '설정', account: '계정', appearance: '테마', appearanceHint: '라이트/다크 모드 전환', language: '언어', languageHint: '인터페이스 언어를 선택하세요', performance: '성능', loadingPerformance: '성능 설정을 불러오는 중…' },
  errors: { generic: '문제가 발생했습니다.', network: '네트워크 오류 — 연결을 확인하세요.', offline: '오프라인 상태입니다. 다시 연결되면 동기화됩니다.', timeout: '요청 시간이 초과되었습니다. 다시 시도하세요.', provider: 'AI 제공자가 요청을 완료하지 못했습니다.', validation: '강조된 필드를 수정하세요.', credits: '이 작업에 필요한 크레딧이 부족합니다.', subscription: '현재 요금제에서는 이 작업을 사용할 수 없습니다.' },
  notifications: { title: '알림', markAllRead: '모두 읽음 표시', empty: '알림이 없습니다.', completed: '생성 완료', failed: '생성 실패', saved: '편집 저장됨' },
  jobs: { title: '작업 센터', queued: '대기 중', running: '실행 중', waiting: '대기', completed: '완료', failed: '실패', cancelled: '취소됨', retrying: '재시도 중', cancel: '취소', pause: '일시정지', resume: '재개', empty: '진행 중인 작업이 없습니다.' },
  creative: { title: '크리에이티브 스튜디오', goal: '목표', ideas: '아이디어', moodBoards: '무드보드', strategy: '전략', generate: '아이디어 생성', apply: '전략 적용' },
  brand: { title: '브랜드 스튜디오', profile: '브랜드 프로필', colors: '색상', fonts: '글꼴', voice: '톤', guidelines: '가이드라인' },
  assets: { title: '에셋 라이브러리', collections: '컬렉션', pinned: '고정됨', smart: '스마트', searchPlaceholder: '에셋 검색…', empty: '아직 에셋이 없습니다.', details: '세부정보' },
};
export default modules;