export const modules = {
  common: { appName: 'Yapay Zekâ Fotoğraf Editörü', save: 'Kaydet', cancel: 'İptal', delete: 'Sil', edit: 'Düzenle', close: 'Kapat', create: 'Oluştur', apply: 'Uygula', retry: 'Yeniden dene', confirm: 'Onayla', back: 'Geri', next: 'İleri', done: 'Tamam', loading: 'Yükleniyor…', search: 'Ara', add: 'Ekle', remove: 'Kaldır', rename: 'Yeniden adlandır', duplicate: 'Çoğalt', download: 'İndir', favorite: 'Favori', archive: 'Arşivle', restore: 'Geri yükle', signOut: 'Çıkış yap', empty: 'Burada henüz bir şey yok', minutes: '{count} dk', seconds: '{seconds}s' },
  editor: { title: 'Editör', undo: 'Geri al', redo: 'Yinele', restoreOriginal: 'Orijinali geri yükle', detectObjects: 'Nesneleri algıla', detecting: 'Nesneler algılanıyor…', prompt: 'Komut', creativeStudio: 'Yaratıcı Stüdyo', recipes: 'Tarifler', aiAgent: 'Yapay Zekâ Ajanı', fashion: 'Moda', outfits: 'Kombinler', before: 'Önce', after: 'Sonra', accept: 'Kabul et', discard: 'Vazgeç', objects: 'Nesneler', versions: 'Sürümler', newVersion: 'Yeni sürüm', sceneMemory: 'Sahne belleği', workspace: 'Çalışma alanı', jobCenter: 'Görev Merkezi', instructionPlaceholder: 'Düzenlemeni açıkla…', projectNotFound: 'Proje bulunamadı' },
  projects: { title: 'Projeler', newProject: 'Yeni proje', upload: 'Görsel yükle', empty: 'Henüz proje yok — başlamak için bir görsel yükle.', open: 'Aç', processing: 'İşleniyor', draft: 'Taslak', completed: 'Tamamlandı' },
  recipes: { title: 'Tarifler', favorite: 'Favori', popular: 'Popüler', recent: 'Son', recommended: 'Önerilen', run: 'Tarifi çalıştır', use: 'Kullan', searchPlaceholder: 'Tarif ara…' },
  workspace: { title: 'Çalışma alanı', auto: 'Otomatik algılandı', manual: 'Manuel', switch: 'Alanı değiştir', recommendations: 'Öneriler', mostUsed: 'En çok kullanılan' },
  automation: { title: 'Otomasyon Stüdyosu', subtitle: 'Kod yazmadan yeniden kullanılabilir düzenleme akışları oluştur.', library: 'Otomasyon kütüphanesi', templateGallery: 'Şablon galerisi', builder: 'Oluşturucu', history: 'Yürütme geçmişi', run: 'Çalıştır', queuing: 'Sıraya alınıyor…', save: 'Kaydet', trigger: 'Tetikleyici', conditions: 'Koşullar', condition: 'Koşul', actions: 'Eylemler', action: 'Eylem', schedule: 'Zamanlama', variables: 'Değişkenler', estimatedCredits: 'Tahmini kredi', estimatedTime: 'Tahmini süre', emptyBuilder: 'Bir şablon seç veya otomasyon oluştur.', emptyLibrary: 'Kütüphaneni oluşturmak için bir şablon kaydet.', noRuns: 'Henüz yürütme yok.', mostExecuted: 'En çok çalıştırılan', successRate: 'Başarı {rate}%', failureRate: 'Hatalar {rate}%', describePlaceholder: 'Bu akışı açıkla', actionsCount: '{count} eylem', untitled: 'Adsız otomasyon', scheduleImmediate: 'Hemen', scheduleScheduled: 'Zamanlanmış', scheduleDaily: 'Günlük', scheduleWeekly: 'Haftalık', scheduleManual: 'Yalnızca manuel', containsPerson: 'Kişi içerir', containsVehicle: 'Araç içerir', containsProduct: 'Ürün içerir', containsAnimal: 'Hayvan içerir', containsText: 'Metin içerir' },
  fashion: { title: 'Moda', wardrobe: 'Gardırop', garments: 'Giysiler', outfits: 'Kombinler', addGarment: 'Giysi ekle', collections: 'Koleksiyonlar', tryOn: 'Sanal deneme', searchPlaceholder: 'Gardıropta ara…', empty: 'Gardırobun boş.' },
  billing: { title: 'Faturalandırma', subscription: 'Abonelik', plan: 'Plan', credits: 'Krediler', upgrade: 'Yükselt', currentPlan: 'Mevcut plan', usage: 'Kullanım', renew: '{date} tarihinde yenilenir' },
  settings: { title: 'Ayarlar', account: 'Hesap', appearance: 'Görünüm', appearanceHint: 'Açık ve koyu mod arasında geçiş yap', language: 'Dil', languageHint: 'Arayüz dilini seç', performance: 'Performans', loadingPerformance: 'Performans ayarları yükleniyor…' },
  errors: { generic: 'Bir şeyler ters gitti.', network: 'Ağ hatası — bağlantını kontrol et.', offline: 'Çevrimdışısın. Değişiklikler bağlanınca eşitlenecek.', timeout: 'İstek zaman aşımına uğradı. Tekrar dene.', provider: 'Yapay zekâ sağlayıcısı isteği tamamlayamadı.', validation: 'Lütfen vurgulanan alanları düzelt.', credits: 'Bu işlem için yeterli krediniz yok.', subscription: 'Planınız bu işleme izin vermiyor.' },
  notifications: { title: 'Bildirimler', markAllRead: 'Tümünü okundu işaretle', empty: 'Bildirim yok.', completed: 'Oluşturma tamamlandı', failed: 'Oluşturma başarısız', saved: 'Düzenleme kaydedildi' },
  jobs: { title: 'Görev Merkezi', queued: 'Sırada', running: 'Çalışıyor', waiting: 'Bekliyor', completed: 'Tamamlandı', failed: 'Başarısız', cancelled: 'İptal edildi', retrying: 'Yeniden deneniyor', cancel: 'İptal', pause: 'Duraklat', resume: 'Devam et', empty: 'Aktif görev yok.' },
  creative: { title: 'Yaratıcı Stüdyo', goal: 'Hedef', ideas: 'Fikirler', moodBoards: 'Mood board’lar', strategy: 'Strateji', generate: 'Fikir üret', apply: 'Stratejiyi uygula' },
  brand: { title: 'Marka Stüdyosu', profile: 'Marka profili', colors: 'Renkler', fonts: 'Yazı tipleri', voice: 'Ton', guidelines: 'Kılavuzlar' },
  assets: { title: 'Varlık Kütüphanesi', collections: 'Koleksiyonlar', pinned: 'Sabitlenmiş', smart: 'Akıllı', searchPlaceholder: 'Varlık ara…', empty: 'Henüz varlık yok.', details: 'Ayrıntılar' },
};
export default modules;